SELECT
		CLAIM_NUMBER,
		R12_INVOICE,
		TAVANT_CLAIM_TYPE,
		SERIAL_NUMBER,
		SIOP_SEGMENT1,
		SIOP_SEGMENT6,
		DEALER_GROUP_NAME
	FROM
		TAV_ITEM_RAW
	WHERE
		CLAIM_NUMBER IN
		(
			SELECT
					CLAIM_NUMBER
				FROM
					TAV_ITEM_RAW
				WHERE
					SIOP_SEGMENT1 IN('RSHVAC', 'CS HVAC')
				GROUP BY
					CLAIM_NUMBER,
					R12_INVOICE
				HAVING
					COUNT(DISTINCT SIOP_SEGMENT6) > 1
		) ;
		
SELECT * FROM V$VERSION;

