SELECT
		/* 'PUEBLO' Source Query */
		SUM(REVENUE_AMOUNT) AS REVENUE_AMOUNT,
		CAST(TO_CHAR(JRNL_DATE, 'YYYY') AS INTEGER) * 100 + CAST(TO_CHAR(JRNL_DATE, 'MM') AS INTEGER) AS JRNL_YEAR_MONTH,
		COUNTRY_INDICATOR
	FROM
		MAP_SALES_DATA
	WHERE
		JRNL_DATE BETWEEN TRUNC(ADD_MONTHS(SYSDATE, - 24), 'MM') AND TRUNC(ADD_MONTHS(LAST_DAY(SYSDATE), - 1))
		AND QUERY_SOURCE = 'PUEBLO'
	GROUP BY
		CAST(TO_CHAR(JRNL_DATE, 'YYYY') AS INTEGER) * 100 + CAST(TO_CHAR(JRNL_DATE, 'MM') AS INTEGER),
		COUNTRY_INDICATOR ;
SELECT
		/*+ INDEX(AP_400_SEL_CRED_JB_CLSS_CD XIE2AP_400_SEL_CRED_JB_CLSS_CD) */
		/* 'PUEBLO' Source Query */
		SUM(NVL(CD.RESOURCE_AMOUNT, 0)) AS REVENUE_AMOUNT
	FROM
		AP_135_PROJ_RESOURCE PR
	INNER JOIN AP_135_TRNPC_PROJ_RES RES          ON PR.BUSINESS_UNIT = RES.BUSINESS_UNIT AND PR.PROJECT_ID = RES.PROJECT_ID AND PR.RESOURCE_ID = RES.RESOURCE_ID AND PR.ACTIVITY_ID = RES.ACTIVITY_ID
	INNER JOIN AP_400_SEL_CRED_JB_CLSS_CD JBCLSCD ON PR.PROJECT_ID = TO_CHAR(JBCLSCD.CREDIT_JOB_ID)
	INNER JOIN AP_400_JOB_CODE JBCD               ON JBCD.JOB_CODE_ID = JBCLSCD.JOB_CODE_ID
	INNER JOIN AP_135_TRNPC_COMM_DATA CD          ON PR.BUSINESS_UNIT = CD.BUSINESS_UNIT AND PR.PROJECT_ID = CD.PROJECT_ID AND PR.RESOURCE_ID = CD.RESOURCE_ID AND PR.ACTIVITY_ID = CD.ACTIVITY_ID
	INNER JOIN AP_400_COMM_CODE CC                ON CD.TRNPC_COMM_CODE = CC.COMM_CODE AND CD.SALES_OFFICE_ID = CC.SALES_OFFICE_ID
	INNER JOIN MD_SECURITY_ENTITY_DRV SEC         ON PR.BUSINESS_UNIT_GL = SEC.PS_GL AND PR.DEPTID = SEC.PS_DEPT_ID
	INNER JOIN MD_PRODUCT_CODE MPC                ON RES.TRNPC_MFG_PROD_CD = MPC.PRODUCT_CODE_VALUE
	WHERE
		0 = 0
		AND PR.BUSINESS_UNIT IN('PCGUS', 'PCGCN')
		AND PR.ANALYSIS_TYPE = 'REV'
		AND(PR.ACCOUNT = '700000'
		OR PR.ACCOUNT = '700020')
		AND PR.GL_DISTRIB_STATUS = 'G'
		AND JBCD.JOB_CLASS_ID = 38
		AND PR.ACCOUNTING_DT BETWEEN TRUNC(ADD_MONTHS(SYSDATE, - 24), 'MM') AND TRUNC(ADD_MONTHS(LAST_DAY(SYSDATE), - 1))
		AND TO_NUMBER(TO_CHAR(PR.ACCOUNTING_DT, 'YYYY')) * 100 + TO_NUMBER(TO_CHAR(PR.ACCOUNTING_DT, 'MM')) = 201703
		AND SEC.NATION_CURRENCY = 'USD' ;
SELECT
		/*+   ORDERED NO_CPU_COSTING  INDEX(PR XAK1AP_135_PROJ_RESOURCE)*/
		SUM(NVL(CD.RESOURCE_AMOUNT, 0)) AS REVENUE_AMOUNT
	FROM
		R12_PROJ_RESOURCE_PS PR
	INNER JOIN AP_135_TRNPC_PROJ_RES RES          ON PR.BUSINESS_UNIT = RES.BUSINESS_UNIT AND PR.PROJECT_ID = RES.PROJECT_ID AND PR.RESOURCE_ID = RES.RESOURCE_ID AND PR.ACTIVITY_ID = RES.ACTIVITY_ID
	INNER JOIN AP_400_SEL_CRED_JB_CLSS_CD JBCLSCD ON PR.PROJECT_ID = CAST(JBCLSCD.CREDIT_JOB_ID AS VARCHAR2(15 BYTE))
	INNER JOIN AP_400_JOB_CODE JBCD               ON JBCD.JOB_CODE_ID = JBCLSCD.JOB_CODE_ID
	INNER JOIN AP_135_TRNPC_COMM_DATA CD          ON PR.BUSINESS_UNIT = CD.BUSINESS_UNIT AND PR.PROJECT_ID = CD.PROJECT_ID AND PR.RESOURCE_ID = CD.RESOURCE_ID AND PR.ACTIVITY_ID = CD.ACTIVITY_ID
	INNER JOIN AP_400_COMM_CODE CC                ON CD.TRNPC_COMM_CODE = CC.COMM_CODE AND CD.SALES_OFFICE_ID = CC.SALES_OFFICE_ID
	INNER JOIN OTR_PROD_CODE_XREF_RCPO PX         ON RES.TRNPC_MFG_PROD_CD = PX.MANF_PROD_CODE AND PX.GL_LEDGER = 'CSD'
	INNER JOIN MD_SECURITY_ENTITY_DRV SEC         ON PR.PS_BUSINESS_UNIT_GL = SEC.PS_GL AND PR.PS_DEPTID = SEC.PS_DEPT_ID
	WHERE
		PR.BUSINESS_UNIT IN('PCGUS', 'PCGCN')
		AND PR.ANALYSIS_TYPE = 'REV'
		AND PR.PS_ACCOUNT IN('700000', '700020')
		AND PR.GL_DISTRIB_STATUS = 'G'
		AND JBCD.JOB_CLASS_ID = 38
		-- AND TRUNC(PR.ACCOUNTING_DT) >= TO_DATE('01/01/2007', 'MM/DD/YYYY')
		-- AND TRUNC(PR.ACCOUNTING_DT) <= TO_DATE('12/31/2050', 'MM/DD/YYYY')
		AND PR.R12_ENTITY IN('5773', '5588', '5575', '5612', '5743', '9256', '9258', '9298', '9299')
		AND TO_NUMBER(TO_CHAR(PR.ACCOUNTING_DT, 'YYYY')) * 100 + TO_NUMBER(TO_CHAR(PR.ACCOUNTING_DT, 'MM')) = 201703
		AND SEC.NATION_CURRENCY = 'USD';