			SELECT
					/*+ INDEX(AP_400_SEL_CRED_JB_CLSS_CD XIE2AP_400_SEL_CRED_JB_CLSS_CD) */
					/* 'PUEBLO' Source Query */
					(CD.RESOURCE_AMOUNT) AS REVENUE_AMOUNT,
					TO_NUMBER(TO_CHAR(PR.ACCOUNTING_DT, 'YYYY')) * 100 + TO_NUMBER(TO_CHAR(PR.ACCOUNTING_DT, 'MM')) AS JRNL_YEAR_MONTH,
					pr.accounting_dt,
					SEC.NATION_CURRENCY AS COUNTRY_INDICATOR,
					'PUEBLO',
					PR.JOURNAL_ID,
					pr.*
				FROM
					AP_135_PROJ_RESOURCE PR
					INNER JOIN AP_135_TRNPC_PROJ_RES RES ON PR.BUSINESS_UNIT = RES.BUSINESS_UNIT AND PR.PROJECT_ID = RES.PROJECT_ID	AND PR.RESOURCE_ID = RES.RESOURCE_ID AND PR.ACTIVITY_ID = RES.ACTIVITY_ID
					INNER JOIN AP_400_SEL_CRED_JB_CLSS_CD JBCLSCD ON PR.PROJECT_ID = TO_CHAR(JBCLSCD.CREDIT_JOB_ID)
					INNER JOIN AP_400_JOB_CODE JBCD ON JBCD.JOB_CODE_ID = JBCLSCD.JOB_CODE_ID
					INNER JOIN AP_135_TRNPC_COMM_DATA CD ON PR.BUSINESS_UNIT = CD.BUSINESS_UNIT	AND PR.PROJECT_ID = CD.PROJECT_ID	AND PR.RESOURCE_ID = CD.RESOURCE_ID	AND PR.ACTIVITY_ID = CD.ACTIVITY_ID
					INNER JOIN AP_400_COMM_CODE CC ON CD.TRNPC_COMM_CODE = CC.COMM_CODE	AND CD.SALES_OFFICE_ID = CC.SALES_OFFICE_ID
					INNER JOIN MD_SECURITY_ENTITY_DRV SEC ON PR.BUSINESS_UNIT_GL = SEC.PS_GL	AND PR.DEPTID = SEC.PS_DEPT_ID
					INNER JOIN MD_PRODUCT_CODE MPC ON RES.TRNPC_MFG_PROD_CD = MPC.PRODUCT_CODE_VALUE
				WHERE 0=0
					and CD.RESOURCE_AMOUNT < -4000
					and PR.ACCOUNTING_DT = '28-feb-17'
					AND PR.BUSINESS_UNIT IN('PCGUS', 'PCGCN')
					AND PR.ANALYSIS_TYPE = 'REV'
					AND(PR.ACCOUNT = '700000' OR PR.ACCOUNT = '700020')
					AND PR.GL_DISTRIB_STATUS = 'G'
					AND JBCD.JOB_CLASS_ID = 38
					AND PR.ACCOUNTING_DT BETWEEN TRUNC(ADD_MONTHS(SYSDATE, - 24), 'MM') AND TRUNC(ADD_MONTHS(LAST_DAY(SYSDATE), - 1))
					AND TO_NUMBER(TO_CHAR(PR.ACCOUNTING_DT, 'YYYY')) * 100 + TO_NUMBER(TO_CHAR(PR.ACCOUNTING_DT, 'MM')) = 201702;