SELECT
		ACCOUNTING_DT,
		JOURNAL_DATE,
		SUM(CD.RESOURCE_AMOUNT) AS REVENUE_AMOUNT
	FROM
		AP_135_PROJ_RESOURCE PR
	INNER JOIN AP_135_TRNPC_COMM_DATA CD ON PR.BUSINESS_UNIT = CD.BUSINESS_UNIT AND PR.PROJECT_ID = CD.PROJECT_ID AND PR.RESOURCE_ID = CD.RESOURCE_ID AND PR.ACTIVITY_ID = CD.ACTIVITY_ID
	WHERE
		0 = 0
		--  AND TO_NUMBER(TO_CHAR(ACCOUNTING_DT, 'YYYY')) * 100 + TO_NUMBER(TO_CHAR(ACCOUNTING_DT, 'MM')) = 201703
		AND ACCOUNTING_DT = '31-mar-17'
		AND PR.BUSINESS_UNIT IN('PCGUS', 'PCGCN')
		AND PR.ANALYSIS_TYPE = 'REV'
		--  AND PR.PS_ACCOUNT IN('700000', '700020')
		AND PR.ACCOUNT IN('700000', '700020')
		AND PR.GL_DISTRIB_STATUS = 'G'
		AND PR.ACCOUNTING_DT = '31-MAR-17'
	GROUP BY
		ACCOUNTING_DT,
		JOURNAL_DATE
	ORDER BY
		1 DESC;
--
SELECT
		ACCOUNTING_DT,
		JOURNAL_DATE,
		SUM(CD.RESOURCE_AMOUNT) AS REVENUE_AMOUNT
	FROM
		R12_PROJ_RESOURCE_PS PR
	INNER JOIN AP_135_TRNPC_COMM_DATA CD ON PR.BUSINESS_UNIT = CD.BUSINESS_UNIT AND PR.PROJECT_ID = CD.PROJECT_ID AND PR.RESOURCE_ID = CD.RESOURCE_ID AND PR.ACTIVITY_ID = CD.ACTIVITY_ID
	WHERE
		0 = 0
		AND ACCOUNTING_DT = '31-mar-17'
		AND PR.BUSINESS_UNIT IN('PCGUS', 'PCGCN')
		AND PR.ANALYSIS_TYPE = 'REV'
		AND PR.PS_ACCOUNT IN('700000', '700020')
		--  AND PR.ACCOUNT IN('700000', '700020')
		AND PR.GL_DISTRIB_STATUS = 'G'
	GROUP BY
		ACCOUNTING_DT,
		JOURNAL_DATE
	ORDER BY
		1 DESC;
SELECT * FROM R12_PROJ_RESOURCE_PS pr WHERE ROWNUM < 2 
		AND ACCOUNTING_DT = '31-mar-17'
		AND PR.BUSINESS_UNIT IN('PCGUS', 'PCGCN')
		AND PR.ANALYSIS_TYPE = 'REV'
		AND PR.PS_ACCOUNT IN('700000', '700020')
		--  AND PR.ACCOUNT IN('700000', '700020')
		AND PR.GL_DISTRIB_STATUS = 'G';