SELECT DISTINCT QUERY_SOURCE FROM MAP_SALES_DATA;
SELECT * FROM MAP_SALES_DATA WHERE QUERY_SOURCE = 'P21R12';
SELECT DISTINCT
		MANF_PROD_ID,
		QUERY_SOURCE
	FROM
		MAP_SALES_DATA
	WHERE
		MANF_PROD_ID IN('CNONP', 'CONN', 'CPROG', 'TYP', 'XSTAT', 'XZONE')
	GROUP BY
		MANF_PROD_ID,
		QUERY_SOURCE;
SELECT DISTINCT
		MANF_PROD_ID
	FROM
		MAP_SALES_DATA
	WHERE
		0 = 0
		--   and QUERY_SOURCE = 'P21R12'
		AND MANF_PROD_ID IN('CNONP', 'CONN', 'CPROG', 'TYP', 'XSTAT', 'XZONE') ;
SELECT * FROM DBO.R12_BI_ACCT_ENTRY_STG;
SELECT DISTINCT R12_PRODUCT FROM R12_BI_ACCT_ENTRY_STG;
SELECT * FROM R12_BI_LINE_STG;
SELECT DISTINCT
		MANF_PROD_ID
	FROM
		R12_BI_LINE_STG
	WHERE
		MANF_PROD_ID IN('CNONP', 'CONN', 'CPROG', 'TYP', 'XSTAT', 'XZONE') ;
SELECT DISTINCT
		MANF_PROD_ID
	FROM
		R12_BI_LINE_PSB
	WHERE
		MANF_PROD_ID IN('CNONP', 'CONN', 'CPROG', 'TYP', 'XSTAT', 'XZONE') ;
SELECT * FROM R12_PROJ_RESOURCE_PS ORDER BY ACCOUNTING_DT DESC;
SELECT
	query_source,
		SUM(
		CASE WHEN QUERY_SOURCE = 'PUEBLO'
			THEN NVL(REVENUE_AMOUNT / 1000000, 0)
			ELSE NVL(REVENUE_AMOUNT / 1000000, 0) * - 1
		END) AS REVENUE_AMOUNT
	FROM
		MAP_SALES_DATA
	WHERE
		COUNTRY_INDICATOR = 'USD'
		-- AND JRNL_DATE BETWEEN '01-mar-17' AND '31-mar-17'
		and jrnl_year_month = 201703
	group by query_source;

SELECT * FROM MAP_SALES_DATA;

select * from DBO.R12_Bi_Acct_Entry_STG;

SELECT
		SUM(NVL(REVENUE_AMT / 1000000, 0))
	FROM
		SY_031_SALES_SUM_STG
	WHERE
		SHIP_PERIOD = 201703
		AND COUNTRY_INDICATOR = 'USD';


SELECT
    JRNL_YEAR_MONTH AS SHIP_PERIOD,
    query_source,
    NVL(SUM(REVENUE_AMOUNT), 0) AS REVENUE_AMT,
		SUM(RA)
 FROM
    (
SELECT
      CAST(TO_CHAR(JRNL_DATE, 'YYYY') AS INTEGER) * 100 + CAST(TO_CHAR(JRNL_DATE, 'MM') AS INTEGER) JRNL_YEAR_MONTH,
			query_source,
      -- For PUEBLO data, leave sign as is. Reverse the sign for all other values.      
      SUM(case when query_source = 'PUEBLO' 
        then REVENUE_AMOUNT
        else revenue_amount * -1
      end) as revenue_amount,
					SUM(
		CASE WHEN QUERY_SOURCE = 'PUEBLO'
			THEN NVL(REVENUE_AMOUNT / 1000000, 0)
			ELSE NVL(REVENUE_AMOUNT / 1000000, 0) * - 1
		END) AS RA
    FROM
      MAP_SALES_DATA
    WHERE 0=0
      and JRNL_DATE BETWEEN TRUNC(ADD_MONTHS(SYSDATE, - 24), 'MM') AND TRUNC(ADD_MONTHS(LAST_DAY(SYSDATE), - 1))
			and jrnl_year_month = 201703
    GROUP BY
      CAST(TO_CHAR(JRNL_DATE, 'YYYY') AS INTEGER) * 100 + CAST(TO_CHAR(JRNL_DATE, 'MM') AS INTEGER),
			query_source
      )
  GROUP BY
    JRNL_YEAR_MONTH,
		QUERY_SOURCE;
		
		
		SELECT
    JRNL_YEAR_MONTH AS SHIP_PERIOD,
    COUNTRY_INDICATOR,
    NVL(SUM(REVENUE_AMOUNT), 0) AS REVENUE_AMT,
    SYSDATE AS ED_CREATE_DATE,
    'SY_031_SALES_SUM_STG.sql' AS ED_CREATE_ID,
    SYSDATE AS ED_UPDATE_DATE,
    'SY_031_SALES_SUM_STG.sql' AS ED_UPDATE_ID
  FROM
    (
SELECT
      CAST(TO_CHAR(JRNL_DATE, 'YYYY') AS INTEGER) * 100 + CAST(TO_CHAR(JRNL_DATE, 'MM') AS INTEGER) JRNL_YEAR_MONTH,
      COUNTRY_INDICATOR,
      -- For PUEBLO data, leave sign as is. Reverse the sign for all other values.      
      SUM(case when query_source = 'PUEBLO' 
        then REVENUE_AMOUNT
        else revenue_amount * -1
      end) as revenue_amount
    FROM
      MAP_SALES_DATA
    WHERE
      JRNL_DATE BETWEEN TRUNC(ADD_MONTHS(SYSDATE, - 24), 'MM') AND TRUNC(ADD_MONTHS(LAST_DAY(SYSDATE), - 1))
    GROUP BY
      CAST(TO_CHAR(JRNL_DATE, 'YYYY') AS INTEGER) * 100 + CAST(TO_CHAR(JRNL_DATE, 'MM') AS INTEGER),
      COUNTRY_INDICATOR
      )
  GROUP BY
    JRNL_YEAR_MONTH,
    COUNTRY_INDICATOR
		ORDER BY JRNl_year_month desc;