SELECT DISTINCT
		MIC.SEGMENT6
	FROM
		MTL_ITEM_CATEGORIES_V MIC,
		MTL_SYSTEM_ITEMS MSI1
	WHERE
		MIC.INVENTORY_ITEM_ID = MSI1.INVENTORY_ITEM_ID
		AND MIC.CATEGORY_SET_NAME = 'IRPLN SIOP CATEGORY'
		AND MIC.ORGANIZATION_ID = MSI1.ORGANIZATION_ID
		-- AND ROWNUM = 1
		AND MIC.SEGMENT6 IN('CNONP', 'CONN', 'CPROG', 'TYP', 'XSTAT', 'XZONE')
;

-- results TYP,CONN,XSTAT