desc R12_Bi_Acct_Entry_Stg_T;

select * from r12_bi_acct_entry_stg_t where claim_number like 'C%';
select * from r12_bi_acct_entry_stg_t where invoice = 50005234 and customer_trx_id = 50671502;
select * from r12_bi_acct_entry_stg where monetary_amount = -403.74;

select journal_date, count(*), sum(Monetary_Amount)
from r12_bi_acct_entry_stg_t 
where 0=0 -- claim_number like 'C%'
group by journal_date
order by 1 desc;

select distinct entry_type, count(*)
FROM R12_BI_ACCT_ENTRY_STG_t A
		INNER JOIN R12_TRNBI_BI_HDR_STG_t B
			ON A.INVOICE = B.INVOICE AND A.CUSTOMER_TRX_ID = B.CUSTOMER_TRX_ID
		INNER JOIN R12_BI_HDR_STG_t C
			ON B.INVOICE = C.INVOICE AND B.CUSTOMER_TRX_ID = C.CUSTOMER_TRX_ID
group by entry_type;

select a.claim_number, a.* 
FROM R12_BI_ACCT_ENTRY_STG_t A
INNER JOIN R12_TRNBI_BI_HDR_STG_t B
	ON A.INVOICE = B.INVOICE AND A.CUSTOMER_TRX_ID = B.CUSTOMER_TRX_ID
INNER JOIN R12_BI_HDR_STG_t C
	ON B.INVOICE = C.INVOICE AND B.CUSTOMER_TRX_ID = C.CUSTOMER_TRX_ID
WHERE ENTRY_TYPE = 'INV'
;
select a.claim_number, a.* 
FROM R12_BI_ACCT_ENTRY_STG_t A
INNER JOIN R12_TRNBI_BI_HDR_STG_t B
	ON A.INVOICE = B.INVOICE AND A.CUSTOMER_TRX_ID = B.CUSTOMER_TRX_ID
INNER JOIN R12_BI_HDR_STG_t C
	ON B.INVOICE = C.INVOICE AND B.CUSTOMER_TRX_ID = C.CUSTOMER_TRX_ID
WHERE claim_number like 'C-20000402%'
;



-- YTD 1
		SELECT
			CASE
				WHEN A.R12_ENTITY IN('5773', '5588') THEN 'CAN'
				ELSE 'USA'
				END AS COUNTRY_INDICATOR,
			A.R12_ACCOUNT Account, 
			AFU.DESCR, 
			A.MONETARY_AMOUNT * - 1 AS REVENUE_AMOUNT,
			C.ENTRY_TYPE,
			a.r12_entity,
			a.journal_date
			
		FROM R12_BI_ACCT_ENTRY_STG A
		INNER JOIN R12_TRNBI_BI_HDR_STG B
			ON A.INVOICE = B.INVOICE AND A.CUSTOMER_TRX_ID = B.CUSTOMER_TRX_ID
		INNER JOIN R12_BI_HDR_STG C
			ON B.INVOICE = C.INVOICE AND B.CUSTOMER_TRX_ID = C.CUSTOMER_TRX_ID
		INNER JOIN R12_ACCOUNT_FILTER_UPD AFU
			ON AFU.R12_ACCOUNT = A.R12_ACCOUNT
		
		WHERE 0=0
		AND A.R12_ENTITY IN ('5773', '5588', '5575', '5612', '5743', '9256', '9258', '9298', '9299', '9984')
		AND C.ENTRY_TYPE in ('INV', 'CM')
		AND AFU.LIKE_5 = 'Y'
		AND A.R12_ACCOUNT = 282109
		and A.claim_number like 'C%'
;
		
-- YTD4
SELECT
  SUM(A.MONETARY_AMOUNT),
  A.R12_ACCOUNT AS Account, 
  AFU.DESCR AS ACCOUNT_DESC, 
  CASE
    WHEN A.R12_ENTITY IN('5773', '5588') THEN 'CAN'
    ELSE 'USA'
    END AS COUNTRY_INDICATOR
  
FROM R12_BI_ACCT_ENTRY_STG A
INNER JOIN R12_TRNBI_BI_HDR_STG B
ON A.INVOICE = B.INVOICE AND A.CUSTOMER_TRX_ID = B.CUSTOMER_TRX_ID
INNER JOIN R12_BI_HDR_STG C
ON B.INVOICE = C.INVOICE AND B.CUSTOMER_TRX_ID = C.CUSTOMER_TRX_ID
INNER JOIN R12_ACCOUNT_FILTER_UPD AFU
ON AFU.R12_ACCOUNT = A.R12_ACCOUNT

WHERE 0=0
AND A.R12_ENTITY IN ('5773', '5588', '5575', '5612', '5743', '9256', '9258', '9298', '9299', '9984')
AND AFU.LIKE_5 = 'Y'
AND A.R12_LOCATION IN('113602', '115615' /* USA */, '129003' /* CANADA */)
AND C.ENTRY_TYPE in ('CR','CM')
		and claim_number like 'C%'  
GROUP BY A.R12_ACCOUNT, 
  AFU.DESCR, 
  CASE
    WHEN A.R12_ENTITY IN('5773', '5588') THEN 'CAN'
    ELSE 'USA'
    END
;

-- MTD 1
    SELECT
      CASE
        WHEN A.R12_ENTITY IN('5773', '5588') THEN 'CAN'
        ELSE 'USA'
        END AS COUNTRY_INDICATOR, 
      A.R12_ACCOUNT AS ACCOUNT, 
      AFU.DESCR, 
      A.MONETARY_AMOUNT * - 1 AS REVENUE_AMOUNT
			, c.entry_type
			, a.claim_number
			, a.invoice
			
      
    FROM R12_BI_ACCT_ENTRY_STG A
    INNER JOIN R12_TRNBI_BI_HDR_STG B
      ON A.INVOICE = B.INVOICE 
      AND A.CUSTOMER_TRX_ID = B.CUSTOMER_TRX_ID
    INNER JOIN R12_BI_HDR_STG C
      ON B.INVOICE = C.INVOICE 
      AND B.CUSTOMER_TRX_ID = C.CUSTOMER_TRX_ID
    INNER JOIN R12_ACCOUNT_FILTER_UPD AFU
      ON AFU.R12_ACCOUNT = A.R12_ACCOUNT
      
    WHERE 0=0
    AND A.R12_ENTITY IN ('5773', '5588', '5575', '5612', '5743', '9256', '9258', '9298', '9299', '9984')
    AND C.ENTRY_TYPE in ('INV','CM')
    AND AFU.LIKE_5 = 'Y'
		and claim_number like 'C%'
		order by claim_number, invoice, monetary_amount
;

-- MTD4
SELECT
  SUM(A.MONETARY_AMOUNT),
  A.R12_ACCOUNT AS Account, 
  AFU.DESCR AS ACCOUNT_DESC,  
  CASE
    WHEN A.R12_ENTITY IN('5773', '5588')
    THEN 'CAN'
    ELSE 'USA'
  END AS COUNTRY_INDICATOR
  
FROM R12_BI_ACCT_ENTRY_STG A
INNER JOIN R12_TRNBI_BI_HDR_STG B
  ON A.INVOICE = B.INVOICE AND A.CUSTOMER_TRX_ID = B.CUSTOMER_TRX_ID
INNER JOIN R12_BI_HDR_STG C
  ON B.INVOICE = C.INVOICE AND B.CUSTOMER_TRX_ID = C.CUSTOMER_TRX_ID
INNER JOIN R12_ACCOUNT_FILTER_UPD AFU
  ON AFU.R12_ACCOUNT = A.R12_ACCOUNT

WHERE 0=0
AND A.R12_ENTITY IN('5773', '5588', '5575', '5612', '5743', '9256', '9258', '9298', '9299', '9984')
AND AFU.LIKE_5 = 'Y'
AND A.R12_LOCATION IN ('113602', '115615' /* USA */, '129003' /* CANADA */)
AND C.ENTRY_TYPE in ( 'CR', 'CM')
		and claim_number like 'C%'
GROUP BY A.R12_ACCOUNT, 
  AFU.DESCR, 
  A.R12_ENTITY
;

select distinct entry_type from R12_BI_HDR_STG;
select * from R12_Bi_Acct_Entry_Stg_T where claim_number like 'C-20000%';

select * from R12_Bi_Acct_Entry_Stg_T where claim_number like 'C%' order by journal_date desc;

grant select on R12_Bi_Acct_Entry_Stg_T to READ_DBO;