SELECT
	count(*)
	FROM
		WC_MAT_LBR_ROLLUP MLR
	INNER JOIN EXPENSE_TYPE_SCD ET               ON MLR.EXPENSE_TYPE_SCD_KEY = ET.EXPENSE_TYPE_SCD_KEY
	-- INNER JOIN DM_FAL_CLAIMS_WARRANTY_XRF FCW    ON MLR.CLAIM_NBR = FCW.CLAIM_NBR AND MLR.DETAIL_NBR = FCW.DETAIL_NBR AND MLR.STEP_NBR = FCW.STEP_NBR
	INNER JOIN TIME_DAY TD3                      ON MLR.CCN_TRX_DATE_KEY = TD3.TIME_KEY
	INNER JOIN TIME_DAY TD2                      ON MLR.ORIGINAL_SHIP_DATE_KEY = TD2.TIME_KEY
	INNER JOIN TIME_DAY TD1                      ON MLR.FAIL_DATE_KEY = TD1.TIME_KEY
	INNER JOIN TIME_DAY TD                       ON MLR.START_DATE_KEY = TD.TIME_KEY
	INNER JOIN CLAIM_TASK_SCD CTASKS             ON MLR.CLAIM_TASK_SCD_KEY = CTASKS.CLAIM_TASK_SCD_KEY
	INNER JOIN CLAIM_TYPE_SCD CTYPES             ON MLR.CLAIM_TYPE_SCD_KEY = CTYPES.CLAIM_TYPE_SCD_KEY
	INNER JOIN R12_GL_ACCOUNT_SCD GLA            ON MLR.GL_ACCOUNT_SCD_KEY = GLA.GL_ACCOUNT_SCD_KEY
	INNER JOIN EXPENSE_TYPE_SCD ETS              ON MLR.EXPENSE_TYPE_SCD_KEY = ETS.EXPENSE_TYPE_SCD_KEY
	INNER JOIN PROD_CODE_SCD PCS                 ON MLR.PROD_CODE_SCD_KEY = PCS.PROD_CODE_SCD_KEY
	INNER JOIN CUST_ACCOUNT_SCD CACCT            ON MLR.CUST_ACCOUNT_SCD_KEY = CACCT.CUST_ACCOUNT_SCD_KEY
	INNER JOIN SUBMIT_OFFICE_SCD SOS             ON MLR.SUBMIT_OFFICE_SCD_KEY = SOS.SUBMIT_OFFICE_SCD_KEY
	INNER JOIN PROD_CODE_XREF_RCPO_DR PRODGRP    ON GLA.PS_COMPANY = PRODGRP.GL_LEDGER AND PCS.PROD_CODE = PRODGRP.MANF_PROD_CODE
	INNER JOIN UD_031_RETROFIT_RULES RES_PCT     ON CTYPES.CLAIM_TYPE_DESCR = RES_PCT.CLAIM_TYPE AND ETS.EXPENSE_TYPE_DESCR = RES_PCT.EXPENSE_TYPE_DESCR AND SOS.COMPANY_OWNED_IND = RES_PCT.COMPANY_OWNED_IND
	INNER JOIN UD_031_RETROFIT_ID RD             ON 1 = 1 AND MLR.RETRO_ID = RD.RETROFIT_ID
	INNER JOIN UD_031_STDWTY_RSV_CLM_ADJ A       ON MLR.CLAIM_NBR = A.CLAIM_NUMBER
	INNER JOIN DM_WAR_CSN_RSV_PCT_REF RS_RES_PCT ON A.CLAIM_TYPE = RS_RES_PCT.CLAIM_TYPE
	WHERE
		MLR.CLAIM_TYPE_SCD_KEY = 3
		AND MLR.CCN_TRX_NBR IS NOT NULL
		AND
		CASE WHEN CACCT.CUST_CREDIT_CATG_CODE = 'Z1'
			THEN 'Y'
			ELSE 'N'
		END = RES_PCT.CUST_CREDIT_CATG_CODE
		AND PRODGRP.PRODUCT_CATEGORY IS NOT NULL
		AND TD3.FULL_DATE >= TO_DATE('1/1/1890', 'MM/DD/YYYY')
		AND TD3.FULL_DATE <= TO_DATE('12/31/2050', 'MM/DD/YYYY')
	 