
SELECT
		CA.CLAIM_NUMBER,
		CA.CREDIT_MEMO_NUMBER,
		CA.FOR_CLAIM,
		CA.CLAIM_ID,
		'Commissions' AS COST_CATEGORY,
		CASE CR_DR_FLAG           WHEN 'CR'
			THEN CD.SPLIT_AMOUNT_AMT WHEN 'DR'
			THEN CD.SPLIT_AMOUNT_AMT * - 1
		END AS GL_AMT,
		CD.SPLIT_AMOUNT_CURR AS GL_CURR
	FROM
		(
			SELECT DISTINCT
					C.CLAIM_NUMBER,
					C.ID CLAIM_ID,
					C.SERVICE_INFORMATION,
					CA.FOR_CLAIM,
					CM.CREDIT_MEMO_NUMBER,
					CM.CR_DR_FLAG
				FROM
					CLAIM C
				INNER JOIN CLAIM_AUDIT CA ON CA.FOR_CLAIM = C.ID
				INNER JOIN PAYMENT P      ON P.ID = CA.PAYMENT
				INNER JOIN CREDIT_MEMO CM ON P.ACTIVE_CREDIT_MEMO = CM.ID
		)
		CA
	INNER JOIN CLAIMED_ITEM                   ON CA.CLAIM_ID = CLAIMED_ITEM.CLAIM
	INNER JOIN INVENTORY_ITEM                 ON CLAIMED_ITEM.ITEM_REF_INV_ITEM = INVENTORY_ITEM.ID
	INNER JOIN SERVICE_INFORMATION SI         ON CA.SERVICE_INFORMATION = SI.ID
	INNER JOIN SERVICE S                      ON SI.SERVICE_DETAIL = S.ID
	INNER JOIN SERVICE_COMMISSION_DETAILS SCD ON S.ID = SCD.SERVICE
	INNER JOIN COMMISSION_DETAIL CD           ON SCD.COMMISSION_DETAILS = CD.ID
	WHERE
		CA.CLAIM_NUMBER IN('C-20000562') -- 'C-20000138','C-20000073','C-20000562')
	ORDER BY
		1,
		2,
		COMMISSION_SPLIT,
		SPLIT_AMOUNT_AMT ;
SELECT
		SI.*
	FROM
		CLAIM C
	INNER JOIN SERVICE_INFORMATION SI ON C.SERVICE_INFORMATION = SI.ID
	WHERE
		C.CLAIM_NUMBER = 'C-20000562' ;
SELECT
		C.CLAIM_NUMBER,
		Cm.Credit_Memo_Number,
		CA.*
	FROM
		CLAIM C
	INNER JOIN CLAIM_AUDIT CA ON C.ID = CA.FOR_CLAIM
		INNER JOIN PAYMENT P              ON P.ID = CA.PAYMENT
		INNER JOIN CREDIT_MEMO CM         ON P.ACTIVE_CREDIT_MEMO = CM.ID	WHERE
		C.CLAIM_NUMBER = 'C-20000124' ;
		
SELECT
		C.CLAIM_NUMBER
	FROM
		CLAIM C
	INNER JOIN CLAIM_AUDIT CA ON C.ID = CA.FOR_CLAIM
		INNER JOIN PAYMENT P              ON P.ID = CA.PAYMENT
		INNER JOIN CREDIT_MEMO CM         ON P.ACTIVE_CREDIT_MEMO = CM.ID	
	GROUP BY C.CLAIM_NUMBER
	HAVING count(distinct cm.credit_memo_NUMBER) > 1
	order by 1
;

