/* $Workfile: BI_HDR_PSB_INC.sql $
*  $Revision: 4 $
*  $Archive: /DRTRNT_or_P/PeopleSoft Billing and RCPO - 115/Tables/OTR_BI_HDR_PSB/BI_HDR_PSB_INC.sql $
*  $Author: Laiqi $
*  $Date: 12/31/11 12:11p $
*
* Description: This table is loaded from Peoplesoft databases FSTRNx.  It is an incremental load that does a truncate/insert
*     on the current partition (NO Archive) which holds the curren year plus two previous years of data.  This was implemented to improve
*     load performance.  An extra check is performed during the month of January to move the oldest year into the non-current
*     (YES Archive) partition.
*
* Destination table = DRTRNx.DBO.OTR_BI_HDR_PSB
* Source table = FSTRNX.SYSADM.PS_BI_HDR
* 
* Revisions: 
* 
*   change Date    Description 
*   -----------------    ------------------- 
*   06/16/2009     Neeraja V,Cognizant - Self-running script. TTP #7916.
*   03/30/2010     Chinnathambi S,Cognizant - ED to DR Migration TTP 7578
*   04/05/2010     Chinnathambi S,Cognizant - Alignment changes TTP 7578
*   07/08/2010     Andrew Wiersma,Trane - Added our Index code TTP 7578
*   06/17/2011     Nithin Raj,Cognizant -  Modified to incremental load to reload present year and past two year data - TTP 10014
*   11/23/2011     Bhavani,Cognizant - Modified the script to move data from non-archive partition into archive partition if more than 3years in
*                                                     january month- TTP 10014
***********************************************************************************/ 
set timing on
set pause off
set feedback on
set echo on

spool bi_hdr_psb_inc.log  
whenever sqlerror exit failure;

prompt User and Database Connected To:
select user, name from v$database;

prompt inserting data into OTR_BI_HDR_PSB
DECLARE

V_START_DATE DATE:=ADD_MONTHS (TRUNC (SYSDATE, 'YYYY'), -24);

BEGIN
/* Perform this check all of Jan to avoid losing data if the module is not run for some reason.
  Checks the data warehouse table to see if there is any data in the No Archive partition that is older than the 3 years that
  will be loaded daily.  If there is, it is moved to the Yes Archive partition before the truncate so that it will not be lost.  The only
  time this can occur is in January of a new year. */
IF TO_NUMBER(TO_CHAR(TRUNC(SYSDATE),'MMDD')) BETWEEN  0101 AND 0131 THEN
insert /*+ APPEND */ into OTR_BI_HDR_PSB
(BUSINESS_UNIT
, INVOICE
, INVOICE_TYPE
, CONSOL_HDR
, CONSOL_KEY
, CONSOL_SETID
, CONSOL_CUST_ID
, CONSOL_BUS_UNIT
, CONSOL_INVOICE
, ORIGINAL_INVOICE
, PRIOR_ADJ_INVOICE
, NEXT_ADJ_INVOICE
, LATEST_INVOICE
, ADJUSTED_FLAG
, BILL_TYPE_ID
, BILL_SOURCE_ID
, BILL_CYCLE_ID
, BILL_BY_ID
, HDR_FIELDS_KEY
, BILLING_FREQUENCY
, TEMPLATE_IVC_FLG
, TEMPLATE_INVOICE
, AUTO_GEN_IVC_NUM
, FROM_DT
, BILL_TO_CUST_ID
, ADDRESS_SEQ_NUM
, BILL_TO_COPIES
, BILL_TO_MEDIA
, CNTCT_SEQ_NUM
, NAME1
, BUSINESS_UNIT_TO
, CR_CARD_FLG
, SUBCUST_QUAL1
, SUBCUST_QUAL2
, BILL_INQUIRY_PHONE
, BILLING_SPECIALIST
, COLLECTOR
, SALES_PERSON
, CR_ANALYST
, PYMNT_TERMS_CD
, BANK_CD
, BANK_ACCT_KEY
, BI_CURRENCY_CD
, BASE_CURRENCY
, CURRENCY_CD_XEU
, FINAL_CURCNV_FLG
, CUR_RT_TYPE
, CUR_RT_SOURCE
, RATE_MULT
, RATE_DIV
, RATE_MULT_XEU
, RATE_DIV_XEU
, RATE_MULT_IU
, RATE_DIV_IU
, RATE_DATE
, PAID_AMT
, FORWARD_BAL_AMT
, INVOICE_AMT_PRETAX
, INVOICE_AMOUNT
, PAID_AMT_BSE
, FORWARD_BAL_BSE
, INVOICE_PRETAX_BSE
, INVOICE_AMT_BSE
, FORWARD_BAL_XEU
, INVOICE_PRETAX_XEU
, INVOICE_AMT_XEU
, PAID_AMT_XEU
, INVOICE_DT
, ACCOUNTING_DT
, DT_INVOICED
, DUE_DT
, INVOICE_FORM_ID
, IVC_PRINTED_FLG
, IVC_PRINTED_DT
, EDI_SENT_FLG
, ENTRY_TYPE
, ENTRY_REASON
, AR_LVL
, AR_DST_OPT
, DST_ID_AR
, ACCOUNT
, ALTACCT
, OPERATING_UNIT
, DEPTID
, PRODUCT
, AFFILIATE
, STATISTICS_CODE
, AR_ENTRY_CREATED
, BUSINESS_UNIT_GL
, GL_LVL
, GL_ENTRY_CREATED
, ENABLE_DFR_REV_FLG
, DFR_ACCTG_DT_CD
, DFR_REV_PRORATION
, DFR_MID_PERIOD_DAY
, DST_ID_DFR
, BILL_STATUS
, BILL_STATUS_TEXT
, MANUAL_LIN_NUM_FLG
, LAST_LINE_SEQ_NUM
, LAST_LINE_AAUX_SEQ
, LAST_NOTE_SEQ_NUM
, ACCRUE_UNBILLED
, DOC_TYPE
, DOC_SEQ_NBR
, DOC_SEQ_DATE
, PC_DISTRIB_STATUS
, PO_REF
, BUSINESS_UNIT_CA
, CONTRACT_NUM
, CONTRACT_DT
, CONTRACT_TYPE
, DIRECT_INVOICING
, BUSINESS_UNIT_OM
, ORDER_NO
, RMA_ID
, ORDER_DATE
, FREIGHT_TERMS
, BILL_OF_LADING
, SHIP_TO_CUST_ID
, SHIP_TO_ADDR_NUM
, SHIP_ID
, SHIP_TYPE_ID
, SHIP_FROM_BU
, SOLD_TO_CUST_ID
, SOLD_TO_ADDR_NUM
, BUSINESS_UNIT_PC
, PROJECT_ID
, ANALYSIS_TYPE
, RESOURCE_TYPE
, RESOURCE_CATEGORY
, RESOURCE_SUB_CAT
, ACTIVITY_ID
, ACTIVITY_TYPE
, SYSTEM_SOURCE
, RANGE_SELECTION_ID
, EMPLID
, SSN
, SERVICE_CUST_ID
, SERVICE_ADDR_NUM
, START_DT
, ERROR_STATUS_BI
, COUNTRY_SHIP_TO
, COUNTRY_SHIP_FROM
, GEN_AP_VCHR_FLG
, DOC_SEQ_STATUS
, EARLY_PY_DSCNT_PCT
, DS_PY_TRMS_TIME_ID
, VAT_ENTITY
, TOT_SU_TAX
, TOT_SU_TAX_BSE
, TOT_SU_TAX_XEU
, TOT_VAT
, TOT_VAT_BSE
, TOT_VAT_XEU
, TOT_VAT_BASIS
, TOT_VAT_BASIS_BSE
, TOT_VAT_BASIS_XEU
, PAYMENT_METHOD
, PACKSLIP_NO
, LC_ID
, PAID_REFERENCE
, PPRC_PROMO_CD
, EMAILID
, FAX
, LANGUAGE_CD
, USER_AMT1
, USER_AMT2
, USER_AMT1_BSE
, USER_AMT2_BSE
, USER_AMT1_XEU
, USER_AMT2_XEU
, USER_DT1
, USER_DT2
, USER1
, USER2
, USER3
, USER4
, USER5
, USER6
, USER7
, USER8
, USER9
, PROCESS_INSTANCE
, ADD_DTTM
, LAST_UPDATE_DTTM
, LAST_MAINT_OPRID
,AP_CREATED_DT
,BILLING_AUTHORITY
,BI_BU_TAX_IND
,BUSINESS_UNIT_AM
,BUSINESS_UNIT_RF
,CF_ACTION_FLG
,COUNTRY_VAT_BILLFR
,COUNTRY_VAT_BILLTO
,END_DT
,ENTRY_EVENT
,EXD_INVOICE_NO
,GEN_AR_ITEM_FLG
,LOC_DOC_ID
,MAST_CONTR_ID
,MAX_TAX_FLG
,PHYSICAL_NATURE
,PRELOAD_IND
,RECURRING_END_DT
,RECURRING_START_DT
,REIMB_AGREEMENT
,REPRINT_GROUP_ID
,SOURCE_REF_KEY
,SOURCE_REF_NO
,SOURCE_REF_TYPE
,SO_ID
,STATE_SHIP_FROM
,STATE_SHIP_TO
,STX_TAX_AUTH_CD
,TOT_EXD_AMT
,TOT_EXD_AMT_BSE
,TOT_STX_AMT
,TOT_STX_AMT_BSE
,TO_DT
,VAT_TREATMENT_GRP
,ED_CREATE_DATE
,ED_CREATE_ID
,ED_SOURCE_ARCHIVE_IND
,ARCHIVE_FLAG
)
SELECT
 BUSINESS_UNIT
, INVOICE
, INVOICE_TYPE
, CONSOL_HDR
, CONSOL_KEY
, CONSOL_SETID
, CONSOL_CUST_ID
, CONSOL_BUS_UNIT
, CONSOL_INVOICE
, ORIGINAL_INVOICE
, PRIOR_ADJ_INVOICE
, NEXT_ADJ_INVOICE
, LATEST_INVOICE
, ADJUSTED_FLAG
, BILL_TYPE_ID
, BILL_SOURCE_ID
, BILL_CYCLE_ID
, BILL_BY_ID
, HDR_FIELDS_KEY
, BILLING_FREQUENCY
, TEMPLATE_IVC_FLG
, TEMPLATE_INVOICE
, AUTO_GEN_IVC_NUM
, FROM_DT
, BILL_TO_CUST_ID
, ADDRESS_SEQ_NUM
, BILL_TO_COPIES
, BILL_TO_MEDIA
, CNTCT_SEQ_NUM
, NAME1
, BUSINESS_UNIT_TO
, CR_CARD_FLG
, SUBCUST_QUAL1
, SUBCUST_QUAL2
, BILL_INQUIRY_PHONE
, BILLING_SPECIALIST
, COLLECTOR
, SALES_PERSON
, CR_ANALYST
, PYMNT_TERMS_CD
, BANK_CD
, BANK_ACCT_KEY
, BI_CURRENCY_CD
, BASE_CURRENCY
, CURRENCY_CD_XEU
, FINAL_CURCNV_FLG
, CUR_RT_TYPE
, CUR_RT_SOURCE
, RATE_MULT
, RATE_DIV
, RATE_MULT_XEU
, RATE_DIV_XEU
, RATE_MULT_IU
, RATE_DIV_IU
, RATE_DATE
, PAID_AMT
, FORWARD_BAL_AMT
, INVOICE_AMT_PRETAX
, INVOICE_AMOUNT
, PAID_AMT_BSE
, FORWARD_BAL_BSE
, INVOICE_PRETAX_BSE
, INVOICE_AMT_BSE
, FORWARD_BAL_XEU
, INVOICE_PRETAX_XEU
, INVOICE_AMT_XEU
, PAID_AMT_XEU
, INVOICE_DT
, ACCOUNTING_DT
, DT_INVOICED
, DUE_DT
, INVOICE_FORM_ID
, IVC_PRINTED_FLG
, IVC_PRINTED_DT
, EDI_SENT_FLG
, ENTRY_TYPE
, ENTRY_REASON
, AR_LVL
, AR_DST_OPT
, DST_ID_AR
, ACCOUNT
, ALTACCT
, OPERATING_UNIT
, DEPTID
, PRODUCT
, AFFILIATE
, STATISTICS_CODE
, AR_ENTRY_CREATED
, BUSINESS_UNIT_GL
, GL_LVL
, GL_ENTRY_CREATED
, ENABLE_DFR_REV_FLG
, DFR_ACCTG_DT_CD
, DFR_REV_PRORATION
, DFR_MID_PERIOD_DAY
, DST_ID_DFR
, BILL_STATUS
, BILL_STATUS_TEXT
, MANUAL_LIN_NUM_FLG
, LAST_LINE_SEQ_NUM
, LAST_LINE_AAUX_SEQ
, LAST_NOTE_SEQ_NUM
, ACCRUE_UNBILLED
, DOC_TYPE
, DOC_SEQ_NBR
, DOC_SEQ_DATE
, PC_DISTRIB_STATUS
, PO_REF
, BUSINESS_UNIT_CA
, CONTRACT_NUM
, CONTRACT_DT
, CONTRACT_TYPE
, DIRECT_INVOICING
, BUSINESS_UNIT_OM
, ORDER_NO
, RMA_ID
, ORDER_DATE
, FREIGHT_TERMS
, BILL_OF_LADING
, SHIP_TO_CUST_ID
, SHIP_TO_ADDR_NUM
, SHIP_ID
, SHIP_TYPE_ID
, SHIP_FROM_BU
, SOLD_TO_CUST_ID
, SOLD_TO_ADDR_NUM
, BUSINESS_UNIT_PC
, PROJECT_ID
, ANALYSIS_TYPE
, RESOURCE_TYPE
, RESOURCE_CATEGORY
, RESOURCE_SUB_CAT
, ACTIVITY_ID
, ACTIVITY_TYPE
, SYSTEM_SOURCE
, RANGE_SELECTION_ID
, EMPLID
, SSN
, SERVICE_CUST_ID
, SERVICE_ADDR_NUM
, START_DT
, ERROR_STATUS_BI
, COUNTRY_SHIP_TO
, COUNTRY_SHIP_FROM
, GEN_AP_VCHR_FLG
, DOC_SEQ_STATUS
, EARLY_PY_DSCNT_PCT
, DS_PY_TRMS_TIME_ID
, VAT_ENTITY
, TOT_SU_TAX
, TOT_SU_TAX_BSE
, TOT_SU_TAX_XEU
, TOT_VAT
, TOT_VAT_BSE
, TOT_VAT_XEU
, TOT_VAT_BASIS
, TOT_VAT_BASIS_BSE
, TOT_VAT_BASIS_XEU
, PAYMENT_METHOD
, PACKSLIP_NO
, LC_ID
, PAID_REFERENCE
, PPRC_PROMO_CD
, EMAILID
, FAX
, LANGUAGE_CD
, USER_AMT1
, USER_AMT2
, USER_AMT1_BSE
, USER_AMT2_BSE
, USER_AMT1_XEU
, USER_AMT2_XEU
, USER_DT1
, USER_DT2
, USER1
, USER2
, USER3
, USER4
, USER5
, USER6
, USER7
, USER8
, USER9
, PROCESS_INSTANCE
, ADD_DTTM
, LAST_UPDATE_DTTM
, LAST_MAINT_OPRID
,AP_CREATED_DT
,BILLING_AUTHORITY
,BI_BU_TAX_IND
,BUSINESS_UNIT_AM
,BUSINESS_UNIT_RF
,CF_ACTION_FLG
,COUNTRY_VAT_BILLFR
,COUNTRY_VAT_BILLTO
,END_DT
,ENTRY_EVENT
,EXD_INVOICE_NO
,GEN_AR_ITEM_FLG
,LOC_DOC_ID
,MAST_CONTR_ID
,MAX_TAX_FLG
,PHYSICAL_NATURE
,PRELOAD_IND
,RECURRING_END_DT
,RECURRING_START_DT
,REIMB_AGREEMENT
,REPRINT_GROUP_ID
,SOURCE_REF_KEY
,SOURCE_REF_NO
,SOURCE_REF_TYPE
,SO_ID
,STATE_SHIP_FROM
,STATE_SHIP_TO
,STX_TAX_AUTH_CD
,TOT_EXD_AMT
,TOT_EXD_AMT_BSE
,TOT_STX_AMT
,TOT_STX_AMT_BSE
,TO_DT
,VAT_TREATMENT_GRP
,SYSDATE as ED_CREATE_DATE,
'BI_HDR_PSB_INC.sql' as ED_CREATE_ID,
'N' as ED_SOURCE_ARCHIVE_IND,
'Y'AS ARCHIVE_FLAG
FROM OTR_BI_HDR_PSB
WHERE ADD_DTTM < V_START_DATE 
AND ARCHIVE_FLAG='N';
COMMIT;
END IF;


-- Truncating the Non-archived partition
dbo.p_truncate_listed_partition('DBO','OTR_BI_HDR_PSB','PART_NO');

-- Making Indexes unusable on dbo.OTR_BI_HDR_PSB
dbo.Pkg_Mass_Load_par_Index_Manip.p_make_tbl_inds_unusable('DBO', 'OTR_BI_HDR_PSB', TRUE, 'PART_NO');


insert /*+ APPEND */ into OTR_BI_HDR_PSB
(BUSINESS_UNIT
, INVOICE
, INVOICE_TYPE
, CONSOL_HDR
, CONSOL_KEY
, CONSOL_SETID
, CONSOL_CUST_ID
, CONSOL_BUS_UNIT
, CONSOL_INVOICE
, ORIGINAL_INVOICE
, PRIOR_ADJ_INVOICE
, NEXT_ADJ_INVOICE
, LATEST_INVOICE
, ADJUSTED_FLAG
, BILL_TYPE_ID
, BILL_SOURCE_ID
, BILL_CYCLE_ID
, BILL_BY_ID
, HDR_FIELDS_KEY
, BILLING_FREQUENCY
, TEMPLATE_IVC_FLG
, TEMPLATE_INVOICE
, AUTO_GEN_IVC_NUM
, FROM_DT
, BILL_TO_CUST_ID
, ADDRESS_SEQ_NUM
, BILL_TO_COPIES
, BILL_TO_MEDIA
, CNTCT_SEQ_NUM
, NAME1
, BUSINESS_UNIT_TO
, CR_CARD_FLG
, SUBCUST_QUAL1
, SUBCUST_QUAL2
, BILL_INQUIRY_PHONE
, BILLING_SPECIALIST
, COLLECTOR
, SALES_PERSON
, CR_ANALYST
, PYMNT_TERMS_CD
, BANK_CD
, BANK_ACCT_KEY
, BI_CURRENCY_CD
, BASE_CURRENCY
, CURRENCY_CD_XEU
, FINAL_CURCNV_FLG
, CUR_RT_TYPE
, CUR_RT_SOURCE
, RATE_MULT
, RATE_DIV
, RATE_MULT_XEU
, RATE_DIV_XEU
, RATE_MULT_IU
, RATE_DIV_IU
, RATE_DATE
, PAID_AMT
, FORWARD_BAL_AMT
, INVOICE_AMT_PRETAX
, INVOICE_AMOUNT
, PAID_AMT_BSE
, FORWARD_BAL_BSE
, INVOICE_PRETAX_BSE
, INVOICE_AMT_BSE
, FORWARD_BAL_XEU
, INVOICE_PRETAX_XEU
, INVOICE_AMT_XEU
, PAID_AMT_XEU
, INVOICE_DT
, ACCOUNTING_DT
, DT_INVOICED
, DUE_DT
, INVOICE_FORM_ID
, IVC_PRINTED_FLG
, IVC_PRINTED_DT
, EDI_SENT_FLG
, ENTRY_TYPE
, ENTRY_REASON
, AR_LVL
, AR_DST_OPT
, DST_ID_AR
, ACCOUNT
, ALTACCT
, OPERATING_UNIT
, DEPTID
, PRODUCT
, AFFILIATE
, STATISTICS_CODE
, AR_ENTRY_CREATED
, BUSINESS_UNIT_GL
, GL_LVL
, GL_ENTRY_CREATED
, ENABLE_DFR_REV_FLG
, DFR_ACCTG_DT_CD
, DFR_REV_PRORATION
, DFR_MID_PERIOD_DAY
, DST_ID_DFR
, BILL_STATUS
, BILL_STATUS_TEXT
, MANUAL_LIN_NUM_FLG
, LAST_LINE_SEQ_NUM
, LAST_LINE_AAUX_SEQ
, LAST_NOTE_SEQ_NUM
, ACCRUE_UNBILLED
, DOC_TYPE
, DOC_SEQ_NBR
, DOC_SEQ_DATE
, PC_DISTRIB_STATUS
, PO_REF
, BUSINESS_UNIT_CA
, CONTRACT_NUM
, CONTRACT_DT
, CONTRACT_TYPE
, DIRECT_INVOICING
, BUSINESS_UNIT_OM
, ORDER_NO
, RMA_ID
, ORDER_DATE
, FREIGHT_TERMS
, BILL_OF_LADING
, SHIP_TO_CUST_ID
, SHIP_TO_ADDR_NUM
, SHIP_ID
, SHIP_TYPE_ID
, SHIP_FROM_BU
, SOLD_TO_CUST_ID
, SOLD_TO_ADDR_NUM
, BUSINESS_UNIT_PC
, PROJECT_ID
, ANALYSIS_TYPE
, RESOURCE_TYPE
, RESOURCE_CATEGORY
, RESOURCE_SUB_CAT
, ACTIVITY_ID
, ACTIVITY_TYPE
, SYSTEM_SOURCE
, RANGE_SELECTION_ID
, EMPLID
, SSN
, SERVICE_CUST_ID
, SERVICE_ADDR_NUM
, START_DT
, ERROR_STATUS_BI
, COUNTRY_SHIP_TO
, COUNTRY_SHIP_FROM
, GEN_AP_VCHR_FLG
, DOC_SEQ_STATUS
, EARLY_PY_DSCNT_PCT
, DS_PY_TRMS_TIME_ID
, VAT_ENTITY
, TOT_SU_TAX
, TOT_SU_TAX_BSE
, TOT_SU_TAX_XEU
, TOT_VAT
, TOT_VAT_BSE
, TOT_VAT_XEU
, TOT_VAT_BASIS
, TOT_VAT_BASIS_BSE
, TOT_VAT_BASIS_XEU
, PAYMENT_METHOD
, PACKSLIP_NO
, LC_ID
, PAID_REFERENCE
, PPRC_PROMO_CD
, EMAILID
, FAX
, LANGUAGE_CD
, USER_AMT1
, USER_AMT2
, USER_AMT1_BSE
, USER_AMT2_BSE
, USER_AMT1_XEU
, USER_AMT2_XEU
, USER_DT1
, USER_DT2
, USER1
, USER2
, USER3
, USER4
, USER5
, USER6
, USER7
, USER8
, USER9
, PROCESS_INSTANCE
, ADD_DTTM
, LAST_UPDATE_DTTM
, LAST_MAINT_OPRID
,AP_CREATED_DT
,BILLING_AUTHORITY
,BI_BU_TAX_IND
,BUSINESS_UNIT_AM
,BUSINESS_UNIT_RF
,CF_ACTION_FLG
,COUNTRY_VAT_BILLFR
,COUNTRY_VAT_BILLTO
,END_DT
,ENTRY_EVENT
,EXD_INVOICE_NO
,GEN_AR_ITEM_FLG
,LOC_DOC_ID
,MAST_CONTR_ID
,MAX_TAX_FLG
,PHYSICAL_NATURE
,PRELOAD_IND
,RECURRING_END_DT
,RECURRING_START_DT
,REIMB_AGREEMENT
,REPRINT_GROUP_ID
,SOURCE_REF_KEY
,SOURCE_REF_NO
,SOURCE_REF_TYPE
,SO_ID
,STATE_SHIP_FROM
,STATE_SHIP_TO
,STX_TAX_AUTH_CD
,TOT_EXD_AMT
,TOT_EXD_AMT_BSE
,TOT_STX_AMT
,TOT_STX_AMT_BSE
,TO_DT
,VAT_TREATMENT_GRP
,ED_CREATE_DATE
,ED_CREATE_ID
,ED_SOURCE_ARCHIVE_IND
,ARCHIVE_FLAG
)
SELECT 
BUSINESS_UNIT,
INVOICE,
INVOICE_TYPE,
CONSOL_HDR,
CONSOL_KEY,
CONSOL_SETID,
CONSOL_CUST_ID,
CONSOL_BUS_UNIT,
CONSOL_INVOICE,
ORIGINAL_INVOICE,
PRIOR_ADJ_INVOICE,
NEXT_ADJ_INVOICE,
LATEST_INVOICE,
ADJUSTED_FLAG,
BILL_TYPE_ID,
BILL_SOURCE_ID,
BILL_CYCLE_ID,
BILL_BY_ID,
HDR_FIELDS_KEY,
BILLING_FREQUENCY,
TEMPLATE_IVC_FLG,
TEMPLATE_INVOICE,
AUTO_GEN_IVC_NUM,
FROM_DT,
BILL_TO_CUST_ID,
ADDRESS_SEQ_NUM,
BILL_TO_COPIES,
BILL_TO_MEDIA,
CNTCT_SEQ_NUM,
NAME1,
BUSINESS_UNIT_TO,
CR_CARD_FLG,
SUBCUST_QUAL1,
SUBCUST_QUAL2,
BILL_INQUIRY_PHONE,
BILLING_SPECIALIST,
COLLECTOR,
SALES_PERSON,
CR_ANALYST,
PYMNT_TERMS_CD,
BANK_CD,
BANK_ACCT_KEY,
BI_CURRENCY_CD,
BASE_CURRENCY,
CURRENCY_CD_XEU,
FINAL_CURCNV_FLG,
CUR_RT_TYPE,
CUR_RT_SOURCE,
RATE_MULT,
RATE_DIV,
RATE_MULT_XEU,
RATE_DIV_XEU,
RATE_MULT_IU,
RATE_DIV_IU,
RATE_DATE,
PAID_AMT,
FORWARD_BAL_AMT,
INVOICE_AMT_PRETAX,
INVOICE_AMOUNT,
PAID_AMT_BSE,
FORWARD_BAL_BSE,
INVOICE_PRETAX_BSE,
INVOICE_AMT_BSE,
FORWARD_BAL_XEU,
INVOICE_PRETAX_XEU,
INVOICE_AMT_XEU,
PAID_AMT_XEU,
INVOICE_DT,
ACCOUNTING_DT,
DT_INVOICED,
DUE_DT,
INVOICE_FORM_ID,
IVC_PRINTED_FLG,
IVC_PRINTED_DT,
EDI_SENT_FLG,
ENTRY_TYPE,
ENTRY_REASON,
AR_LVL,
AR_DST_OPT,
' ', --DST_ID_AR, No longer exists
' ', --ACCOUNT, No longer exists
' ', --ALTACCT, No longer exists
' ', --OPERATING_UNIT,  No longer exists
' ', --DEPTID, No longer exists
' ', --PRODUCT, No longer exists
' ', --AFFILIATE, No longer exists
' ', --STATISTICS_CODE, No longer exists
AR_ENTRY_CREATED,
BUSINESS_UNIT_GL,
GL_LVL,
GL_ENTRY_CREATED,
ENABLE_DFR_REV_FLG,
DFR_ACCTG_DT_CD,
DFR_REV_PRORATION,
DFR_MID_PERIOD_DAY,
DST_ID_DFR,
BILL_STATUS,
BILL_STATUS_TEXT,
MANUAL_LIN_NUM_FLG,
LAST_LINE_SEQ_NUM,
LAST_LINE_AAUX_SEQ,
LAST_NOTE_SEQ_NUM,
ACCRUE_UNBILLED,
DOC_TYPE,
DOC_SEQ_NBR,
DOC_SEQ_DATE,
PC_DISTRIB_STATUS,
PO_REF,
BUSINESS_UNIT_CA,
CONTRACT_NUM,
CONTRACT_DT,
CONTRACT_TYPE,
DIRECT_INVOICING,
BUSINESS_UNIT_OM,
ORDER_NO,
RMA_ID,
ORDER_DATE,
FREIGHT_TERMS,
BILL_OF_LADING,
SHIP_TO_CUST_ID,
SHIP_TO_ADDR_NUM,
SHIP_ID,
SHIP_TYPE_ID,
SHIP_FROM_BU,
SOLD_TO_CUST_ID,
SOLD_TO_ADDR_NUM,
BUSINESS_UNIT_PC,
PROJECT_ID,
ANALYSIS_TYPE,
RESOURCE_TYPE,
RESOURCE_CATEGORY,
RESOURCE_SUB_CAT,
ACTIVITY_ID,
ACTIVITY_TYPE,
SYSTEM_SOURCE,
RANGE_SELECTION_ID,
EMPLID,
SSN,
SERVICE_CUST_ID,
SERVICE_ADDR_NUM,
START_DT,
ERROR_STATUS_BI,
COUNTRY_SHIP_TO,
COUNTRY_SHIP_FROM,
GEN_AP_VCHR_FLG,
DOC_SEQ_STATUS,
EARLY_PY_DSCNT_PCT,
DS_PY_TRMS_TIME_ID,
VAT_ENTITY,
TOT_SU_TAX,
TOT_SU_TAX_BSE,
TOT_SU_TAX_XEU,
TOT_VAT,
TOT_VAT_BSE,
TOT_VAT_XEU,
TOT_VAT_BASIS,
TOT_VAT_BASIS_BSE,
TOT_VAT_BASIS_XEU,
PAYMENT_METHOD,
PACKSLIP_NO,
LC_ID,
PAID_REFERENCE,
PPRC_PROMO_CD,
EMAILID,
FAX,
LANGUAGE_CD,
USER_AMT1,
USER_AMT2,
USER_AMT1_BSE,
USER_AMT2_BSE,
USER_AMT1_XEU,
USER_AMT2_XEU,
USER_DT1,
USER_DT2,
USER1,
USER2,
USER3,
USER4,
USER5,
USER6,
USER7,
USER8,
USER9,
PROCESS_INSTANCE,
ADD_DTTM,
LAST_UPDATE_DTTM,
LAST_MAINT_OPRID,
AP_CREATED_DT,
BILLING_AUTHORITY,
BI_BU_TAX_IND,
BUSINESS_UNIT_AM,
BUSINESS_UNIT_RF,
CF_ACTION_FLG,
COUNTRY_VAT_BILLFR,
COUNTRY_VAT_BILLTO,
END_DT,
ENTRY_EVENT,
EXD_INVOICE_NO,
GEN_AR_ITEM_FLG,
LOC_DOC_ID,
MAST_CONTR_ID,
MAX_TAX_FLG,
PHYSICAL_NATURE,
PRELOAD_IND,
RECURRING_END_DT,
RECURRING_START_DT,
REIMB_AGREEMENT,
REPRINT_GROUP_ID,
SOURCE_REF_KEY,
SOURCE_REF_NO,
SOURCE_REF_TYPE,
SO_ID,
STATE_SHIP_FROM,
STATE_SHIP_TO,
STX_TAX_AUTH_CD,
TOT_EXD_AMT,
TOT_EXD_AMT_BSE,
TOT_STX_AMT,
TOT_STX_AMT_BSE,
TO_DT,
VAT_TREATMENT_GRP,
SYSDATE as ED_CREATE_DATE,
'BI_HDR_PSB_INC.sql' as ED_CREATE_ID,
'N' as ED_SOURCE_ARCHIVE_IND,
'N' as ARCHIVE_FLAG
from
PS_BI_HDR where ADD_DTTM >=V_START_DATE
;
COMMIT;

-- Rebuilding Indexes on dbo.OTR_BI_HDR_PSB
dbo.Pkg_Mass_Load_par_Index_Manip.p_rebuild_tbl_inds('DBO', 'OTR_BI_HDR_PSB', FALSE, 'PART_NO');
END;
/

prompt Updating OTR_LOAD_CONTROL
Declare
    count1 number :=0;
    tablename varchar2(30) := 'OTR_BI_HDR_PSB';
    comment_prod varchar2(400) := 'BEFORE6; Incremental Truncates NO Archive partition and loads current year and two previous years only.';
    comment_test varchar2(400) := 'BEFORE6; Not in production yet.';

BEGIN
    SELECT count(*) into count1
    FROM OTR_LOAD_CONTROL olc
    WHERE olc.TABLE_NAME=tablename;

    If count1=0 then
    INSERT into OTR_LOAD_CONTROL
      VALUES(tablename, sysdate, comment_test);
    end if;
    
  IF '&production_variable' = 'Y' then
    UPDATE OTR_LOAD_CONTROL olc 
    SET LOAD_COMMENT=comment_prod,
        LAST_LOAD_DATE=sysdate 
    WHERE olc.TABLE_NAME=tablename;
  ELSIF '&production_variable' = 'N' THEN
    UPDATE OTR_LOAD_CONTROL olc 
    SET LOAD_COMMENT=comment_test,
        LAST_LOAD_DATE=sysdate 
    WHERE olc.TABLE_NAME=tablename;
  ELSE /* Do not change load_comment */
    UPDATE OTR_LOAD_CONTROL olc 
    SET LAST_LOAD_DATE=sysdate
    WHERE olc.TABLE_NAME=tablename;
  END if;


   COMMIT;
    
END;
/

EXIT