-- CREATE TABLE R12_AP_030_ARC_BILL LIKE AP_030_ARC_BILL;
-- DR
-- ADD R12_ACCOUNT
-- ADD R12_ENTITY

-- assumptions:
-- COMPANY = BUSINESS_UNIT
-- ACCOUNT = ACCOUNT
-- COST_CENTER = DEPT_ID
-- PRODUCT_CODE = PRODUCT

select count(*) from ap_030_arc_bill; -- 96597254 8/26 9:30 AM MDT

CREATE TABLE DBO.R12_AP_030_ARC_BILL (
	-- TRX_NUMBER VARCHAR2(20 BYTE) NOT NULL,
	-- TRX_DATE DATE NOT NULL,
	-- TRX_TYPE VARCHAR2(20 BYTE),
	CATEGORY VARCHAR2(14 BYTE),
	-- CURRENCY_CODE VARCHAR2(15 BYTE),
	-- LINE_NUMBER NUMBER,
	-- BATCH_ID NUMBER(15, 0),
	-- LINE_TYPE VARCHAR2(20 BYTE),
	-- LINKED_LINE_NUMBER NUMBER,
	AMOUNT NUMBER,
	-- POSTING_CONTROL_ID NUMBER(15, 0) NOT NULL,
	-- GL_DATE DATE,
	GL_POSTED_DATE DATE,
	-- ACCOUNT_CLASS VARCHAR2(80 BYTE) NOT NULL,
	COMPANY VARCHAR2(25 BYTE),
	ACCOUNT VARCHAR2(25 BYTE),
	-- COST_CENTER VARCHAR2(25 BYTE),
	-- PRODUCT_CODE VARCHAR2(25 BYTE),
	-- CODE_COMBINATION_ID NUMBER(15, 0) NOT NULL 
	R12_ACCOUNT VARCHAR2(25 BYTE), -- 25?
	R12_ENTITY VARCHAR2(25 BYTE) -- 25?
);
-- primary key?
-- indexes?
-- constraints?

TRUNCATE TABLE R12_AP_030_ARC_BILL;
INSERT INTO R12_AP_030_ARC_BILL
(
-- TRX_NUMBER,
-- TRX_DATE,
-- TRX_TYPE,
CATEGORY, -- DM_030_EXT_SALES_MVW
-- CURRENCY_CODE,
-- LINE_NUMBER,
-- BATCH_ID,
-- LINE_TYPE,
-- LINKED_LINE_NUMBER,
AMOUNT, -- DM_030_EXT_SALES_MVW
-- POSTING_CONTROL_ID,
-- GL_DATE,
GL_POSTED_DATE, -- DM_030_EXT_SALES_MVW
-- ACCOUNT_CLASS,
COMPANY, -- DM_030_EXT_SALES_MVW
ACCOUNT, -- DM_030_EXT_SALES_MVW
-- COST_CENTER,
-- PRODUCT_CODE,
-- CODE_COMBINATION_ID,
R12_ACCOUNT,
R12_ENTITY
)
SELECT
-- TRX_NUMBER,
-- TRX_DATE,
-- TRX_TYPE,
CATEGORY,
-- CURRENCY_CODE,
-- LINE_NUMBER,
-- BATCH_ID,
-- LINE_TYPE,
-- LINKED_LINE_NUMBER,
AMOUNT,
-- POSTING_CONTROL_ID,
-- GL_DATE,
GL_POSTED_DATE,
-- ACCOUNT_CLASS,
COMPANY,
ACCOUNT,
-- COST_CENTER,
-- PRODUCT_CODE,
-- CODE_COMBINATION_ID,
DBO.F_GET_R12_ACCOUNT_STRING ('ACCOUNT', COMPANY, ACCOUNT, COST_CENTER, PRODUCT_CODE, null) as R12_ACCOUNT,
DBO.F_GET_R12_ACCOUNT_STRING ('ENTITY', COMPANY, ACCOUNT, COST_CENTER, PRODUCT_CODE, null) as R12_ENTITY
FROM
AP_030_ARC_BILL;

-- CREATE TABLE BH.R12_GL_CODE_COMBINATIONS LIKE BH.GL_CODE_COMBINATIONS
-- ADD R12_ACCOUNT
-- ADD R12_PRODUCT
-- ADD R12_LOCATION
-- ADD R12_ENTITY

-- assumptions:
-- SEGMENT1 = BUSINESS_UNIT
-- SEGMENT2 = ACCOUNT
-- SEGMENT3 = DEPT

select count(*) from bh.gl_code_combinations; -- 500419 8/26 9:30 AM MDT

CREATE TABLE BH.R12_GL_CODE_COMBINATIONS 
(
	CODE_COMBINATION_ID NUMBER(15, 0) NOT NULL,
	-- LAST_UPDATE_DATE DATE NOT NULL,
	-- LAST_UPDATED_BY NUMBER NOT NULL,
	-- CHART_OF_ACCOUNTS_ID NUMBER(15, 0) NOT NULL,
	-- DETAIL_POSTING_ALLOWED_FLAG VARCHAR2(1 BYTE) NOT NULL,
	-- DETAIL_BUDGETING_ALLOWED_FLAG VARCHAR2(1 BYTE) NOT NULL,
	-- ACCOUNT_TYPE VARCHAR2(1 BYTE) NOT NULL,
	-- ENABLED_FLAG VARCHAR2(1 BYTE) NOT NULL,
	-- SUMMARY_FLAG VARCHAR2(1 BYTE) NOT NULL,
	SEGMENT1 VARCHAR2(25 BYTE),
	SEGMENT2 VARCHAR2(25 BYTE),
	SEGMENT3 VARCHAR2(25 BYTE),
	SEGMENT4 VARCHAR2(25 BYTE),
	-- SEGMENT5 VARCHAR2(25 BYTE),
	-- SEGMENT6 VARCHAR2(25 BYTE),
	-- SEGMENT7 VARCHAR2(25 BYTE),
	-- SEGMENT8 VARCHAR2(25 BYTE),
	-- SEGMENT9 VARCHAR2(25 BYTE),
	-- SEGMENT10 VARCHAR2(25 BYTE),
	-- SEGMENT11 VARCHAR2(25 BYTE),
	-- SEGMENT12 VARCHAR2(25 BYTE),
	-- SEGMENT13 VARCHAR2(25 BYTE),
	-- SEGMENT14 VARCHAR2(25 BYTE),
	-- SEGMENT15 VARCHAR2(25 BYTE),
	-- SEGMENT16 VARCHAR2(25 BYTE),
	-- SEGMENT17 VARCHAR2(25 BYTE),
	-- SEGMENT18 VARCHAR2(25 BYTE),
	-- SEGMENT19 VARCHAR2(25 BYTE),
	-- SEGMENT20 VARCHAR2(25 BYTE),
	-- SEGMENT21 VARCHAR2(25 BYTE),
	-- SEGMENT22 VARCHAR2(25 BYTE),
	-- SEGMENT23 VARCHAR2(25 BYTE),
	-- SEGMENT24 VARCHAR2(25 BYTE),
	-- SEGMENT25 VARCHAR2(25 BYTE),
	-- SEGMENT26 VARCHAR2(25 BYTE),
	-- SEGMENT27 VARCHAR2(25 BYTE),
	-- SEGMENT28 VARCHAR2(25 BYTE),
	-- SEGMENT29 VARCHAR2(25 BYTE),
	-- SEGMENT30 VARCHAR2(25 BYTE),
	-- DESCRIPTION VARCHAR2(240 BYTE),
	-- TEMPLATE_ID NUMBER(15, 0),
	-- ALLOCATION_CREATE_FLAG VARCHAR2(1 BYTE),
	-- START_DATE_ACTIVE DATE,
	-- END_DATE_ACTIVE DATE,
	-- ATTRIBUTE1 VARCHAR2(150 BYTE),
	-- ATTRIBUTE2 VARCHAR2(150 BYTE),
	-- ATTRIBUTE3 VARCHAR2(150 BYTE),
	-- ATTRIBUTE4 VARCHAR2(150 BYTE),
	-- ATTRIBUTE5 VARCHAR2(150 BYTE),
	-- ATTRIBUTE6 VARCHAR2(150 BYTE),
	-- ATTRIBUTE7 VARCHAR2(150 BYTE),
	-- ATTRIBUTE8 VARCHAR2(150 BYTE),
	-- ATTRIBUTE9 VARCHAR2(150 BYTE),
	-- ATTRIBUTE10 VARCHAR2(150 BYTE),
	-- CONTEXT VARCHAR2(150 BYTE),
	-- SEGMENT_ATTRIBUTE1 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE2 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE3 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE4 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE5 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE6 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE7 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE8 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE9 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE10 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE11 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE12 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE13 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE14 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE15 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE16 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE17 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE18 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE19 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE20 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE21 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE22 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE23 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE24 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE25 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE26 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE27 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE28 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE29 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE30 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE31 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE32 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE33 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE34 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE35 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE36 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE37 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE38 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE39 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE40 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE41 VARCHAR2(60 BYTE),
	-- SEGMENT_ATTRIBUTE42 VARCHAR2(60 BYTE),
	-- JGZZ_RECON_FLAG VARCHAR2(1 BYTE),
	-- REFERENCE1 VARCHAR2(1 BYTE),
	-- REFERENCE2 VARCHAR2(1 BYTE),
	-- REFERENCE3 VARCHAR2(1 BYTE),
	-- REFERENCE4 VARCHAR2(1 BYTE),
	-- REFERENCE5 VARCHAR2(1 BYTE),
	-- JGZZ_RECON_CONTEXT VARCHAR2(30 BYTE),
	-- FALCON_GL_ACCOUNT VARCHAR2(100 BYTE) 
	R12_ACCOUNT VARCHAR2(25 BYTE), -- 25?
	R12_LOCATION VARCHAR2(25 BYTE), -- 25?
	R12_ENTITY VARCHAR(25 BYTE) -- 25?
);
-- primary key?
-- indexes?
-- constraints?

TRUNCATE TABLE BH.R12_GL_CODE_COMBINATIONS;
INSERT INTO BH.R12_GL_CODE_COMBINATIONS
(
CODE_COMBINATION_ID, -- DM_030_EXT_COMM_MVW
-- LAST_UPDATE_DATE,
-- LAST_UPDATED_BY,
-- CHART_OF_ACCOUNTS_ID,
-- DETAIL_POSTING_ALLOWED_FLAG,
-- DETAIL_BUDGETING_ALLOWED_FLAG,
-- ACCOUNT_TYPE,
-- ENABLED_FLAG,
-- SUMMARY_FLAG,
SEGMENT1, -- DM_030_EXT_COMM_MVW, mapExtendedWarrantyCommissionData
SEGMENT2, -- DM_030_EXT_COMM_MVW, mapExtendedWarrantyCommissionData
SEGMENT3, -- DM_030_EXT_COMM_MVW, mapExtendedWarrantyCommissionData
SEGMENT4, -- mapExtendedWarrantyCommissionData
-- SEGMENT5,
-- SEGMENT6,
-- SEGMENT7,
-- SEGMENT8,
-- SEGMENT9,
-- SEGMENT10,
-- SEGMENT11,
-- SEGMENT12,
-- SEGMENT13,
-- SEGMENT14,
-- SEGMENT15,
-- SEGMENT16,
-- SEGMENT17,
-- SEGMENT18,
-- SEGMENT19,
-- SEGMENT20,
-- SEGMENT21,
-- SEGMENT22,
-- SEGMENT23,
-- SEGMENT24,
-- SEGMENT25,
-- SEGMENT26,
-- SEGMENT27,
-- SEGMENT28,
-- SEGMENT29,
-- SEGMENT30,
-- DESCRIPTION,
-- TEMPLATE_ID,
-- ALLOCATION_CREATE_FLAG,
-- START_DATE_ACTIVE,
-- END_DATE_ACTIVE,
-- ATTRIBUTE1,
-- ATTRIBUTE2,
-- ATTRIBUTE3,
-- ATTRIBUTE4,
-- ATTRIBUTE5,
-- ATTRIBUTE6,
-- ATTRIBUTE7,
-- ATTRIBUTE8,
-- ATTRIBUTE9,
-- ATTRIBUTE10,
-- CONTEXT,
-- SEGMENT_ATTRIBUTE1,
-- SEGMENT_ATTRIBUTE2,
-- SEGMENT_ATTRIBUTE3,
-- SEGMENT_ATTRIBUTE4,
-- SEGMENT_ATTRIBUTE5,
-- SEGMENT_ATTRIBUTE6,
-- SEGMENT_ATTRIBUTE7,
-- SEGMENT_ATTRIBUTE8,
-- SEGMENT_ATTRIBUTE9,
-- SEGMENT_ATTRIBUTE10,
-- SEGMENT_ATTRIBUTE11,
-- SEGMENT_ATTRIBUTE12,
-- SEGMENT_ATTRIBUTE13,
-- SEGMENT_ATTRIBUTE14,
-- SEGMENT_ATTRIBUTE15,
-- SEGMENT_ATTRIBUTE16,
-- SEGMENT_ATTRIBUTE17,
-- SEGMENT_ATTRIBUTE18,
-- SEGMENT_ATTRIBUTE19,
-- SEGMENT_ATTRIBUTE20,
-- SEGMENT_ATTRIBUTE21,
-- SEGMENT_ATTRIBUTE22,
-- SEGMENT_ATTRIBUTE23,
-- SEGMENT_ATTRIBUTE24,
-- SEGMENT_ATTRIBUTE25,
-- SEGMENT_ATTRIBUTE26,
-- SEGMENT_ATTRIBUTE27,
-- SEGMENT_ATTRIBUTE28,
-- SEGMENT_ATTRIBUTE29,
-- SEGMENT_ATTRIBUTE30,
-- SEGMENT_ATTRIBUTE31,
-- SEGMENT_ATTRIBUTE32,
-- SEGMENT_ATTRIBUTE33,
-- SEGMENT_ATTRIBUTE34,
-- SEGMENT_ATTRIBUTE35,
-- SEGMENT_ATTRIBUTE36,
-- SEGMENT_ATTRIBUTE37,
-- SEGMENT_ATTRIBUTE38,
-- SEGMENT_ATTRIBUTE39,
-- SEGMENT_ATTRIBUTE40,
-- SEGMENT_ATTRIBUTE41,
-- SEGMENT_ATTRIBUTE42,
-- JGZZ_RECON_FLAG,
-- REFERENCE1,
-- REFERENCE2,
-- REFERENCE3,
-- REFERENCE4,
-- REFERENCE5,
-- JGZZ_RECON_CONTEXT,
-- FALCON_GL_ACCOUNT,
R12_ACCOUNT,
R12_LOCATION,
R12_ENTITY
)
SELECT
CODE_COMBINATION_ID,
-- LAST_UPDATE_DATE,
-- LAST_UPDATED_BY,
-- CHART_OF_ACCOUNTS_ID,
-- DETAIL_POSTING_ALLOWED_FLAG,
-- DETAIL_BUDGETING_ALLOWED_FLAG,
-- ACCOUNT_TYPE,
-- ENABLED_FLAG,
-- SUMMARY_FLAG,
SEGMENT1,
SEGMENT2,
SEGMENT3,
SEGMENT4,
-- SEGMENT5,
-- SEGMENT6,
-- SEGMENT7,
-- SEGMENT8,
-- SEGMENT9,
-- SEGMENT10,
-- SEGMENT11,
-- SEGMENT12,
-- SEGMENT13,
-- SEGMENT14,
-- SEGMENT15,
-- SEGMENT16,
-- SEGMENT17,
-- SEGMENT18,
-- SEGMENT19,
-- SEGMENT20,
-- SEGMENT21,
-- SEGMENT22,
-- SEGMENT23,
-- SEGMENT24,
-- SEGMENT25,
-- SEGMENT26,
-- SEGMENT27,
-- SEGMENT28,
-- SEGMENT29,
-- SEGMENT30,
-- DESCRIPTION,
-- TEMPLATE_ID,
-- ALLOCATION_CREATE_FLAG,
-- START_DATE_ACTIVE,
-- END_DATE_ACTIVE,
-- ATTRIBUTE1,
-- ATTRIBUTE2,
-- ATTRIBUTE3,
-- ATTRIBUTE4,
-- ATTRIBUTE5,
-- ATTRIBUTE6,
-- ATTRIBUTE7,
-- ATTRIBUTE8,
-- ATTRIBUTE9,
-- ATTRIBUTE10,
-- CONTEXT,
-- SEGMENT_ATTRIBUTE1,
-- SEGMENT_ATTRIBUTE2,
-- SEGMENT_ATTRIBUTE3,
-- SEGMENT_ATTRIBUTE4,
-- SEGMENT_ATTRIBUTE5,
-- SEGMENT_ATTRIBUTE6,
-- SEGMENT_ATTRIBUTE7,
-- SEGMENT_ATTRIBUTE8,
-- SEGMENT_ATTRIBUTE9,
-- SEGMENT_ATTRIBUTE10,
-- SEGMENT_ATTRIBUTE11,
-- SEGMENT_ATTRIBUTE12,
-- SEGMENT_ATTRIBUTE13,
-- SEGMENT_ATTRIBUTE14,
-- SEGMENT_ATTRIBUTE15,
-- SEGMENT_ATTRIBUTE16,
-- SEGMENT_ATTRIBUTE17,
-- SEGMENT_ATTRIBUTE18,
-- SEGMENT_ATTRIBUTE19,
-- SEGMENT_ATTRIBUTE20,
-- SEGMENT_ATTRIBUTE21,
-- SEGMENT_ATTRIBUTE22,
-- SEGMENT_ATTRIBUTE23,
-- SEGMENT_ATTRIBUTE24,
-- SEGMENT_ATTRIBUTE25,
-- SEGMENT_ATTRIBUTE26,
-- SEGMENT_ATTRIBUTE27,
-- SEGMENT_ATTRIBUTE28,
-- SEGMENT_ATTRIBUTE29,
-- SEGMENT_ATTRIBUTE30,
-- SEGMENT_ATTRIBUTE31,
-- SEGMENT_ATTRIBUTE32,
-- SEGMENT_ATTRIBUTE33,
-- SEGMENT_ATTRIBUTE34,
-- SEGMENT_ATTRIBUTE35,
-- SEGMENT_ATTRIBUTE36,
-- SEGMENT_ATTRIBUTE37,
-- SEGMENT_ATTRIBUTE38,
-- SEGMENT_ATTRIBUTE39,
-- SEGMENT_ATTRIBUTE40,
-- SEGMENT_ATTRIBUTE41,
-- SEGMENT_ATTRIBUTE42,
-- JGZZ_RECON_FLAG,
-- REFERENCE1,
-- REFERENCE2,
-- REFERENCE3,
-- REFERENCE4,
-- REFERENCE5,
-- JGZZ_RECON_CONTEXT,
-- FALCON_GL_ACCOUNT,
DBO.F_GET_R12_ACCOUNT_STRING ('ACCOUNT', SEGMENT1, SEGMENT2, SEGMENT3, SEGMENT4, null) as R12_ACCOUNT,
DBO.F_GET_R12_ACCOUNT_STRING ('LOCATION', SEGMENT1, SEGMENT2, SEGMENT3, SEGMENT4, null) as R12_LOCATION,
DBO.F_GET_R12_ACCOUNT_STRING ('ENTITY', SEGMENT1, SEGMENT2, SEGMENT3, SEGMENT4, null) as R12_ENTITY
FROM
BH.GL_CODE_COMBINATIONS;

-- CREATE TABLE R12_OTR_BI_ACCT_ENTRY_PSB like OTR_BI_ACCT_ENTRY_PSB
-- DR
-- add R12_ACCOUNT
-- add R12_PRODUCT
-- add R12_ENTITY
-- add R12_LOCATION

select count(*) from OTR_BI_ACCT_ENTRY_PSB; -- 204281093 9:45 AM MDT

CREATE TABLE DBO.R12_OTR_BI_ACCT_ENTRY_PSB (
	BUSINESS_UNIT VARCHAR2(5 BYTE),
	INVOICE VARCHAR2(22 BYTE),
	LINE_SEQ_NUM NUMBER(*, 0),
	-- ACCOUNTING_DT DATE,
	ACCT_ENTRY_TYPE VARCHAR2(3 BYTE),
	-- DISC_SUR_LVL NUMBER(*, 0),
	-- DISC_SUR_ID VARCHAR2(15 BYTE),
	-- LINE_DST_SEQ_NUM NUMBER(*, 0),
	-- TAX_AUTHORITY_CD VARCHAR2(3 BYTE),
	-- PROCESS_INSTANCE NUMBER(10, 0),
	-- DISC_SUR_INDICATOR VARCHAR2(1 BYTE),
	BUSINESS_UNIT_GL VARCHAR2(5 BYTE),
	-- LEDGER_GROUP VARCHAR2(10 BYTE),
	LEDGER VARCHAR2(10 BYTE),
	-- ACCOUNTING_PERIOD NUMBER(*, 0),
	-- FISCAL_YEAR NUMBER(*, 0),
	ACCOUNT VARCHAR2(10 BYTE),
	-- ALTACCT VARCHAR2(10 BYTE),
	-- OPERATING_UNIT VARCHAR2(8 BYTE),
	DEPTID VARCHAR2(10 BYTE),
	PRODUCT VARCHAR2(6 BYTE),
	-- PROJECT_ID VARCHAR2(15 BYTE),
	-- AFFILIATE VARCHAR2(5 BYTE),
	-- STATISTICS_CODE VARCHAR2(3 BYTE),
	MONETARY_AMOUNT NUMBER(26, 3),
	-- STATISTIC_AMOUNT NUMBER(15, 2),
	-- JRNL_LN_REF VARCHAR2(10 BYTE),
	-- LINE_DESCR VARCHAR2(30 BYTE),
	-- USER1 VARCHAR2(6 BYTE),
	-- USER2 VARCHAR2(2 BYTE),
	-- USER3 VARCHAR2(2 BYTE),
	-- USER4 VARCHAR2(1 BYTE),
	-- USER5 VARCHAR2(3 BYTE),
	JOURNAL_ID VARCHAR2(10 BYTE),
	JOURNAL_DATE DATE,
	-- JOURNAL_LINE NUMBER(*, 0),
	-- BUDGET_HDR_STATUS VARCHAR2(1 BYTE),
	-- BUDGET_LINE_STATUS VARCHAR2(1 BYTE),
	-- KK_TRAN_OVER_FLAG VARCHAR2(1 BYTE),
	-- KK_TRAN_OVER_OPRID VARCHAR2(30 BYTE),
	-- GL_DISTRIB_STATUS VARCHAR2(1 BYTE),
	-- APPL_JRNL_ID VARCHAR2(10 BYTE),
	CURRENCY_CD VARCHAR2(3 BYTE),
	-- FOREIGN_CURRENCY VARCHAR2(3 BYTE),
	-- FOREIGN_AMOUNT NUMBER(26, 3),
	-- RT_TYPE VARCHAR2(5 BYTE),
	-- DOC_TYPE VARCHAR2(8 BYTE),
	-- DOC_SEQ_NBR VARCHAR2(12 BYTE),
	-- DOC_SEQ_DATE DATE,
	-- RATE_MULT NUMBER(15, 8),
	-- RATE_DIV NUMBER(15, 8),
	-- FROM_ACCRUAL VARCHAR2(1 BYTE),
	-- BUSINESS_UNIT_PC VARCHAR2(5 BYTE),
	-- ACTIVITY_ID VARCHAR2(15 BYTE),
	-- RESOURCE_TYPE VARCHAR2(5 BYTE),
	-- RESOURCE_CATEGORY VARCHAR2(5 BYTE),
	-- RESOURCE_SUB_CAT VARCHAR2(5 BYTE),
	-- AFFILIATE_INTRA1 VARCHAR2(10 BYTE),
	-- AFFILIATE_INTRA2 VARCHAR2(10 BYTE),
	-- BUDGET_DT DATE,
	-- BUDGET_REF VARCHAR2(8 BYTE),
	-- CHARTFIELD1 VARCHAR2(10 BYTE),
	-- CHARTFIELD2 VARCHAR2(10 BYTE),
	-- CHARTFIELD3 VARCHAR2(10 BYTE),
	-- CLASS_FLD VARCHAR2(5 BYTE),
	-- ENTRY_EVENT VARCHAR2(10 BYTE),
	-- FUND_CODE VARCHAR2(5 BYTE),
	-- KK_TRAN_OVER_DTTM DATE,
	-- PROGRAM_CODE VARCHAR2(5 BYTE),
	-- ED_CREATE_DATE DATE,
	-- ED_CREATE_ID VARCHAR2(100 BYTE),
	-- ARCHIVE_FLAG VARCHAR2(1 BYTE) NOT NULL 
	R12_ACCOUNT VARCHAR2(10 BYTE),
	R12_PRODUCT VARCHAR2(6 BYTE),
	R12_ENTITY VARCHAR2(5 BYTE),
	R12_LOCATION VARCHAR2(10 BYTE)
);
-- primary key?
-- indexes?
-- constraints?

truncate table R12_OTR_BI_ACCT_ENTRY_PSB;
insert into R12_OTR_BI_ACCT_ENTRY_PSB
(
BUSINESS_UNIT, -- VARCHAR2(5), DM_030_EXT_SALES_MVW, mapSalesData68, mapExtendedWarrantySalesData1, mapExtendedYTD, mapSalesData1
INVOICE, -- VARCHAR2(22), DM_030_EXT_SALES_MVW, mapSalesData68, mapExtendedWarrantySalesData1, mapExtendedYTD, mapSalesData1
LINE_SEQ_NUM, -- NUMBER(38), mapSalesData68, mapSalesData1
-- ACCOUNTING_DT, -- DATE
ACCT_ENTRY_TYPE, -- VARCHAR2(3), mapSalesData68, mapSalesData1
-- DISC_SUR_LVL, -- NUMBER(38)
-- DISC_SUR_ID, -- VARCHAR2(15)
-- LINE_DST_SEQ_NUM, -- NUMBER(38)
-- TAX_AUTHORITY_CD, -- VARCHAR2(3)
-- PROCESS_INSTANCE, -- NUMBER(10)
-- DISC_SUR_INDICATOR, -- VARCHAR2(1)
BUSINESS_UNIT_GL, -- VARCHAR2(5), DM_030_EXT_SALES_MVW, mapExtendedWarrantySalesData1, mapExtendedYTD, mapSalesData1
-- LEDGER_GROUP, -- VARCHAR2(10)
LEDGER, -- VARCHAR2(10), mapSalesData68, mapSalesData1
-- ACCOUNTING_PERIOD, -- NUMBER(38)
-- FISCAL_YEAR, -- NUMBER(38)
ACCOUNT, -- VARCHAR2(10), DM_030_EXT_SALES_MVW, mapSalesData68, mapExtendedWarrantySalesData1, mapExtendedYTD, mapSalesData1
-- ALTACCT, -- VARCHAR2(10)
-- OPERATING_UNIT, -- VARCHAR2(8)
DEPTID, -- VARCHAR2(10), mapSalesData68, mapExtendedWarrantySalesData1, mapSalesData1
PRODUCT, -- VARCHAR2(6), mapSalesData68, mapExtendedWarrantySalesData1, mapSalesData1
-- PROJECT_ID, -- VARCHAR2(15)
-- AFFILIATE, -- VARCHAR2(5)
-- STATISTICS_CODE, -- VARCHAR2(3)
MONETARY_AMOUNT, -- NUMBER(26,3), DM_030_EXT_SALES_MVW, mapSalesData68, mapExtendedWarrantySalesData1, mapExtendedYTD, mapSalesData1
-- STATISTIC_AMOUNT, -- NUMBER(15,2)
-- JRNL_LN_REF, -- VARCHAR2(10)
-- LINE_DESCR, -- VARCHAR2(30)
-- USER1, -- VARCHAR2(6)
-- USER2, -- VARCHAR2(2)
-- USER3, -- VARCHAR2(2)
-- USER4, -- VARCHAR2(1)
-- USER5, -- VARCHAR2(3)
JOURNAL_ID, -- VARCHAR2(10), mapSalesData68, mapExtendedWarrantySalesData1, mapSalesData1
JOURNAL_DATE, -- DATE, DM_030_EXT_SALES_MVW, mapSalesData68, mapExtendedWarrantySalesData1, mapExtendedYTD, mapSalesData1
-- JOURNAL_LINE, -- NUMBER(38)
-- BUDGET_HDR_STATUS, -- VARCHAR2(1)
-- BUDGET_LINE_STATUS, -- VARCHAR2(1)
-- KK_TRAN_OVER_FLAG, -- VARCHAR2(1)
-- KK_TRAN_OVER_OPRID, -- VARCHAR2(30)
-- GL_DISTRIB_STATUS, -- VARCHAR2(1)
-- APPL_JRNL_ID, -- VARCHAR2(10)
CURRENCY_CD, -- VARCHAR2(3), mapSalesData68, mapSalesData1
-- FOREIGN_CURRENCY, -- VARCHAR2(3)
-- FOREIGN_AMOUNT, -- NUMBER(26,3)
-- RT_TYPE, -- VARCHAR2(5)
-- DOC_TYPE, -- VARCHAR2(8)
-- DOC_SEQ_NBR, -- VARCHAR2(12)
-- DOC_SEQ_DATE, -- DATE
-- RATE_MULT, -- NUMBER(15,8)
-- RATE_DIV, -- NUMBER(15,8)
-- FROM_ACCRUAL, -- VARCHAR2(1)
-- BUSINESS_UNIT_PC, -- VARCHAR2(5)
-- ACTIVITY_ID, -- VARCHAR2(15)
-- RESOURCE_TYPE, -- VARCHAR2(5)
-- RESOURCE_CATEGORY, -- VARCHAR2(5)
-- RESOURCE_SUB_CAT, -- VARCHAR2(5)
-- AFFILIATE_INTRA1, -- VARCHAR2(10)
-- AFFILIATE_INTRA2, -- VARCHAR2(10)
-- BUDGET_DT, -- DATE
-- BUDGET_REF, -- VARCHAR2(8)
-- CHARTFIELD1, -- VARCHAR2(10)
-- CHARTFIELD2, -- VARCHAR2(10)
-- CHARTFIELD3, -- VARCHAR2(10)
-- CLASS_FLD, -- VARCHAR2(5)
-- ENTRY_EVENT, -- VARCHAR2(10)
-- FUND_CODE, -- VARCHAR2(5)
-- KK_TRAN_OVER_DTTM, -- DATE
-- PROGRAM_CODE, -- VARCHAR2(5)
-- ED_CREATE_DATE, -- DATE
-- ED_CREATE_ID, -- VARCHAR2(100)
-- ARCHIVE_FLAG, -- NOT NULL VARCHAR2(1)
R12_ACCOUNT,
R12_PRODUCT,
R12_ENTITY,
R12_LOCATION
)
select
BUSINESS_UNIT, -- VARCHAR2(5)
INVOICE, -- VARCHAR2(22)
LINE_SEQ_NUM, -- NUMBER(38)
-- ACCOUNTING_DT, -- DATE
ACCT_ENTRY_TYPE, -- VARCHAR2(3)
-- DISC_SUR_LVL, -- NUMBER(38)
-- DISC_SUR_ID, -- VARCHAR2(15)
-- LINE_DST_SEQ_NUM, -- NUMBER(38)
-- TAX_AUTHORITY_CD, -- VARCHAR2(3)
-- PROCESS_INSTANCE, -- NUMBER(10)
-- DISC_SUR_INDICATOR, -- VARCHAR2(1)
BUSINESS_UNIT_GL, -- VARCHAR2(5)
-- LEDGER_GROUP, -- VARCHAR2(10)
LEDGER, -- VARCHAR2(10)
-- ACCOUNTING_PERIOD, -- NUMBER(38)
-- FISCAL_YEAR, -- NUMBER(38)
ACCOUNT, -- VARCHAR2(10)
-- ALTACCT, -- VARCHAR2(10)
-- OPERATING_UNIT, -- VARCHAR2(8)
DEPTID, -- VARCHAR2(10)
PRODUCT, -- VARCHAR2(6)
-- PROJECT_ID, -- VARCHAR2(15)
-- AFFILIATE, -- VARCHAR2(5)
-- STATISTICS_CODE, -- VARCHAR2(3)
MONETARY_AMOUNT, -- NUMBER(26,3)
-- STATISTIC_AMOUNT, -- NUMBER(15,2)
-- JRNL_LN_REF, -- VARCHAR2(10)
-- LINE_DESCR, -- VARCHAR2(30)
-- USER1, -- VARCHAR2(6)
-- USER2, -- VARCHAR2(2)
-- USER3, -- VARCHAR2(2)
-- USER4, -- VARCHAR2(1)
-- USER5, -- VARCHAR2(3)
JOURNAL_ID, -- VARCHAR2(10)
JOURNAL_DATE, -- DATE
-- JOURNAL_LINE, -- NUMBER(38)
-- BUDGET_HDR_STATUS, -- VARCHAR2(1)
-- BUDGET_LINE_STATUS, -- VARCHAR2(1)
-- KK_TRAN_OVER_FLAG, -- VARCHAR2(1)
-- KK_TRAN_OVER_OPRID, -- VARCHAR2(30)
-- GL_DISTRIB_STATUS, -- VARCHAR2(1)
-- APPL_JRNL_ID, -- VARCHAR2(10)
CURRENCY_CD, -- VARCHAR2(3)
-- FOREIGN_CURRENCY, -- VARCHAR2(3)
-- FOREIGN_AMOUNT, -- NUMBER(26,3)
-- RT_TYPE, -- VARCHAR2(5)
-- DOC_TYPE, -- VARCHAR2(8)
-- DOC_SEQ_NBR, -- VARCHAR2(12)
-- DOC_SEQ_DATE, -- DATE
-- RATE_MULT, -- NUMBER(15,8)
-- RATE_DIV, -- NUMBER(15,8)
-- FROM_ACCRUAL, -- VARCHAR2(1)
-- BUSINESS_UNIT_PC, -- VARCHAR2(5)
-- ACTIVITY_ID, -- VARCHAR2(15)
-- RESOURCE_TYPE, -- VARCHAR2(5)
-- RESOURCE_CATEGORY, -- VARCHAR2(5)
-- RESOURCE_SUB_CAT, -- VARCHAR2(5)
-- AFFILIATE_INTRA1, -- VARCHAR2(10)
-- AFFILIATE_INTRA2, -- VARCHAR2(10)
-- BUDGET_DT, -- DATE
-- BUDGET_REF, -- VARCHAR2(8)
-- CHARTFIELD1, -- VARCHAR2(10)
-- CHARTFIELD2, -- VARCHAR2(10)
-- CHARTFIELD3, -- VARCHAR2(10)
-- CLASS_FLD, -- VARCHAR2(5)
-- ENTRY_EVENT, -- VARCHAR2(10)
-- FUND_CODE, -- VARCHAR2(5)
-- KK_TRAN_OVER_DTTM, -- DATE
-- PROGRAM_CODE, -- VARCHAR2(5)
-- ED_CREATE_DATE, -- DATE
-- ED_CREATE_ID, -- VARCHAR2(100)
-- ARCHIVE_FLAG, -- NOT NULL VARCHAR2(1)
DBO.F_GET_R12_ACCOUNT_STRING ('ACCOUNT', BUSINESS_UNIT, ACCOUNT, DEPTID, PRODUCT, AFFILIATE) as R12_ACCOUNT,
DBO.F_GET_R12_ACCOUNT_STRING ('PRODUCT', BUSINESS_UNIT, ACCOUNT, DEPTID, PRODUCT, AFFILIATE) as R12_PRODUCT,
DBO.F_GET_R12_ACCOUNT_STRING ('ENTITY', BUSINESS_UNIT, ACCOUNT, DEPTID, PRODUCT, AFFILIATE) as R12_ENTITY,
DBO.F_GET_R12_ACCOUNT_STRING ('LOCATION', BUSINESS_UNIT, ACCOUNT, DEPTID, PRODUCT, AFFILIATE) as R12_LOCATION
from
DBO.OTR_BI_ACCT_ENTRY_PSB;

-- create table R12_OTR_BI_HDR_PSB like OTR_BI_HDR_PSB
-- DR
-- add R12_ENTITY

select count(*) from OTR_BI_HDR_PSB; -- 29249590 9:45 AM MDT

CREATE TABLE DBO.R12_OTR_BI_HDR_PSB (
	BUSINESS_UNIT VARCHAR2(5 BYTE) NOT NULL,
	INVOICE VARCHAR2(22 BYTE) NOT NULL,
	-- INVOICE_TYPE VARCHAR2(3 BYTE) NOT NULL,
	-- CONSOL_HDR VARCHAR2(1 BYTE) NOT NULL,
	-- CONSOL_KEY VARCHAR2(22 BYTE) NOT NULL,
	-- CONSOL_SETID VARCHAR2(5 BYTE) NOT NULL,
	-- CONSOL_CUST_ID VARCHAR2(15 BYTE) NOT NULL,
	-- CONSOL_BUS_UNIT VARCHAR2(5 BYTE) NOT NULL,
	-- CONSOL_INVOICE VARCHAR2(22 BYTE) NOT NULL,
	-- ORIGINAL_INVOICE VARCHAR2(22 BYTE) NOT NULL,
	-- PRIOR_ADJ_INVOICE VARCHAR2(22 BYTE) NOT NULL,
	-- NEXT_ADJ_INVOICE VARCHAR2(22 BYTE) NOT NULL,
	-- LATEST_INVOICE VARCHAR2(22 BYTE) NOT NULL,
	-- ADJUSTED_FLAG VARCHAR2(1 BYTE) NOT NULL,
	-- BILL_TYPE_ID VARCHAR2(3 BYTE) NOT NULL,
	BILL_SOURCE_ID VARCHAR2(10 BYTE) NOT NULL,
	-- BILL_CYCLE_ID VARCHAR2(10 BYTE) NOT NULL,
	-- BILL_BY_ID VARCHAR2(10 BYTE) NOT NULL,
	-- HDR_FIELDS_KEY VARCHAR2(30 BYTE) NOT NULL,
	-- BILLING_FREQUENCY VARCHAR2(3 BYTE) NOT NULL,
	-- TEMPLATE_IVC_FLG VARCHAR2(1 BYTE) NOT NULL,
	-- TEMPLATE_INVOICE VARCHAR2(22 BYTE),
	-- AUTO_GEN_IVC_NUM VARCHAR2(1 BYTE),
	-- FROM_DT DATE,
	-- BILL_TO_CUST_ID VARCHAR2(15 BYTE),
	-- ADDRESS_SEQ_NUM NUMBER(*, 0),
	-- BILL_TO_COPIES NUMBER(*, 0),
	-- BILL_TO_MEDIA VARCHAR2(1 BYTE),
	-- CNTCT_SEQ_NUM NUMBER(*, 0),
	-- NAME1 VARCHAR2(40 BYTE),
	-- BUSINESS_UNIT_TO VARCHAR2(5 BYTE),
	-- CR_CARD_FLG VARCHAR2(1 BYTE),
	-- SUBCUST_QUAL1 VARCHAR2(15 BYTE),
	-- SUBCUST_QUAL2 VARCHAR2(15 BYTE),
	-- BILL_INQUIRY_PHONE VARCHAR2(24 BYTE),
	-- BILLING_SPECIALIST VARCHAR2(8 BYTE),
	-- COLLECTOR VARCHAR2(8 BYTE),
	-- SALES_PERSON VARCHAR2(8 BYTE),
	-- CR_ANALYST VARCHAR2(8 BYTE),
	-- PYMNT_TERMS_CD VARCHAR2(5 BYTE),
	-- BANK_CD VARCHAR2(5 BYTE),
	-- BANK_ACCT_KEY VARCHAR2(4 BYTE),
	-- BI_CURRENCY_CD VARCHAR2(3 BYTE),
	-- BASE_CURRENCY VARCHAR2(3 BYTE),
	-- CURRENCY_CD_XEU VARCHAR2(3 BYTE),
	-- FINAL_CURCNV_FLG VARCHAR2(1 BYTE),
	-- CUR_RT_TYPE VARCHAR2(5 BYTE),
	-- CUR_RT_SOURCE VARCHAR2(1 BYTE),
	-- RATE_MULT NUMBER(15, 8),
	-- RATE_DIV NUMBER(15, 8),
	-- RATE_MULT_XEU NUMBER(15, 8),
	-- RATE_DIV_XEU NUMBER(15, 8),
	-- RATE_MULT_IU NUMBER(15, 8),
	-- RATE_DIV_IU NUMBER(15, 8),
	-- RATE_DATE DATE,
	-- PAID_AMT NUMBER(26, 3),
	-- FORWARD_BAL_AMT NUMBER(26, 3),
	-- INVOICE_AMT_PRETAX NUMBER(26, 3),
	-- INVOICE_AMOUNT NUMBER(26, 3),
	-- PAID_AMT_BSE NUMBER(26, 3),
	-- FORWARD_BAL_BSE NUMBER(26, 3),
	-- INVOICE_PRETAX_BSE NUMBER(26, 3),
	-- INVOICE_AMT_BSE NUMBER(26, 3),
	-- FORWARD_BAL_XEU NUMBER(26, 3),
	-- INVOICE_PRETAX_XEU NUMBER(26, 3),
	-- INVOICE_AMT_XEU NUMBER(26, 3),
	-- PAID_AMT_XEU NUMBER(26, 3),
	-- INVOICE_DT DATE,
	-- ACCOUNTING_DT DATE,
	-- DT_INVOICED DATE,
	-- DUE_DT DATE,
	-- INVOICE_FORM_ID VARCHAR2(10 BYTE),
	-- IVC_PRINTED_FLG VARCHAR2(1 BYTE),
	-- IVC_PRINTED_DT DATE,
	-- EDI_SENT_FLG VARCHAR2(1 BYTE),
	ENTRY_TYPE VARCHAR2(5 BYTE),
	-- ENTRY_REASON VARCHAR2(5 BYTE),
	-- AR_LVL VARCHAR2(1 BYTE),
	-- AR_DST_OPT VARCHAR2(1 BYTE),
	-- DST_ID_AR VARCHAR2(10 BYTE),
	-- ACCOUNT VARCHAR2(10 BYTE),
	-- ALTACCT VARCHAR2(10 BYTE),
	-- OPERATING_UNIT VARCHAR2(8 BYTE),
	-- DEPTID VARCHAR2(10 BYTE),
	-- PRODUCT VARCHAR2(6 BYTE),
	-- AFFILIATE VARCHAR2(5 BYTE),
	-- STATISTICS_CODE VARCHAR2(3 BYTE),
	-- AR_ENTRY_CREATED VARCHAR2(1 BYTE),
	-- BUSINESS_UNIT_GL VARCHAR2(5 BYTE),
	-- GL_LVL VARCHAR2(1 BYTE),
	-- GL_ENTRY_CREATED VARCHAR2(1 BYTE),
	-- ENABLE_DFR_REV_FLG VARCHAR2(1 BYTE),
	-- DFR_ACCTG_DT_CD VARCHAR2(1 BYTE),
	-- DFR_REV_PRORATION VARCHAR2(1 BYTE),
	-- DFR_MID_PERIOD_DAY NUMBER(*, 0),
	-- DST_ID_DFR VARCHAR2(10 BYTE),
	-- BILL_STATUS VARCHAR2(3 BYTE),
	-- BILL_STATUS_TEXT VARCHAR2(50 BYTE),
	-- MANUAL_LIN_NUM_FLG VARCHAR2(1 BYTE),
	-- LAST_LINE_SEQ_NUM NUMBER(*, 0),
	-- LAST_LINE_AAUX_SEQ NUMBER(*, 0),
	-- LAST_NOTE_SEQ_NUM NUMBER(*, 0),
	-- ACCRUE_UNBILLED VARCHAR2(1 BYTE),
	-- DOC_TYPE VARCHAR2(8 BYTE),
	-- DOC_SEQ_NBR VARCHAR2(12 BYTE),
	-- DOC_SEQ_DATE DATE,
	-- PC_DISTRIB_STATUS VARCHAR2(1 BYTE),
	-- PO_REF VARCHAR2(30 BYTE),
	-- BUSINESS_UNIT_CA VARCHAR2(5 BYTE),
	-- CONTRACT_NUM VARCHAR2(25 BYTE),
	-- CONTRACT_DT DATE,
	-- CONTRACT_TYPE VARCHAR2(15 BYTE),
	-- DIRECT_INVOICING VARCHAR2(1 BYTE),
	-- BUSINESS_UNIT_OM VARCHAR2(5 BYTE),
	-- ORDER_NO VARCHAR2(10 BYTE),
	-- RMA_ID VARCHAR2(10 BYTE),
	-- ORDER_DATE DATE,
	-- FREIGHT_TERMS VARCHAR2(10 BYTE),
	-- BILL_OF_LADING VARCHAR2(30 BYTE),
	-- SHIP_TO_CUST_ID VARCHAR2(15 BYTE),
	-- SHIP_TO_ADDR_NUM NUMBER(*, 0),
	-- SHIP_ID VARCHAR2(10 BYTE),
	-- SHIP_TYPE_ID VARCHAR2(10 BYTE),
	-- SHIP_FROM_BU VARCHAR2(5 BYTE),
	-- SOLD_TO_CUST_ID VARCHAR2(15 BYTE),
	-- SOLD_TO_ADDR_NUM NUMBER(*, 0),
	-- BUSINESS_UNIT_PC VARCHAR2(5 BYTE),
	-- PROJECT_ID VARCHAR2(15 BYTE),
	-- ANALYSIS_TYPE VARCHAR2(3 BYTE),
	-- RESOURCE_TYPE VARCHAR2(5 BYTE),
	-- RESOURCE_CATEGORY VARCHAR2(5 BYTE),
	-- RESOURCE_SUB_CAT VARCHAR2(5 BYTE),
	-- ACTIVITY_ID VARCHAR2(15 BYTE),
	-- ACTIVITY_TYPE VARCHAR2(5 BYTE),
	-- SYSTEM_SOURCE VARCHAR2(3 BYTE),
	-- RANGE_SELECTION_ID VARCHAR2(30 BYTE),
	-- EMPLID VARCHAR2(11 BYTE),
	-- SSN VARCHAR2(9 BYTE),
	-- SERVICE_CUST_ID VARCHAR2(15 BYTE),
	-- SERVICE_ADDR_NUM NUMBER(*, 0),
	-- START_DT DATE,
	-- ERROR_STATUS_BI VARCHAR2(4 BYTE),
	-- COUNTRY_SHIP_TO VARCHAR2(3 BYTE),
	-- COUNTRY_SHIP_FROM VARCHAR2(3 BYTE),
	-- GEN_AP_VCHR_FLG VARCHAR2(1 BYTE),
	-- DOC_SEQ_STATUS VARCHAR2(1 BYTE),
	-- EARLY_PY_DSCNT_PCT NUMBER(6, 3),
	-- DS_PY_TRMS_TIME_ID VARCHAR2(3 BYTE),
	-- VAT_ENTITY VARCHAR2(20 BYTE),
	-- TOT_SU_TAX NUMBER(26, 3),
	-- TOT_SU_TAX_BSE NUMBER(26, 3),
	-- TOT_SU_TAX_XEU NUMBER(26, 3),
	-- TOT_VAT NUMBER(26, 3),
	-- TOT_VAT_BSE NUMBER(26, 3),
	-- TOT_VAT_XEU NUMBER(26, 3),
	-- TOT_VAT_BASIS NUMBER(26, 3),
	-- TOT_VAT_BASIS_BSE NUMBER(26, 3),
	-- TOT_VAT_BASIS_XEU NUMBER(26, 3),
	-- PAYMENT_METHOD VARCHAR2(3 BYTE),
	-- PACKSLIP_NO VARCHAR2(22 BYTE),
	-- LC_ID VARCHAR2(12 BYTE),
	-- PAID_REFERENCE VARCHAR2(30 BYTE),
	-- PPRC_PROMO_CD VARCHAR2(20 BYTE),
	-- EMAILID VARCHAR2(70 BYTE),
	-- FAX VARCHAR2(24 BYTE),
	-- LANGUAGE_CD VARCHAR2(3 BYTE),
	-- USER_AMT1 NUMBER(26, 3),
	-- USER_AMT2 NUMBER(26, 3),
	-- USER_AMT1_BSE NUMBER(26, 3),
	-- USER_AMT2_BSE NUMBER(26, 3),
	-- USER_AMT1_XEU NUMBER(26, 3),
	-- USER_AMT2_XEU NUMBER(26, 3),
	-- USER_DT1 DATE,
	-- USER_DT2 DATE,
	-- USER1 VARCHAR2(6 BYTE),
	-- USER2 VARCHAR2(2 BYTE),
	-- USER3 VARCHAR2(2 BYTE),
	-- USER4 VARCHAR2(1 BYTE),
	-- USER5 VARCHAR2(3 BYTE),
	-- USER6 VARCHAR2(8 BYTE),
	-- USER7 VARCHAR2(1 BYTE),
	-- USER8 VARCHAR2(5 BYTE),
	-- USER9 VARCHAR2(25 BYTE),
	-- PROCESS_INSTANCE NUMBER(10, 0),
	-- ADD_DTTM DATE,
	-- LAST_UPDATE_DTTM DATE,
	-- LAST_MAINT_OPRID VARCHAR2(30 BYTE),
	-- AP_CREATED_DT DATE,
	-- BILLING_AUTHORITY VARCHAR2(8 BYTE),
	-- BI_BU_TAX_IND VARCHAR2(1 BYTE),
	-- BUSINESS_UNIT_AM VARCHAR2(5 BYTE),
	-- BUSINESS_UNIT_RF VARCHAR2(5 BYTE),
	-- CF_ACTION_FLG VARCHAR2(1 BYTE),
	-- COUNTRY_VAT_BILLFR VARCHAR2(3 BYTE),
	-- COUNTRY_VAT_BILLTO VARCHAR2(3 BYTE),
	-- END_DT DATE,
	-- ENTRY_EVENT VARCHAR2(10 BYTE),
	-- EXD_INVOICE_NO VARCHAR2(10 BYTE),
	-- GEN_AR_ITEM_FLG VARCHAR2(1 BYTE),
	-- LOC_DOC_ID VARCHAR2(15 BYTE),
	-- MAST_CONTR_ID VARCHAR2(25 BYTE),
	-- MAX_TAX_FLG VARCHAR2(1 BYTE),
	-- PHYSICAL_NATURE VARCHAR2(1 BYTE),
	-- PRELOAD_IND VARCHAR2(1 BYTE),
	-- RECURRING_END_DT DATE,
	-- RECURRING_START_DT DATE,
	-- REIMB_AGREEMENT VARCHAR2(25 BYTE),
	-- REPRINT_GROUP_ID VARCHAR2(30 BYTE),
	-- SOURCE_REF_KEY VARCHAR2(5 BYTE),
	-- SOURCE_REF_NO VARCHAR2(35 BYTE),
	-- SOURCE_REF_TYPE VARCHAR2(3 BYTE),
	-- SO_ID VARCHAR2(10 BYTE),
	-- STATE_SHIP_FROM VARCHAR2(6 BYTE),
	-- STATE_SHIP_TO VARCHAR2(6 BYTE),
	-- STX_TAX_AUTH_CD VARCHAR2(8 BYTE),
	-- TOT_EXD_AMT NUMBER(26, 3),
	-- TOT_EXD_AMT_BSE NUMBER(26, 3),
	-- TOT_STX_AMT NUMBER(26, 3),
	-- TOT_STX_AMT_BSE NUMBER(26, 3),
	-- TO_DT DATE,
	-- VAT_TREATMENT_GRP VARCHAR2(4 BYTE),
	-- ED_CREATE_DATE DATE,
	-- ED_CREATE_ID VARCHAR2(100 BYTE),
	-- ED_SOURCE_ARCHIVE_IND VARCHAR2(1 BYTE),
	-- ARCHIVE_FLAG VARCHAR2(1 BYTE) NOT NULL 
	R12_ENTITY VARCHAR2(5 BYTE) NOT NULL
);
-- primary key?
-- indexes?
-- constraints?

truncate table R12_OTR_BI_HDR_PSB;
insert into R12_OTR_BI_HDR_PSB
(
BUSINESS_UNIT, -- VARCHAR2(5), DM_030_EXT_SALES_MVW, mapSalesData68, mapExtendedWarrantySalesData1, mapExtendedYTD, mapSalesData1
INVOICE, -- VARCHAR2(22), DM_030_EXT_SALES_MVW, mapSalesData68, mapExtendedWarrantySalesData1, mapExtendedYTD, mapSalesData1
-- INVOICE_TYPE, -- VARCHAR2(3)
-- CONSOL_HDR, -- VARCHAR2(1)
-- CONSOL_KEY, -- VARCHAR2(22)
-- CONSOL_SETID, -- VARCHAR2(5)
-- CONSOL_CUST_ID, -- VARCHAR2(15)
-- CONSOL_BUS_UNIT, -- VARCHAR2(5)
-- CONSOL_INVOICE, -- VARCHAR2(22)
-- ORIGINAL_INVOICE, -- VARCHAR2(22)
-- PRIOR_ADJ_INVOICE, -- VARCHAR2(22)
-- NEXT_ADJ_INVOICE, -- VARCHAR2(22)
-- LATEST_INVOICE, -- VARCHAR2(22)
-- ADJUSTED_FLAG, -- VARCHAR2(1)
-- BILL_TYPE_ID, -- VARCHAR2(3)
BILL_SOURCE_ID, -- VARCHAR2(10), mapSalesData68, mapSalesData1
-- BILL_CYCLE_ID, -- VARCHAR2(10)
-- BILL_BY_ID, -- VARCHAR2(10)
-- HDR_FIELDS_KEY, -- VARCHAR2(30)
-- BILLING_FREQUENCY, -- VARCHAR2(3)
-- TEMPLATE_IVC_FLG, -- VARCHAR2(1)
-- TEMPLATE_INVOICE, -- VARCHAR2(22)
-- AUTO_GEN_IVC_NUM, -- VARCHAR2(1)
-- FROM_DT, -- DATE
-- BILL_TO_CUST_ID, -- VARCHAR2(15)
-- ADDRESS_SEQ_NUM, -- NUMBER(38)
-- BILL_TO_COPIES, -- NUMBER(38)
-- BILL_TO_MEDIA, -- VARCHAR2(1)
-- CNTCT_SEQ_NUM, -- NUMBER(38)
-- NAME1, -- VARCHAR2(40)
-- BUSINESS_UNIT_TO, -- VARCHAR2(5)
-- CR_CARD_FLG, -- VARCHAR2(1)
-- SUBCUST_QUAL1, -- VARCHAR2(15)
-- SUBCUST_QUAL2, -- VARCHAR2(15)
-- BILL_INQUIRY_PHONE, -- VARCHAR2(24)
-- BILLING_SPECIALIST, -- VARCHAR2(8)
-- COLLECTOR, -- VARCHAR2(8)
-- SALES_PERSON, -- VARCHAR2(8)
-- CR_ANALYST, -- VARCHAR2(8)
-- PYMNT_TERMS_CD, -- VARCHAR2(5)
-- BANK_CD, -- VARCHAR2(5)
-- BANK_ACCT_KEY, -- VARCHAR2(4)
-- BI_CURRENCY_CD, -- VARCHAR2(3)
-- BASE_CURRENCY, -- VARCHAR2(3)
-- CURRENCY_CD_XEU, -- VARCHAR2(3)
-- FINAL_CURCNV_FLG, -- VARCHAR2(1)
-- CUR_RT_TYPE, -- VARCHAR2(5)
-- CUR_RT_SOURCE, -- VARCHAR2(1)
-- RATE_MULT, -- NUMBER(15,8)
-- RATE_DIV, -- NUMBER(15,8)
-- RATE_MULT_XEU, -- NUMBER(15,8)
-- RATE_DIV_XEU, -- NUMBER(15,8)
-- RATE_MULT_IU, -- NUMBER(15,8)
-- RATE_DIV_IU, -- NUMBER(15,8)
-- RATE_DATE, -- DATE
-- PAID_AMT, -- NUMBER(26,3)
-- FORWARD_BAL_AMT, -- NUMBER(26,3)
-- INVOICE_AMT_PRETAX, -- NUMBER(26,3)
-- INVOICE_AMOUNT, -- NUMBER(26,3)
-- PAID_AMT_BSE, -- NUMBER(26,3)
-- FORWARD_BAL_BSE, -- NUMBER(26,3)
-- INVOICE_PRETAX_BSE, -- NUMBER(26,3)
-- INVOICE_AMT_BSE, -- NUMBER(26,3)
-- FORWARD_BAL_XEU, -- NUMBER(26,3)
-- INVOICE_PRETAX_XEU, -- NUMBER(26,3)
-- INVOICE_AMT_XEU, -- NUMBER(26,3)
-- PAID_AMT_XEU, -- NUMBER(26,3)
-- INVOICE_DT, -- DATE
-- ACCOUNTING_DT, -- DATE
-- DT_INVOICED, -- DATE
-- DUE_DT, -- DATE
-- INVOICE_FORM_ID, -- VARCHAR2(10)
-- IVC_PRINTED_FLG, -- VARCHAR2(1)
-- IVC_PRINTED_DT, -- DATE
-- EDI_SENT_FLG, -- VARCHAR2(1)
ENTRY_TYPE, -- VARCHAR2(5), DM_030_EXT_SALES_MVW, mapExtendedWarrantySalesData1, mapExtendedYTD
-- ENTRY_REASON, -- VARCHAR2(5)
-- AR_LVL, -- VARCHAR2(1)
-- AR_DST_OPT, -- VARCHAR2(1)
-- DST_ID_AR, -- VARCHAR2(10)
-- ACCOUNT, -- VARCHAR2(10)
-- ALTACCT, -- VARCHAR2(10)
-- OPERATING_UNIT, -- VARCHAR2(8)
-- DEPTID, -- VARCHAR2(10)
-- PRODUCT, -- VARCHAR2(6)
-- AFFILIATE, -- VARCHAR2(5)
-- STATISTICS_CODE, -- VARCHAR2(3)
-- AR_ENTRY_CREATED, -- VARCHAR2(1)
-- BUSINESS_UNIT_GL, -- VARCHAR2(5)
-- GL_LVL, -- VARCHAR2(1)
-- GL_ENTRY_CREATED, -- VARCHAR2(1)
-- ENABLE_DFR_REV_FLG, -- VARCHAR2(1)
-- DFR_ACCTG_DT_CD, -- VARCHAR2(1)
-- DFR_REV_PRORATION, -- VARCHAR2(1)
-- DFR_MID_PERIOD_DAY, -- NUMBER(38)
-- DST_ID_DFR, -- VARCHAR2(10)
-- BILL_STATUS, -- VARCHAR2(3)
-- BILL_STATUS_TEXT, -- VARCHAR2(50)
-- MANUAL_LIN_NUM_FLG, -- VARCHAR2(1)
-- LAST_LINE_SEQ_NUM, -- NUMBER(38)
-- LAST_LINE_AAUX_SEQ, -- NUMBER(38)
-- LAST_NOTE_SEQ_NUM, -- NUMBER(38)
-- ACCRUE_UNBILLED, -- VARCHAR2(1)
-- DOC_TYPE, -- VARCHAR2(8)
-- DOC_SEQ_NBR, -- VARCHAR2(12)
-- DOC_SEQ_DATE, -- DATE
-- PC_DISTRIB_STATUS, -- VARCHAR2(1)
-- PO_REF, -- VARCHAR2(30)
-- BUSINESS_UNIT_CA, -- VARCHAR2(5)
-- CONTRACT_NUM, -- VARCHAR2(25)
-- CONTRACT_DT, -- DATE
-- CONTRACT_TYPE, -- VARCHAR2(15)
-- DIRECT_INVOICING, -- VARCHAR2(1)
-- BUSINESS_UNIT_OM, -- VARCHAR2(5)
-- ORDER_NO, -- VARCHAR2(10)
-- RMA_ID, -- VARCHAR2(10)
-- ORDER_DATE, -- DATE
-- FREIGHT_TERMS, -- VARCHAR2(10)
-- BILL_OF_LADING, -- VARCHAR2(30)
-- SHIP_TO_CUST_ID, -- VARCHAR2(15)
-- SHIP_TO_ADDR_NUM, -- NUMBER(38)
-- SHIP_ID, -- VARCHAR2(10)
-- SHIP_TYPE_ID, -- VARCHAR2(10)
-- SHIP_FROM_BU, -- VARCHAR2(5)
-- SOLD_TO_CUST_ID, -- VARCHAR2(15)
-- SOLD_TO_ADDR_NUM, -- NUMBER(38)
-- BUSINESS_UNIT_PC, -- VARCHAR2(5)
-- PROJECT_ID, -- VARCHAR2(15)
-- ANALYSIS_TYPE, -- VARCHAR2(3)
-- RESOURCE_TYPE, -- VARCHAR2(5)
-- RESOURCE_CATEGORY, -- VARCHAR2(5)
-- RESOURCE_SUB_CAT, -- VARCHAR2(5)
-- ACTIVITY_ID, -- VARCHAR2(15)
-- ACTIVITY_TYPE, -- VARCHAR2(5)
-- SYSTEM_SOURCE, -- VARCHAR2(3)
-- RANGE_SELECTION_ID, -- VARCHAR2(30)
-- EMPLID, -- VARCHAR2(11)
-- SSN, -- VARCHAR2(9)
-- SERVICE_CUST_ID, -- VARCHAR2(15)
-- SERVICE_ADDR_NUM, -- NUMBER(38)
-- START_DT, -- DATE
-- ERROR_STATUS_BI, -- VARCHAR2(4)
-- COUNTRY_SHIP_TO, -- VARCHAR2(3)
-- COUNTRY_SHIP_FROM, -- VARCHAR2(3)
-- GEN_AP_VCHR_FLG, -- VARCHAR2(1)
-- DOC_SEQ_STATUS, -- VARCHAR2(1)
-- EARLY_PY_DSCNT_PCT, -- NUMBER(6,3)
-- DS_PY_TRMS_TIME_ID, -- VARCHAR2(3)
-- VAT_ENTITY, -- VARCHAR2(20)
-- TOT_SU_TAX, -- NUMBER(26,3)
-- TOT_SU_TAX_BSE, -- NUMBER(26,3)
-- TOT_SU_TAX_XEU, -- NUMBER(26,3)
-- TOT_VAT, -- NUMBER(26,3)
-- TOT_VAT_BSE, -- NUMBER(26,3)
-- TOT_VAT_XEU, -- NUMBER(26,3)
-- TOT_VAT_BASIS, -- NUMBER(26,3)
-- TOT_VAT_BASIS_BSE, -- NUMBER(26,3)
-- TOT_VAT_BASIS_XEU, -- NUMBER(26,3)
-- PAYMENT_METHOD, -- VARCHAR2(3)
-- PACKSLIP_NO, -- VARCHAR2(22)
-- LC_ID, -- VARCHAR2(12)
-- PAID_REFERENCE, -- VARCHAR2(30)
-- PPRC_PROMO_CD, -- VARCHAR2(20)
-- EMAILID, -- VARCHAR2(70)
-- FAX, -- VARCHAR2(24)
-- LANGUAGE_CD, -- VARCHAR2(3)
-- USER_AMT1, -- NUMBER(26,3)
-- USER_AMT2, -- NUMBER(26,3)
-- USER_AMT1_BSE, -- NUMBER(26,3)
-- USER_AMT2_BSE, -- NUMBER(26,3)
-- USER_AMT1_XEU, -- NUMBER(26,3)
-- USER_AMT2_XEU, -- NUMBER(26,3)
-- USER_DT1, -- DATE
-- USER_DT2, -- DATE
-- USER1, -- VARCHAR2(6)
-- USER2, -- VARCHAR2(2)
-- USER3, -- VARCHAR2(2)
-- USER4, -- VARCHAR2(1)
-- USER5, -- VARCHAR2(3)
-- USER6, -- VARCHAR2(8)
-- USER7, -- VARCHAR2(1)
-- USER8, -- VARCHAR2(5)
-- USER9, -- VARCHAR2(25)
-- PROCESS_INSTANCE, -- NUMBER(10)
-- ADD_DTTM, -- DATE
-- LAST_UPDATE_DTTM, -- DATE
-- LAST_MAINT_OPRID, -- VARCHAR2(30)
-- AP_CREATED_DT, -- DATE
-- BILLING_AUTHORITY, -- VARCHAR2(8)
-- BI_BU_TAX_IND, -- VARCHAR2(1)
-- BUSINESS_UNIT_AM, -- VARCHAR2(5)
-- BUSINESS_UNIT_RF, -- VARCHAR2(5)
-- CF_ACTION_FLG, -- VARCHAR2(1)
-- COUNTRY_VAT_BILLFR, -- VARCHAR2(3)
-- COUNTRY_VAT_BILLTO, -- VARCHAR2(3)
-- END_DT, -- DATE
-- ENTRY_EVENT, -- VARCHAR2(10)
-- EXD_INVOICE_NO, -- VARCHAR2(10)
-- GEN_AR_ITEM_FLG, -- VARCHAR2(1)
-- LOC_DOC_ID, -- VARCHAR2(15)
-- MAST_CONTR_ID, -- VARCHAR2(25)
-- MAX_TAX_FLG, -- VARCHAR2(1)
-- PHYSICAL_NATURE, -- VARCHAR2(1)
-- PRELOAD_IND, -- VARCHAR2(1)
-- RECURRING_END_DT, -- DATE
-- RECURRING_START_DT, -- DATE
-- REIMB_AGREEMENT, -- VARCHAR2(25)
-- REPRINT_GROUP_ID, -- VARCHAR2(30)
-- SOURCE_REF_KEY, -- VARCHAR2(5)
-- SOURCE_REF_NO, -- VARCHAR2(35)
-- SOURCE_REF_TYPE, -- VARCHAR2(3)
-- SO_ID, -- VARCHAR2(10)
-- STATE_SHIP_FROM, -- VARCHAR2(6)
-- STATE_SHIP_TO, -- VARCHAR2(6)
-- STX_TAX_AUTH_CD, -- VARCHAR2(8)
-- TOT_EXD_AMT, -- NUMBER(26,3)
-- TOT_EXD_AMT_BSE, -- NUMBER(26,3)
-- TOT_STX_AMT, -- NUMBER(26,3)
-- TOT_STX_AMT_BSE, -- NUMBER(26,3)
-- TO_DT, -- DATE
-- VAT_TREATMENT_GRP, -- VARCHAR2(4)
-- ED_CREATE_DATE, -- DATE
-- ED_CREATE_ID, -- VARCHAR2(100)
-- ED_SOURCE_ARCHIVE_IND, -- VARCHAR2(1)
-- ARCHIVE_FLAG, -- NOT NULL VARCHAR2(1)
R12_ENTITY
)
select
BUSINESS_UNIT, -- VARCHAR2(5)
INVOICE, -- VARCHAR2(22)
-- INVOICE_TYPE, -- VARCHAR2(3)
-- CONSOL_HDR, -- VARCHAR2(1)
-- CONSOL_KEY, -- VARCHAR2(22)
-- CONSOL_SETID, -- VARCHAR2(5)
-- CONSOL_CUST_ID, -- VARCHAR2(15)
-- CONSOL_BUS_UNIT, -- VARCHAR2(5)
-- CONSOL_INVOICE, -- VARCHAR2(22)
-- ORIGINAL_INVOICE, -- VARCHAR2(22)
-- PRIOR_ADJ_INVOICE, -- VARCHAR2(22)
-- NEXT_ADJ_INVOICE, -- VARCHAR2(22)
-- LATEST_INVOICE, -- VARCHAR2(22)
-- ADJUSTED_FLAG, -- VARCHAR2(1)
-- BILL_TYPE_ID, -- VARCHAR2(3)
BILL_SOURCE_ID, -- VARCHAR2(10)
-- BILL_CYCLE_ID, -- VARCHAR2(10)
-- BILL_BY_ID, -- VARCHAR2(10)
-- HDR_FIELDS_KEY, -- VARCHAR2(30)
-- BILLING_FREQUENCY, -- VARCHAR2(3)
-- TEMPLATE_IVC_FLG, -- VARCHAR2(1)
-- TEMPLATE_INVOICE, -- VARCHAR2(22)
-- AUTO_GEN_IVC_NUM, -- VARCHAR2(1)
-- FROM_DT, -- DATE
-- BILL_TO_CUST_ID, -- VARCHAR2(15)
-- ADDRESS_SEQ_NUM, -- NUMBER(38)
-- BILL_TO_COPIES, -- NUMBER(38)
-- BILL_TO_MEDIA, -- VARCHAR2(1)
-- CNTCT_SEQ_NUM, -- NUMBER(38)
-- NAME1, -- VARCHAR2(40)
-- BUSINESS_UNIT_TO, -- VARCHAR2(5)
-- CR_CARD_FLG, -- VARCHAR2(1)
-- SUBCUST_QUAL1, -- VARCHAR2(15)
-- SUBCUST_QUAL2, -- VARCHAR2(15)
-- BILL_INQUIRY_PHONE, -- VARCHAR2(24)
-- BILLING_SPECIALIST, -- VARCHAR2(8)
-- COLLECTOR, -- VARCHAR2(8)
-- SALES_PERSON, -- VARCHAR2(8)
-- CR_ANALYST, -- VARCHAR2(8)
-- PYMNT_TERMS_CD, -- VARCHAR2(5)
-- BANK_CD, -- VARCHAR2(5)
-- BANK_ACCT_KEY, -- VARCHAR2(4)
-- BI_CURRENCY_CD, -- VARCHAR2(3)
-- BASE_CURRENCY, -- VARCHAR2(3)
-- CURRENCY_CD_XEU, -- VARCHAR2(3)
-- FINAL_CURCNV_FLG, -- VARCHAR2(1)
-- CUR_RT_TYPE, -- VARCHAR2(5)
-- CUR_RT_SOURCE, -- VARCHAR2(1)
-- RATE_MULT, -- NUMBER(15,8)
-- RATE_DIV, -- NUMBER(15,8)
-- RATE_MULT_XEU, -- NUMBER(15,8)
-- RATE_DIV_XEU, -- NUMBER(15,8)
-- RATE_MULT_IU, -- NUMBER(15,8)
-- RATE_DIV_IU, -- NUMBER(15,8)
-- RATE_DATE, -- DATE
-- PAID_AMT, -- NUMBER(26,3)
-- FORWARD_BAL_AMT, -- NUMBER(26,3)
-- INVOICE_AMT_PRETAX, -- NUMBER(26,3)
-- INVOICE_AMOUNT, -- NUMBER(26,3)
-- PAID_AMT_BSE, -- NUMBER(26,3)
-- FORWARD_BAL_BSE, -- NUMBER(26,3)
-- INVOICE_PRETAX_BSE, -- NUMBER(26,3)
-- INVOICE_AMT_BSE, -- NUMBER(26,3)
-- FORWARD_BAL_XEU, -- NUMBER(26,3)
-- INVOICE_PRETAX_XEU, -- NUMBER(26,3)
-- INVOICE_AMT_XEU, -- NUMBER(26,3)
-- PAID_AMT_XEU, -- NUMBER(26,3)
-- INVOICE_DT, -- DATE
-- ACCOUNTING_DT, -- DATE
-- DT_INVOICED, -- DATE
-- DUE_DT, -- DATE
-- INVOICE_FORM_ID, -- VARCHAR2(10)
-- IVC_PRINTED_FLG, -- VARCHAR2(1)
-- IVC_PRINTED_DT, -- DATE
-- EDI_SENT_FLG, -- VARCHAR2(1)
ENTRY_TYPE, -- VARCHAR2(5)
-- ENTRY_REASON, -- VARCHAR2(5)
-- AR_LVL, -- VARCHAR2(1)
-- AR_DST_OPT, -- VARCHAR2(1)
-- DST_ID_AR, -- VARCHAR2(10)
-- ACCOUNT, -- VARCHAR2(10)
-- ALTACCT, -- VARCHAR2(10)
-- OPERATING_UNIT, -- VARCHAR2(8)
-- DEPTID, -- VARCHAR2(10)
-- PRODUCT, -- VARCHAR2(6)
-- AFFILIATE, -- VARCHAR2(5)
-- STATISTICS_CODE, -- VARCHAR2(3)
-- AR_ENTRY_CREATED, -- VARCHAR2(1)
-- BUSINESS_UNIT_GL, -- VARCHAR2(5)
-- GL_LVL, -- VARCHAR2(1)
-- GL_ENTRY_CREATED, -- VARCHAR2(1)
-- ENABLE_DFR_REV_FLG, -- VARCHAR2(1)
-- DFR_ACCTG_DT_CD, -- VARCHAR2(1)
-- DFR_REV_PRORATION, -- VARCHAR2(1)
-- DFR_MID_PERIOD_DAY, -- NUMBER(38)
-- DST_ID_DFR, -- VARCHAR2(10)
-- BILL_STATUS, -- VARCHAR2(3)
-- BILL_STATUS_TEXT, -- VARCHAR2(50)
-- MANUAL_LIN_NUM_FLG, -- VARCHAR2(1)
-- LAST_LINE_SEQ_NUM, -- NUMBER(38)
-- LAST_LINE_AAUX_SEQ, -- NUMBER(38)
-- LAST_NOTE_SEQ_NUM, -- NUMBER(38)
-- ACCRUE_UNBILLED, -- VARCHAR2(1)
-- DOC_TYPE, -- VARCHAR2(8)
-- DOC_SEQ_NBR, -- VARCHAR2(12)
-- DOC_SEQ_DATE, -- DATE
-- PC_DISTRIB_STATUS, -- VARCHAR2(1)
-- PO_REF, -- VARCHAR2(30)
-- BUSINESS_UNIT_CA, -- VARCHAR2(5)
-- CONTRACT_NUM, -- VARCHAR2(25)
-- CONTRACT_DT, -- DATE
-- CONTRACT_TYPE, -- VARCHAR2(15)
-- DIRECT_INVOICING, -- VARCHAR2(1)
-- BUSINESS_UNIT_OM, -- VARCHAR2(5)
-- ORDER_NO, -- VARCHAR2(10)
-- RMA_ID, -- VARCHAR2(10)
-- ORDER_DATE, -- DATE
-- FREIGHT_TERMS, -- VARCHAR2(10)
-- BILL_OF_LADING, -- VARCHAR2(30)
-- SHIP_TO_CUST_ID, -- VARCHAR2(15)
-- SHIP_TO_ADDR_NUM, -- NUMBER(38)
-- SHIP_ID, -- VARCHAR2(10)
-- SHIP_TYPE_ID, -- VARCHAR2(10)
-- SHIP_FROM_BU, -- VARCHAR2(5)
-- SOLD_TO_CUST_ID, -- VARCHAR2(15)
-- SOLD_TO_ADDR_NUM, -- NUMBER(38)
-- BUSINESS_UNIT_PC, -- VARCHAR2(5)
-- PROJECT_ID, -- VARCHAR2(15)
-- ANALYSIS_TYPE, -- VARCHAR2(3)
-- RESOURCE_TYPE, -- VARCHAR2(5)
-- RESOURCE_CATEGORY, -- VARCHAR2(5)
-- RESOURCE_SUB_CAT, -- VARCHAR2(5)
-- ACTIVITY_ID, -- VARCHAR2(15)
-- ACTIVITY_TYPE, -- VARCHAR2(5)
-- SYSTEM_SOURCE, -- VARCHAR2(3)
-- RANGE_SELECTION_ID, -- VARCHAR2(30)
-- EMPLID, -- VARCHAR2(11)
-- SSN, -- VARCHAR2(9)
-- SERVICE_CUST_ID, -- VARCHAR2(15)
-- SERVICE_ADDR_NUM, -- NUMBER(38)
-- START_DT, -- DATE
-- ERROR_STATUS_BI, -- VARCHAR2(4)
-- COUNTRY_SHIP_TO, -- VARCHAR2(3)
-- COUNTRY_SHIP_FROM, -- VARCHAR2(3)
-- GEN_AP_VCHR_FLG, -- VARCHAR2(1)
-- DOC_SEQ_STATUS, -- VARCHAR2(1)
-- EARLY_PY_DSCNT_PCT, -- NUMBER(6,3)
-- DS_PY_TRMS_TIME_ID, -- VARCHAR2(3)
-- VAT_ENTITY, -- VARCHAR2(20)
-- TOT_SU_TAX, -- NUMBER(26,3)
-- TOT_SU_TAX_BSE, -- NUMBER(26,3)
-- TOT_SU_TAX_XEU, -- NUMBER(26,3)
-- TOT_VAT, -- NUMBER(26,3)
-- TOT_VAT_BSE, -- NUMBER(26,3)
-- TOT_VAT_XEU, -- NUMBER(26,3)
-- TOT_VAT_BASIS, -- NUMBER(26,3)
-- TOT_VAT_BASIS_BSE, -- NUMBER(26,3)
-- TOT_VAT_BASIS_XEU, -- NUMBER(26,3)
-- PAYMENT_METHOD, -- VARCHAR2(3)
-- PACKSLIP_NO, -- VARCHAR2(22)
-- LC_ID, -- VARCHAR2(12)
-- PAID_REFERENCE, -- VARCHAR2(30)
-- PPRC_PROMO_CD, -- VARCHAR2(20)
-- EMAILID, -- VARCHAR2(70)
-- FAX, -- VARCHAR2(24)
-- LANGUAGE_CD, -- VARCHAR2(3)
-- USER_AMT1, -- NUMBER(26,3)
-- USER_AMT2, -- NUMBER(26,3)
-- USER_AMT1_BSE, -- NUMBER(26,3)
-- USER_AMT2_BSE, -- NUMBER(26,3)
-- USER_AMT1_XEU, -- NUMBER(26,3)
-- USER_AMT2_XEU, -- NUMBER(26,3)
-- USER_DT1, -- DATE
-- USER_DT2, -- DATE
-- USER1, -- VARCHAR2(6)
-- USER2, -- VARCHAR2(2)
-- USER3, -- VARCHAR2(2)
-- USER4, -- VARCHAR2(1)
-- USER5, -- VARCHAR2(3)
-- USER6, -- VARCHAR2(8)
-- USER7, -- VARCHAR2(1)
-- USER8, -- VARCHAR2(5)
-- USER9, -- VARCHAR2(25)
-- PROCESS_INSTANCE, -- NUMBER(10)
-- ADD_DTTM, -- DATE
-- LAST_UPDATE_DTTM, -- DATE
-- LAST_MAINT_OPRID, -- VARCHAR2(30)
-- AP_CREATED_DT, -- DATE
-- BILLING_AUTHORITY, -- VARCHAR2(8)
-- BI_BU_TAX_IND, -- VARCHAR2(1)
-- BUSINESS_UNIT_AM, -- VARCHAR2(5)
-- BUSINESS_UNIT_RF, -- VARCHAR2(5)
-- CF_ACTION_FLG, -- VARCHAR2(1)
-- COUNTRY_VAT_BILLFR, -- VARCHAR2(3)
-- COUNTRY_VAT_BILLTO, -- VARCHAR2(3)
-- END_DT, -- DATE
-- ENTRY_EVENT, -- VARCHAR2(10)
-- EXD_INVOICE_NO, -- VARCHAR2(10)
-- GEN_AR_ITEM_FLG, -- VARCHAR2(1)
-- LOC_DOC_ID, -- VARCHAR2(15)
-- MAST_CONTR_ID, -- VARCHAR2(25)
-- MAX_TAX_FLG, -- VARCHAR2(1)
-- PHYSICAL_NATURE, -- VARCHAR2(1)
-- PRELOAD_IND, -- VARCHAR2(1)
-- RECURRING_END_DT, -- DATE
-- RECURRING_START_DT, -- DATE
-- REIMB_AGREEMENT, -- VARCHAR2(25)
-- REPRINT_GROUP_ID, -- VARCHAR2(30)
-- SOURCE_REF_KEY, -- VARCHAR2(5)
-- SOURCE_REF_NO, -- VARCHAR2(35)
-- SOURCE_REF_TYPE, -- VARCHAR2(3)
-- SO_ID, -- VARCHAR2(10)
-- STATE_SHIP_FROM, -- VARCHAR2(6)
-- STATE_SHIP_TO, -- VARCHAR2(6)
-- STX_TAX_AUTH_CD, -- VARCHAR2(8)
-- TOT_EXD_AMT, -- NUMBER(26,3)
-- TOT_EXD_AMT_BSE, -- NUMBER(26,3)
-- TOT_STX_AMT, -- NUMBER(26,3)
-- TOT_STX_AMT_BSE, -- NUMBER(26,3)
-- TO_DT, -- DATE
-- VAT_TREATMENT_GRP, -- VARCHAR2(4)
-- ED_CREATE_DATE, -- DATE
-- ED_CREATE_ID, -- VARCHAR2(100)
-- ED_SOURCE_ARCHIVE_IND, -- VARCHAR2(1)
-- ARCHIVE_FLAG, -- NOT NULL VARCHAR2(1)
DBO.F_GET_R12_ACCOUNT_STRING ('ENTITY', BUSINESS_UNIT, ACCOUNT, DEPTID, PRODUCT, null) as R12_ENTITY
from
OTR_BI_HDR_PSB;

-- CREATE TABLE R12_OTR_BI_LINE_PSB like OTR_BI_LINE_PSB
-- add R12_ENTITY

select count(*) from OTR_BI_LINE_PSB; -- 86535630 9:50 AM MDT

CREATE TABLE DBO.R12_OTR_BI_LINE_PSB (
	BUSINESS_UNIT VARCHAR2(5 BYTE),
	INVOICE VARCHAR2(22 BYTE),
	LINE_SEQ_NUM NUMBER(*, 0),
	-- INVOICE_LINE NUMBER(*, 0),
	-- ORIGINAL_INVOICE VARCHAR2(22 BYTE),
	-- ORIGINAL_LINE_SEQ NUMBER(*, 0),
	-- NEXT_ADJ_INVOICE VARCHAR2(22 BYTE),
	-- NEXT_ADJ_LINE_SEQ NUMBER(*, 0),
	-- PRIOR_ADJ_INVOICE VARCHAR2(22 BYTE),
	-- PRIOR_ADJ_LINE_SEQ NUMBER(*, 0),
	-- LATEST_INVOICE VARCHAR2(22 BYTE),
	-- LATEST_LINE_SEQ NUMBER(*, 0),
	-- BILL_SOURCE_ID VARCHAR2(10 BYTE),
	-- SUBCUST_QUAL1 VARCHAR2(15 BYTE),
	-- SUBCUST_QUAL2 VARCHAR2(15 BYTE),
	-- ADJ_LINE_TYPE VARCHAR2(3 BYTE),
	-- ADJUSTED_FLAG VARCHAR2(1 BYTE),
	-- LINE_TYPE VARCHAR2(4 BYTE),
	-- BI_CURRENCY_CD VARCHAR2(3 BYTE),
	-- BASE_CURRENCY VARCHAR2(3 BYTE),
	-- CURRENCY_CD_XEU VARCHAR2(3 BYTE),
	-- CHARGE_FROM_DT DATE,
	IDENTIFIER VARCHAR2(18 BYTE),
	-- DESCR VARCHAR2(30 BYTE),
	-- UNIT_OF_MEASURE VARCHAR2(3 BYTE),
	-- QTY NUMBER(15, 4),
	-- UNIT_AMT NUMBER(15, 4),
	-- PRICE_RECALC_FLG VARCHAR2(1 BYTE),
	-- TAX_CD VARCHAR2(8 BYTE),
	-- TAX_EXEMPT_CERT VARCHAR2(30 BYTE),
	-- TAX_EXEMPT_FLG VARCHAR2(1 BYTE),
	-- GROSS_EXTENDED_AMT NUMBER(26, 3),
	-- NET_EXTENDED_AMT NUMBER(26, 3),
	-- ORIG_AMOUNT NUMBER(26, 3),
	-- GROSS_EXTENDED_BSE NUMBER(26, 3),
	-- NET_EXTENDED_BSE NUMBER(26, 3),
	-- GROSS_EXTENDED_XEU NUMBER(26, 3),
	-- NET_EXTENDED_XEU NUMBER(26, 3),
	-- TAX_AMT NUMBER(26, 3),
	-- TAX_AMT_BSE NUMBER(26, 3),
	-- TAX_AMT_XEU NUMBER(26, 3),
	-- TAX_PCT NUMBER(6, 4),
	-- FINAL_TAX_FLG VARCHAR2(1 BYTE),
	-- VAT_BASIS_AMT NUMBER(26, 3),
	-- VAT_BASIS_AMT_BSE NUMBER(26, 3),
	-- VAT_BASIS_AMT_XEU NUMBER(26, 3),
	-- VAT_AMT NUMBER(26, 3),
	-- VAT_AMT_BSE NUMBER(26, 3),
	-- VAT_AMT_XEU NUMBER(26, 3),
	-- VAT_TRANS_AMT NUMBER(26, 3),
	-- VAT_TRANS_AMT_BSE NUMBER(26, 3),
	-- VAT_TXN_TYPE_CD VARCHAR2(4 BYTE),
	-- TAX_CD_VAT VARCHAR2(8 BYTE),
	-- TAX_CD_VAT_PCT NUMBER(7, 4),
	-- VAT_APPLICABILITY VARCHAR2(1 BYTE),
	-- PROD_GRP_SETID VARCHAR2(5 BYTE),
	-- VAT_PRODUCT_GROUP VARCHAR2(10 BYTE),
	-- PRODUCT_KIT_ID VARCHAR2(18 BYTE),
	-- VAT_DISTRIB_STATUS VARCHAR2(1 BYTE),
	-- TAX_VAT_FLG VARCHAR2(1 BYTE),
	-- REV_RECOG_BASIS VARCHAR2(3 BYTE),
	-- DEFERRED_STATUS VARCHAR2(1 BYTE),
	-- TOT_LINE_DST_PCT NUMBER(5, 2),
	-- TOT_LINE_DFR_PCT NUMBER(5, 2),
	-- TOT_LINE_UAR_PCT NUMBER(5, 2),
	-- TOT_LINE_DST_AMT NUMBER(26, 3),
	-- TOT_LINE_DFR_AMT NUMBER(26, 3),
	-- TOT_LINE_UAR_AMT NUMBER(26, 3),
	-- TOT_LINE_DST_BSE NUMBER(26, 3),
	-- TOT_LINE_DFR_BSE NUMBER(26, 3),
	-- TOT_LINE_UAR_BSE NUMBER(26, 3),
	-- TOT_LINE_DST_XEU NUMBER(26, 3),
	-- TOT_LINE_DFR_XEU NUMBER(26, 3),
	-- TOT_LINE_UAR_XEU NUMBER(26, 3),
	-- TOT_DISCOUNT_AMT NUMBER(26, 3),
	-- TOT_SURCHARGE_AMT NUMBER(26, 3),
	-- TOT_DISCOUNT_BSE NUMBER(26, 3),
	-- TOT_SURCHARGE_BSE NUMBER(26, 3),
	-- TOT_DISCOUNT_XEU NUMBER(26, 3),
	-- TOT_SURCHARGE_XEU NUMBER(26, 3),
	-- LINE_DST_SEQ_NUM NUMBER(*, 0),
	-- LINE_DFR_SEQ_NUM NUMBER(*, 0),
	-- LINE_UAR_SEQ_NUM NUMBER(*, 0),
	-- LAST_NOTE_SEQ_NUM NUMBER(*, 0),
	-- ENTRY_TYPE VARCHAR2(5 BYTE),
	-- ENTRY_REASON VARCHAR2(5 BYTE),
	-- PC_DISTRIB_STATUS VARCHAR2(1 BYTE),
	-- PO_REF VARCHAR2(30 BYTE),
	-- PO_LINE NUMBER(*, 0),
	-- BUSINESS_UNIT_CA VARCHAR2(5 BYTE),
	-- CONTRACT_NUM VARCHAR2(25 BYTE),
	-- CONTRACT_DT DATE,
	-- CONTRACT_TYPE VARCHAR2(15 BYTE),
	-- BILL_PLAN_ID VARCHAR2(10 BYTE),
	-- BPLAN_LN_NBR NUMBER(*, 0),
	-- EVENT_OCCURRENCE NUMBER(*, 0),
	-- XREF_SEQ_NUM NUMBER(*, 0),
	-- CONTRACT_PPD_SEQ NUMBER(*, 0),
	-- BUSINESS_UNIT_OM VARCHAR2(5 BYTE),
	-- ORDER_NO VARCHAR2(10 BYTE),
	-- ORDER_DATE DATE,
	-- ORDER_INT_LINE_NO NUMBER(*, 0),
	-- SCHED_LINE_NBR NUMBER(*, 0),
	-- BUSINESS_UNIT_RMA VARCHAR2(5 BYTE),
	-- RMA_ID VARCHAR2(10 BYTE),
	-- RMA_LINE_NBR NUMBER(*, 0),
	-- PRODUCT_ID VARCHAR2(18 BYTE),
	-- DIST_CFG_FLAG VARCHAR2(1 BYTE),
	-- FREIGHT_TERMS VARCHAR2(10 BYTE),
	-- BILL_OF_LADING VARCHAR2(30 BYTE),
	-- SHIP_TO_CUST_ID VARCHAR2(15 BYTE),
	-- SHIP_TO_ADDR_NUM NUMBER(*, 0),
	-- SHIP_ID VARCHAR2(10 BYTE),
	-- SHIP_TYPE_ID VARCHAR2(10 BYTE),
	-- SHIP_FROM_BU VARCHAR2(5 BYTE),
	-- SHIP_DATE DATE,
	-- SEQUENCE_NBR NUMBER(*, 0),
	-- SOLD_TO_CUST_ID VARCHAR2(15 BYTE),
	-- SOLD_TO_ADDR_NUM NUMBER(*, 0),
	-- BUSINESS_UNIT_PC VARCHAR2(5 BYTE),
	-- RESOURCE_ID VARCHAR2(40 BYTE),
	-- PROJECT_ID VARCHAR2(15 BYTE),
	-- ANALYSIS_TYPE VARCHAR2(3 BYTE),
	-- RESOURCE_TYPE VARCHAR2(5 BYTE),
	-- RESOURCE_CATEGORY VARCHAR2(5 BYTE),
	-- RESOURCE_SUB_CAT VARCHAR2(5 BYTE),
	-- ACTIVITY_ID VARCHAR2(15 BYTE),
	-- ACTIVITY_TYPE VARCHAR2(5 BYTE),
	-- SYSTEM_SOURCE VARCHAR2(3 BYTE),
	-- EMPLID VARCHAR2(11 BYTE),
	-- SSN VARCHAR2(9 BYTE),
	-- EMPL_RCD NUMBER(*, 0),
	-- SERVICE_CUST_ID VARCHAR2(15 BYTE),
	-- SERVICE_ADDR_NUM NUMBER(*, 0),
	-- START_DT DATE,
	-- ACCUMULATE VARCHAR2(1 BYTE),
	-- ERROR_STATUS_BI VARCHAR2(4 BYTE),
	-- CONTRACT_LINE_NUM NUMBER(*, 0),
	-- BUSINESS_UNIT_TO VARCHAR2(5 BYTE),
	-- IST_TXN_FLG VARCHAR2(1 BYTE),
	-- IST_DISTRIB_STATUS VARCHAR2(1 BYTE),
	-- INVENTORY_ITEM VARCHAR2(1 BYTE),
	-- FISCAL_REGIME VARCHAR2(2 BYTE),
	-- NATURE_OF_TXN1 VARCHAR2(1 BYTE),
	-- NATURE_OF_TXN2 VARCHAR2(1 BYTE),
	-- IDENTIFIER_TBL VARCHAR2(3 BYTE),
	-- PACKSLIP_NO VARCHAR2(22 BYTE),
	-- PPRC_PROMO_CD VARCHAR2(20 BYTE),
	-- LIST_PRICE NUMBER(15, 4),
	-- USER_AMT1 NUMBER(26, 3),
	-- USER_AMT2 NUMBER(26, 3),
	-- USER_AMT1_BSE NUMBER(26, 3),
	-- USER_AMT2_BSE NUMBER(26, 3),
	-- USER_AMT1_XEU NUMBER(26, 3),
	-- USER_AMT2_XEU NUMBER(26, 3),
	-- USER_DT1 DATE,
	-- USER1 VARCHAR2(6 BYTE),
	-- USER2 VARCHAR2(2 BYTE),
	-- USER3 VARCHAR2(2 BYTE),
	-- USER4 VARCHAR2(1 BYTE),
	-- USER5 VARCHAR2(3 BYTE),
	-- USER6 VARCHAR2(8 BYTE),
	-- USER7 VARCHAR2(1 BYTE),
	-- USER8 VARCHAR2(5 BYTE),
	-- USER9 VARCHAR2(25 BYTE),
	-- PROCESS_INSTANCE NUMBER(10, 0),
	-- ADD_DTTM DATE,
	-- LAST_UPDATE_DTTM DATE,
	-- LAST_MAINT_OPRID VARCHAR2(30 BYTE),
	-- ACCRUE_DT DATE,
	-- ASSET_ID VARCHAR2(12 BYTE),
	-- BI_TAX_TIMING VARCHAR2(1 BYTE),
	-- BUSINESS_UNIT_AMTO VARCHAR2(5 BYTE),
	-- BUSINESS_UNIT_RF VARCHAR2(5 BYTE),
	-- CHARGE_TO_DT DATE,
	-- COST_TYPE VARCHAR2(1 BYTE),
	-- COUNTRY_LOC_BUYER VARCHAR2(3 BYTE),
	-- COUNTRY_LOC_SELLER VARCHAR2(3 BYTE),
	-- COUNTRY_SHIP_FROM VARCHAR2(3 BYTE),
	-- COUNTRY_SHIP_TO VARCHAR2(3 BYTE),
	-- COUNTRY_VAT_BILLFR VARCHAR2(3 BYTE),
	-- COUNTRY_VAT_BILLTO VARCHAR2(3 BYTE),
	-- COUNTRY_VAT_PERFRM VARCHAR2(3 BYTE),
	-- COUNTRY_VAT_SUPPLY VARCHAR2(3 BYTE),
	-- DEFER_DT DATE,
	-- END_DT DATE,
	-- ENTRY_EVENT VARCHAR2(10 BYTE),
	-- EXD_APPL_FLG VARCHAR2(1 BYTE),
	-- EXD_ASSESS_VALUE NUMBER(26, 3),
	-- EXD_CONVERSION_RT NUMBER(15, 8),
	-- EXD_CUST_CATG_CD VARCHAR2(10 BYTE),
	-- EXD_INVOICE_LINE NUMBER,
	-- EXD_INVOICE_NO VARCHAR2(10 BYTE),
	-- EXD_ITM_CATG_CD VARCHAR2(10 BYTE),
	-- EXD_TAX_AMT NUMBER(26, 3),
	-- EXD_TAX_AMT_BSE NUMBER(26, 3),
	-- EXD_TAX_AMT_RPT NUMBER(26, 3),
	-- EXD_TAX_RATE_CD VARCHAR2(10 BYTE),
	-- EXD_TAX_RATE_SRC VARCHAR2(1 BYTE),
	-- EXD_UOM VARCHAR2(3 BYTE),
	-- EXD_USE_AV_FLG VARCHAR2(1 BYTE),
	-- EXS_CURRENCY_RPTG VARCHAR2(3 BYTE),
	-- EXS_DFLTS_APPLIED VARCHAR2(1 BYTE),
	-- EXS_SERV_TAX_FLG VARCHAR2(1 BYTE),
	-- EXS_TAX_TXN_TYPE VARCHAR2(4 BYTE),
	-- FORM_DISTRIB_STAT VARCHAR2(1 BYTE),
	-- INV_ITEM_ID VARCHAR2(18 BYTE),
	-- LANG_DESCR_OVR VARCHAR2(3 BYTE),
	-- MAX_TAX_FLG VARCHAR2(1 BYTE),
	-- MERCH_TYPE VARCHAR2(10 BYTE),
	-- ORG_CODE VARCHAR2(6 BYTE),
	-- ORG_SETID VARCHAR2(5 BYTE),
	-- ORG_TAX_LOC_CD VARCHAR2(10 BYTE),
	-- ORIG_QTY NUMBER(15, 4),
	-- PHYSICAL_NATURE VARCHAR2(1 BYTE),
	-- PROFILE_ID VARCHAR2(10 BYTE),
	-- QTY_BASE NUMBER(15, 4),
	-- RT_EFFDT DATE,
	-- SHIP_TIME DATE,
	-- SOURCE_REF_KEY VARCHAR2(5 BYTE),
	-- SOURCE_REF_NO VARCHAR2(35 BYTE),
	-- SOURCE_REF_TYPE VARCHAR2(3 BYTE),
	-- SO_ID VARCHAR2(10 BYTE),
	-- STATE_LOC_BUYER VARCHAR2(6 BYTE),
	-- STATE_LOC_SELLER VARCHAR2(6 BYTE),
	-- STATE_SHIP_FROM VARCHAR2(6 BYTE),
	-- STATE_SHIP_TO VARCHAR2(6 BYTE),
	-- STATE_VAT_DEFAULT VARCHAR2(6 BYTE),
	-- STATE_VAT_PERFRM VARCHAR2(6 BYTE),
	-- STATE_VAT_SUPPLY VARCHAR2(6 BYTE),
	-- STX_APPL_FLG VARCHAR2(1 BYTE),
	-- STX_CUST_CATG_CD VARCHAR2(10 BYTE),
	-- STX_FORM_CD VARCHAR2(8 BYTE),
	-- STX_ITM_CATG_CD VARCHAR2(10 BYTE),
	-- STX_TAX_AMT NUMBER(26, 3),
	-- STX_TAX_AMT_BSE NUMBER(26, 3),
	-- STX_TAX_AMT_RPT NUMBER(26, 3),
	-- STX_TAX_AUTH_CD VARCHAR2(8 BYTE),
	-- STX_TAX_RATE_CD VARCHAR2(10 BYTE),
	-- STX_TAX_RATE_SRC VARCHAR2(1 BYTE),
	-- USER_DT2 DATE,
	-- VAT_DFLT_DONE_FLG VARCHAR2(1 BYTE),
	-- VAT_SERVICE_TYPE VARCHAR2(1 BYTE),
	-- VAT_SVC_SUPPLY_FLG VARCHAR2(1 BYTE),
	-- VAT_TREATMENT VARCHAR2(4 BYTE),
	-- ED_CREATE_DATE DATE,
	-- ED_CREATE_ID VARCHAR2(100 BYTE),
	-- ED_SOURCE_ARCHIVE_IND VARCHAR2(1 BYTE),
	-- ARCHIVE_FLAG VARCHAR2(1 BYTE) NOT NULL 
	R12_ENTITY VARCHAR2(5 BYTE)
);
-- primary key?
-- indexes?
-- constraints?

truncate table R12_OTR_BI_LINE_PSB;
insert into R12_OTR_BI_LINE_PSB
(
BUSINESS_UNIT, -- VARCHAR2(5), mapSalesData68, mapSalesData1
INVOICE, -- VARCHAR2(22), mapSalesData68, mapSalesData1
LINE_SEQ_NUM, -- NUMBER(38), mapSalesData68, mapSalesData1
-- INVOICE_LINE, -- NUMBER(38)
-- ORIGINAL_INVOICE, -- VARCHAR2(22)
-- ORIGINAL_LINE_SEQ, -- NUMBER(38)
-- NEXT_ADJ_INVOICE, -- VARCHAR2(22)
-- NEXT_ADJ_LINE_SEQ, -- NUMBER(38)
-- PRIOR_ADJ_INVOICE, -- VARCHAR2(22)
-- PRIOR_ADJ_LINE_SEQ, -- NUMBER(38)
-- LATEST_INVOICE, -- VARCHAR2(22)
-- LATEST_LINE_SEQ, -- NUMBER(38)
-- BILL_SOURCE_ID, -- VARCHAR2(10)
-- SUBCUST_QUAL1, -- VARCHAR2(15)
-- SUBCUST_QUAL2, -- VARCHAR2(15)
-- ADJ_LINE_TYPE, -- VARCHAR2(3)
-- ADJUSTED_FLAG, -- VARCHAR2(1)
-- LINE_TYPE, -- VARCHAR2(4)
-- BI_CURRENCY_CD, -- VARCHAR2(3)
-- BASE_CURRENCY, -- VARCHAR2(3)
-- CURRENCY_CD_XEU, -- VARCHAR2(3)
-- CHARGE_FROM_DT, -- DATE
IDENTIFIER, -- VARCHAR2(18), mapSalesData68, mapSalesData1
-- DESCR, -- VARCHAR2(30)
-- UNIT_OF_MEASURE, -- VARCHAR2(3)
-- QTY, -- NUMBER(15,4)
-- UNIT_AMT, -- NUMBER(15,4)
-- PRICE_RECALC_FLG, -- VARCHAR2(1)
-- TAX_CD, -- VARCHAR2(8)
-- TAX_EXEMPT_CERT, -- VARCHAR2(30)
-- TAX_EXEMPT_FLG, -- VARCHAR2(1)
-- GROSS_EXTENDED_AMT, -- NUMBER(26,3)
-- NET_EXTENDED_AMT, -- NUMBER(26,3)
-- ORIG_AMOUNT, -- NUMBER(26,3)
-- GROSS_EXTENDED_BSE, -- NUMBER(26,3)
-- NET_EXTENDED_BSE, -- NUMBER(26,3)
-- GROSS_EXTENDED_XEU, -- NUMBER(26,3)
-- NET_EXTENDED_XEU, -- NUMBER(26,3)
-- TAX_AMT, -- NUMBER(26,3)
-- TAX_AMT_BSE, -- NUMBER(26,3)
-- TAX_AMT_XEU, -- NUMBER(26,3)
-- TAX_PCT, -- NUMBER(6,4)
-- FINAL_TAX_FLG, -- VARCHAR2(1)
-- VAT_BASIS_AMT, -- NUMBER(26,3)
-- VAT_BASIS_AMT_BSE, -- NUMBER(26,3)
-- VAT_BASIS_AMT_XEU, -- NUMBER(26,3)
-- VAT_AMT, -- NUMBER(26,3)
-- VAT_AMT_BSE, -- NUMBER(26,3)
-- VAT_AMT_XEU, -- NUMBER(26,3)
-- VAT_TRANS_AMT, -- NUMBER(26,3)
-- VAT_TRANS_AMT_BSE, -- NUMBER(26,3)
-- VAT_TXN_TYPE_CD, -- VARCHAR2(4)
-- TAX_CD_VAT, -- VARCHAR2(8)
-- TAX_CD_VAT_PCT, -- NUMBER(7,4)
-- VAT_APPLICABILITY, -- VARCHAR2(1)
-- PROD_GRP_SETID, -- VARCHAR2(5)
-- VAT_PRODUCT_GROUP, -- VARCHAR2(10)
-- PRODUCT_KIT_ID, -- VARCHAR2(18)
-- VAT_DISTRIB_STATUS, -- VARCHAR2(1)
-- TAX_VAT_FLG, -- VARCHAR2(1)
-- REV_RECOG_BASIS, -- VARCHAR2(3)
-- DEFERRED_STATUS, -- VARCHAR2(1)
-- TOT_LINE_DST_PCT, -- NUMBER(5,2)
-- TOT_LINE_DFR_PCT, -- NUMBER(5,2)
-- TOT_LINE_UAR_PCT, -- NUMBER(5,2)
-- TOT_LINE_DST_AMT, -- NUMBER(26,3)
-- TOT_LINE_DFR_AMT, -- NUMBER(26,3)
-- TOT_LINE_UAR_AMT, -- NUMBER(26,3)
-- TOT_LINE_DST_BSE, -- NUMBER(26,3)
-- TOT_LINE_DFR_BSE, -- NUMBER(26,3)
-- TOT_LINE_UAR_BSE, -- NUMBER(26,3)
-- TOT_LINE_DST_XEU, -- NUMBER(26,3)
-- TOT_LINE_DFR_XEU, -- NUMBER(26,3)
-- TOT_LINE_UAR_XEU, -- NUMBER(26,3)
-- TOT_DISCOUNT_AMT, -- NUMBER(26,3)
-- TOT_SURCHARGE_AMT, -- NUMBER(26,3)
-- TOT_DISCOUNT_BSE, -- NUMBER(26,3)
-- TOT_SURCHARGE_BSE, -- NUMBER(26,3)
-- TOT_DISCOUNT_XEU, -- NUMBER(26,3)
-- TOT_SURCHARGE_XEU, -- NUMBER(26,3)
-- LINE_DST_SEQ_NUM, -- NUMBER(38)
-- LINE_DFR_SEQ_NUM, -- NUMBER(38)
-- LINE_UAR_SEQ_NUM, -- NUMBER(38)
-- LAST_NOTE_SEQ_NUM, -- NUMBER(38)
-- ENTRY_TYPE, -- VARCHAR2(5)
-- ENTRY_REASON, -- VARCHAR2(5)
-- PC_DISTRIB_STATUS, -- VARCHAR2(1)
-- PO_REF, -- VARCHAR2(30)
-- PO_LINE, -- NUMBER(38)
-- BUSINESS_UNIT_CA, -- VARCHAR2(5)
-- CONTRACT_NUM, -- VARCHAR2(25)
-- CONTRACT_DT, -- DATE
-- CONTRACT_TYPE, -- VARCHAR2(15)
-- BILL_PLAN_ID, -- VARCHAR2(10)
-- BPLAN_LN_NBR, -- NUMBER(38)
-- EVENT_OCCURRENCE, -- NUMBER(38)
-- XREF_SEQ_NUM, -- NUMBER(38)
-- CONTRACT_PPD_SEQ, -- NUMBER(38)
-- BUSINESS_UNIT_OM, -- VARCHAR2(5)
-- ORDER_NO, -- VARCHAR2(10)
-- ORDER_DATE, -- DATE
-- ORDER_INT_LINE_NO, -- NUMBER(38)
-- SCHED_LINE_NBR, -- NUMBER(38)
-- BUSINESS_UNIT_RMA, -- VARCHAR2(5)
-- RMA_ID, -- VARCHAR2(10)
-- RMA_LINE_NBR, -- NUMBER(38)
-- PRODUCT_ID, -- VARCHAR2(18)
-- DIST_CFG_FLAG, -- VARCHAR2(1)
-- FREIGHT_TERMS, -- VARCHAR2(10)
-- BILL_OF_LADING, -- VARCHAR2(30)
-- SHIP_TO_CUST_ID, -- VARCHAR2(15)
-- SHIP_TO_ADDR_NUM, -- NUMBER(38)
-- SHIP_ID, -- VARCHAR2(10)
-- SHIP_TYPE_ID, -- VARCHAR2(10)
-- SHIP_FROM_BU, -- VARCHAR2(5)
-- SHIP_DATE, -- DATE
-- SEQUENCE_NBR, -- NUMBER(38)
-- SOLD_TO_CUST_ID, -- VARCHAR2(15)
-- SOLD_TO_ADDR_NUM, -- NUMBER(38)
-- BUSINESS_UNIT_PC, -- VARCHAR2(5)
-- RESOURCE_ID, -- VARCHAR2(40)
-- PROJECT_ID, -- VARCHAR2(15)
-- ANALYSIS_TYPE, -- VARCHAR2(3)
-- RESOURCE_TYPE, -- VARCHAR2(5)
-- RESOURCE_CATEGORY, -- VARCHAR2(5)
-- RESOURCE_SUB_CAT, -- VARCHAR2(5)
-- ACTIVITY_ID, -- VARCHAR2(15)
-- ACTIVITY_TYPE, -- VARCHAR2(5)
-- SYSTEM_SOURCE, -- VARCHAR2(3)
-- EMPLID, -- VARCHAR2(11)
-- SSN, -- VARCHAR2(9)
-- EMPL_RCD, -- NUMBER(38)
-- SERVICE_CUST_ID, -- VARCHAR2(15)
-- SERVICE_ADDR_NUM, -- NUMBER(38)
-- START_DT, -- DATE
-- ACCUMULATE, -- VARCHAR2(1)
-- ERROR_STATUS_BI, -- VARCHAR2(4)
-- CONTRACT_LINE_NUM, -- NUMBER(38)
-- BUSINESS_UNIT_TO, -- VARCHAR2(5)
-- IST_TXN_FLG, -- VARCHAR2(1)
-- IST_DISTRIB_STATUS, -- VARCHAR2(1)
-- INVENTORY_ITEM, -- VARCHAR2(1)
-- FISCAL_REGIME, -- VARCHAR2(2)
-- NATURE_OF_TXN1, -- VARCHAR2(1)
-- NATURE_OF_TXN2, -- VARCHAR2(1)
-- IDENTIFIER_TBL, -- VARCHAR2(3)
-- PACKSLIP_NO, -- VARCHAR2(22)
-- PPRC_PROMO_CD, -- VARCHAR2(20)
-- LIST_PRICE, -- NUMBER(15,4)
-- USER_AMT1, -- NUMBER(26,3)
-- USER_AMT2, -- NUMBER(26,3)
-- USER_AMT1_BSE, -- NUMBER(26,3)
-- USER_AMT2_BSE, -- NUMBER(26,3)
-- USER_AMT1_XEU, -- NUMBER(26,3)
-- USER_AMT2_XEU, -- NUMBER(26,3)
-- USER_DT1, -- DATE
-- USER1, -- VARCHAR2(6)
-- USER2, -- VARCHAR2(2)
-- USER3, -- VARCHAR2(2)
-- USER4, -- VARCHAR2(1)
-- USER5, -- VARCHAR2(3)
-- USER6, -- VARCHAR2(8)
-- USER7, -- VARCHAR2(1)
-- USER8, -- VARCHAR2(5)
-- USER9, -- VARCHAR2(25)
-- PROCESS_INSTANCE, -- NUMBER(10)
-- ADD_DTTM, -- DATE
-- LAST_UPDATE_DTTM, -- DATE
-- LAST_MAINT_OPRID, -- VARCHAR2(30)
-- ACCRUE_DT, -- DATE
-- ASSET_ID, -- VARCHAR2(12)
-- BI_TAX_TIMING, -- VARCHAR2(1)
-- BUSINESS_UNIT_AMTO, -- VARCHAR2(5)
-- BUSINESS_UNIT_RF, -- VARCHAR2(5)
-- CHARGE_TO_DT, -- DATE
-- COST_TYPE, -- VARCHAR2(1)
-- COUNTRY_LOC_BUYER, -- VARCHAR2(3)
-- COUNTRY_LOC_SELLER, -- VARCHAR2(3)
-- COUNTRY_SHIP_FROM, -- VARCHAR2(3)
-- COUNTRY_SHIP_TO, -- VARCHAR2(3)
-- COUNTRY_VAT_BILLFR, -- VARCHAR2(3)
-- COUNTRY_VAT_BILLTO, -- VARCHAR2(3)
-- COUNTRY_VAT_PERFRM, -- VARCHAR2(3)
-- COUNTRY_VAT_SUPPLY, -- VARCHAR2(3)
-- DEFER_DT, -- DATE
-- END_DT, -- DATE
-- ENTRY_EVENT, -- VARCHAR2(10)
-- EXD_APPL_FLG, -- VARCHAR2(1)
-- EXD_ASSESS_VALUE, -- NUMBER(26,3)
-- EXD_CONVERSION_RT, -- NUMBER(15,8)
-- EXD_CUST_CATG_CD, -- VARCHAR2(10)
-- EXD_INVOICE_LINE, -- NUMBER
-- EXD_INVOICE_NO, -- VARCHAR2(10)
-- EXD_ITM_CATG_CD, -- VARCHAR2(10)
-- EXD_TAX_AMT, -- NUMBER(26,3)
-- EXD_TAX_AMT_BSE, -- NUMBER(26,3)
-- EXD_TAX_AMT_RPT, -- NUMBER(26,3)
-- EXD_TAX_RATE_CD, -- VARCHAR2(10)
-- EXD_TAX_RATE_SRC, -- VARCHAR2(1)
-- EXD_UOM, -- VARCHAR2(3)
-- EXD_USE_AV_FLG, -- VARCHAR2(1)
-- EXS_CURRENCY_RPTG, -- VARCHAR2(3)
-- EXS_DFLTS_APPLIED, -- VARCHAR2(1)
-- EXS_SERV_TAX_FLG, -- VARCHAR2(1)
-- EXS_TAX_TXN_TYPE, -- VARCHAR2(4)
-- FORM_DISTRIB_STAT, -- VARCHAR2(1)
-- INV_ITEM_ID, -- VARCHAR2(18)
-- LANG_DESCR_OVR, -- VARCHAR2(3)
-- MAX_TAX_FLG, -- VARCHAR2(1)
-- MERCH_TYPE, -- VARCHAR2(10)
-- ORG_CODE, -- VARCHAR2(6)
-- ORG_SETID, -- VARCHAR2(5)
-- ORG_TAX_LOC_CD, -- VARCHAR2(10)
-- ORIG_QTY, -- NUMBER(15,4)
-- PHYSICAL_NATURE, -- VARCHAR2(1)
-- PROFILE_ID, -- VARCHAR2(10)
-- QTY_BASE, -- NUMBER(15,4)
-- RT_EFFDT, -- DATE
-- SHIP_TIME, -- DATE
-- SOURCE_REF_KEY, -- VARCHAR2(5)
-- SOURCE_REF_NO, -- VARCHAR2(35)
-- SOURCE_REF_TYPE, -- VARCHAR2(3)
-- SO_ID, -- VARCHAR2(10)
-- STATE_LOC_BUYER, -- VARCHAR2(6)
-- STATE_LOC_SELLER, -- VARCHAR2(6)
-- STATE_SHIP_FROM, -- VARCHAR2(6)
-- STATE_SHIP_TO, -- VARCHAR2(6)
-- STATE_VAT_DEFAULT, -- VARCHAR2(6)
-- STATE_VAT_PERFRM, -- VARCHAR2(6)
-- STATE_VAT_SUPPLY, -- VARCHAR2(6)
-- STX_APPL_FLG, -- VARCHAR2(1)
-- STX_CUST_CATG_CD, -- VARCHAR2(10)
-- STX_FORM_CD, -- VARCHAR2(8)
-- STX_ITM_CATG_CD, -- VARCHAR2(10)
-- STX_TAX_AMT, -- NUMBER(26,3)
-- STX_TAX_AMT_BSE, -- NUMBER(26,3)
-- STX_TAX_AMT_RPT, -- NUMBER(26,3)
-- STX_TAX_AUTH_CD, -- VARCHAR2(8)
-- STX_TAX_RATE_CD, -- VARCHAR2(10)
-- STX_TAX_RATE_SRC, -- VARCHAR2(1)
-- USER_DT2, -- DATE
-- VAT_DFLT_DONE_FLG, -- VARCHAR2(1)
-- VAT_SERVICE_TYPE, -- VARCHAR2(1)
-- VAT_SVC_SUPPLY_FLG, -- VARCHAR2(1)
-- VAT_TREATMENT, -- VARCHAR2(4)
-- ED_CREATE_DATE, -- DATE
-- ED_CREATE_ID, -- VARCHAR2(100)
-- ED_SOURCE_ARCHIVE_IND, -- VARCHAR2(1)
-- ARCHIVE_FLAG, -- NOT NULL VARCHAR2(1)
R12_ENTITY
)
select
BUSINESS_UNIT, -- VARCHAR2(5)
INVOICE, -- VARCHAR2(22)
LINE_SEQ_NUM, -- NUMBER(38)
-- INVOICE_LINE, -- NUMBER(38)
-- ORIGINAL_INVOICE, -- VARCHAR2(22)
-- ORIGINAL_LINE_SEQ, -- NUMBER(38)
-- NEXT_ADJ_INVOICE, -- VARCHAR2(22)
-- NEXT_ADJ_LINE_SEQ, -- NUMBER(38)
-- PRIOR_ADJ_INVOICE, -- VARCHAR2(22)
-- PRIOR_ADJ_LINE_SEQ, -- NUMBER(38)
-- LATEST_INVOICE, -- VARCHAR2(22)
-- LATEST_LINE_SEQ, -- NUMBER(38)
-- BILL_SOURCE_ID, -- VARCHAR2(10)
-- SUBCUST_QUAL1, -- VARCHAR2(15)
-- SUBCUST_QUAL2, -- VARCHAR2(15)
-- ADJ_LINE_TYPE, -- VARCHAR2(3)
-- ADJUSTED_FLAG, -- VARCHAR2(1)
-- LINE_TYPE, -- VARCHAR2(4)
-- BI_CURRENCY_CD, -- VARCHAR2(3)
-- BASE_CURRENCY, -- VARCHAR2(3)
-- CURRENCY_CD_XEU, -- VARCHAR2(3)
-- CHARGE_FROM_DT, -- DATE
IDENTIFIER, -- VARCHAR2(18)
-- DESCR, -- VARCHAR2(30)
-- UNIT_OF_MEASURE, -- VARCHAR2(3)
-- QTY, -- NUMBER(15,4)
-- UNIT_AMT, -- NUMBER(15,4)
-- PRICE_RECALC_FLG, -- VARCHAR2(1)
-- TAX_CD, -- VARCHAR2(8)
-- TAX_EXEMPT_CERT, -- VARCHAR2(30)
-- TAX_EXEMPT_FLG, -- VARCHAR2(1)
-- GROSS_EXTENDED_AMT, -- NUMBER(26,3)
-- NET_EXTENDED_AMT, -- NUMBER(26,3)
-- ORIG_AMOUNT, -- NUMBER(26,3)
-- GROSS_EXTENDED_BSE, -- NUMBER(26,3)
-- NET_EXTENDED_BSE, -- NUMBER(26,3)
-- GROSS_EXTENDED_XEU, -- NUMBER(26,3)
-- NET_EXTENDED_XEU, -- NUMBER(26,3)
-- TAX_AMT, -- NUMBER(26,3)
-- TAX_AMT_BSE, -- NUMBER(26,3)
-- TAX_AMT_XEU, -- NUMBER(26,3)
-- TAX_PCT, -- NUMBER(6,4)
-- FINAL_TAX_FLG, -- VARCHAR2(1)
-- VAT_BASIS_AMT, -- NUMBER(26,3)
-- VAT_BASIS_AMT_BSE, -- NUMBER(26,3)
-- VAT_BASIS_AMT_XEU, -- NUMBER(26,3)
-- VAT_AMT, -- NUMBER(26,3)
-- VAT_AMT_BSE, -- NUMBER(26,3)
-- VAT_AMT_XEU, -- NUMBER(26,3)
-- VAT_TRANS_AMT, -- NUMBER(26,3)
-- VAT_TRANS_AMT_BSE, -- NUMBER(26,3)
-- VAT_TXN_TYPE_CD, -- VARCHAR2(4)
-- TAX_CD_VAT, -- VARCHAR2(8)
-- TAX_CD_VAT_PCT, -- NUMBER(7,4)
-- VAT_APPLICABILITY, -- VARCHAR2(1)
-- PROD_GRP_SETID, -- VARCHAR2(5)
-- VAT_PRODUCT_GROUP, -- VARCHAR2(10)
-- PRODUCT_KIT_ID, -- VARCHAR2(18)
-- VAT_DISTRIB_STATUS, -- VARCHAR2(1)
-- TAX_VAT_FLG, -- VARCHAR2(1)
-- REV_RECOG_BASIS, -- VARCHAR2(3)
-- DEFERRED_STATUS, -- VARCHAR2(1)
-- TOT_LINE_DST_PCT, -- NUMBER(5,2)
-- TOT_LINE_DFR_PCT, -- NUMBER(5,2)
-- TOT_LINE_UAR_PCT, -- NUMBER(5,2)
-- TOT_LINE_DST_AMT, -- NUMBER(26,3)
-- TOT_LINE_DFR_AMT, -- NUMBER(26,3)
-- TOT_LINE_UAR_AMT, -- NUMBER(26,3)
-- TOT_LINE_DST_BSE, -- NUMBER(26,3)
-- TOT_LINE_DFR_BSE, -- NUMBER(26,3)
-- TOT_LINE_UAR_BSE, -- NUMBER(26,3)
-- TOT_LINE_DST_XEU, -- NUMBER(26,3)
-- TOT_LINE_DFR_XEU, -- NUMBER(26,3)
-- TOT_LINE_UAR_XEU, -- NUMBER(26,3)
-- TOT_DISCOUNT_AMT, -- NUMBER(26,3)
-- TOT_SURCHARGE_AMT, -- NUMBER(26,3)
-- TOT_DISCOUNT_BSE, -- NUMBER(26,3)
-- TOT_SURCHARGE_BSE, -- NUMBER(26,3)
-- TOT_DISCOUNT_XEU, -- NUMBER(26,3)
-- TOT_SURCHARGE_XEU, -- NUMBER(26,3)
-- LINE_DST_SEQ_NUM, -- NUMBER(38)
-- LINE_DFR_SEQ_NUM, -- NUMBER(38)
-- LINE_UAR_SEQ_NUM, -- NUMBER(38)
-- LAST_NOTE_SEQ_NUM, -- NUMBER(38)
-- ENTRY_TYPE, -- VARCHAR2(5)
-- ENTRY_REASON, -- VARCHAR2(5)
-- PC_DISTRIB_STATUS, -- VARCHAR2(1)
-- PO_REF, -- VARCHAR2(30)
-- PO_LINE, -- NUMBER(38)
-- BUSINESS_UNIT_CA, -- VARCHAR2(5)
-- CONTRACT_NUM, -- VARCHAR2(25)
-- CONTRACT_DT, -- DATE
-- CONTRACT_TYPE, -- VARCHAR2(15)
-- BILL_PLAN_ID, -- VARCHAR2(10)
-- BPLAN_LN_NBR, -- NUMBER(38)
-- EVENT_OCCURRENCE, -- NUMBER(38)
-- XREF_SEQ_NUM, -- NUMBER(38)
-- CONTRACT_PPD_SEQ, -- NUMBER(38)
-- BUSINESS_UNIT_OM, -- VARCHAR2(5)
-- ORDER_NO, -- VARCHAR2(10)
-- ORDER_DATE, -- DATE
-- ORDER_INT_LINE_NO, -- NUMBER(38)
-- SCHED_LINE_NBR, -- NUMBER(38)
-- BUSINESS_UNIT_RMA, -- VARCHAR2(5)
-- RMA_ID, -- VARCHAR2(10)
-- RMA_LINE_NBR, -- NUMBER(38)
-- PRODUCT_ID, -- VARCHAR2(18)
-- DIST_CFG_FLAG, -- VARCHAR2(1)
-- FREIGHT_TERMS, -- VARCHAR2(10)
-- BILL_OF_LADING, -- VARCHAR2(30)
-- SHIP_TO_CUST_ID, -- VARCHAR2(15)
-- SHIP_TO_ADDR_NUM, -- NUMBER(38)
-- SHIP_ID, -- VARCHAR2(10)
-- SHIP_TYPE_ID, -- VARCHAR2(10)
-- SHIP_FROM_BU, -- VARCHAR2(5)
-- SHIP_DATE, -- DATE
-- SEQUENCE_NBR, -- NUMBER(38)
-- SOLD_TO_CUST_ID, -- VARCHAR2(15)
-- SOLD_TO_ADDR_NUM, -- NUMBER(38)
-- BUSINESS_UNIT_PC, -- VARCHAR2(5)
-- RESOURCE_ID, -- VARCHAR2(40)
-- PROJECT_ID, -- VARCHAR2(15)
-- ANALYSIS_TYPE, -- VARCHAR2(3)
-- RESOURCE_TYPE, -- VARCHAR2(5)
-- RESOURCE_CATEGORY, -- VARCHAR2(5)
-- RESOURCE_SUB_CAT, -- VARCHAR2(5)
-- ACTIVITY_ID, -- VARCHAR2(15)
-- ACTIVITY_TYPE, -- VARCHAR2(5)
-- SYSTEM_SOURCE, -- VARCHAR2(3)
-- EMPLID, -- VARCHAR2(11)
-- SSN, -- VARCHAR2(9)
-- EMPL_RCD, -- NUMBER(38)
-- SERVICE_CUST_ID, -- VARCHAR2(15)
-- SERVICE_ADDR_NUM, -- NUMBER(38)
-- START_DT, -- DATE
-- ACCUMULATE, -- VARCHAR2(1)
-- ERROR_STATUS_BI, -- VARCHAR2(4)
-- CONTRACT_LINE_NUM, -- NUMBER(38)
-- BUSINESS_UNIT_TO, -- VARCHAR2(5)
-- IST_TXN_FLG, -- VARCHAR2(1)
-- IST_DISTRIB_STATUS, -- VARCHAR2(1)
-- INVENTORY_ITEM, -- VARCHAR2(1)
-- FISCAL_REGIME, -- VARCHAR2(2)
-- NATURE_OF_TXN1, -- VARCHAR2(1)
-- NATURE_OF_TXN2, -- VARCHAR2(1)
-- IDENTIFIER_TBL, -- VARCHAR2(3)
-- PACKSLIP_NO, -- VARCHAR2(22)
-- PPRC_PROMO_CD, -- VARCHAR2(20)
-- LIST_PRICE, -- NUMBER(15,4)
-- USER_AMT1, -- NUMBER(26,3)
-- USER_AMT2, -- NUMBER(26,3)
-- USER_AMT1_BSE, -- NUMBER(26,3)
-- USER_AMT2_BSE, -- NUMBER(26,3)
-- USER_AMT1_XEU, -- NUMBER(26,3)
-- USER_AMT2_XEU, -- NUMBER(26,3)
-- USER_DT1, -- DATE
-- USER1, -- VARCHAR2(6)
-- USER2, -- VARCHAR2(2)
-- USER3, -- VARCHAR2(2)
-- USER4, -- VARCHAR2(1)
-- USER5, -- VARCHAR2(3)
-- USER6, -- VARCHAR2(8)
-- USER7, -- VARCHAR2(1)
-- USER8, -- VARCHAR2(5)
-- USER9, -- VARCHAR2(25)
-- PROCESS_INSTANCE, -- NUMBER(10)
-- ADD_DTTM, -- DATE
-- LAST_UPDATE_DTTM, -- DATE
-- LAST_MAINT_OPRID, -- VARCHAR2(30)
-- ACCRUE_DT, -- DATE
-- ASSET_ID, -- VARCHAR2(12)
-- BI_TAX_TIMING, -- VARCHAR2(1)
-- BUSINESS_UNIT_AMTO, -- VARCHAR2(5)
-- BUSINESS_UNIT_RF, -- VARCHAR2(5)
-- CHARGE_TO_DT, -- DATE
-- COST_TYPE, -- VARCHAR2(1)
-- COUNTRY_LOC_BUYER, -- VARCHAR2(3)
-- COUNTRY_LOC_SELLER, -- VARCHAR2(3)
-- COUNTRY_SHIP_FROM, -- VARCHAR2(3)
-- COUNTRY_SHIP_TO, -- VARCHAR2(3)
-- COUNTRY_VAT_BILLFR, -- VARCHAR2(3)
-- COUNTRY_VAT_BILLTO, -- VARCHAR2(3)
-- COUNTRY_VAT_PERFRM, -- VARCHAR2(3)
-- COUNTRY_VAT_SUPPLY, -- VARCHAR2(3)
-- DEFER_DT, -- DATE
-- END_DT, -- DATE
-- ENTRY_EVENT, -- VARCHAR2(10)
-- EXD_APPL_FLG, -- VARCHAR2(1)
-- EXD_ASSESS_VALUE, -- NUMBER(26,3)
-- EXD_CONVERSION_RT, -- NUMBER(15,8)
-- EXD_CUST_CATG_CD, -- VARCHAR2(10)
-- EXD_INVOICE_LINE, -- NUMBER
-- EXD_INVOICE_NO, -- VARCHAR2(10)
-- EXD_ITM_CATG_CD, -- VARCHAR2(10)
-- EXD_TAX_AMT, -- NUMBER(26,3)
-- EXD_TAX_AMT_BSE, -- NUMBER(26,3)
-- EXD_TAX_AMT_RPT, -- NUMBER(26,3)
-- EXD_TAX_RATE_CD, -- VARCHAR2(10)
-- EXD_TAX_RATE_SRC, -- VARCHAR2(1)
-- EXD_UOM, -- VARCHAR2(3)
-- EXD_USE_AV_FLG, -- VARCHAR2(1)
-- EXS_CURRENCY_RPTG, -- VARCHAR2(3)
-- EXS_DFLTS_APPLIED, -- VARCHAR2(1)
-- EXS_SERV_TAX_FLG, -- VARCHAR2(1)
-- EXS_TAX_TXN_TYPE, -- VARCHAR2(4)
-- FORM_DISTRIB_STAT, -- VARCHAR2(1)
-- INV_ITEM_ID, -- VARCHAR2(18)
-- LANG_DESCR_OVR, -- VARCHAR2(3)
-- MAX_TAX_FLG, -- VARCHAR2(1)
-- MERCH_TYPE, -- VARCHAR2(10)
-- ORG_CODE, -- VARCHAR2(6)
-- ORG_SETID, -- VARCHAR2(5)
-- ORG_TAX_LOC_CD, -- VARCHAR2(10)
-- ORIG_QTY, -- NUMBER(15,4)
-- PHYSICAL_NATURE, -- VARCHAR2(1)
-- PROFILE_ID, -- VARCHAR2(10)
-- QTY_BASE, -- NUMBER(15,4)
-- RT_EFFDT, -- DATE
-- SHIP_TIME, -- DATE
-- SOURCE_REF_KEY, -- VARCHAR2(5)
-- SOURCE_REF_NO, -- VARCHAR2(35)
-- SOURCE_REF_TYPE, -- VARCHAR2(3)
-- SO_ID, -- VARCHAR2(10)
-- STATE_LOC_BUYER, -- VARCHAR2(6)
-- STATE_LOC_SELLER, -- VARCHAR2(6)
-- STATE_SHIP_FROM, -- VARCHAR2(6)
-- STATE_SHIP_TO, -- VARCHAR2(6)
-- STATE_VAT_DEFAULT, -- VARCHAR2(6)
-- STATE_VAT_PERFRM, -- VARCHAR2(6)
-- STATE_VAT_SUPPLY, -- VARCHAR2(6)
-- STX_APPL_FLG, -- VARCHAR2(1)
-- STX_CUST_CATG_CD, -- VARCHAR2(10)
-- STX_FORM_CD, -- VARCHAR2(8)
-- STX_ITM_CATG_CD, -- VARCHAR2(10)
-- STX_TAX_AMT, -- NUMBER(26,3)
-- STX_TAX_AMT_BSE, -- NUMBER(26,3)
-- STX_TAX_AMT_RPT, -- NUMBER(26,3)
-- STX_TAX_AUTH_CD, -- VARCHAR2(8)
-- STX_TAX_RATE_CD, -- VARCHAR2(10)
-- STX_TAX_RATE_SRC, -- VARCHAR2(1)
-- USER_DT2, -- DATE
-- VAT_DFLT_DONE_FLG, -- VARCHAR2(1)
-- VAT_SERVICE_TYPE, -- VARCHAR2(1)
-- VAT_SVC_SUPPLY_FLG, -- VARCHAR2(1)
-- VAT_TREATMENT, -- VARCHAR2(4)
-- ED_CREATE_DATE, -- DATE
-- ED_CREATE_ID, -- VARCHAR2(100)
-- ED_SOURCE_ARCHIVE_IND, -- VARCHAR2(1)
-- ARCHIVE_FLAG, -- NOT NULL VARCHAR2(1)
DBO.F_GET_R12_ACCOUNT_STRING ('ENTITY', BUSINESS_UNIT, null, null, PRODUCT_ID, null) as R12_ENTITY
from
OTR_BI_LINE_PSB;

-- CREATE TABLE R12_OTR_TRNBI_BI_HDR_PSB like OTR_TRNBI_BI_HDR_PSB
-- add R12_ENTITY

select count(*) from OTR_TRNBI_BI_HDR_PSB; -- 29249585 9:55 AM MDT

CREATE TABLE DBO.R12_OTR_TRNBI_BI_HDR_PSB (
	BUSINESS_UNIT VARCHAR2(5 BYTE) NOT NULL,
	INVOICE VARCHAR2(22 BYTE) NOT NULL,
	-- TRNBI_ORIG_SYS_REF VARCHAR2(150 BYTE) NOT NULL,
	-- TRNBI_CLAIM_NUMBER VARCHAR2(30 BYTE) NOT NULL,
	-- TRNBI_TRX_TYPE NUMBER(10, 0) NOT NULL,
	-- TRNBI_CR_JOB_NBR VARCHAR2(15 BYTE) NOT NULL,
	-- TRNBI_CREDIT_JB_ID VARCHAR2(15 BYTE) NOT NULL,
	-- TRNBI_SALES_ORD_ID NUMBER(10, 0) NOT NULL,
	-- TRNBI_DELIV_OPTION VARCHAR2(3 BYTE) NOT NULL,
	-- TRNBI_MFG_BU VARCHAR2(3 BYTE) NOT NULL,
	-- TRNBI_MFG_LOC VARCHAR2(3 BYTE) NOT NULL,
	-- TRNBI_NBR_OF_LEGS VARCHAR2(1 BYTE) NOT NULL,
	-- TRNBI_LEG_NBR VARCHAR2(1 BYTE) NOT NULL,
	-- TRNBI_DOC_TYPE VARCHAR2(30 BYTE) NOT NULL,
	-- TRNBI_TRAN_CUS_NBR VARCHAR2(8 BYTE) NOT NULL,
	-- TRNBI_TRAN_BIL_ADD NUMBER(*, 0) NOT NULL,
	-- TRNBI_SALES_OFFICE NUMBER(15, 0) NOT NULL,
	-- TRNBI_INI_CONTRACT NUMBER(26, 3) NOT NULL,
	-- TRNBI_TOTAL_STORED NUMBER(26, 3) NOT NULL,
	-- TRNBI_PREV_CON_ADD NUMBER(26, 3) NOT NULL,
	-- TRNBI_PREV_CON_DED NUMBER(26, 3) NOT NULL,
	-- TRNBI_CURR_CON_ADD NUMBER(26, 3) NOT NULL,
	-- TRNBI_CURR_CON_DED NUMBER(26, 3) NOT NULL,
	-- TRNBI_PCT_CON_COMP NUMBER(26, 3) NOT NULL,
	-- TRNBI_RETAINAGE_CM NUMBER(26, 3) NOT NULL,
	-- TRNBI_STORE_MT_RET NUMBER(7, 2) NOT NULL,
	-- TRNBI_STORE_MAT_CM NUMBER(26, 3) NOT NULL,
	-- TRNBI_TOT_RETAINAG NUMBER(26, 3) NOT NULL,
	-- TRNBI_CON_BIL_TODT NUMBER(26, 3) NOT NULL,
	-- TRNBI_CON_EFF_DATE DATE,
	-- TRNBI_CUS_PROJ_NBR VARCHAR2(50 BYTE) NOT NULL,
	-- TRNBI_CONT_COMP_NM VARCHAR2(150 BYTE) NOT NULL,
	-- TRNBI_CONT_CONTACT VARCHAR2(150 BYTE) NOT NULL,
	-- TRNBI_CON_APP_DATE DATE,
	-- TRNBI_VIAARCHITECT VARCHAR2(36 BYTE) NOT NULL,
	-- TRNBI_ARCHITECT_AD VARCHAR2(36 BYTE) NOT NULL,
	-- TRNBI_ARCHITECT_CT VARCHAR2(30 BYTE) NOT NULL,
	-- TRNBI_ARCHITECT_ST VARCHAR2(30 BYTE) NOT NULL,
	-- TRNBI_ARCHITECT_PC VARCHAR2(15 BYTE) NOT NULL,
	-- TRNBI_ARC_PREV_AMT NUMBER(26, 3) NOT NULL,
	-- TRNBI_ARC_CERT_IND VARCHAR2(1 BYTE) NOT NULL,
	-- TRNBI_ARC_COMPANY VARCHAR2(150 BYTE) NOT NULL,
	-- TRNBI_ARC_NAME VARCHAR2(150 BYTE) NOT NULL,
	-- TRNBI_ARC_CERT_DT DATE,
	-- TRNBI_ARC_AMT_CERT NUMBER(26, 3) NOT NULL,
	-- TRNBI_CUS_PREV_AMT NUMBER(26, 3) NOT NULL,
	-- TRNBI_CUS_CERT_IND VARCHAR2(1 BYTE) NOT NULL,
	-- TRNBI_CUS_CERT_CON VARCHAR2(150 BYTE) NOT NULL,
	-- TRNBI_CUS_CERT_AMT NUMBER(26, 3) NOT NULL,
	-- TRNBI_FIN_INV_IND VARCHAR2(1 BYTE) NOT NULL,
	-- TRNBI_IN_EMAIL_ADD VARCHAR2(50 BYTE) NOT NULL,
	-- TRNBI_PLAN_SHPMT VARCHAR2(8 BYTE) NOT NULL,
	-- TRNBI_CR_JOB_NAME VARCHAR2(50 BYTE) NOT NULL,
	TRNBI_PROJECT_TYPE VARCHAR2(10 BYTE) NOT NULL,
	-- TRNBI_REL_TRX_NBR VARCHAR2(20 BYTE) NOT NULL,
	-- TRNBI_SHIP_TO_REF VARCHAR2(50 BYTE) NOT NULL,
	-- TRNBI_RETAINAGE_PC NUMBER(7, 2) NOT NULL,
	-- TRNBI_TOTAL_ADD NUMBER(26, 3) NOT NULL,
	-- TRNBI_TOTAL_DED NUMBER(26, 3) NOT NULL,
	-- TRNBI_CON_SUM_TODT NUMBER(26, 3) NOT NULL,
	-- TRNBI_NET_CHG_BY NUMBER(26, 3) NOT NULL,
	-- TRNBI_PROJECT_NAME VARCHAR2(50 BYTE) NOT NULL,
	-- BI_CURRENCY_CD VARCHAR2(3 BYTE) NOT NULL,
	-- CREATED_BY_USER VARCHAR2(30 BYTE) NOT NULL,
	-- TRNBI_ORDER_TYPE VARCHAR2(30 BYTE) NOT NULL,
	-- TRNBI_PRIM_SALESMN NUMBER(15, 0) NOT NULL,
	-- TRNBI_WAYBILLNBR VARCHAR2(75 BYTE) NOT NULL,
	-- FOB_TERMS VARCHAR2(10 BYTE) NOT NULL,
	-- REMIT_FROM_CUST_ID VARCHAR2(15 BYTE) NOT NULL,
	-- TRNBI_BATCH_ID VARCHAR2(50 BYTE) NOT NULL,
	-- TRNBI_BILL_REVIEW VARCHAR2(1 BYTE) NOT NULL,
	-- TRNBI_HDR_NOTE VARCHAR2(4000 BYTE),
	-- TRNBI_SRV_CALL_ID VARCHAR2(40 BYTE),
	-- TRNBI_CUS_CERT_DAT DATE,
	-- TRNBI_AUTH_ID VARCHAR2(40 BYTE),
	-- BUSINESS_UNIT_AR VARCHAR2(5 BYTE),
	-- TRNBI_ORIG_CUST_ID VARCHAR2(15 BYTE),
	-- TRNBI_FS_GRP_CD VARCHAR2(5 BYTE),
	-- TRNBI_MSTR_DEL_OPT VARCHAR2(3 BYTE),
	-- TRNBI_MSTR_INV_FRM VARCHAR2(10 BYTE),
	-- TRNBI_LOGO_KEY VARCHAR2(10 BYTE),
	-- ED_CREATE_DATE DATE,
	-- ED_CREATE_ID VARCHAR2(100 BYTE),
	-- ED_UPDATE_DATE DATE,
	-- ED_UPDATE_ID VARCHAR2(100 BYTE),
	-- ED_SOURCE_ARCHIVE_IND VARCHAR2(1 BYTE) 
	R12_ENTITY VARCHAR2(5 BYTE) NOT NULL
);
-- primary key?
-- indexes?
-- constraints?

truncate table R12_OTR_TRNBI_BI_HDR_PSB;
insert into R12_OTR_TRNBI_BI_HDR_PSB
(
BUSINESS_UNIT, -- VARCHAR2(5), DM_030_EXT_SALES_MVW, mapSalesData68, mapExtendedWarrantySaleData1, mapExtendedYTD, mapSalesData1
INVOICE, -- VARCHAR2(22), DM_030_EXT_SALES_MVW, mapSalesData68, mapExtendedWarrantySaleData1, mapExtendedYTD, mapSalesData1
-- TRNBI_ORIG_SYS_REF, -- VARCHAR2(150)
-- TRNBI_CLAIM_NUMBER, -- VARCHAR2(30)
-- TRNBI_TRX_TYPE, -- NUMBER(10)
-- TRNBI_CR_JOB_NBR, -- VARCHAR2(15)
-- TRNBI_CREDIT_JB_ID, -- VARCHAR2(15)
-- TRNBI_SALES_ORD_ID, -- NUMBER(10)
-- TRNBI_DELIV_OPTION, -- VARCHAR2(3)
-- TRNBI_MFG_BU, -- VARCHAR2(3)
-- TRNBI_MFG_LOC, -- VARCHAR2(3)
-- TRNBI_NBR_OF_LEGS, -- VARCHAR2(1)
-- TRNBI_LEG_NBR, -- VARCHAR2(1)
-- TRNBI_DOC_TYPE, -- VARCHAR2(30)
-- TRNBI_TRAN_CUS_NBR, -- VARCHAR2(8)
-- TRNBI_TRAN_BIL_ADD, -- NUMBER(38)
-- TRNBI_SALES_OFFICE, -- NUMBER(15)
-- TRNBI_INI_CONTRACT, -- NUMBER(26,3)
-- TRNBI_TOTAL_STORED, -- NUMBER(26,3)
-- TRNBI_PREV_CON_ADD, -- NUMBER(26,3)
-- TRNBI_PREV_CON_DED, -- NUMBER(26,3)
-- TRNBI_CURR_CON_ADD, -- NUMBER(26,3)
-- TRNBI_CURR_CON_DED, -- NUMBER(26,3)
-- TRNBI_PCT_CON_COMP, -- NUMBER(26,3)
-- TRNBI_RETAINAGE_CM, -- NUMBER(26,3)
-- TRNBI_STORE_MT_RET, -- NUMBER(7,2)
-- TRNBI_STORE_MAT_CM, -- NUMBER(26,3)
-- TRNBI_TOT_RETAINAG, -- NUMBER(26,3)
-- TRNBI_CON_BIL_TODT, -- NUMBER(26,3)
-- TRNBI_CON_EFF_DATE, -- DATE
-- TRNBI_CUS_PROJ_NBR, -- VARCHAR2(50)
-- TRNBI_CONT_COMP_NM, -- VARCHAR2(150)
-- TRNBI_CONT_CONTACT, -- VARCHAR2(150)
-- TRNBI_CON_APP_DATE, -- DATE
-- TRNBI_VIAARCHITECT, -- VARCHAR2(36)
-- TRNBI_ARCHITECT_AD, -- VARCHAR2(36)
-- TRNBI_ARCHITECT_CT, -- VARCHAR2(30)
-- TRNBI_ARCHITECT_ST, -- VARCHAR2(30)
-- TRNBI_ARCHITECT_PC, -- VARCHAR2(15)
-- TRNBI_ARC_PREV_AMT, -- NUMBER(26,3)
-- TRNBI_ARC_CERT_IND, -- VARCHAR2(1)
-- TRNBI_ARC_COMPANY, -- VARCHAR2(150)
-- TRNBI_ARC_NAME, -- VARCHAR2(150)
-- TRNBI_ARC_CERT_DT, -- DATE
-- TRNBI_ARC_AMT_CERT, -- NUMBER(26,3)
-- TRNBI_CUS_PREV_AMT, -- NUMBER(26,3)
-- TRNBI_CUS_CERT_IND, -- VARCHAR2(1)
-- TRNBI_CUS_CERT_CON, -- VARCHAR2(150)
-- TRNBI_CUS_CERT_AMT, -- NUMBER(26,3)
-- TRNBI_FIN_INV_IND, -- VARCHAR2(1)
-- TRNBI_IN_EMAIL_ADD, -- VARCHAR2(50)
-- TRNBI_PLAN_SHPMT, -- VARCHAR2(8)
-- TRNBI_CR_JOB_NAME, -- VARCHAR2(50)
TRNBI_PROJECT_TYPE, -- VARCHAR2(10), mapSalesData68, mapSalesData1
-- TRNBI_REL_TRX_NBR, -- VARCHAR2(20)
-- TRNBI_SHIP_TO_REF, -- VARCHAR2(50)
-- TRNBI_RETAINAGE_PC, -- NUMBER(7,2)
-- TRNBI_TOTAL_ADD, -- NUMBER(26,3)
-- TRNBI_TOTAL_DED, -- NUMBER(26,3)
-- TRNBI_CON_SUM_TODT, -- NUMBER(26,3)
-- TRNBI_NET_CHG_BY, -- NUMBER(26,3)
-- TRNBI_PROJECT_NAME, -- VARCHAR2(50)
-- BI_CURRENCY_CD, -- VARCHAR2(3)
-- CREATED_BY_USER, -- VARCHAR2(30)
-- TRNBI_ORDER_TYPE, -- VARCHAR2(30)
-- TRNBI_PRIM_SALESMN, -- NUMBER(15)
-- TRNBI_WAYBILLNBR, -- VARCHAR2(75)
-- FOB_TERMS, -- VARCHAR2(10)
-- REMIT_FROM_CUST_ID, -- VARCHAR2(15)
-- TRNBI_BATCH_ID, -- VARCHAR2(50)
-- TRNBI_BILL_REVIEW, -- VARCHAR2(1)
-- TRNBI_HDR_NOTE, -- VARCHAR2(4000)
-- TRNBI_SRV_CALL_ID, -- VARCHAR2(40)
-- TRNBI_CUS_CERT_DAT, -- DATE
-- TRNBI_AUTH_ID, -- VARCHAR2(40)
-- BUSINESS_UNIT_AR, -- VARCHAR2(5)
-- TRNBI_ORIG_CUST_ID, -- VARCHAR2(15)
-- TRNBI_FS_GRP_CD, -- VARCHAR2(5)
-- TRNBI_MSTR_DEL_OPT, -- VARCHAR2(3)
-- TRNBI_MSTR_INV_FRM, -- VARCHAR2(10)
-- TRNBI_LOGO_KEY, -- VARCHAR2(10)
-- ED_CREATE_DATE, -- DATE
-- ED_CREATE_ID, -- VARCHAR2(100)
-- ED_UPDATE_DATE, -- DATE
-- ED_UPDATE_ID, -- VARCHAR2(100)
-- ED_SOURCE_ARCHIVE_IND, -- VARCHAR2(1)
R12_ENTITY
)
select
BUSINESS_UNIT, -- VARCHAR2(5)
INVOICE, -- VARCHAR2(22)
-- TRNBI_ORIG_SYS_REF, -- VARCHAR2(150)
-- TRNBI_CLAIM_NUMBER, -- VARCHAR2(30)
-- TRNBI_TRX_TYPE, -- NUMBER(10)
-- TRNBI_CR_JOB_NBR, -- VARCHAR2(15)
-- TRNBI_CREDIT_JB_ID, -- VARCHAR2(15)
-- TRNBI_SALES_ORD_ID, -- NUMBER(10)
-- TRNBI_DELIV_OPTION, -- VARCHAR2(3)
-- TRNBI_MFG_BU, -- VARCHAR2(3)
-- TRNBI_MFG_LOC, -- VARCHAR2(3)
-- TRNBI_NBR_OF_LEGS, -- VARCHAR2(1)
-- TRNBI_LEG_NBR, -- VARCHAR2(1)
-- TRNBI_DOC_TYPE, -- VARCHAR2(30)
-- TRNBI_TRAN_CUS_NBR, -- VARCHAR2(8)
-- TRNBI_TRAN_BIL_ADD, -- NUMBER(38)
-- TRNBI_SALES_OFFICE, -- NUMBER(15)
-- TRNBI_INI_CONTRACT, -- NUMBER(26,3)
-- TRNBI_TOTAL_STORED, -- NUMBER(26,3)
-- TRNBI_PREV_CON_ADD, -- NUMBER(26,3)
-- TRNBI_PREV_CON_DED, -- NUMBER(26,3)
-- TRNBI_CURR_CON_ADD, -- NUMBER(26,3)
-- TRNBI_CURR_CON_DED, -- NUMBER(26,3)
-- TRNBI_PCT_CON_COMP, -- NUMBER(26,3)
-- TRNBI_RETAINAGE_CM, -- NUMBER(26,3)
-- TRNBI_STORE_MT_RET, -- NUMBER(7,2)
-- TRNBI_STORE_MAT_CM, -- NUMBER(26,3)
-- TRNBI_TOT_RETAINAG, -- NUMBER(26,3)
-- TRNBI_CON_BIL_TODT, -- NUMBER(26,3)
-- TRNBI_CON_EFF_DATE, -- DATE
-- TRNBI_CUS_PROJ_NBR, -- VARCHAR2(50)
-- TRNBI_CONT_COMP_NM, -- VARCHAR2(150)
-- TRNBI_CONT_CONTACT, -- VARCHAR2(150)
-- TRNBI_CON_APP_DATE, -- DATE
-- TRNBI_VIAARCHITECT, -- VARCHAR2(36)
-- TRNBI_ARCHITECT_AD, -- VARCHAR2(36)
-- TRNBI_ARCHITECT_CT, -- VARCHAR2(30)
-- TRNBI_ARCHITECT_ST, -- VARCHAR2(30)
-- TRNBI_ARCHITECT_PC, -- VARCHAR2(15)
-- TRNBI_ARC_PREV_AMT, -- NUMBER(26,3)
-- TRNBI_ARC_CERT_IND, -- VARCHAR2(1)
-- TRNBI_ARC_COMPANY, -- VARCHAR2(150)
-- TRNBI_ARC_NAME, -- VARCHAR2(150)
-- TRNBI_ARC_CERT_DT, -- DATE
-- TRNBI_ARC_AMT_CERT, -- NUMBER(26,3)
-- TRNBI_CUS_PREV_AMT, -- NUMBER(26,3)
-- TRNBI_CUS_CERT_IND, -- VARCHAR2(1)
-- TRNBI_CUS_CERT_CON, -- VARCHAR2(150)
-- TRNBI_CUS_CERT_AMT, -- NUMBER(26,3)
-- TRNBI_FIN_INV_IND, -- VARCHAR2(1)
-- TRNBI_IN_EMAIL_ADD, -- VARCHAR2(50)
-- TRNBI_PLAN_SHPMT, -- VARCHAR2(8)
-- TRNBI_CR_JOB_NAME, -- VARCHAR2(50)
TRNBI_PROJECT_TYPE, -- VARCHAR2(10)
-- TRNBI_REL_TRX_NBR, -- VARCHAR2(20)
-- TRNBI_SHIP_TO_REF, -- VARCHAR2(50)
-- TRNBI_RETAINAGE_PC, -- NUMBER(7,2)
-- TRNBI_TOTAL_ADD, -- NUMBER(26,3)
-- TRNBI_TOTAL_DED, -- NUMBER(26,3)
-- TRNBI_CON_SUM_TODT, -- NUMBER(26,3)
-- TRNBI_NET_CHG_BY, -- NUMBER(26,3)
-- TRNBI_PROJECT_NAME, -- VARCHAR2(50)
-- BI_CURRENCY_CD, -- VARCHAR2(3)
-- CREATED_BY_USER, -- VARCHAR2(30)
-- TRNBI_ORDER_TYPE, -- VARCHAR2(30)
-- TRNBI_PRIM_SALESMN, -- NUMBER(15)
-- TRNBI_WAYBILLNBR, -- VARCHAR2(75)
-- FOB_TERMS, -- VARCHAR2(10)
-- REMIT_FROM_CUST_ID, -- VARCHAR2(15)
-- TRNBI_BATCH_ID, -- VARCHAR2(50)
-- TRNBI_BILL_REVIEW, -- VARCHAR2(1)
-- TRNBI_HDR_NOTE, -- VARCHAR2(4000)
-- TRNBI_SRV_CALL_ID, -- VARCHAR2(40)
-- TRNBI_CUS_CERT_DAT, -- DATE
-- TRNBI_AUTH_ID, -- VARCHAR2(40)
-- BUSINESS_UNIT_AR, -- VARCHAR2(5)
-- TRNBI_ORIG_CUST_ID, -- VARCHAR2(15)
-- TRNBI_FS_GRP_CD, -- VARCHAR2(5)
-- TRNBI_MSTR_DEL_OPT, -- VARCHAR2(3)
-- TRNBI_MSTR_INV_FRM, -- VARCHAR2(10)
-- TRNBI_LOGO_KEY, -- VARCHAR2(10)
-- ED_CREATE_DATE, -- DATE
-- ED_CREATE_ID, -- VARCHAR2(100)
-- ED_UPDATE_DATE, -- DATE
-- ED_UPDATE_ID, -- VARCHAR2(100)
-- ED_SOURCE_ARCHIVE_IND, -- VARCHAR2(1)
DBO.F_GET_R12_ACCOUNT_STRING ('ENTITY', BUSINESS_UNIT, ACCOUNT, DEPTID, PRODUCT, null) as R12_ENTITY
from
OTR_TRNBI_BI_HDR_PSB;

-- CREATE TABLE R12_OTR_PROD_CODE_XREF_RCPO like OTR_PROD_CODE_XREF_RCPO
-- add R12_PRODUCT
-- add R12_ENTITY

select count(*) from OTR_PROD_CODE_XREF_RCPO; -- 3374 9:50 AM MDT

CREATE TABLE DBO.R12_OTR_PROD_CODE_XREF_RCPO (
	GL_LEDGER VARCHAR2(6 BYTE) NOT NULL,
	MANF_PROD_CODE VARCHAR2(6 BYTE) NOT NULL,
	MANF_PROD_CODE_DESCR VARCHAR2(50 BYTE),
	-- DIST_PROD_CODE VARCHAR2(6 BYTE),
	-- DIST_PROD_CODE_DESCR VARCHAR2(50 BYTE),
	-- PARTS_PROD_CODE_IND VARCHAR2(3 BYTE),
	-- PROD_TYPE_INDICATOR VARCHAR2(20 BYTE),
	-- PROCESS_GROUP VARCHAR2(30 BYTE),
	PRODUCT_CATEGORY VARCHAR2(5 BYTE),
	TWO_FIVE VARCHAR2(1 BYTE),
	-- MFG_RESPONSIBILITY VARCHAR2(50 BYTE),
	-- PROD_CODE_TYPE VARCHAR2(50 BYTE),
	-- CLOSURE_RATE_COJO_FLAG VARCHAR2(1 BYTE),
	-- REVENUE_STREAM VARCHAR2(40 BYTE),
	-- ED_CREATE_DATE DATE NOT NULL,
	-- ED_CREATE_ID VARCHAR2(100 BYTE) NOT NULL,
	-- ED_UPDATE_DATE DATE NOT NULL,
	-- ED_UPDATE_ID VARCHAR2(100 BYTE) NOT NULL,
	-- GL_REVENUE_STREAM VARCHAR2(40 BYTE),
	-- MANF_PLANT_DEPT_ID VARCHAR2(10 BYTE),
	-- GL_PRODUCT_CODE VARCHAR2(6 BYTE),
	-- GL_PRODUCT_CODE_DESCR VARCHAR2(50 BYTE),
	-- PRODUCT_FAMILY_1 VARCHAR2(50 BYTE),
	-- PRODUCT_FAMILY_2 VARCHAR2(50 BYTE),
	-- PRODUCT_FAMILY_3 VARCHAR2(50 BYTE),
	-- HERITAGE_INCLUSION_IND VARCHAR2(1 CHAR),
	-- INVENTORY_ORG_ID VARCHAR2(20 BYTE),
	-- PROD_FAMILY_OFFSET VARCHAR2(30 BYTE),
	-- PRI_DIST_PROD_CODE VARCHAR2(10 BYTE),
	-- PRI_GL_PROD_CODE VARCHAR2(10 BYTE),
	R12_PRODUCT VARCHAR2(6 BYTE) NOT NULL,
	R12_ENTITY VARCHAR2(6 BYTE) NOT NULL,
	CONSTRAINT XPK_R12_OTR_PROD_CODE_XREF_RCPO PRIMARY KEY(GL_LEDGER, MANF_PROD_CODE) ENABLE 
);
-- indexes?
-- constraints?

truncate table R12_OTR_PROD_CODE_XREF_RCPO;
insert into R12_OTR_PROD_CODE_XREF_RCPO
(
GL_LEDGER, -- NOT NULL VARCHAR2(6), mapSalesData68, mapExtendedWarrantyCostFlow, mapExtendedWarrantyCostFlowtest, mapExtendedWarrantyExpenseData, mapSalesData1
MANF_PROD_CODE, -- NOT NULL VARCHAR2(6), mapSalesData68, mapExtendedWarrantyCostFlow, mapExtendedWarrantyCostFlowtest, mapExtendedWarrantyExpenseData, mapSalesData1
MANF_PROD_CODE_DESCR, -- VARCHAR2(50), mapSalesData68, mapSalesData1
-- DIST_PROD_CODE, -- VARCHAR2(6)
-- DIST_PROD_CODE_DESCR, -- VARCHAR2(50)
-- PARTS_PROD_CODE_IND, -- VARCHAR2(3)
-- PROD_TYPE_INDICATOR, -- VARCHAR2(20)
-- PROCESS_GROUP, -- VARCHAR2(30)
PRODUCT_CATEGORY, -- VARCHAR2(5), mapSalesData68, mapExtendedWarrantyCostFlow, mapExtendedWarrantyCostFlowtest, mapExtendedWarrantyExpenseData, mapSalesData1
TWO_FIVE, -- VARCHAR2(1), mapSalesData68
-- MFG_RESPONSIBILITY, -- VARCHAR2(50)
-- PROD_CODE_TYPE, -- VARCHAR2(50)
-- CLOSURE_RATE_COJO_FLAG, -- VARCHAR2(1)
-- REVENUE_STREAM, -- VARCHAR2(40)
-- ED_CREATE_DATE, -- NOT NULL DATE
-- ED_CREATE_ID, -- NOT NULL VARCHAR2(100)
-- ED_UPDATE_DATE, -- NOT NULL DATE
-- ED_UPDATE_ID, -- NOT NULL VARCHAR2(100)
-- GL_REVENUE_STREAM, -- VARCHAR2(40)
-- MANF_PLANT_DEPT_ID, -- VARCHAR2(10)
-- GL_PRODUCT_CODE, -- VARCHAR2(6)
-- GL_PRODUCT_CODE_DESCR, -- VARCHAR2(50)
-- PRODUCT_FAMILY_1, -- VARCHAR2(50)
-- PRODUCT_FAMILY_2, -- VARCHAR2(50)
-- PRODUCT_FAMILY_3, -- VARCHAR2(50)
-- HERITAGE_INCLUSION_IND, -- VARCHAR2(1 CHAR)
-- INVENTORY_ORG_ID, -- VARCHAR2(20)
-- PROD_FAMILY_OFFSET, -- VARCHAR2(30)
-- PRI_DIST_PROD_CODE, -- VARCHAR2(10)
-- PRI_GL_PROD_CODE, -- VARCHAR2(10)
R12_PRODUCT,
R12_ENTITY
)
select
GL_LEDGER, -- NOT NULL VARCHAR2(6)
MANF_PROD_CODE, -- NOT NULL VARCHAR2(6)
MANF_PROD_CODE_DESCR, -- VARCHAR2(50)
-- DIST_PROD_CODE, -- VARCHAR2(6)
-- DIST_PROD_CODE_DESCR, -- VARCHAR2(50)
-- PARTS_PROD_CODE_IND, -- VARCHAR2(3)
-- PROD_TYPE_INDICATOR, -- VARCHAR2(20)
-- PROCESS_GROUP, -- VARCHAR2(30)
PRODUCT_CATEGORY, -- VARCHAR2(5)
TWO_FIVE, -- VARCHAR2(1)
-- MFG_RESPONSIBILITY, -- VARCHAR2(50)
-- PROD_CODE_TYPE, -- VARCHAR2(50)
-- CLOSURE_RATE_COJO_FLAG, -- VARCHAR2(1)
-- REVENUE_STREAM, -- VARCHAR2(40)
-- ED_CREATE_DATE, -- NOT NULL DATE
-- ED_CREATE_ID, -- NOT NULL VARCHAR2(100)
-- ED_UPDATE_DATE, -- NOT NULL DATE
-- ED_UPDATE_ID, -- NOT NULL VARCHAR2(100)
-- GL_REVENUE_STREAM, -- VARCHAR2(40)
-- MANF_PLANT_DEPT_ID, -- VARCHAR2(10)
-- GL_PRODUCT_CODE, -- VARCHAR2(6)
-- GL_PRODUCT_CODE_DESCR, -- VARCHAR2(50)
-- PRODUCT_FAMILY_1, -- VARCHAR2(50)
-- PRODUCT_FAMILY_2, -- VARCHAR2(50)
-- PRODUCT_FAMILY_3, -- VARCHAR2(50)
-- HERITAGE_INCLUSION_IND, -- VARCHAR2(1 CHAR)
-- INVENTORY_ORG_ID, -- VARCHAR2(20)
-- PROD_FAMILY_OFFSET, -- VARCHAR2(30)
-- PRI_DIST_PROD_CODE, -- VARCHAR2(10)
-- PRI_GL_PROD_CODE, -- VARCHAR2(10)
DBO.F_GET_R12_ACCOUNT_STRING ('PRODUCT', GL_LEDGER, null, null, MANF_PROD_CODE, null) as R12_PRODUCT,
DBO.F_GET_R12_ACCOUNT_STRING ('ENTITY', GL_LEDGER, null, null, MANF_PROD_CODE, null) as R12_ENTITY
from
OTR_PROD_CODE_XREF_RCPO;

-- CREATE TABLE R12_OTR_TRANE_PRODUCTS_PS like OTR_TRANE_PRODUCTS_PS
-- add R12_PRODUCT

select count(*) from OTR_TRANE_PRODUCTS_PS; -- 1764 9:50 AM MDT

CREATE TABLE DBO.R12_OTR_TRANE_PRODUCTS_PS (
	PRODUCT VARCHAR2(6 BYTE) NOT NULL,
	DESCR VARCHAR2(30 BYTE),
	-- DESCRSHORT VARCHAR2(10 BYTE),
	R12_PRODUCT VARCHAR2(6 BYTE) NOT NULL,
	CONSTRAINT XPK_R12_OTR_TRANE_PRODUCTS_PS PRIMARY KEY(PRODUCT) ENABLE 
);
-- indexes?
-- constraints?

truncate table R12_OTR_TRANE_PRODUCTS_PS;
insert into R12_OTR_TRANE_PRODUCTS_PS
(
PRODUCT, -- NOT NULL VARCHAR2(6), mapSalesData68, mapSalesData1
DESCR, -- VARCHAR2(30), mapSalesData68, mapSalesData1
-- DESCRSHORT, -- VARCHAR2(10)
R12_PRODUCT
)
select
PRODUCT, -- NOT NULL VARCHAR2(6)
DESCR, -- VARCHAR2(30)
-- DESCRSHORT, -- VARCHAR2(10)
DBO.F_GET_R12_ACCOUNT_STRING ('PRODUCT', null, null, null, PRODUCT, null) as R12_PRODUCT
from
OTR_TRANE_PRODUCTS_PS;

-- CREATE TABLE R12_OTR_TRNCO_CM_DIST_PSB like OTR_TRNCO_CM_DIST_PSB;
-- add R12_ACCOUNT
-- add R12_PRODUCT
-- add R12_ENTITY
-- add R12_LOCATION

select count(*) from OTR_TRNCO_CM_DIST_PSB; -- 128197164 9:55 AM MDT

CREATE TABLE DBO.R12_OTR_TRNCO_CM_DIST_PSB (
	BUSINESS_UNIT VARCHAR2(5 BYTE) NOT NULL,
	-- TRNCO_TRAN_SRC_TYP VARCHAR2(4 BYTE) NOT NULL,
	-- TRNCO_TRAN_SRC_ID VARCHAR2(100 BYTE) NOT NULL,
	-- TRNCO_TRAN_LN_SEQ NUMBER(*, 0) NOT NULL,
	-- TRNCO_CM_HDR_SEQ NUMBER(*, 0) NOT NULL,
	-- TRNCO_CM_LN_SEQ NUMBER(*, 0) NOT NULL,
	-- TRNCO_CM_EVT_SEQ NUMBER(*, 0) NOT NULL,
	-- TRNCO_CM_DST_SEQ NUMBER(*, 0) NOT NULL,
	-- TRNCO_CM_DIST_ID NUMBER(15, 0),
	-- CREATE_DATE DATE,
	-- CREATED_BY_USER VARCHAR2(30 BYTE),
	-- LAST_MAINT_DTTM DATE,
	-- LAST_MAINT_OPRID VARCHAR2(30 BYTE),
	BUSINESS_UNIT_GL VARCHAR2(5 BYTE),
	ACCOUNT VARCHAR2(10 BYTE),
	DEPTID VARCHAR2(10 BYTE),
	PRODUCT VARCHAR2(6 BYTE),
	DEBIT_AMT NUMBER(15, 2),
	CREDIT_AMOUNT NUMBER(15, 2),
	-- ACCOUNTING_DT DATE,
	JOURNAL_ID VARCHAR2(10 BYTE),
	JOURNAL_DATE DATE,
	-- JOURNAL_LINE NUMBER(*, 0),
	-- ACCOUNTING_PERIOD NUMBER(*, 0),
	-- FISCAL_YEAR NUMBER(*, 0),
	-- LEDGER_GROUP VARCHAR2(10 BYTE),
	-- LEDGER VARCHAR2(10 BYTE),
	-- GL_DISTRIB_STATUS VARCHAR2(1 BYTE),
	-- CURRENCY_CD VARCHAR2(3 BYTE),
	-- FOREIGN_CURRENCY VARCHAR2(3 BYTE),
	-- FOREIGN_AMOUNT NUMBER(26, 3),
	-- PROCESS_INSTANCE NUMBER(10, 0),
	R12_ACCOUNT VARCHAR2(10 BYTE),
	R12_PRODUCT VARCHAR2(6 BYTE),
	R12_ENTITY VARCHAR2(5 BYTE) NOT NULL,
	R12_LOCATION VARCHAR2(10 BYTE),
	CONSTRAINT XPK_R12_OTR_TRNCO_CM_DIST_PSB PRIMARY KEY (
		BUSINESS_UNIT,
		TRNCO_TRAN_SRC_TYP,
		TRNCO_TRAN_SRC_ID,
		TRNCO_TRAN_LN_SEQ,
		TRNCO_CM_HDR_SEQ,
		TRNCO_CM_LN_SEQ,
		TRNCO_CM_EVT_SEQ,
		TRNCO_CM_DST_SEQ 
	) ENABLE 
);
-- indexes?
-- constraints?

truncate table R12_OTR_TRNCO_CM_DIST_PSB;
insert into R12_OTR_TRNCO_CM_DIST_PSB
(
BUSINESS_UNIT, -- VARCHAR2(5), mapExtendedWarrantyCommissionData
-- TRNCO_TRAN_SRC_TYP, -- VARCHAR2(4)
-- TRNCO_TRAN_SRC_ID, -- VARCHAR2(100)
-- TRNCO_TRAN_LN_SEQ, -- NUMBER(38)
-- TRNCO_CM_HDR_SEQ, -- NUMBER(38)
-- TRNCO_CM_LN_SEQ, -- NUMBER(38)
-- TRNCO_CM_EVT_SEQ, -- NUMBER(38)
-- TRNCO_CM_DST_SEQ, -- NUMBER(38)
-- TRNCO_CM_DIST_ID, -- NUMBER(15)
-- CREATE_DATE, -- DATE
-- CREATED_BY_USER, -- VARCHAR2(30)
-- LAST_MAINT_DTTM, -- DATE
-- LAST_MAINT_OPRID, -- VARCHAR2(30)
BUSINESS_UNIT_GL, -- VARCHAR2(5), DM_030_EXT_COMM_MVW, mapExtendedWarrantyCommissionData
ACCOUNT, -- VARCHAR2(10), DM_030_EXT_COMM_MVW, mapExtendedWarrantyCommissionData
DEPTID, -- VARCHAR2(10), DM_030_EXT_COMM_MVW, mapExtendedWarrantyCommissionData
PRODUCT, -- VARCHAR2(6), mapExtendedWarrantyCommissionData
DEBIT_AMT, -- NUMBER(15,2), DM_030_EXT_COMM_MVW, mapExtendedWarrantyCommissionData
CREDIT_AMOUNT, -- NUMBER(15,2), DM_030_EXT_COMM_MVW, mapExtendedWarrantyCommissionData
-- ACCOUNTING_DT, -- DATE
JOURNAL_ID, -- VARCHAR2(10), DM_030_EXT_COMM_MVW
JOURNAL_DATE, -- DATE, DM_030_EXT_COMM_MVW, mapExtendedWarrantyCommissionData
-- JOURNAL_LINE, -- NUMBER(38)
-- ACCOUNTING_PERIOD, -- NUMBER(38)
-- FISCAL_YEAR, -- NUMBER(38)
-- LEDGER_GROUP, -- VARCHAR2(10)
-- LEDGER, -- VARCHAR2(10)
-- GL_DISTRIB_STATUS, -- VARCHAR2(1)
-- CURRENCY_CD, -- VARCHAR2(3)
-- FOREIGN_CURRENCY, -- VARCHAR2(3)
-- FOREIGN_AMOUNT, -- NUMBER(26,3)
-- PROCESS_INSTANCE, -- NUMBER(10)
R12_ACCOUNT,
R12_PRODUCT,
R12_ENTITY,
R12_LOCATION
)
select
BUSINESS_UNIT, -- VARCHAR2(5)
-- TRNCO_TRAN_SRC_TYP, -- VARCHAR2(4)
-- TRNCO_TRAN_SRC_ID, -- VARCHAR2(100)
-- TRNCO_TRAN_LN_SEQ, -- NUMBER(38)
-- TRNCO_CM_HDR_SEQ, -- NUMBER(38)
-- TRNCO_CM_LN_SEQ, -- NUMBER(38)
-- TRNCO_CM_EVT_SEQ, -- NUMBER(38)
-- TRNCO_CM_DST_SEQ, -- NUMBER(38)
-- TRNCO_CM_DIST_ID, -- NUMBER(15)
-- CREATE_DATE, -- DATE
-- CREATED_BY_USER, -- VARCHAR2(30)
-- LAST_MAINT_DTTM, -- DATE
-- LAST_MAINT_OPRID, -- VARCHAR2(30)
BUSINESS_UNIT_GL, -- VARCHAR2(5)
ACCOUNT, -- VARCHAR2(10)
DEPTID, -- VARCHAR2(10)
PRODUCT, -- VARCHAR2(6)
DEBIT_AMT, -- NUMBER(15,2)
CREDIT_AMOUNT, -- NUMBER(15,2)
-- ACCOUNTING_DT, -- DATE
JOURNAL_ID, -- VARCHAR2(10)
JOURNAL_DATE, -- DATE
-- JOURNAL_LINE, -- NUMBER(38)
-- ACCOUNTING_PERIOD, -- NUMBER(38)
-- FISCAL_YEAR, -- NUMBER(38)
-- LEDGER_GROUP, -- VARCHAR2(10)
-- LEDGER, -- VARCHAR2(10)
-- GL_DISTRIB_STATUS, -- VARCHAR2(1)
-- CURRENCY_CD, -- VARCHAR2(3)
-- FOREIGN_CURRENCY, -- VARCHAR2(3)
-- FOREIGN_AMOUNT, -- NUMBER(26,3)
-- PROCESS_INSTANCE, -- NUMBER(10)
DBO.F_GET_R12_ACCOUNT_STRING ('ACCOUNT', BUSINESS_UNIT, ACCOUNT, DEPTID, PRODUCT, null) as R12_ACCOUNT,
DBO.F_GET_R12_ACCOUNT_STRING ('PRODUCT', BUSINESS_UNIT, ACCOUNT, DEPTID, PRODUCT, null) as R12_PRODUCT,
DBO.F_GET_R12_ACCOUNT_STRING ('ENTITY', BUSINESS_UNIT, ACCOUNT, DEPTID, PRODUCT, null) as R12_ENTITY,
DBO.F_GET_R12_ACCOUNT_STRING ('LOCATION', BUSINESS_UNIT, ACCOUNT, DEPTID, PRODUCT, null) as R12_LOCATION
from
OTR_TRNCO_CM_DIST_PSB;

-- updates

-- MD_030_COMMISSION_DTL_UPD add column, one-time update

select count(*) from MD_030_COMMISSION_DTL_UPD; -- 960 9:40 AM MDT
alter table MD_030_COMMISSION_DTL_UPD add R12_ACCOUNT VARCHAR(10); -- 10?

update MD_030_COMMISSION_DTL_UPD
set R12_ACCOUNT = DBO.F_GET_R12_ACCOUNT_STRING ('ACCOUNT', null, GL_ACCOUNT, null, null, null);

-- MD_030_SALES_DTL_UPD add column, one-time update

select count(*) from MD_030_SALES_DTL_UPD; -- 990 9:40 AM MDT
alter table MD_030_SALES_DTL_UPD add R12_ACCOUNT varchar(10); -- 10?

update MD_030_SALES_DTL_UPD
set R12_ACCOUNT = DBO.F_GET_R12_ACCOUNT_STRING ('ACCOUNT', null, GL_ACCOUNT, null, null, null);

