/* Inner query
select count(*) from WC_LABOR_ROLLUP; -- 3.5 mil
select count(*) from TIME_DAY; --37,000 
select count(*) from CLAIM_TYPE_SCD; -- 11
select count(*) from R12_GL_ACCOUNT_SCD;  -- 9,600
-- 1.4 mill in the inner query total
*/

ALTER SESSION SET SQL_TRACE=TRUE;
ALTER SESSION SET TRACEFILE_IDENTIFIER=dm_fal_claims_err;      
select count(*) from (SELECT 	DISTINCT CLAIM_NBR, STEP_NBR, WA_POLICY_TYPE, WA_RANGE FROM DM_FAL_CLAIMS_WARRANTY_XRF ) a;

		/* -SS- */
		--,EXPENSE_TYPE_SCD ETS
	INNER JOIN PROD_CODE_SCD PCS              ON CCN_DATA.PROD_CODE_SCD_KEY = PCS.PROD_CODE_SCD_KEY
	INNER JOIN CUST_ACCOUNT_SCD CACCT         ON CCN_DATA.CUST_ACCOUNT_SCD_KEY = CACCT.CUST_ACCOUNT_SCD_KEY
	INNER JOIN SUBMIT_OFFICE_SCD SOS          ON CCN_DATA.SUBMIT_OFFICE_SCD_KEY = SOS.SUBMIT_OFFICE_SCD_KEY
	INNER JOIN PROD_CODE_XREF_RCPO_DR PRODGRP ON -- -SS- issue 22
		PCS.PROD_CODE = PRODGRP.MANF_PROD_CODE      -- -SS- issues 55, 56
		AND GLA.PS_COMPANY = PRODGRP.GL_LEDGER      -- SR-r12???
		-- -SS- ,ACTUATE_SEC_XREF ASX
	INNER JOIN DM_WAR_CSN_RSV_PCT_REF RES_PCT   ON CCN_DATA.EXPENSE_TYPE_DESCR = RES_PCT.EXPENSE_TYPE_DESCR AND CCN_DATA.EXPENSE_TYPE_CATG = UPPER(RES_PCT.EXPENSE_TYPE_CATG) AND SOS.COMPANY_OWNED_IND = RES_PCT.COMPANY_OWNED_IND
	LEFT OUTER JOIN UD_031_STDWTY_RSV_CLM_ADJ A ON CCN_DATA.CLAIM_NBR = A.CLAIM_NUMBER
		/* FOR RESERVE GROUP */
	LEFT OUTER JOIN DM_WAR_CSN_RSV_PCT_REF RES_PCT1 ON A.CLAIM_TYPE = RES_PCT1.CLAIM_TYPE


SELECT  count(*) cnt
		/*+  no_cpu_costing */
		/*
		'SPD/Retrofit Labor/Extended Purchased Labor' AS TYPE,
		LR.CLAIM_NBR,
		LR.RETRO_ID,
		CT.CLAIM_TYPE_CODE AS CLAIM_TYPE,
		(
		CASE WHEN EXPENSE_TYPE_SCD_KEY IN(58, 60, 61)
			THEN 'MATERIAL'
			ELSE 'LABOR'
		END) AS EXPENSE_TYPE_DESCR,
		(
		CASE WHEN EXPENSE_TYPE_SCD_KEY IN(58, 60, 61)
			THEN 'MATERIAL'
			ELSE 'LABOR'
		END) AS EXPENSE_TYPE_CATG,
		LR.CHARGE_COMM_PCT,
		LR.CHARGE_COMPANY_PCT,
		LR.ALLOCATED_EXP_TYPE_AMOUNT * - 1 AS DOLLAR_AMOUNT,
		LR.STEP_NBR,
		LR.CCN_TRX_DATE_KEY,
		LR.ORIGINAL_SHIP_DATE_KEY,
		LR.FAIL_DATE_KEY,
		LR.START_DATE_KEY,
		LR.GL_ACCOUNT_SCD_KEY,
		LR.PROD_CODE_SCD_KEY,
		LR.CUST_ACCOUNT_SCD_KEY,
		LR.SUBMIT_OFFICE_SCD_KEY,
		LR.TRX_CURRENCY
		*/
	FROM
		WC_LABOR_ROLLUP LR
	INNER JOIN TIME_DAY TD            ON TD.TIME_KEY = LR.CCN_TRX_DATE_KEY --, EXPENSE_TYPE_SCD ET
	INNER JOIN CLAIM_TYPE_SCD CT      ON LR.CLAIM_TYPE_SCD_KEY = CT.CLAIM_TYPE_SCD_KEY
	INNER JOIN R12_GL_ACCOUNT_SCD GLA ON GLA.GL_ACCOUNT_SCD_KEY = LR.GL_ACCOUNT_SCD_KEY
		/* -SS- */
		-- -SS- NEW
		-- INNER JOIN R12_ACCOUNT_FILTER_UPD AFU ON AFU.R12_ACCOUNT = GLA.R12_ACCOUNT
		-- -SS- /NEW
	WHERE
		1 = 1
		/* for 'SPD','RETROFIT LABOR','EXTD PURCHASED LABOR' only */
		AND LR.CLAIM_TYPE_SCD_KEY IN(1, 2, 9)
		AND TD.FULL_DATE >= TO_DATE('1/1/2001', 'MM/DD/YYYY')
		-- -SS- NEW
		/* SR PS ONLY
		AND((GLA.PS_ACCOUNT = 'NA'
		AND AFU.STANDARD_WARRANTY_EXPENSE = 'Y')
		OR GLA.PS_ACCOUNT LIKE '0620%'
		OR GLA.PS_ACCOUNT LIKE '8062%')
		*/
		AND GLA.PS_ACCOUNT IN('062000', '062004', '062005', '806200', '806201', '806202', '806204', '806205', '806207', '806208')
