CREATE TABLE MAP_SALES_DATA_68 (
	"QUERY_SOURCE" NVARCHAR2(10), 
	"BU" NVARCHAR2(20), 
	"REVENUE_AMOUNT" FLOAT(126), 
	"REVENUE_AMOUNT_DEC" FLOAT(126), 
	"GL_ACCOUNT" NVARCHAR2(10), 
	"DEPT_ID" NVARCHAR2(40), 
	"DEPT_DESCR" NVARCHAR2(50), 
	"MANF_PROD_ID" NVARCHAR2(18), 
	"MANF_PROD_DESCR" NVARCHAR2(50), 
	"DIST_GL_PRODUCT" NVARCHAR2(15), 
	"RESERVE_GROUP" NVARCHAR2(35), 
	"JRNL_DATE" TIMESTAMP (6), 
	"JRNL_YEAR" FLOAT(126), 
	"JRNL_MONTH" FLOAT(126), 
	"JRNL_YEAR_MONTH" FLOAT(126), 
	"JRNL_ID" NVARCHAR2(16), 
	"CURRENCY" NVARCHAR2(3), 
	"COUNTRY_INDICATOR" NVARCHAR2(5)
   );

COMMIT;

TRUNCATE TABLE MAP_SALES_DATA_68;
COMMIT;

DELETE FROM MAP_SALES_DATA_68 WHERE QUERY_SOURCE = 'RCPO';
INSERT INTO MAP_SALES_DATA_68
SELECT
	/*+ NO_CPU_COSTING */
	'RCPO' AS QUERY_SOURCE,
	NVL(PS.GL_BU_ID, CASE
	    WHEN PS.CURRENCY_CODE = 'USD' THEN 'GS303'
	    WHEN PS.CURRENCY_CODE = 'CAD' THEN 'GS315'
		ELSE NULL -- INVALID CODE
		END) AS BU,
	SUM(PS.ORDER_AMOUNT) AS REVENUE_AMOUNT,
	SUM(100 *(PS.ORDER_AMOUNT - TRUNC(PS.ORDER_AMOUNT))) AS REVENUE_AMOUNT_DEC,
	PS.R12_ACCOUNT AS GL_ACCOUNT,
	NVL(PS.R12_LOCATION, CASE
	    WHEN PS.CURRENCY_CODE = 'USD' THEN 97001
	    WHEN PS.CURRENCY_CODE = 'CAD' THEN 97011
		ELSE -10
		END) AS DEPT_ID,
	COALESCE(DP.DESCR, CASE
	    WHEN PS.CURRENCY_CODE = 'USD' THEN 'OTHER EQUIPMENT GROUP'
	    WHEN PS.CURRENCY_CODE = 'CAD' THEN 'CAN OTHER EQUIPMENT GROUP'
		ELSE 'INVALID CURRENCY-' || PS.CURRENCY_CODE
	END) AS DEPT_DESCR,
	PS.PLNT_GL_PROD AS MANF_PROD_ID,
	PX.MANF_PROD_CODE_DESCR AS MANF_PROD_DESCR,
	CASE
		WHEN PS.PART_TYPE = 'Y' AND PS.PARTS_PROD_CODE_IND = 'PCR'
			THEN '41204'
		ELSE PS.R12_PRODUCT
		END AS DIST_GL_PRODUCT,
	NVL(PX.PRODUCT_CATEGORY, 'INVALID PROD CODE - ' || PS.PLNT_GL_PROD) AS RESERVE_GROUP,
	PS.JRNL_DATE AS JRNL_DATE,
	CAST(TO_CHAR(JRNL_DATE, 'YYYY') AS INTEGER) AS JRNL_YEAR,
	CAST(TO_CHAR(JRNL_DATE, 'MM') AS   INTEGER) AS JRNL_MONTH,
	CAST(TO_CHAR(JRNL_DATE, 'YYYY') AS INTEGER) * 100 + CAST(TO_CHAR(JRNL_DATE, 'MM') AS INTEGER) AS JRNL_YEAR_MONTH,
	PS.ORGN_JRNL_ID AS JRNL_ID,
	PS.CURRENCY_CODE AS CURRENCY,
	CASE
		WHEN PS.R12_ENTITY IN('5773', '5588') THEN 'CAD'
		ELSE 'USD'
		END AS COUNTRY_INDICATOR
FROM
	R12_ORACLE_PS_REV_RCPO PS
INNER JOIN OTR_PROD_CODE_XREF_RCPO PX
	ON PS.PLNT_GL_BU = PX.GL_LEDGER
	AND PS.PLNT_GL_PROD = PX.MANF_PROD_CODE
LEFT OUTER JOIN R12_TRANE_LOCATIONS DP
	ON DP.R12_LOCATION = PS.R12_LOCATION
WHERE
	PS.JRNL_DATE BETWEEN TO_DATE('01/01/2005', 'MM/DD/YYYY') AND LAST_DAY(ADD_MONTHS(SYSDATE, - 1))
	AND PX.TWO_FIVE = 'Y'
GROUP BY
	PS.GL_BU_ID,
	PS.R12_ACCOUNT,
	PS.R12_LOCATION,
	DP.DESCR,
	PS.PLNT_GL_PROD,
	PX.MANF_PROD_CODE_DESCR,
	CASE
		WHEN PS.PART_TYPE = 'Y' AND PS.PARTS_PROD_CODE_IND = 'PCR'
			THEN '41204'
		ELSE PS.R12_PRODUCT
		END,
	PS.R12_PRODUCT,
	PX.PRODUCT_CATEGORY,
	PS.JRNL_DATE,
	CAST(TO_CHAR(PS.JRNL_DATE, 'YYYY') AS INTEGER),
	CAST(TO_CHAR(PS.JRNL_DATE, 'MM') AS   INTEGER),
	CAST(TO_CHAR(PS.JRNL_DATE, 'YYYY') AS INTEGER) * 100 + CAST(TO_CHAR(PS.JRNL_DATE, 'MM') AS INTEGER),
	PS.ORGN_JRNL_ID,
	PS.CURRENCY_CODE,
	CASE
		WHEN PS.R12_ENTITY IN('5773', '5588') THEN 'CAD'
		ELSE 'USD'
		END;

COMMIT;

-- 446,394 rows inserted.  104 seconds.

DELETE FROM MAP_SALES_DATA_68 WHERE QUERY_SOURCE = 'P/S GL';
INSERT INTO MAP_SALES_DATA_68
SELECT
		/*+ NO_CPU_COSTING */
		'P/S GL' AS QUERY_SOURCE,
		GA.BUSINESS_UNIT AS BU,
		SUM(L.MONETARY_AMOUNT) AS REVENUE_AMOUNT,
		SUM(100 *(L.MONETARY_AMOUNT - TRUNC(L.MONETARY_AMOUNT))) AS REVENUE_AMOUNT_DEC,
		L.R12_ACCOUNT AS GL_ACCOUNT,
		L.R12_LOCATION AS DEPT_ID,
		DP.DESCR AS DEPT_DESCR,
		L.PS_PRODUCT AS MANF_PROD_ID,
		PR.DESCR AS MANF_PROD_DESCR,
		L.R12_PRODUCT AS DIST_GL_PRODUCT,
		NVL(PX.PRODUCT_CATEGORY, 'INVALID PROD CODE - ' || L.R12_PRODUCT) AS RESERVE_GROUP,
		GA.JOURNAL_DATE AS JRNL_DATE,
		TO_NUMBER(TO_CHAR(GA.JOURNAL_DATE, 'YYYY')) AS JRNL_YEAR,
		TO_NUMBER(TO_CHAR(GA.JOURNAL_DATE, 'MM')) AS JRNL_MONTH,
		TO_NUMBER(TO_CHAR(GA.JOURNAL_DATE, 'YYYY')) * 100 + TO_NUMBER(TO_CHAR(GA.JOURNAL_DATE, 'MM')) AS JRNL_YEAR_MONTH,
		GA.JOURNAL_ID AS JRNL_ID,
		L.CURRENCY_CD AS CURRENCY,
		CASE
			WHEN L.R12_ENTITY IN('5773', '5588') THEN 'CAD'
			ELSE 'USD'
			END AS COUNTRY_INDICATOR
	FROM
		R12_JRNL_LN_PS L
	INNER JOIN R12_JRNL_HEADER_PS GA
		ON GA.BUSINESS_UNIT = L.BUSINESS_UNIT
		AND GA.JOURNAL_ID = L.JOURNAL_ID
		AND GA.JOURNAL_DATE = L.JOURNAL_DATE
		AND GA.UNPOST_SEQ = L.UNPOST_SEQ
	INNER JOIN R12_ACCOUNT_FILTER_UPD AFU
		ON AFU.R12_ACCOUNT = L.R12_ACCOUNT
	LEFT OUTER JOIN R12_TRANE_PRODUCTS_PS PR
		ON L.R12_PRODUCT = PR.R12_PRODUCT
	LEFT OUTER JOIN R12_TRANE_LOCATIONS DP
		ON L.R12_LOCATION = DP.R12_LOCATION 
	INNER JOIN OTR_PROD_CODE_XREF_RCPO PX ON L.BUSINESS_UNIT = PX.GL_LEDGER
		AND L.PS_PRODUCT = PX.MANF_PROD_CODE
	WHERE
		GA.JRNL_HDR_STATUS IN('P', 'U')
		AND GA.FISCAL_YEAR IN('2003', '2004')
		AND L.LEDGER = 'ACTUALS'
		AND((L.PS_ACCOUNT = 'NA'
		AND AFU.EQUAL_700000 = 'Y')
		OR(L.PS_ACCOUNT <> 'NA'
		AND L.PS_ACCOUNT = '700000'))
		AND GA.BUSINESS_UNIT IN('CAN', 'CSD')
		AND PX.TWO_FIVE = 'Y'
	GROUP BY
		GA.BUSINESS_UNIT,
		L.R12_ACCOUNT,
		L.R12_LOCATION,
		DP.DESCR,
		L.PS_PRODUCT,
		L.R12_PRODUCT,
		PR.DESCR,
		PX.PRODUCT_CATEGORY,
		GA.JOURNAL_DATE,
		TO_NUMBER(TO_CHAR(GA.JOURNAL_DATE, 'YYYY')),
		TO_NUMBER(TO_CHAR(GA.JOURNAL_DATE, 'MM')),
		TO_NUMBER(TO_CHAR(GA.JOURNAL_DATE, 'YYYY')) * 100 + TO_NUMBER(TO_CHAR(GA.JOURNAL_DATE, 'MM')),
		GA.JOURNAL_ID,
		L.CURRENCY_CD,
		CASE
			WHEN L.R12_ENTITY IN('5773', '5588') THEN 'CAD'
			ELSE 'USD'
			END;

COMMIT;

-- 12,191 rows inserted. 120 seconds

DELETE FROM MAP_SALES_DATA_68 WHERE QUERY_SOURCE = 'P/S LEDGER';
INSERT INTO MAP_SALES_DATA_68
SELECT
		/*+ NO_CPU_COSTING */
		'P/S LEDGER' AS QUERY_SOURCE,
		PS.BUSINESS_UNIT AS BU,
		SUM(PS.POSTED_TOTAL_AMT) AS REVENUE_AMOUNT,
		SUM(100 *(PS.POSTED_TOTAL_AMT - TRUNC(PS.POSTED_TOTAL_AMT))) AS REVENUE_AMOUNT_DEC,
		PS.R12_ACCOUNT AS GL_ACCOUNT,
		PS.R12_LOCATION AS DEPT_ID,
		DP.DESCR AS DEPT_DESCR,
		PS.PS_PRODUCT AS MANF_PROD_ID,
		PR.DESCR AS MANF_PROD_DESCR,
		PS.R12_PRODUCT AS DIST_GL_PRODUCT,
		NVL(PX.PRODUCT_CATEGORY, 'INVALID PROD CODE - '|| PS.R12_PRODUCT) AS RESERVE_GROUP,
		TO_DATE('15-' || PS.ACCOUNTING_PERIOD || '-' || PS.FISCAL_YEAR, 'DD-MM-YYYY') AS JRNL_DATE,
		PS.FISCAL_YEAR AS JRNL_YEAR,
		PS.ACCOUNTING_PERIOD AS JRNL_MONTH,
		PS.FISCAL_YEAR * 100 + PS.ACCOUNTING_PERIOD AS JRNL_YEAR_MONTH,
		'ZZZZZZ' AS JRNL_ID,
		PS.CURRENCY_CD AS CURRENCY,
		CASE
			WHEN PS.BUSINESS_UNIT = 'CSD' THEN 'USD'
			WHEN PS.BUSINESS_UNIT = 'CAN' THEN 'CAD'
			ELSE ''
			END AS COUNTRY_INDICATOR
	FROM
		R12_LEDGER2_PS PS
	INNER JOIN R12_ACCOUNT_FILTER_UPD AFU
		ON AFU.R12_ACCOUNT = PS.R12_ACCOUNT
	LEFT OUTER JOIN R12_TRANE_PRODUCTS_PS PR
		ON PS.R12_PRODUCT = PR.R12_PRODUCT
	LEFT OUTER JOIN R12_TRANE_LOCATIONS DP
		ON PS.R12_LOCATION = DP.R12_LOCATION
	INNER JOIN OTR_PROD_CODE_XREF_RCPO PX
		ON PS.PS_PRODUCT = PX.MANF_PROD_CODE
		AND PS.BUSINESS_UNIT = PX.GL_LEDGER
	WHERE
		PS.FISCAL_YEAR IN('2000', '2001', '2002')
		AND PS.ACCOUNTING_PERIOD <= '12'
		AND((PS.PS_ACCOUNT = 'NA'
		AND AFU.EQUAL_700000 = 'Y')
		OR(PS.PS_ACCOUNT <> 'NA'
		AND PS.PS_ACCOUNT = '700000'))
		AND PS.LEDGER = 'ACTUALS'
		/* 2-5 year Warranty Project Rule */
		AND PX.TWO_FIVE = 'Y'
	GROUP BY
		PS.BUSINESS_UNIT,
		PS.R12_ACCOUNT,
		PS.R12_LOCATION,
		DP.DESCR,
		PS.PS_PRODUCT,
		PS.R12_PRODUCT,
		PR.DESCR,
		PX.PRODUCT_CATEGORY,
		TO_DATE('15-' || PS.ACCOUNTING_PERIOD || '-' || PS.FISCAL_YEAR, 'DD-MM-YYYY'),
		PS.FISCAL_YEAR,
		PS.ACCOUNTING_PERIOD,
		PS.FISCAL_YEAR * 100 + PS.ACCOUNTING_PERIOD,
		PS.CURRENCY_CD,
		CASE
			WHEN PS.BUSINESS_UNIT = 'CSD' THEN 'USD'
			WHEN PS.BUSINESS_UNIT = 'CAN' THEN 'CAD'
			ELSE ''
			END;
			
COMMIT;

-- 756 rows inserted. 15 seconds

/* 4th -New Query to get the Residential data for Year 2000 and 2001, on 10/01/07  */
DELETE FROM MAP_SALES_DATA_68 WHERE QUERY_SOURCE = 'CS_LD';
INSERT INTO MAP_SALES_DATA_68
SELECT
		/*+ NO_CPU_COSTING */
		DISTINCT
		'CS_LD' AS QUERY_SOURCE,
		RS_LEDGER.BUSINESS_UNIT AS BU,
		SUM(RS_LEDGER.SALES_TOTAL) AS REVENUE_AMOUNT,
		SUM(100 *(RS_LEDGER.SALES_TOTAL - TRUNC(RS_LEDGER.SALES_TOTAL))) AS REVENUE_AMOUNT_DEC,
		RS_LEDGER.R12_ACCOUNT
		AS GL_ACCOUNT,
		RS_LEDGER.R12_LOCATION
		AS DEPT_ID,
		DP.DESCR AS DEPT_DESCR,
		RS_LEDGER.PS_PRODUCT_ID
		AS MANF_PROD_ID,
		PR.DESCR AS MANF_PROD_DESCR,
		RS_LEDGER.R12_PRODUCT
		AS DIST_GL_PRODUCT,
		NVL(PX.PRODUCT_CATEGORY, 'INVALID PROD CODE - ' || RS_LEDGER.R12_PRODUCT) AS RESERVE_GROUP,
		TO_DATE('15-' || RS_LEDGER.ACCOUNTING_PERIOD || '-' || RS_LEDGER.ACCOUNTING_YEAR, 'DD-MM-YYYY') AS JRNL_DATE,
		RS_LEDGER.ACCOUNTING_YEAR AS JRNL_YEAR,
		RS_LEDGER.ACCOUNTING_PERIOD AS JRNL_MONTH,
		RS_LEDGER.ACCOUNTING_YEAR * 100 + RS_LEDGER.ACCOUNTING_PERIOD AS JRNL_YEAR_MONTH,
		'ZZZZZZ' AS JRNL_ID,
		SUBSTR('', 3) AS CURRENCY,
		CASE
			WHEN RS_LEDGER.R12_ENTITY IN('5773', '5588') THEN 'CAD'
			ELSE 'USD'
			END AS COUNTRY_INDICATOR
	FROM
		R12_COM_SALES_RS_LEDGER RS_LEDGER
	INNER JOIN R12_ACCOUNT_FILTER_UPD AFU
		ON AFU.R12_ACCOUNT = RS_LEDGER.R12_ACCOUNT
	LEFT OUTER JOIN R12_TRANE_PRODUCTS_PS PR
		ON RS_LEDGER.R12_PRODUCT = PR.R12_PRODUCT 
	LEFT OUTER JOIN R12_TRANE_LOCATIONS DP
		ON RS_LEDGER.R12_LOCATION = DP.R12_LOCATION
	INNER JOIN OTR_PROD_CODE_XREF_RCPO PX
		ON RS_LEDGER.PS_PRODUCT_ID = PX.MANF_PROD_CODE AND RS_LEDGER.BUSINESS_UNIT = PX.GL_LEDGER
	WHERE
		PX.TWO_FIVE = 'Y'
		AND((RS_LEDGER.PS_ACCOUNT = 'NA'
		AND AFU.EQUAL_700000 = 'Y')
		OR(RS_LEDGER.PS_ACCOUNT <> 'NA'
		AND RS_LEDGER.PS_ACCOUNT = '700000'))
		AND RS_LEDGER.LEDGER = 'ACTUALS'
		AND RS_LEDGER.ACCOUNTING_PERIOD <= '12'
		AND RS_LEDGER.ACCOUNTING_YEAR IN('2000', '2001')
	GROUP BY
		RS_LEDGER.BUSINESS_UNIT,
		RS_LEDGER.R12_ACCOUNT,
		RS_LEDGER.R12_LOCATION,
		DP.DESCR,
		RS_LEDGER.PS_PRODUCT_ID,
		RS_LEDGER.R12_PRODUCT,
		PR.DESCR,
		RS_LEDGER.R12_PRODUCT,
		PX.PRODUCT_CATEGORY,
		TO_DATE('15-' || RS_LEDGER.ACCOUNTING_PERIOD || '-' || RS_LEDGER.ACCOUNTING_YEAR, 'DD-MM-YYYY'),
		RS_LEDGER.ACCOUNTING_YEAR,
		RS_LEDGER.ACCOUNTING_PERIOD,
		RS_LEDGER.ACCOUNTING_YEAR * 100 + RS_LEDGER.ACCOUNTING_PERIOD,
		CASE
			WHEN RS_LEDGER.R12_ENTITY IN('5773', '5588') THEN 'CAD'
			ELSE 'USD'
			END;

COMMIT;

-- 386 rows inserted. 0 seconds

/*- 5TH QUERY 5/1 */
DELETE FROM MAP_SALES_DATA_68 WHERE QUERY_SOURCE = 'PBS';
INSERT INTO MAP_SALES_DATA_68
SELECT
		/*+ NO_CPU_COSTING */
		'PBS' AS QUERY_SOURCE,
		BUSINESS_UNIT AS BU,
		SUM(P7_TOTAL) AS REVENUE_AMOUNT,
		SUM(100 *(P7_TOTAL - TRUNC(P7_TOTAL))) AS REVENUE_AMOUNT_DEC,
		GL_ACCOUNT AS GL_ACCOUNT,
		DEPTID AS DEPT_ID,
		DEPT_DESCR,
		PRODCODE AS MANF_PROD_ID,
		PROD_DESCR AS MANF_PROD_DESCR,
		GL_PRODCODE AS DIST_GL_PRODUCT,
		NVL(RESERVE_GROUP, 'LARGE') AS RESERVE_GROUP,
		JRNL_DATE AS JRNL_DATE,
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'YYYY')) AS JRNL_YEAR,
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'MM')) AS JRNL_MONTH,
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'YYYY')) * 100 + TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'MM')) AS JRNL_YEAR_MONTH,
		JRNL_ID AS JRNL_ID,
		CURRENCY AS CURRENCY,
		NATION_CURR AS COUNTRY_INDICATOR
	FROM
		(
			SELECT
					/*+ NO_CPU_COSTING */
					D.R12_ENTITY AS BUSINESS_UNIT,
					D.INVOICE AS INVOICE,
					D.LINE_SEQ_NUM AS SEQ_NUM,
					D.ACCT_ENTRY_TYPE AS ENTRY_TYPE,
					D.JOURNAL_ID AS JRNL_ID,
					D.JOURNAL_DATE AS JRNL_DATE,
					D.R12_ACCOUNT AS GL_ACCOUNT,
					D.MONETARY_AMOUNT AS P7_TOTAL,
					D.R12_LOCATION AS DEPTID,
					DP.DESCR AS DEPT_DESCR,
					PR.DESCR AS PROD_DESCR,
					X.PRODUCT_CATEGORY AS RESERVE_GROUP,
					A.MANF_PROD_ID AS PRODCODE,
					CASE
						WHEN D.R12_PRODUCT IN('41204', '41198') THEN '41204'
						ELSE D.R12_PRODUCT
						END AS GL_PRODCODE,
					D.CURRENCY_CD AS CURRENCY,
					CASE
						WHEN D.R12_ENTITY IN('5773', '5588') THEN 'CAD'
						ELSE 'USD'
						END AS NATION_CURR
				FROM
					R12_BI_LINE_PSB A
				INNER JOIN R12_BI_ACCT_ENTRY_PSB D
					ON D.LINE_SEQ_NUM = A.LINE_SEQ_NUM
					AND D.INVOICE = A.INVOICE AND D.BUSINESS_UNIT = A.BUSINESS_UNIT AND D.CUSTOMER_TRX_ID = A.CUSTOMER_TRX_ID
				INNER JOIN R12_BI_HDR_PSB B
					ON D.INVOICE = B.INVOICE AND D.BUSINESS_UNIT = B.PS_BUSINESS_UNIT AND D.CUSTOMER_TRX_ID = B.CUSTOMER_TRX_ID
				INNER JOIN R12_TRNBI_BI_HDR_PSB C
					ON D.INVOICE = C.INVOICE AND D.BUSINESS_UNIT = C.BUSINESS_UNIT AND D.CUSTOMER_TRX_ID = C.CUSTOMER_TRX_ID
				INNER JOIN R12_ACCOUNT_FILTER_UPD AFU 
					ON AFU.R12_ACCOUNT = D.R12_ACCOUNT
				INNER JOIN OTR_PROD_CODE_XREF_RCPO X
					ON A.MANF_PROD_ID = X.MANF_PROD_CODE
				LEFT OUTER JOIN R12_TRANE_PRODUCTS_PS PR
					ON D.R12_PRODUCT = PR.R12_PRODUCT
				LEFT OUTER JOIN R12_TRANE_LOCATIONS DP
					ON D.R12_LOCATION = DP.R12_LOCATION
				WHERE
					D.JOURNAL_DATE BETWEEN TO_DATE('03/01/2006', 'MM/DD/YYYY') AND LAST_DAY(ADD_MONTHS(SYSDATE, - 1))
					AND D.PS_ACCOUNT = '700000'
					AND B.BILL_SOURCE_ID = 'PBS'
					AND C.TRNBI_PROJECT_TYPE = '7'
					AND X.GL_LEDGER = 'CSD'
					AND X.TWO_FIVE = 'Y'
					AND D.LEDGER = 'ACTUALS' 
					AND D.PS_PRODUCT <> '804180'
					AND D.PS_PRODUCT <> '804120'
					AND D.PS_PRODUCT <> '804190'
		)
	GROUP BY
		BUSINESS_UNIT,
		GL_ACCOUNT,
		DEPTID,
		DEPT_DESCR,
		PROD_DESCR,
		PRODCODE,
		GL_PRODCODE,
		NVL(RESERVE_GROUP, 'LARGE'),
		JRNL_DATE,
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'YYYY')),
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'MM')),
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'YYYY')) * 100 + TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'MM')),
		JRNL_ID,
		CURRENCY,
		NATION_CURR;

COMMIT;

-- 80,076 rows inserted. 1637 seconds, 27 mins

DELETE FROM MAP_SALES_DATA_68 WHERE QUERY_SOURCE = 'P21';
INSERT INTO MAP_SALES_DATA_68
SELECT
		/*+ NO_CPU_COSTING */
		'P21' AS QUERY_SOURCE,
		BUSINESS_UNIT AS BU,
		SUM(P7_TOTAL) AS REVENUE_AMOUNT,
		SUM(100 *(P7_TOTAL - TRUNC(P7_TOTAL))) AS REVENUE_AMOUNT_DEC,
		GL_ACCOUNT AS GL_ACCOUNT,
		DEPTID AS DEPT_ID,
		DEPT_DESCR AS DEPT_DESCR,
		PRODCODE AS MANF_PROD_ID,
		PROD_DESCR AS MANF_PROD_DESCR,
		GL_PRODCODE AS DIST_GL_PRODUCT,
		NVL(RESERVE_GROUP, 'LARGE') AS RESERVE_GROUP,
		JRNL_DATE AS JRNL_DATE,
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'YYYY')) AS JRNL_YEAR,
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'MM')) AS JRNL_MONTH,
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'YYYY')) * 100 + TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'MM')) AS JRNL_YEAR_MONTH,
		JRNL_ID AS JRNL_ID,
		CURRENCY AS CURRENCY,
		NATION_CURR AS COUNTRY_INDICATOR
	FROM
		(
			SELECT
					/*+ NO_CPU_COSTING */
					D.R12_ENTITY AS BUSINESS_UNIT,
					D.INVOICE AS INVOICE,
					D.LINE_SEQ_NUM AS SEQ_NUM,
					D.ACCT_ENTRY_TYPE AS ENTRY_TYPE,
					D.JOURNAL_ID AS JRNL_ID,
					D.JOURNAL_DATE AS JRNL_DATE,
					D.R12_ACCOUNT AS GL_ACCOUNT,
					D.MONETARY_AMOUNT AS P7_TOTAL,
					D.R12_LOCATION AS DEPTID,
					DP.DESCR AS DEPT_DESCR,
					PR.DESCR AS PROD_DESCR,
					X.PRODUCT_CATEGORY AS RESERVE_GROUP,
					A.MANF_PROD_ID AS PRODCODE,
					CASE
						WHEN D.R12_PRODUCT IN('41204', '41198') THEN '41204'
						ELSE D.R12_PRODUCT
						END AS GL_PRODCODE,
					D.CURRENCY_CD AS CURRENCY,
					CASE
						WHEN D.R12_ENTITY IN('5773', '5588') THEN 'CAD'
						ELSE 'USD'
						END AS NATION_CURR
				FROM
					R12_BI_LINE_PSB A
				INNER JOIN R12_BI_ACCT_ENTRY_PSB D
					ON D.LINE_SEQ_NUM = A.LINE_SEQ_NUM
					AND D.INVOICE = A.INVOICE
					AND D.BUSINESS_UNIT = A.BUSINESS_UNIT
					AND D.CUSTOMER_TRX_ID = A.CUSTOMER_TRX_ID
				INNER JOIN R12_BI_HDR_PSB B
					ON D.INVOICE = B.INVOICE
					AND D.BUSINESS_UNIT = B.PS_BUSINESS_UNIT
					AND D.CUSTOMER_TRX_ID = B.CUSTOMER_TRX_ID
				INNER JOIN R12_TRNBI_BI_HDR_PSB C
					ON D.INVOICE = C.INVOICE
					AND D.BUSINESS_UNIT = C.BUSINESS_UNIT
					AND D.CUSTOMER_TRX_ID = C.CUSTOMER_TRX_ID
				INNER JOIN R12_ACCOUNT_FILTER_UPD AFU
					ON AFU.R12_ACCOUNT = D.R12_ACCOUNT
				INNER JOIN OTR_PROD_CODE_XREF_RCPO X
					ON A.MANF_PROD_ID = X.MANF_PROD_CODE
				LEFT OUTER JOIN R12_TRANE_PRODUCTS_PS PR
					ON D.R12_PRODUCT = PR.R12_PRODUCT
				LEFT OUTER JOIN R12_TRANE_LOCATIONS DP
					ON DP.R12_LOCATION = D.R12_LOCATION
				WHERE
					D.JOURNAL_DATE BETWEEN TO_DATE('03/01/2006', 'MM/DD/YYYY') AND LAST_DAY(ADD_MONTHS(SYSDATE, - 1))
					AND B.BILL_SOURCE_ID = 'P21'
					AND C.TRNBI_PROJECT_TYPE = '7'
					AND D.PS_DEPTID != 'NA'
					AND D.LEDGER = 'ACTUALS'
					AND X.TWO_FIVE = 'Y'
					AND X.GL_LEDGER = 'CSD'
					AND ((D.PS_ACCOUNT = 'NA' AND AFU.EQUAL_700000 = 'Y') OR (D.PS_ACCOUNT = '700000'))
					AND ((D.PS_PRODUCT <> 'NA' AND D.PS_PRODUCT <> '805100') OR (D.PS_PRODUCT = 'NA' AND D.R12_PRODUCT <> '41208'))
					AND ((D.PS_PRODUCT <> 'NA' AND D.PS_PRODUCT <> '802921') OR (D.PS_PRODUCT = 'NA' AND D.R12_PRODUCT <> '41399'))
					AND ((D.PS_PRODUCT <> 'NA' AND D.PS_PRODUCT <> '801270') OR (D.PS_PRODUCT = 'NA' AND D.R12_PRODUCT <> '41132'))
					AND ((D.PS_PRODUCT <> 'NA' AND D.PS_PRODUCT <> '803270') OR (D.PS_PRODUCT = 'NA' AND D.R12_PRODUCT <> '41499'))
					AND ((D.PS_PRODUCT <> 'NA' AND D.PS_PRODUCT <> '804140') OR (D.PS_PRODUCT = 'NA' AND D.R12_PRODUCT <> '41205'))
		)
	GROUP BY
		BUSINESS_UNIT,
		GL_ACCOUNT,
		DEPTID,
		DEPT_DESCR,
		PROD_DESCR,
		PRODCODE,
		GL_PRODCODE,
		NVL(RESERVE_GROUP, 'LARGE'),
		JRNL_DATE,
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'YYYY')),
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'MM')),
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'YYYY')) * 100 + TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'MM')),
		JRNL_ID,
		CURRENCY,
		NATION_CURR;

-- 25,712 rows inserted. 1767 seconds, 29 min

COMMIT;

-- select query_source, count(*) from MAP_SALES_DATA_68 group by QUERY_SOURCE;