-- OTR_JRNL_LN_PS
-- DR
-- ACCOUNT -> R12_ACCOUNT
-- PRODUCT -> R12_PRODUCT
-- DEPTID -> R12_LOCATION

select count(*) from OTR_JRNL_LN_PS; -- 83808283 10:10 AM MDT

CREATE TABLE "DBO"."R12_JRNL_LN_PS" (
	"BUSINESS_UNIT" VARCHAR2(5 BYTE), -- mapSalesData68
	"JOURNAL_ID" VARCHAR2(10 BYTE), -- mapSalesData68
	"JOURNAL_DATE" DATE, -- mapSalesData68
	"UNPOST_SEQ" NUMBER(*,0), -- mapSalesData68
	-- "JOURNAL_LINE" NUMBER(*,0), 
	"LEDGER" VARCHAR2(10 BYTE), -- mapSalesData68
	"PS_ACCOUNT" VARCHAR2(10 BYTE), -- mapSalesData68
	-- "ALTACCT" VARCHAR2(10 BYTE), 
	-- "OPERATING_UNIT" VARCHAR2(8 BYTE), 
	"PS_DEPTID" VARCHAR2(10 BYTE), -- mapSalesData68
	"PS_PRODUCT" VARCHAR2(6 BYTE), -- mapSalesData68
	-- "PROJECT_ID" VARCHAR2(15 BYTE), 
	-- "AFFILIATE" VARCHAR2(5 BYTE), 
	-- "SCENARIO" VARCHAR2(10 BYTE), 
	"CURRENCY_CD" VARCHAR2(3 BYTE), -- mapSalesData68
	-- "STATISTICS_CODE" VARCHAR2(3 BYTE), 
	"MONETARY_AMOUNT" NUMBER(26,3), -- mapSalesData68
	-- "MOVEMENT_FLAG" VARCHAR2(1 BYTE), 
	-- "STATISTIC_AMOUNT" NUMBER(15,2), 
	-- "JRNL_LN_REF" VARCHAR2(10 BYTE), 
	-- "SUSPENDED_LINE" NUMBER(*,0), 
	-- "LINE_DESCR" VARCHAR2(30 BYTE), 
	-- "JRNL_LINE_STATUS" VARCHAR2(1 BYTE), 
	-- "JOURNAL_LINE_DATE" DATE, 
	-- "FOREIGN_CURRENCY" VARCHAR2(3 BYTE), 
	-- "RT_TYPE" VARCHAR2(5 BYTE), 
	-- "FOREIGN_AMOUNT" NUMBER(26,3), 
	-- "RATE_DIV" NUMBER(15,8), 
	-- "RATE_MULT" NUMBER(15,8), 
	-- "PROCESS_INSTANCE" NUMBER(10,0), 
	-- "DOC_TYPE" VARCHAR2(8 BYTE), 
	-- "DOC_SEQ_NBR" VARCHAR2(12 BYTE), 
	-- "DOC_SEQ_DATE" DATE, 
	-- "DOC_SEQ_STATUS" VARCHAR2(1 BYTE), 
	-- "JRNL_LINE_SOURCE" VARCHAR2(3 BYTE), 
	-- "BUSINESS_UNIT_PC" VARCHAR2(5 BYTE), 
	-- "ACTIVITY_ID" VARCHAR2(15 BYTE), 
	-- "ANALYSIS_TYPE" VARCHAR2(3 BYTE), 
	-- "RESOURCE_TYPE" VARCHAR2(5 BYTE), 
	-- "RESOURCE_CATEGORY" VARCHAR2(5 BYTE), 
	-- "RESOURCE_SUB_CAT" VARCHAR2(5 BYTE), 
	-- "BUDGET_DT" DATE, 
	-- "BUDGET_LINE_STATUS" VARCHAR2(1 BYTE), 
	-- "CLOSING_STATUS" VARCHAR2(1 BYTE), 
	-- "ARCHIVE_FLAG" VARCHAR2(1 BYTE) DEFAULT 'N'
	R12_ENTITY VARCHAR2(5 BYTE),
	R12_ACCOUNT VARCHAR2(10 BYTE),
	R12_PRODUCT VARCHAR2(6 BYTE),
	R12_LOCATION VARCHAR2(10 BYTE),
	R12_COSTCENTER VARCHAR2(10 BYTE)
);

insert into R12_JRNL_LN_PS (
	"BUSINESS_UNIT",
	"JOURNAL_ID",
	"JOURNAL_DATE",
	"UNPOST_SEQ",
	"LEDGER",
	"ACCOUNT",
	"DEPTID",
	"PRODUCT",
	"CURRENCY_CD",
	"MONETARY_AMOUNT",
	R12_ACCOUNT,
	R12_ENTITY,
	R12_PRODUCT,
	R12_LOCATION,
	R12_COSTCENTER
)
select
	"BUSINESS_UNIT",
	"JOURNAL_ID",
	"JOURNAL_DATE",
	"UNPOST_SEQ",
	"LEDGER",
	"PS_ACCOUNT",
	"PS_DEPTID",
	"PS_PRODUCT",
	"CURRENCY_CD",
	"MONETARY_AMOUNT",
	DBO.F_GET_R12_ACCOUNT_STRING ('ACCOUNT', null, ACCOUNT, DEPTID, PRODUCT, null) as R12_ACCOUNT,
	DBO.F_GET_R12_ACCOUNT_STRING ('PRODUCT', null, ACCOUNT, DEPTID, PRODUCT, null) as R12_PRODUCT,
	DBO.F_GET_R12_ACCOUNT_STRING ('LOCATION', null, ACCOUNT, DEPTID, PRODUCT, null) as R12_LOCATION
from
OTR_JRNL_LN_PS;

