-- OTR_JRNL_HEADER_PS
-- DR

select count(*) from OTR_JRNL_HEADER_PS; -- 5826426 10:05 AM MDT

CREATE TABLE "DBO"."R12_JRNL_HEADER_PS" (
	"BUSINESS_UNIT" VARCHAR2(5 BYTE), -- mapSalesData68, mapExtendedYTD
	"JOURNAL_ID" VARCHAR2(10 BYTE), -- mapSalesData68, mapExtendedYTD
	"JOURNAL_DATE" DATE, -- mapSalesData68, mapExtendedYTD
	"UNPOST_SEQ" NUMBER(*,0), -- mapSalesData68, mapExtendedYTD
	-- "BUSINESS_UNIT_IU" VARCHAR2(5 BYTE), 
	-- "ADJUSTING_ENTRY" VARCHAR2(1 BYTE), 
	"FISCAL_YEAR" NUMBER(*,0), -- mapSalesData68, mapExtendedYTD
	-- "ACCOUNTING_PERIOD" NUMBER(*,0), 
	-- "ADB_DATE" DATE, 
	-- "LEDGER_GROUP" VARCHAR2(10 BYTE), 
	-- "LEDGER" VARCHAR2(10 BYTE), 
	-- "AUTO_GEN_LINES" VARCHAR2(1 BYTE), 
	-- "REVERSAL_CD" VARCHAR2(1 BYTE), 
	-- "REVERSAL_DATE" DATE, 
	-- "REVERSAL_ADJ_PER" NUMBER(*,0), 
	-- "REVERSAL_CD_ADB" VARCHAR2(1 BYTE), 
	-- "REVERSAL_DATE_ADB" DATE, 
	-- "JRNL_TOTAL_LINES" NUMBER(*,0), 
	-- "JRNL_TOTAL_DEBITS" NUMBER(26,3), 
	-- "JRNL_TOT_CREDITS" NUMBER(26,3), 
	-- "JRNL_NET_UNITS" NUMBER(15,2), 
	-- "SOURCE" VARCHAR2(3 BYTE), 
	-- "TRANS_REF_NUM" VARCHAR2(8 BYTE), 
	-- "JRNL_BALANCE_STAT" VARCHAR2(1 BYTE), 
	-- "CONTROL_TOTAL_STAT" VARCHAR2(1 BYTE), 
	-- "JRNL_EDIT_ERR_STAT" VARCHAR2(1 BYTE), 
	"JRNL_HDR_STATUS" VARCHAR2(1 BYTE) -- mapSalesData68, mapExtendedYTD
	-- "SUSP_RECON_STATUS" VARCHAR2(1 BYTE), 
	-- "JRNL_PROCESS_REQST" VARCHAR2(1 BYTE), 
	-- "JRNL_SUMLED_REQST" VARCHAR2(1 BYTE), 
	-- "SJE_TYPE" VARCHAR2(1 BYTE), 
	-- "SCHEDULE" VARCHAR2(10 BYTE), 
	-- "EVENT_OCCURRENCE" NUMBER(*,0), 
	-- "POSTED_DATE" DATE, 
	-- "PROCESS_INSTANCE" NUMBER(10,0), 
	-- "SOURCE_INSTANCE" NUMBER(14,4), 
	-- "TRANSACTION_DATE" DATE, 
	-- "LAST_LN_COMMITTED" NUMBER(*,0), 
	-- "OPRID" VARCHAR2(30 BYTE), 
	-- "DTTM_STAMP_SEC" DATE, 
	-- "DESCR" VARCHAR2(30 BYTE), 
	-- "CURRENCY_CD" VARCHAR2(3 BYTE), 
	-- "FOREIGN_CURRENCY" VARCHAR2(3 BYTE), 
	-- "RT_TYPE" VARCHAR2(5 BYTE), 
	-- "CUR_EFFDT" DATE, 
	-- "RATE_DIV" NUMBER(15,8), 
	-- "RATE_MULT" NUMBER(15,8), 
	-- "SYSTEM_SOURCE" VARCHAR2(3 BYTE), 
	-- "DOC_TYPE" VARCHAR2(8 BYTE), 
	-- "DOC_SEQ_NBR" VARCHAR2(12 BYTE), 
	-- "DOC_SEQ_DATE" DATE, 
	-- "DOC_SEQ_STATUS" VARCHAR2(1 BYTE), 
	-- "ACCTG_DEF_NAME" VARCHAR2(10 BYTE), 
	-- "PC_DISTRIB_STATUS" VARCHAR2(1 BYTE), 
	-- "BUDGET_HDR_STATUS" VARCHAR2(1 BYTE), 
	-- "KK_AMOUNT_TYPE" VARCHAR2(1 BYTE), 
	-- "KK_TRAN_OVER_FLAG" VARCHAR2(1 BYTE), 
	-- "KK_TRAN_OVER_OPRID" VARCHAR2(30 BYTE), 
	-- "KK_TRAN_OVER_DTTM" DATE, 
	-- "KK_SKIP" VARCHAR2(1 BYTE), 
	-- "JOURNAL_LOCKED" VARCHAR2(1 BYTE), 
	-- "PROC_PART_ID" VARCHAR2(10 BYTE), 
	-- "DESCR254" VARCHAR2(254 BYTE), 
	-- "ARCHIVE_FLAG" VARCHAR2(1 BYTE) DEFAULT 'N'
);

insert into "DBO"."R12_JRNL_HEADER_PS" (
	"BUSINESS_UNIT",
	"JOURNAL_ID",
	"JOURNAL_DATE",
	"UNPOST_SEQ",
	"FISCAL_YEAR",
	"JRNL_HDR_STATUS"
)
select
	"BUSINESS_UNIT",
	"JOURNAL_ID",
	"JOURNAL_DATE",
	"UNPOST_SEQ",
	"FISCAL_YEAR",
	"JRNL_HDR_STATUS"
from
OTR_JRNL_HEADER_PS;

