-- OTR_LEDGER2_PS
-- DR
-- ACCOUNT -> R12_ACCOUNT
-- PRODUCT -> R12_PRODUCT
-- DEPTID -> R12_LOCATION

select count(*) from OTR_LEDGER2_PS; -- 4283301 10:10 AM MDT

CREATE TABLE "DBO"."R12_LEDGER2_PS" (
	"BUSINESS_UNIT" VARCHAR2(5 BYTE), -- mapSalesData68, mapExtendedYTD, mapSalesData
	"LEDGER" VARCHAR2(10 BYTE), -- mapSalesData68, mapExtendedYTD, mapSalesData
	"PS_ACCOUNT" VARCHAR2(10 BYTE), -- mapSalesData68, mapExtendedYTD, mapSalesData
	-- "ALTACCT" VARCHAR2(10 BYTE), 
	-- "OPERATING_UNIT" VARCHAR2(8 BYTE), 
	"PS_DEPTID" VARCHAR2(10 BYTE), -- mapSalesData68, mapExtendedYTD, mapSalesData
	"PS_PRODUCT" VARCHAR2(6 BYTE), -- mapSalesData68, mapSalesData
	-- "PROJECT_ID" VARCHAR2(15 BYTE), 
	-- "AFFILIATE" VARCHAR2(5 BYTE), 
	"CURRENCY_CD" VARCHAR2(3 BYTE), -- mapSalesData68, mapSalesData
	-- "STATISTICS_CODE" VARCHAR2(3 BYTE), 
	"FISCAL_YEAR" NUMBER(38,0), -- mapSalesData68, mapExtendedYTD, mapSalesData
	"ACCOUNTING_PERIOD" NUMBER(38,0), -- mapSalesData68, mapSalesData
	"POSTED_TOTAL_AMT" NUMBER(26,3), -- mapSalesData68, mapSalesData
	"POSTED_BASE_AMT" NUMBER(26,3), -- mapExtendedYTD
	-- "POSTED_TRAN_AMT" NUMBER(26,3), 
	-- "BASE_CURRENCY" VARCHAR2(3 BYTE), 
	-- "DTTM_STAMP_SEC" DATE, 
	-- "PROCESS_INSTANCE" NUMBER(10,0)
	R12_ACCOUNT VARCHAR2(10 BYTE),
	R12_PRODUCT VARCHAR2(6 BYTE),
	R12_LOCATION VARCHAR2(10 BYTE)
);

insert into R12_LEDGER2_PS (
	"BUSINESS_UNIT",
	"LEDGER",
	"PS_ACCOUNT",
	"PS_DEPTID",
	"PS_PRODUCT",
	"CURRENCY_CD",
	"FISCAL_YEAR",
	"ACCOUNTING_PERIOD",
	"POSTED_TOTAL_AMT",
	"POSTED_BASE_AMT",
	R12_ACCOUNT,
	R12_PRODUCT,
	R12_LOCATION
)
select
	"BUSINESS_UNIT",
	"LEDGER",
	"ACCOUNT",
	"DEPTID",
	"PRODUCT",
	"CURRENCY_CD",
	"FISCAL_YEAR",
	"ACCOUNTING_PERIOD",
	"POSTED_TOTAL_AMT",
	"POSTED_BASE_AMT",
	DBO.F_GET_R12_ACCOUNT_STRING ('ACCOUNT', null, ACCOUNT, DEPTID, PRODUCT, null) as R12_ACCOUNT,
	DBO.F_GET_R12_ACCOUNT_STRING ('PRODUCT', null, ACCOUNT, DEPTID, PRODUCT, null) as R12_PRODUCT,
	DBO.F_GET_R12_ACCOUNT_STRING ('LOCATION', null, ACCOUNT, DEPTID, PRODUCT, null) as R12_LOCATION
from
OTR_LEDGER2_PS;

