-- OTR_COM_SALES_RS_LEDGER
-- DR
-- DEPT_ID -> R12_LOCATION 
-- ACCOUNT -> R12_ACCOUNT
-- PRODUCT_ID -> R12_PRODUCT  
-- notes
-- DEPT_ID is always 8300 on DRTRNT which converts to location as 9999 and costcenter as 00000
-- ACCOUNT is always 700000 on DRTRNT which converts to 411101

select count(*) from OTR_COM_SALES_RS_LEDGER; -- 1226 10:05 AM MDT
CREATE TABLE "DBO"."R12_COM_SALES_RS_LEDGER" (
	"BUSINESS_UNIT" VARCHAR2(5 BYTE), 
	"ACCOUNTING_PERIOD" NUMBER(*,0), 
	"ACCOUNTING_YEAR" NUMBER(*,0), 
	"LEDGER" VARCHAR2(10 BYTE), 
	"PS_ACCOUNT" VARCHAR2(10 BYTE), 
	"PS_DEPT_ID" VARCHAR2(10 BYTE), 
	"PS_PRODUCT_ID" VARCHAR2(15 BYTE), 
	"SALES_TOTAL" NUMBER(26,3),
	R12_ACCOUNT VARCHAR2(10 BYTE),
	R12_ENTITY VARCHAR2(5 BYTE),
	R12_LOCATION VARCHAR2(10 BYTE),
	R12_PRODUCT VARCHAR2(15 BYTE),
	R12_COSTCENTER VARCHAR2(10 BYTE)
);

insert into DBO.R12_COM_SALES_RS_LEDGER (
	BUSINESS_UNIT, -- map_sales_data68
	ACCOUNTING_PERIOD, -- map_sales_data68
	ACCOUNTING_YEAR, -- map_sales_data68
	LEDGER, -- map_sales_data68
	ACCOUNT, -- map_sales_data68
	DEPT_ID, -- map_sales_data68
	PRODUCT_ID, -- map_sales_data68
	SALES_TOTAL, -- map_sales_data68
	R12_ACCOUNT,
	R12_ENTITY,
	R12_LOCATION,
	R12_PRODUCT,
	R12_COSTCENTER
)
select
	BUSINESS_UNIT, -- map_sales_data68
	ACCOUNTING_PERIOD, -- map_sales_data68
	ACCOUNTING_YEAR, -- map_sales_data68
	LEDGER, -- map_sales_data68
	PS_ACCOUNT, -- map_sales_data68
	PS_DEPT_ID, -- map_sales_data68
	PS_PRODUCT_ID, -- map_sales_data68
	SALES_TOTAL, -- map_sales_data68
	DBO.F_GET_R12_ACCOUNT_STRING ('ACCOUNT', null, ACCOUNT, DEPT_ID, PRODUCT_ID, null) as R12_ACCOUNT,
	DBO.F_GET_R12_ACCOUNT_STRING ('LOCATION', null, ACCOUNT, DEPT_ID, PRODUCT_ID, null) as R12_LOCATION,
	DBO.F_GET_R12_ACCOUNT_STRING ('PRODUCT', null, ACCOUNT, DEPT_ID, PRODUCT_ID, null) as R12_PRODUCT
from
OTR_COM_SALES_RS_LEDGER;

