		create table map_ccn_data as
			SELECT
					/*+  no_cpu_costing */
					'SPD/Retrofit Labor/Extended Purchased Labor' AS TYPE,
					LR.CLAIM_NBR,
					LR.RETRO_ID,
					CT.CLAIM_TYPE_CODE AS CLAIM_TYPE,
					(
					CASE WHEN EXPENSE_TYPE_SCD_KEY IN(58, 60, 61)
						THEN 'MATERIAL'
						ELSE 'LABOR'
					END) AS EXPENSE_TYPE_DESCR,
					(
					CASE WHEN EXPENSE_TYPE_SCD_KEY IN(58, 60, 61)
						THEN 'MATERIAL'
						ELSE 'LABOR'
					END) AS EXPENSE_TYPE_CATG,
					LR.CHARGE_COMM_PCT,
					LR.CHARGE_COMPANY_PCT,
					LR.ALLOCATED_EXP_TYPE_AMOUNT * - 1 AS DOLLAR_AMOUNT,
					LR.STEP_NBR,
					LR.CCN_TRX_DATE_KEY,
					LR.ORIGINAL_SHIP_DATE_KEY,
					LR.FAIL_DATE_KEY,
					LR.START_DATE_KEY,
					LR.GL_ACCOUNT_SCD_KEY,
					LR.PROD_CODE_SCD_KEY,
					LR.CUST_ACCOUNT_SCD_KEY,
					LR.SUBMIT_OFFICE_SCD_KEY,
					LR.TRX_CURRENCY,
					GLA.R12_ENTITY,
					GLA.R12_ACCOUNT,
					GLA.R12_COST_CENTER,
					GLA.PS_COMPANY,
					GLA.R12_PRODUCT,
					TD.FULL_DATE,
					TD.YEAR,
					TD.MONTH,
					TD.TIME_KEY
				FROM
					WC_LABOR_ROLLUP LR
				INNER JOIN TIME_DAY TD            ON TD.TIME_KEY = LR.CCN_TRX_DATE_KEY --, EXPENSE_TYPE_SCD ET
				INNER JOIN CLAIM_TYPE_SCD CT      ON LR.CLAIM_TYPE_SCD_KEY = CT.CLAIM_TYPE_SCD_KEY
				INNER JOIN R12_GL_ACCOUNT_SCD GLA ON GLA.GL_ACCOUNT_SCD_KEY = LR.GL_ACCOUNT_SCD_KEY
					/* -SS- */
					-- -SS- NEW
				LEFT OUTER JOIN R12_ACCOUNT_FILTER_UPD AFU ON AFU.R12_ACCOUNT = GLA.R12_ACCOUNT
					-- -SS- /NEW
				WHERE
					1 = 1
					/* for 'SPD','RETROFIT LABOR','EXTD PURCHASED LABOR' only */
					AND LR.CLAIM_TYPE_SCD_KEY IN(1, 2, 9)
					AND TD.FULL_DATE BETWEEN add_months(trunc(sysdate,'YEAR'),'-72') and last_day(add_months(trunc(sysdate,'mm'),-1)) 
					-- -SS- NEW
					AND((GLA.PS_ACCOUNT = 'NA'
					AND AFU.STANDARD_WARRANTY_EXPENSE = 'Y')
					OR GLA.PS_ACCOUNT LIKE '0620%'
					OR GLA.PS_ACCOUNT LIKE '8062%')
;
					-- -SS- /NEW
					-- -SS- AND(GLA.ACCOUNT LIKE '0620%' OR GLA.ACCOUNT LIKE '8062%')
					-- AND LR.CLAIM_NBR = 8543136