/* Core Portion for Material */
SELECT
		/*+ NO_CPU_COSTING */
		MLR.CLAIM_NBR AS CLAIM_NUMBER,
		MLR.STEP_NBR AS STEP_NUMBER,
		GLA.R12_ENTITY
		-- -SS- COMPANY
		AS BUSINESS_UNIT,
		'MATERIAL' AS CLAIM_TYPE,
		CASE WHEN TD1.FULL_DATE - TD2.FULL_DATE <= 548
			THEN '<= 548 DAYS'
			ELSE '> 548 DAYS'
		END AS CONCESSION_DAYS,
		MLR.EXP_TYPE_AMOUNT * - 1 AS EXPENSE_AMOUNT,
		100 *(MLR.EXP_TYPE_AMOUNT * - 1 - TRUNC(MLR.EXP_TYPE_AMOUNT * - 1)) AS EXPENSE_AMOUNT_DEC,
		RES_PCT.EXPENSE_TYPE_CATG AS MATERIAL_LABOR,
		GLA.R12_ACCOUNT
		-- -SS- ACCOUNT
		AS GL_ACCOUNT,
		ETS.EXPENSE_TYPE_DESCR AS EXPENSE_TYPE_DESCR,
		SOS.SUBMIT_OFFICE_NAME AS OFFICE_NAME,
		GLA.R12_PRODUCT
		-- -SS- PROD_CODE
		AS GL_PROD_CODE,
		PCS.PROD_CODE AS MANF_PROD_CODE,
		SOS.COMPANY_OWNED_IND AS COMPANY_OWNED,
		CACCT.ACCOUNT_NUMBER AS CUSTOMER_NUMBER,
		CACCT.CUST_ACCT_NAME AS CUSTOMER_NAME,
		(
		CASE WHEN CACCT.CUST_CREDIT_CATG_CODE = 'Z1'
			THEN 'Y'
			ELSE 'N'
		END) AS INTERNAL_EXTERNAL,
		--CACCT.CUSTOMER_COMPANATE,
		TD3.FULL_DATE AS TRX_DATE,
		TO_CHAR(TD3.YEAR) AS TRX_YEAR,
		TO_CHAR(TD3.MONTH) AS TRX_MONTH,
		CEIL(ABS(MONTHS_BETWEEN(TD3.FULL_DATE, ADD_MONTHS(TRUNC(SYSDATE, 'MM'), - 1)))) + 1 AS INTMONTHS_TRX_TO_BASE,
		CEIL(ABS(MONTHS_BETWEEN(TD2.FULL_DATE, ADD_MONTHS(TRUNC(SYSDATE, 'MM'), - 1)))) + 1 AS INTMONTHS_SHIP_TO_BASE,
		TD2.FULL_DATE AS SHIP_DATE,
		(TD2.YEAR * 100 + TD2.MONTH) AS SHIP_YEAR_MONTH,
		/* 7/30 Jackie requested   */
		--CEIL( ( (TD3.TIME_KEY - TD2.TIME_KEY) / 30.42 ) ) + 1 AS INTMONTHS_SHIP_TO_TRX,
		0 AS INTMONTHS_SHIP_TO_TRX,
		TD.FULL_DATE AS START_DATE,
		((TD3.TIME_KEY - TD.TIME_KEY) / 30.42) AS INTMONTHS_START_TO_TRX,
		TD1.FULL_DATE AS FAIL_DATE,
		((TD3.TIME_KEY - TD1.TIME_KEY) / 30.42) AS INTMONTHS_FAIL_TO_TRX,
		MLR.TRX_CURRENCY AS CURRENCY,
		(
		CASE WHEN GLA.R12_ENTITY NOT IN('5773', '5588')
				-- -SS- ASX.NATION_CURR='USD'
			THEN 'USA'
			ELSE 'CAN'
				/* -SS-
				WHEN ASX.NATION_CURR='CAD' THEN 'CAN'
				ELSE 'CURRENCY: ' || ASX.NATION_CURR
				*/
		END) AS COUNTRY_INDICATOR
		/* new fields added 5/21/07 */
		,
		MLR.RETRO_ID AS RETROFIT_ID,
		GLA.R12_COST_CENTER
		-- -SS- COST_CENTER
		AS GL_DEPT
		/*New Logic by Jackie (6/12/07)Only for concession detail Report(All >548 days are ‘Not In Reserve no matter what) */
		,
		CASE WHEN A.CLAIM_NUMBER IS NULL
			THEN 10000 *(
				CASE WHEN TD1.FULL_DATE - TD2.FULL_DATE > 548
					THEN 0
					ELSE RES_PCT.RESERVE_PCT
				END)
			ELSE RES_PCT1.RESERVE_PCT
		END AS IN_RESERVE_PERCENT,
		ROUND((TD3.FULL_DATE - TD2.FULL_DATE) / 30.42) AS TRX_LAG,
		100 * TD3.YEAR + TD3.MONTH AS TRXYEARMONTH
		/* this rule must be in the report */
		--,(CASE WHEN TD1.FULL_DATE-TD2.FULL_DATE <=548 THEN  MLR.EXP_TYPE_AMOUNT*RES_PCT.RESERVE_PCT ELSE 0 END )*-1
		,
		0 AS EXPENSE_AMT_IN_RES--,(CASE WHEN TD1.FULL_DATE-TD2.FULL_DATE >548 THEN MLR.EXP_TYPE_AMOUNT else MLR.EXP_TYPE_AMOUNT*(1-RES_PCT.RESERVE_PCT) END)*-1   AS EXPENSE_AMT_NOT_IN_RES
		,
		0 AS EXPENSE_AMT_NOT_IN_RES
	FROM
		WC_MAT_LBR_ROLLUP MLR
	INNER JOIN EXPENSE_TYPE_SCD ET ON MLR.EXPENSE_TYPE_SCD_KEY = ET.EXPENSE_TYPE_SCD_KEY
		--, CLAIM_TYPE_SCD CT
	INNER JOIN TIME_DAY TD3          ON MLR.CCN_TRX_DATE_KEY = TD3.TIME_KEY       -- /* TD3 FOR TRX DATE */
	INNER JOIN TIME_DAY TD2          ON MLR.ORIGINAL_SHIP_DATE_KEY = TD2.TIME_KEY -- /* TD2 FOR ORIGINAL SHIP DATE */
	INNER JOIN TIME_DAY TD1          ON MLR.FAIL_DATE_KEY = TD1.TIME_KEY          -- /* TD1 FOR FAIL DATE */
	INNER JOIN TIME_DAY TD           ON MLR.START_DATE_KEY = TD.TIME_KEY          -- /* TD FOR START DATE */
	INNER JOIN CLAIM_TASK_SCD CTASKS ON MLR.CLAIM_TASK_SCD_KEY = CTASKS.CLAIM_TASK_SCD_KEY
		--,CLAIM_TYPE_SCD CTYPES
	INNER JOIN R12_GL_ACCOUNT_SCD
		/* -SS- */
		GLA                              ON MLR.GL_ACCOUNT_SCD_KEY = GLA.GL_ACCOUNT_SCD_KEY
	INNER JOIN EXPENSE_TYPE_SCD ETS   ON MLR.EXPENSE_TYPE_SCD_KEY = ETS.EXPENSE_TYPE_SCD_KEY
	INNER JOIN PROD_CODE_SCD PCS      ON MLR.PROD_CODE_SCD_KEY = PCS.PROD_CODE_SCD_KEY
	INNER JOIN CUST_ACCOUNT_SCD CACCT ON MLR.CUST_ACCOUNT_SCD_KEY = CACCT.CUST_ACCOUNT_SCD_KEY
	INNER JOIN SUBMIT_OFFICE_SCD SOS  ON MLR.SUBMIT_OFFICE_SCD_KEY = SOS.SUBMIT_OFFICE_SCD_KEY
		-- -SS- ACTUATE_SEC_XREF ASX,
	INNER JOIN DM_WAR_CSN_RSV_PCT_REF RES_PCT ON ETS.EXPENSE_TYPE_DESCR = RES_PCT.EXPENSE_TYPE_DESCR AND SOS.COMPANY_OWNED_IND = RES_PCT.COMPANY_OWNED_IND
		-- -SS- NEW
	INNER JOIN R12_ACCOUNT_FILTER_UPD AFU ON AFU.R12_ACCOUNT = GLA.R12_ACCOUNT
		-- -SS- /NEW
	LEFT OUTER JOIN UD_031_STDWTY_RSV_CLM_ADJ A     ON MLR.CLAIM_NBR = A.CLAIM_NUMBER
	LEFT OUTER JOIN DM_WAR_CSN_RSV_PCT_REF RES_PCT1 ON A.CLAIM_TYPE = RES_PCT1.CLAIM_TYPE
	WHERE
		/* for MATERIAL only */
		MLR.CLAIM_TYPE_SCD_KEY = 10
		--AND MLR.CLAIM_TYPE_SCD_KEY = CT.CLAIM_TYPE_SCD_KEY
		--AND MLR.CLAIM_TYPE_SCD_KEY = CTYPES.CLAIM_TYPE_SCD_KEY
		/* NATION CURRENCY */
		-- -SS- AND GLA.COMPANY = ASX.PSGL(+)
		/* reserve percent and lab/mat classification */
		AND 'MATERIAL' = RES_PCT.CLAIM_TYPE
		AND(
		CASE WHEN CACCT.CUST_CREDIT_CATG_CODE = 'Z1'
			THEN 'Y'
			ELSE 'N'
		END) = RES_PCT.CUST_CREDIT_CATG_CODE
		--AND TD3.FULL_DATE BETWEEN TO_DATE('04/01/2005','MM/DD/YYYY') AND TO_DATE('03/31/2007','MM/DD/YYYY')
		--AND ABS(MONTHS_BETWEEN(TD3.FULL_DATE, ADD_MONTHS(TRUNC(SYSDATE,'MM'),-1))) < 24
		--AND CT.CLAIM_TYPE_CODE ='MATERIAL'
		/* Concession specific */
		---AND (GLA.COMPANY ='CSD' or GLA.COMPANY ='CAN'   or GLA.COMPANY like 'GS%')
		--and TD3.FULL_DATE >= TO_DATE('1/1/2006','MM/DD/YYYY') and TD3.FULL_DATE < TO_DATE('6/1/2007','MM/DD/YYYY')
		AND TD3.FULL_DATE >= TO_DATE('1/1/2001', 'MM/DD/YYYY')
		-- -SS- NEW
		AND((GLA.PS_ACCOUNT = 'NA'
		AND(AFU.EQUAL_428000 = 'Y'
		OR AFU.EQUAL_710000 = 'Y'
		OR AFU.EQUAL_806300 = 'Y'))
		OR(GLA.PS_ACCOUNT <> 'NA'
		AND GLA.PS_ACCOUNT IN('710000', '428000', '806300')))
		AND MLR.CLAIM_NBR IN (9499254)
;