SELECT
		/*+   ORDERED NO_CPU_COSTING  INDEX(PR XAK1AP_135_PROJ_RESOURCE)*/
		'PUEBLO' AS QUERY_SOURCE,
		PR.R12_ENTITY AS BU, 
		CD.RESOURCE_AMOUNT AS REVENUE_AMOUNT,
		100 *(CD.RESOURCE_AMOUNT - TRUNC(CD.RESOURCE_AMOUNT)) AS REVENUE_AMOUNT_DEC,
		PR.R12_ACCOUNT AS GL_ACCOUNT, 
		PR.R12_LOCATION AS DEPT_ID,   -- -SS-- DEPTID
		PR.DESCR AS DEPT_DESCR,
		RES.TRNPC_MFG_PROD_CD AS MANF_PROD_ID,
		MPC.PRODUCT_CODE_DESCRIPTION AS MANF_PROD_DESCR,
		MPC.DIST_PROD_CODE AS DIST_GL_PRODUCT,
		'Large' AS RESERVE_GROUP,
		PR.ACCOUNTING_DT AS JRNL_DATE,
		TO_NUMBER(TO_CHAR(PR.ACCOUNTING_DT, 'YYYY')) AS JRNL_YEAR,
		TO_NUMBER(TO_CHAR(PR.ACCOUNTING_DT, 'MM')) AS JRNL_MONTH,
		TO_NUMBER(TO_CHAR(PR.ACCOUNTING_DT, 'YYYY')) * 100 + TO_NUMBER(TO_CHAR(PR.ACCOUNTING_DT, 'MM')) AS JRNL_YEAR_MONTH,
		PR.JOURNAL_ID AS JRNL_ID,
		PR.CURRENCY_CD AS CURRENCY,
		CASE
			WHEN PR.R12_ENTITY IN('5773', '5588') THEN 'CAD'
			WHEN PR.R12_ENTITY IN('5575', '5612', '5743', '9256', '9258', '9298', '9299') THEN 'USD'
			ELSE '???'
			END AS COUNTRY_INDICATOR,
		PR.R12_ENTITY
	FROM
		R12_PROJ_RESOURCE_PS PR
		INNER JOIN AP_135_TRNPC_PROJ_RES RES ON PR.BUSINESS_UNIT = RES.BUSINESS_UNIT AND PR.PROJECT_ID = RES.PROJECT_ID AND PR.RESOURCE_ID = RES.RESOURCE_ID AND PR.ACTIVITY_ID = RES.ACTIVITY_ID
		INNER JOIN AP_400_SEL_CRED_JB_CLSS_CD JBCLSCD ON PR.PROJECT_ID = CAST(JBCLSCD.CREDIT_JOB_ID AS VARCHAR2(15 BYTE))
		INNER JOIN AP_400_JOB_CODE JBCD ON JBCD.JOB_CODE_ID = JBCLSCD.JOB_CODE_ID
		INNER JOIN AP_135_TRNPC_COMM_DATA CD ON PR.BUSINESS_UNIT = CD.BUSINESS_UNIT AND PR.PROJECT_ID = CD.PROJECT_ID AND PR.RESOURCE_ID = CD.RESOURCE_ID AND PR.ACTIVITY_ID = CD.ACTIVITY_ID
		INNER JOIN AP_400_COMM_CODE CC ON CD.TRNPC_COMM_CODE = CC.COMM_CODE	AND CD.SALES_OFFICE_ID = CC.SALES_OFFICE_ID
		INNER JOIN MD_PRODUCT_CODE MPC ON RES.TRNPC_MFG_PROD_CD = MPC.PRODUCT_CODE_VALUE
			INNER JOIN MD_SECURITY_ENTITY_DRV SEC ON 1=1 AND PR.ps_BUSINESS_UNIT_GL = SEC.PS_GL AND PR.ps_DEPTID = SEC.PS_DEPT_ID
--	INNER JOIN R12_ACCOUNT_FILTER_UPD AFU ON AFU.R12_ACCOUNT = PR.R12_ACCOUNT
	WHERE
		PR.BUSINESS_UNIT IN('PCGUS', 'PCGCN')
		AND PR.ANALYSIS_TYPE = 'REV'
		AND PR.PS_ACCOUNT IN('700000', '700020')
		AND PR.GL_DISTRIB_STATUS = 'G'
		AND JBCD.JOB_CLASS_ID = 38
--		AND TRUNC(PR.ACCOUNTING_DT) >= TO_DATE('10/01/2016', 'MM/DD/YYYY') -- sr mod
--		AND TRUNC(PR.ACCOUNTING_DT) <= TO_DATE('10/31/2016', 'MM/DD/YYYY') -- sr mod
		AND PR.R12_ENTITY IN('5773', '5588', '5575', '5612', '5743', '9256', '9258', '9298', '9299') -- -SS- CAN, USA   
		AND TRUNC(PR.ACCOUNTING_DT) betweeN TO_DATE('10/24/2016', 'MM/DD/YYYY') AND TO_DATE('10/26/2016', 'MM/DD/YYYY')
		and RES.TRNPC_MFG_PROD_CD like '%169%'
;