SELECT
		/*+   ORDERED NO_CPU_COSTING  INDEX(PR XAK1AP_135_PROJ_RESOURCE)*/
		'PUEBLO' AS QUERY_SOURCE,
		PR.BUSINESS_UNIT_GL AS BU,
		(CD.RESOURCE_AMOUNT) AS REVENUE_AMOUNT,
		(100 *(CD.RESOURCE_AMOUNT - TRUNC(CD.RESOURCE_AMOUNT))) AS REVENUE_AMOUNT_DEC,
		PR.ACCOUNT GL_ACCOUNT,
		PR.DEPTID AS DEPT_ID,
		PR.DESCR AS DEPT_DESCR,
		RES.TRNPC_MFG_PROD_CD AS MANF_PROD_ID,
		MPC.PRODUCT_CODE_DESCRIPTION AS MANF_PROD_DESCR,
		MPC.DIST_PROD_CODE AS DIST_GL_PRODUCT,
		'Large' AS RESERVE_GROUP,
		PR.ACCOUNTING_DT AS JRNL_DATE,
		TO_NUMBER(TO_CHAR(PR.ACCOUNTING_DT, 'YYYY')) AS JRNL_YEAR,
		TO_NUMBER(TO_CHAR(PR.ACCOUNTING_DT, 'MM')) AS JRNL_MONTH,
		TO_NUMBER(TO_CHAR(PR.ACCOUNTING_DT, 'YYYY')) * 100 + TO_NUMBER(TO_CHAR(PR.ACCOUNTING_DT, 'MM')) AS JRNL_YEAR_MONTH,
		PR.JOURNAL_ID AS JRNL_ID,
		PR.CURRENCY_CD AS CURRENCY,
		SEC.NATION_CURRENCY AS COUNTRY_INDICATOR
	FROM
		AP_135_PROJ_RESOURCE PR
		INNER JOIN AP_135_TRNPC_PROJ_RES RES ON 1=1 AND PR.BUSINESS_UNIT = RES.BUSINESS_UNIT AND PR.PROJECT_ID = RES.PROJECT_ID	AND PR.RESOURCE_ID = RES.RESOURCE_ID AND PR.ACTIVITY_ID = RES.ACTIVITY_ID
		INNER JOIN AP_400_SEL_CRED_JB_CLSS_CD JBCLSCD ON 1=1 AND PR.PROJECT_ID = CAST(JBCLSCD.CREDIT_JOB_ID AS VARCHAR2(15 BYTE)) 
		INNER JOIN AP_400_JOB_CODE JBCD ON 1=1 AND JBCD.JOB_CODE_ID = JBCLSCD.JOB_CODE_ID
		left outer JOIN AP_135_TRNPC_COMM_DATA CD ON 1=1 AND PR.BUSINESS_UNIT = CD.BUSINESS_UNIT AND PR.PROJECT_ID = CD.PROJECT_ID AND PR.RESOURCE_ID = CD.RESOURCE_ID AND PR.ACTIVITY_ID = CD.ACTIVITY_ID
		INNER JOIN AP_400_COMM_CODE CC ON 1=1 AND CD.TRNPC_COMM_CODE = CC.COMM_CODE AND CD.SALES_OFFICE_ID = CC.SALES_OFFICE_ID
		INNER JOIN MD_SECURITY_ENTITY_DRV SEC ON 1=1 AND PR.BUSINESS_UNIT_GL = SEC.PS_GL AND PR.DEPTID = SEC.PS_DEPT_ID
		INNER JOIN MD_PRODUCT_CODE MPC ON 1=1 AND RES.TRNPC_MFG_PROD_CD = MPC.PRODUCT_CODE_VALUE
	WHERE 0=0
		AND PR.BUSINESS_UNIT IN('PCGUS', 'PCGCN')
		AND PR.ANALYSIS_TYPE = 'REV'
		AND(PR.ACCOUNT = '700000' OR PR.ACCOUNT = '700020')
		AND PR.GL_DISTRIB_STATUS = 'G'
		AND JBCD.JOB_CLASS_ID = 38
--		AND TRUNC(PR.ACCOUNTING_DT) >= TO_DATE('01/01/2007', 'MM/DD/YYYY')
--		AND TRUNC(PR.ACCOUNTING_DT) <= TO_DATE('12/31/2050', 'MM/DD/YYYY')
		AND TRUNC(PR.ACCOUNTING_DT) betweeN TO_DATE('10/24/2016', 'MM/DD/YYYY') AND TO_DATE('10/26/2016', 'MM/DD/YYYY')
		and RES.TRNPC_MFG_PROD_CD like '%169%'
;