SELECT
		/*+ NO_CPU_COSTING */
		D.BUSINESS_UNIT_GL AS BUSINESS_UNIT,
		D.INVOICE AS INVOICE,
		D.LINE_SEQ_NUM AS SEQ_NUM,
		D.ACCT_ENTRY_TYPE AS ENTRY_TYPE,
		D.JOURNAL_ID AS JRNL_ID,
		D.JOURNAL_DATE AS JRNL_DATE,
		D.ACCOUNT AS GL_ACCOUNT,
		D.MONETARY_AMOUNT AS P7_TOTAL,
		D.DEPTID AS DEPTID,
		AOL.OFFICE_NAME AS DEPT_DESCR,
		PR.DESCR AS PROD_DESCR,
		X.PRODUCT_CATEGORY AS RESERVE_GROUP,
		A.IDENTIFIER AS PRODCODE,
		CASE WHEN D.PRODUCT = '0064'
			THEN '804155'
			ELSE D.PRODUCT
		END AS GL_PRODCODE,
		D.CURRENCY_CD AS CURRENCY,
		AOL.NATION_CURR
	FROM
		OTR_BI_LINE_PSB A
	INNER JOIN OTR_BI_ACCT_ENTRY_PSB D          ON D.LINE_SEQ_NUM = A.LINE_SEQ_NUM AND D.INVOICE = A.INVOICE AND D.BUSINESS_UNIT = A.BUSINESS_UNIT
	LEFT OUTER JOIN OTR_PROD_CODE_XREF_RCPO X   ON A.IDENTIFIER = X.MANF_PROD_CODE
	LEFT OUTER JOIN OTR_TRANE_PRODUCTS_PS PR    ON D.PRODUCT = PR.PRODUCT
	LEFT OUTER JOIN ACTUATE_OFFICE_LOCATION AOL ON D.DEPTID = AOL.DEPT_ID
	WHERE
		D.JOURNAL_DATE BETWEEN TO_DATE('03/01/2006', 'MM/DD/YYYY') AND LAST_DAY(ADD_MONTHS(SYSDATE, - 1))
		AND '700000' = D.ACCOUNT
		AND 'ACTUALS' = D.LEDGER
		AND '805100' <> D.PRODUCT
		AND '802921' <> D.PRODUCT
		AND '801270' <> D.PRODUCT
		AND '803270' <> D.PRODUCT
		AND '804140' <> D.PRODUCT
		/* 2-5 year Warranty Project Rule */
		AND X.TWO_FIVE = 'Y'
		/* 2-5 year Warranty Project Rule */
		/*New Logic Adedd as of Oct27-2010 as  Jackie Req */
		--AND D.BUSINESS_UNIT = X.GL_LEDGER (+)
		-- AND D.PRODUCT = X.MANF_PROD_CODE (+)
		AND X.GL_LEDGER = 'CSD'
		/* New Logic Adedd as of Oct27-2010 as  Jackie Req  */
		AND EXISTS
		(
			SELECT
					'X'
				FROM
					OTR_BI_HDR_PSB B
				WHERE
					B.BILL_SOURCE_ID = 'P21'
					AND D.INVOICE = B.INVOICE
					AND D.BUSINESS_UNIT = B.BUSINESS_UNIT
		)
		AND EXISTS
		(
			SELECT
					'X'
				FROM
					OTR_TRNBI_BI_HDR_PSB C
				WHERE
					'7' = C.TRNBI_PROJECT_TYPE
					AND D.INVOICE = C.INVOICE
					AND D.BUSINESS_UNIT = C.BUSINESS_UNIT
		)
		and d.invoice in ('1079585X')
;

select * from OTR_BI_ACCT_ENTRY_PSB d where d.invoice in ('1079585X');
