* RETROFIT DETAIL CLAIMS QRY */
SELECT
		/*+  no_cpu_costing */
		CLAIM_NUMBER,
		STEP_NUMBER,
		BUSINESS_UNIT,
		--RESERVE_GROUP,
		CLAIM_TYPE,
		EXPENSE_AMOUNT,
		EXPENSE_AMOUNT * IN_RESERVE_PERCENT / 10000 AS EXPENSE_AMT_IN_RES,
		0 AS EXPENSE_AMOUNT_DEC,
		MATERIAL_LABOR,
		GL_ACCOUNT,
		EXPENSE_TYPE_DESCR,
		OFFICE_NAME,
		GL_PROD_CODE,
		MANF_PROD_CODE,
		COMPANY_OWNED,
		CUSTOMER_NUMBER,
		CUSTOMER_NAME,
		INTERNAL_EXTERNAL,
		TRX_DATE,
		TRX_YEAR,
		TRX_MONTH,
		INTMONTHS_TRX_TO_BASE,
		INTMONTHS_SHIP_TO_BASE,
		SHIP_DATE,
		SHIP_YEAR_MONTH,
		INTMONTHS_SHIP_TO_TRX,
		START_DATE,
		INTMONTHS_START_TO_TRX,
		FAIL_DATE,
		INTMONTHS_FAIL_TO_TRX,
		WARRANTY_TYPE,
		--WARRANTY_DURATION,
		CURRENCY,
		COUNTRY_INDICATOR,
		RETROFIT_ID,
		NEW_RESOLVED_IND AS RETROFIT_NEW_RESOLVED_IND,
		GL_DEPT
		--, 10000*(CASE WHEN PCS.PROD_CODE='0061'  or FCW.WA_RANGE<>'1' THEN 0 ELSE RES_PCT.RESERVE_PCT  END) AS IN_RESERVE_PERCENT
		,
		IN_RESERVE_PERCENT / 10000 AS IN_RESERVE_PERCENT,
		NEW_RESOLVED_IND,
		TRX_LAG,
		TRXYEARMONTH,
		0 AS EXPENSE_AMT_NOT_IN_RES
	FROM
		(
			/* Retrofit Material */
			SELECT
					/*+  no_cpu_costing   no_expand cardinality ( MLR,500)  */
					MLR.CLAIM_NBR AS CLAIM_NUMBER,
					MLR.STEP_NBR AS STEP_NUMBER,
					GLA.COMPANY AS BUSINESS_UNIT,
					PRODGRP.PRODUCT_CATEGORY AS RESERVE_GROUP,
					CTYPES.CLAIM_TYPE_DESCR AS CLAIM_TYPE,
					SUM(MLR.EXP_TYPE_AMOUNT * - 1) AS EXPENSE_AMOUNT,
					SUM(100 *(MLR.EXP_TYPE_AMOUNT * - 1 - TRUNC(MLR.EXP_TYPE_AMOUNT * - 1))) AS EXPENSE_AMOUNT_DEC,
					RES_PCT.EXPENSE_TYPE_CATG AS MATERIAL_LABOR,
					GLA.ACCOUNT AS GL_ACCOUNT,
					ETS.EXPENSE_TYPE_DESCR AS EXPENSE_TYPE_DESCR,
					SOS.SUBMIT_OFFICE_NAME AS OFFICE_NAME,
					CASE WHEN GLA.PROD_CODE IS NULL OR GLA.PROD_CODE = ''
						THEN PCS.PROD_CODE
						ELSE GLA.PROD_CODE
					END AS GL_PROD_CODE,
					PCS.PROD_CODE AS MANF_PROD_CODE,
					SOS.COMPANY_OWNED_IND AS COMPANY_OWNED,
					CACCT.ACCOUNT_NUMBER AS CUSTOMER_NUMBER,
					CACCT.CUST_ACCT_NAME AS CUSTOMER_NAME,
					(
					CASE WHEN CACCT.CUST_CREDIT_CATG_CODE = 'Z1'
						THEN 'Y'
						ELSE 'N'
					END) AS INTERNAL_EXTERNAL,
					TD3.FULL_DATE AS TRX_DATE,
					TO_CHAR(TD3.YEAR) AS TRX_YEAR,
					TO_CHAR(TD3.MONTH) AS TRX_MONTH,
					CEIL(ABS(MONTHS_BETWEEN(TD3.FULL_DATE, ADD_MONTHS(TRUNC(SYSDATE, 'MM'), - 1)))) + 1 AS INTMONTHS_TRX_TO_BASE,
					CEIL(ABS(MONTHS_BETWEEN(TD2.FULL_DATE, ADD_MONTHS(TRUNC(SYSDATE, 'MM'), - 1)))) + 1 AS INTMONTHS_SHIP_TO_BASE,
					TD2.FULL_DATE AS SHIP_DATE,
					(TD2.YEAR * 100 + TD2.MONTH) AS SHIP_YEAR_MONTH,
					CEIL(((TD3.TIME_KEY - TD2.TIME_KEY) / 30.42)) + 1 AS INTMONTHS_SHIP_TO_TRX,
					TD.FULL_DATE AS START_DATE,
					((TD3.TIME_KEY - TD.TIME_KEY) / 30.42) AS INTMONTHS_START_TO_TRX,
					TD1.FULL_DATE AS FAIL_DATE,
					((TD3.TIME_KEY - TD1.TIME_KEY) / 30.42) AS INTMONTHS_FAIL_TO_TRX,
					(
					CASE WHEN TD1.FULL_DATE = TO_DATE('1/1/1900', 'MM/DD/YYYY') OR TD1.FULL_DATE IS NULL
						THEN 'NO'
						ELSE FCW.WA_POLICY_TYPE
					END) AS WARRANTY_TYPE,
					(
					CASE                                   WHEN FCW.WA_RANGE = '1'
						THEN '1st Year Standard Warranty'     WHEN FCW.WA_RANGE = '2'
						THEN '2nd-5th Year Standard Warranty' WHEN FCW.WA_RANGE = '5'
						THEN '> 5th Year Standard Warranty'
						ELSE 'Out of Standard Warranty'
					END) AS WARRANTY_DURATION,
					MLR.TRX_CURRENCY AS CURRENCY,
					(
					CASE       WHEN ASX.NATION_CURR = 'USD'
						THEN 'USA'WHEN ASX.NATION_CURR = 'CAD'
						THEN 'CAN'
						ELSE 'CURRENCY: ' ||ASX.NATION_CURR
					END) AS COUNTRY_INDICATOR,
					MLR.RETRO_ID AS RETROFIT_ID,
					GLA.COST_CENTER AS GL_DEPT
					--, 10000*(CASE WHEN PCS.PROD_CODE='0061'  or FCW.WA_RANGE<>'1' THEN 0 ELSE RES_PCT.RESERVE_PCT  END) AS IN_RESERVE_PERCENT
					,
					(
					CASE WHEN A.CLAIM_NUMBER IS NULL
						THEN 10000 *(
							CASE WHEN(PCS.PROD_CODE IN('0054', '0197')) OR(RD.NEW_RESOLVED_IND = 'R' AND RD.SPECIFIC_RESERVE_IND = 'Y' OR RD.PCT_100_RECOVERY_IND = 'Y')
								THEN 0
								ELSE RES_PCT.RESERVE_PCT
							END)
						ELSE RES_PCT1.RESERVE_PCT
					END) AS IN_RESERVE_PERCENT,
					RD.NEW_RESOLVED_IND,
					ROUND((TD3.FULL_DATE - TD2.FULL_DATE) / 30.42) AS TRX_LAG,
					100 * TD3.YEAR + TD3.MONTH AS TRXYEARMONTH,
					0 AS EXPENSE_AMT_IN_RES,
					0 AS EXPENSE_AMT_NOT_IN_RES
				FROM
					WC_MAT_LBR_ROLLUP MLR,
					EXPENSE_TYPE_SCD ET,
					DM_FAL_CLAIMS_WARRANTY_XRF FCW,
					TIME_DAY TD3,
					TIME_DAY TD2,
					TIME_DAY TD1,
					TIME_DAY TD,
					CLAIM_TASK_SCD CTASKS,
					CLAIM_TYPE_SCD CTYPES,
					GL_ACCOUNT_SCD GLA,
					EXPENSE_TYPE_SCD ETS,
					PROD_CODE_SCD PCS,
					CUST_ACCOUNT_SCD CACCT,
					SUBMIT_OFFICE_SCD SOS,
					PROD_CODE_XREF_RCPO_DR PRODGRP
					--,OTR_PROD_CODE_XREF_RCPO@DR_INTFC_DW.LAX.TRANE.COM PRODGRP
					,
					ACTUATE_SEC_XREF ASX,
					UD_031_RETROFIT_RULES RES_PCT,
					UD_031_RETROFIT_RULES RES_PCT1,
					UD_031_STDWTY_RSV_CLM_ADJ A
					--, DM_WAR_CSN_RSV_PCT_REF RES_PCT
					,
					UD_031_RETROFIT_ID RD
				WHERE
					1 = 1
					AND MLR.CLAIM_TYPE_SCD_KEY = 3
					AND MLR.EXPENSE_TYPE_SCD_KEY = ET.EXPENSE_TYPE_SCD_KEY
					AND MLR.CLAIM_NBR = FCW.CLAIM_NBR (+)
					AND MLR.DETAIL_NBR = FCW.DETAIL_NBR (+)
					AND MLR.STEP_NBR = FCW.STEP_NBR(+)
					AND MLR.CCN_TRX_DATE_KEY = TD3.TIME_KEY
					AND MLR.ORIGINAL_SHIP_DATE_KEY = TD2.TIME_KEY
					AND MLR.FAIL_DATE_KEY = TD1.TIME_KEY
					AND MLR.START_DATE_KEY = TD.TIME_KEY
					AND MLR.CLAIM_TASK_SCD_KEY = CTASKS.CLAIM_TASK_SCD_KEY
					AND MLR.CLAIM_TYPE_SCD_KEY = CTYPES.CLAIM_TYPE_SCD_KEY
					AND MLR.GL_ACCOUNT_SCD_KEY = GLA.GL_ACCOUNT_SCD_KEY
					AND MLR.EXPENSE_TYPE_SCD_KEY = ETS.EXPENSE_TYPE_SCD_KEY
					AND MLR.PROD_CODE_SCD_KEY = PCS.PROD_CODE_SCD_KEY
					AND MLR.CUST_ACCOUNT_SCD_KEY = CACCT.CUST_ACCOUNT_SCD_KEY
					AND MLR.SUBMIT_OFFICE_SCD_KEY = SOS.SUBMIT_OFFICE_SCD_KEY
					AND GLA.COMPANY = ASX.PSGL(+)
					AND CTYPES.CLAIM_TYPE_DESCR = RES_PCT.CLAIM_TYPE
					AND ETS.EXPENSE_TYPE_DESCR = RES_PCT.EXPENSE_TYPE_DESCR
					AND SOS.COMPANY_OWNED_IND = RES_PCT.COMPANY_OWNED_IND
					/* NEW_RETROFIT_ID */
					AND MLR.RETRO_ID = RD.RETROFIT_ID
					/* NEW_RETROFIT_ID */
					AND(
					CASE WHEN CACCT.CUST_CREDIT_CATG_CODE = 'Z1'
						THEN 'Y'
						ELSE 'N'
					END) = RES_PCT.CUST_CREDIT_CATG_CODE
					AND GLA.COMPANY = PRODGRP.GL_LEDGER
					AND PCS.PROD_CODE = PRODGRP.MANF_PROD_CODE
					AND PRODGRP.PRODUCT_CATEGORY IS NOT NULL
					AND TD3.FULL_DATE >= TO_DATE('1/1/2001', 'MM/DD/YYYY')
					AND TD3.FULL_DATE <= TO_DATE('12/31/2050', 'MM/DD/YYYY')
					AND(GLA.ACCOUNT LIKE '8062%'
					OR GLA.ACCOUNT LIKE '0620%')
					AND MLR.CLAIM_NBR = A.CLAIM_NUMBER (+)
					AND A.CLAIM_TYPE = RES_PCT1.CLAIM_TYPE(+)
					--and mlr.CLAIM_NBR  IN ('4410816','4496418')
				GROUP BY
					MLR.CLAIM_NBR,
					MLR.STEP_NBR,
					GLA.COMPANY,
					PRODGRP.PRODUCT_CATEGORY,
					CTYPES.CLAIM_TYPE_DESCR,
					RES_PCT.EXPENSE_TYPE_CATG,
					GLA.ACCOUNT,
					ETS.EXPENSE_TYPE_DESCR,
					SOS.SUBMIT_OFFICE_NAME,
					GLA.PROD_CODE,
					PCS.PROD_CODE,
					SOS.COMPANY_OWNED_IND,
					CACCT.ACCOUNT_NUMBER,
					CACCT.CUST_ACCT_NAME,
					(
					CASE WHEN CACCT.CUST_CREDIT_CATG_CODE = 'Z1'
						THEN 'Y'
						ELSE 'N'
					END),
					TD3.FULL_DATE,
					TO_CHAR(TD3.YEAR),
					TO_CHAR(TD3.MONTH),
					CEIL(ABS(MONTHS_BETWEEN(TD3.FULL_DATE, ADD_MONTHS(TRUNC(SYSDATE, 'MM'), - 1)))) + 1,
					CEIL(ABS(MONTHS_BETWEEN(TD2.FULL_DATE, ADD_MONTHS(TRUNC(SYSDATE, 'MM'), - 1)))) + 1,
					TD2.FULL_DATE,
					(TD2.YEAR * 100 + TD2.MONTH),
					CEIL(((TD3.TIME_KEY - TD2.TIME_KEY) / 30.42)) + 1,
					TD.FULL_DATE,
					((TD3.TIME_KEY - TD.TIME_KEY) / 30.42),
					TD1.FULL_DATE,
					((TD3.TIME_KEY - TD1.TIME_KEY) / 30.42),
					(
					CASE WHEN TD1.FULL_DATE = TO_DATE('1/1/1900', 'MM/DD/YYYY') OR TD1.FULL_DATE IS NULL
						THEN 'NO'
						ELSE FCW.WA_POLICY_TYPE
					END),
					(
					CASE                                   WHEN FCW.WA_RANGE = '1'
						THEN '1st Year Standard Warranty'     WHEN FCW.WA_RANGE = '2'
						THEN '2nd-5th Year Standard Warranty' WHEN FCW.WA_RANGE = '5'
						THEN '> 5th Year Standard Warranty'
						ELSE 'Out of Standard Warranty'
					END),
					MLR.TRX_CURRENCY,
					(
					CASE       WHEN ASX.NATION_CURR = 'USD'
						THEN 'USA'WHEN ASX.NATION_CURR = 'CAD'
						THEN 'CAN'
						ELSE 'CURRENCY: ' ||ASX.NATION_CURR
					END),
					MLR.RETRO_ID,
					GLA.COST_CENTER,
					(
					CASE WHEN A.CLAIM_NUMBER IS NULL
						THEN 10000 *(
							CASE WHEN(PCS.PROD_CODE IN('0054', '0197')) OR(RD.NEW_RESOLVED_IND = 'R' AND RD.SPECIFIC_RESERVE_IND = 'Y' OR RD.PCT_100_RECOVERY_IND = 'Y')
								THEN 0
								ELSE RES_PCT.RESERVE_PCT
							END)
						ELSE RES_PCT1.RESERVE_PCT
					END),
					RD.NEW_RESOLVED_IND,
					ROUND((TD3.FULL_DATE - TD2.FULL_DATE) / 30.42),
					100 * TD3.YEAR + TD3.MONTH
			UNION ALL

			/* Retrofit Labor */
			SELECT
					/*+  no_cpu_costing   no_expand cardinality ( CCN_DATA,500)  */
					CCN_DATA.CLAIM_NBR AS CLAIM_NUMBER,
					CCN_DATA.STEP_NBR AS STEP_NUMBER,
					GLA.COMPANY AS BUSINESS_UNIT,
					PRODGRP.PRODUCT_CATEGORY AS RESERVE_GROUP,
					CCN_DATA.CLAIM_TYPE AS CLAIM_TYPE,
					CCN_DATA.DOLLAR_AMOUNT AS EXPENSE_AMOUNT,
					100 *(CCN_DATA.DOLLAR_AMOUNT - TRUNC(CCN_DATA.DOLLAR_AMOUNT)) AS EXPENSE_AMOUNT_DEC,
					CCN_DATA.EXPENSE_TYPE_CATG AS MATERIAL_LABOR,
					GLA.ACCOUNT AS GL_ACCOUNT,
					CCN_DATA.EXPENSE_TYPE_DESCR AS EXPENSE_TYPE_DESCR,
					SOS.SUBMIT_OFFICE_NAME AS OFFICE_NAME,
					CASE WHEN GLA.PROD_CODE IS NULL OR GLA.PROD_CODE = ''
						THEN PCS.PROD_CODE
						ELSE GLA.PROD_CODE
					END AS GL_PROD_CODE,
					PCS.PROD_CODE AS MANF_PROD_CODE,
					SOS.COMPANY_OWNED_IND AS COMPANY_OWNED,
					CACCT.ACCOUNT_NUMBER AS CUSTOMER_NUMBER,
					CACCT.CUST_ACCT_NAME AS CUSTOMER_NAME,
					(
					CASE WHEN CACCT.CUST_CREDIT_CATG_CODE = 'Z1'
						THEN 'Y'
						ELSE 'N'
					END) AS INTERNAL_EXTERNAL,
					TD3.FULL_DATE AS TRX_DATE,
					TO_CHAR(TD3.YEAR) AS TRX_YEAR,
					TO_CHAR(TD3.MONTH) AS TRX_MONTH,
					CEIL(ABS(MONTHS_BETWEEN(TD3.FULL_DATE, ADD_MONTHS(TRUNC(SYSDATE, 'MM'), - 1)))) + 1 AS INTMONTHS_TRX_TO_BASE,
					CEIL(ABS(MONTHS_BETWEEN(TD2.FULL_DATE, ADD_MONTHS(TRUNC(SYSDATE, 'MM'), - 1)))) + 1 AS INTMONTHS_SHIP_TO_BASE,
					TD2.FULL_DATE AS SHIP_DATE,
					(TD2.YEAR * 100 + TD2.MONTH) AS SHIP_YEAR_MONTH,
					CEIL(((TD3.TIME_KEY - TD2.TIME_KEY) / 30.42)) + 1 AS INTMONTHS_SHIP_TO_TRX,
					TD.FULL_DATE AS START_DATE,
					((TD3.TIME_KEY - TD.TIME_KEY) / 30.42) AS INTMONTHS_START_TO_TRX,
					TD1.FULL_DATE AS FAIL_DATE,
					((TD3.TIME_KEY - TD1.TIME_KEY) / 30.42) AS INTMONTHS_FAIL_TO_TRX,
					(
					CASE WHEN TD1.FULL_DATE = TO_DATE('1/1/1900', 'MM/DD/YYYY') OR TD1.FULL_DATE IS NULL
						THEN 'NO'
						ELSE FCW.WA_POLICY_TYPE
					END) AS WARRANTY_TYPE,
					(
					CASE WHEN CCN_DATA.CLAIM_TYPE = 'EXTD PURCHASED LABOR'
						THEN 'Out of Standard Warranty'
						ELSE(
							CASE                                   WHEN FCW.WA_RANGE = '1'
								THEN '1st Year Standard Warranty'     WHEN FCW.WA_RANGE = '2'
								THEN '2nd-5th Year Standard Warranty' WHEN FCW.WA_RANGE = '5'
								THEN '> 5th Year Standard Warranty'
								ELSE 'Out of Standard Warranty'
							END)
					END) AS WARRANTY_DURATION,
					CCN_DATA.TRX_CURRENCY AS CURRENCY,
					(
					CASE       WHEN ASX.NATION_CURR = 'USD'
						THEN 'USA'WHEN ASX.NATION_CURR = 'CAD'
						THEN 'CAN'
						ELSE 'CURRENCY: ' ||ASX.NATION_CURR
					END) AS COUNTRY_INDICATOR,
					CCN_DATA.RETRO_ID AS RETROFIT_ID,
					GLA.COST_CENTER AS GL_DEPT,
					(
					CASE WHEN A.CLAIM_NUMBER IS NULL
						THEN 10000 *(
							CASE WHEN(PCS.PROD_CODE IN('0054', '0197')) OR(RD.NEW_RESOLVED_IND = 'R' AND RD.SPECIFIC_RESERVE_IND = 'Y' OR RD.PCT_100_RECOVERY_IND = 'Y')
								THEN 0
								ELSE RES_PCT.RESERVE_PCT
							END)
						ELSE RES_PCT1.RESERVE_PCT
					END) AS IN_RESERVE_PERCENT,
					RD.NEW_RESOLVED_IND,
					ROUND((TD3.FULL_DATE - TD2.FULL_DATE) / 30.42) AS TRX_LAG,
					100 * TD3.YEAR + TD3.MONTH AS TRXYEARMONTH,
					0 AS EXPENSE_AMT_IN_RES,
					0 AS EXPENSE_AMT_NOT_IN_RES
				FROM
					(
						/* THIS IS THE CORE PORTION FOR  CLAIM TYPE TO RETRIEVE EXPENSE RELATED INFORMATION */
						SELECT
								'SPD/Retrofit Labor/Extended Purchased Labor' AS TYPE,
								LR.CLAIM_NBR,
								LR.RETRO_ID,
								CT.CLAIM_TYPE_CODE AS CLAIM_TYPE,
								(
								CASE WHEN EXPENSE_TYPE_SCD_KEY IN(58, 60, 61)
									THEN 'MATERIAL'
									ELSE 'LABOR'
								END) AS EXPENSE_TYPE_DESCR,
								(
								CASE WHEN EXPENSE_TYPE_SCD_KEY IN(58, 60, 61)
									THEN 'MATERIAL'
									ELSE 'LABOR'
								END) AS EXPENSE_TYPE_CATG,
								LR.CHARGE_COMM_PCT,
								LR.CHARGE_COMPANY_PCT,
								LR.ALLOCATED_EXP_TYPE_AMOUNT * - 1 AS DOLLAR_AMOUNT,
								LR.STEP_NBR,
								LR.CCN_TRX_DATE_KEY,
								LR.ORIGINAL_SHIP_DATE_KEY,
								LR.FAIL_DATE_KEY,
								LR.START_DATE_KEY,
								LR.GL_ACCOUNT_SCD_KEY,
								LR.PROD_CODE_SCD_KEY,
								LR.CUST_ACCOUNT_SCD_KEY,
								LR.SUBMIT_OFFICE_SCD_KEY,
								LR.TRX_CURRENCY
							FROM
								WC_LABOR_ROLLUP LR,
								TIME_DAY TD,
								CLAIM_TYPE_SCD CT,
								GL_ACCOUNT_SCD GLA
							WHERE
								1 = 1
								/* for 'RETROFIT LABOR' */
								AND LR.CLAIM_TYPE_SCD_KEY = 2
								AND TD.TIME_KEY = LR.CCN_TRX_DATE_KEY
								--AND TD.FULL_DATE>=TO_DATE('6/1/2006','MM/DD/YYYY') AND TD.FULL_DATE<TO_DATE('7/1/2007','MM/DD/YYYY')
								--AND MONTHS_BETWEEN(last_day(SYSDATE), last_day(TD.full_date))<=12
								--AND MONTHS_BETWEEN(last_day(SYSDATE), last_day(TD.full_date))>=1
								AND TD.FULL_DATE >= TO_DATE('1/1/2001', 'MM/DD/YYYY')
								AND TD.FULL_DATE <= TO_DATE('12/31/2050', 'MM/DD/YYYY')
								AND GLA.GL_ACCOUNT_SCD_KEY = LR.GL_ACCOUNT_SCD_KEY
								AND LR.CLAIM_TYPE_SCD_KEY = CT.CLAIM_TYPE_SCD_KEY
								AND(GLA.ACCOUNT LIKE '8062%'
								OR GLA.ACCOUNT LIKE '0620%')
					)
					CCN_DATA,
					(
						SELECT DISTINCT CLAIM_NBR, STEP_NBR, WA_POLICY_TYPE, WA_RANGE FROM DM_FAL_CLAIMS_WARRANTY_XRF
					)
					FCW,
					TIME_DAY TD3,
					TIME_DAY TD2,
					TIME_DAY TD1,
					TIME_DAY TD,
					GL_ACCOUNT_SCD GLA,
					PROD_CODE_SCD PCS,
					CUST_ACCOUNT_SCD CACCT,
					SUBMIT_OFFICE_SCD SOS,
					PROD_CODE_XREF_RCPO_DR PRODGRP
					--,OTR_PROD_CODE_XREF_RCPO@DR_INTFC_DW.LAX.TRANE.COM PRODGRP
					,
					ACTUATE_SEC_XREF ASX,
					UD_031_RETROFIT_RULES RES_PCT,
					UD_031_RETROFIT_RULES RES_PCT1,
					UD_031_STDWTY_RSV_CLM_ADJ A
					--, DM_WAR_CSN_RSV_PCT_REF RES_PCT
					,
					UD_031_RETROFIT_ID RD
				WHERE
					1 = 1
					AND CCN_DATA.CLAIM_NBR = FCW.CLAIM_NBR (+)
					AND CCN_DATA.STEP_NBR = FCW.STEP_NBR(+)
					AND CCN_DATA.CCN_TRX_DATE_KEY = TD3.TIME_KEY
					AND CCN_DATA.ORIGINAL_SHIP_DATE_KEY = TD2.TIME_KEY
					AND CCN_DATA.FAIL_DATE_KEY = TD1.TIME_KEY
					AND CCN_DATA.START_DATE_KEY = TD.TIME_KEY
					AND CCN_DATA.GL_ACCOUNT_SCD_KEY = GLA.GL_ACCOUNT_SCD_KEY
					AND CCN_DATA.PROD_CODE_SCD_KEY = PCS.PROD_CODE_SCD_KEY
					AND CCN_DATA.CUST_ACCOUNT_SCD_KEY = CACCT.CUST_ACCOUNT_SCD_KEY
					AND CCN_DATA.SUBMIT_OFFICE_SCD_KEY = SOS.SUBMIT_OFFICE_SCD_KEY
					AND GLA.COMPANY = ASX.PSGL(+)
					AND(
					CASE WHEN CCN_DATA.CLAIM_TYPE = 'EXTD PURCHASED LABOR'
						THEN 'EXTENDED PURCHASED LABOR'
						ELSE CCN_DATA.CLAIM_TYPE
					END) = RES_PCT.CLAIM_TYPE
					AND CCN_DATA.EXPENSE_TYPE_DESCR = RES_PCT.EXPENSE_TYPE_DESCR
					AND CCN_DATA.EXPENSE_TYPE_CATG = UPPER(RES_PCT.EXPENSE_TYPE_CATG)
					AND SOS.COMPANY_OWNED_IND = RES_PCT.COMPANY_OWNED_IND
					AND(
					CASE WHEN CACCT.CUST_CREDIT_CATG_CODE = 'Z1'
						THEN 'Y'
						ELSE 'N'
					END) = RES_PCT.CUST_CREDIT_CATG_CODE
					AND GLA.COMPANY = PRODGRP.GL_LEDGER
					AND PCS.PROD_CODE = PRODGRP.MANF_PROD_CODE
					AND PRODGRP.PRODUCT_CATEGORY IS NOT NULL
					/* NEW_RETROFIT_ID */
					AND CCN_DATA.RETRO_ID = RD.RETROFIT_ID
					/* NEW_RETROFIT_ID */
					AND CCN_DATA.CLAIM_NBR = A.CLAIM_NUMBER (+)
					AND A.CLAIM_TYPE = RES_PCT1.CLAIM_TYPE(+)
					--and CCN_DATA.CLAIM_NBR  IN ('4410816','4496418')
		)
	WHERE
		:?PRMCOUNTRY
		/*x*/
		/*system*/
	ORDER BY
		COUNTRY_INDICATOR,
		TRXYEARMON