/* Formatted on 2016/06/14 16:37 (Formatter Plus v4.8.8) */
-- Billing Detail Report Query
SELECT
		RCT.TRX_NUMBER TRAN_NBR,
		RCT.INVOICE_CURRENCY_CODE CURRENCY,
		RCT.PURCHASE_ORDER PO_NBR,
		RCT.TRX_DATE SHIP_DATE,
		RCT.TRX_DATE INV_DATE,
		HCA_BILLTO.ACCOUNT_NUMBER BILL_CUST_ACCT,
		HCSU_BILLTO.LOCATION BILL_TO_LOCATION,
		DECODE(RBS.NAME, 'P21', RCT.INTERFACE_HEADER_ATTRIBUTE2, NVL(RCTL.SALES_ORDER, RCTL.INTERFACE_LINE_ATTRIBUTE1)) SALES_ORD_NBR,
		NVL(APS.AMOUNT_DUE_ORIGINAL,
		(
			SELECT
					SUM(NVL(RCTL1.EXTENDED_AMOUNT, 0))
				FROM
					RA_CUSTOMER_TRX_LINES_ALL RCTL1
				WHERE
					RCTL1.CUSTOMER_TRX_ID = RCTL.CUSTOMER_TRX_ID
		)
		) HEADER_TOTAL,
		HCA_SHIPTO.ACCOUNT_NAME SHIP_CUST_ACCT,
		HCSU_SHIPTO.LOCATION SHIP_TO_LOCATION,
		HCA_BILLTO.ACCOUNT_NAME BILL_CUST_NAME,
		LOC_BILLTO.ADDRESS1 BILL_CUST_ADDRESS1,
		LOC_BILLTO.ADDRESS2 BILL_CUST_ADDRESS2,
		LOC_BILLTO.ADDRESS3 BILL_CUST_ADDRESS3,
		LOC_BILLTO.ADDRESS4 BILL_CUST_ADDRESS4,
		LOC_BILLTO.CITY BILL_CITY,
		LOC_BILLTO.STATE BILL_STATE,
		LOC_BILLTO.COUNTY BILL_COUNTY,
		LOC_BILLTO.POSTAL_CODE BILL_POSTAL,
		RCT.ATTRIBUTE8 CRD_JOB_NBR,
		RCT.INTERNAL_NOTES CRD_JOB_NAME
		--,Decode(rbs.NAME ,'ORDER ENTRY',interface_line_attribute3 , null) planned_shipment
		,
		NULL PLANNED_SHIPMENT,
		RCT.ATTRIBUTE9 PROJ_TYPE
		--,(SELECT NAME  FROM hr_organization_units_v houv  WHERE houv.organization_id = rctl.warehouse_id and rownum=1) business_unit -- for p21 it will be sale office name
		,
		NULL BUSINESS_UNIT
		--        ,Decode(rbs.NAME ,'P21' ,
		--           ( select resource_name from jtf_rs_resource_extns_tl jrt where jrt.resource_id = jrre.resource_id and rownum =1)
		--           ,(SELECT mtl.ORGANIZATION_CODE  FROM mtl_parameters mtl  WHERE mtl.organization_id = rctl.warehouse_id and rownum=1)) plant_loc
		,
		NULL PLANT_LOC,
		HCA_SHIPTO.ACCOUNT_NUMBER SHIP_CUST_NAME,
		LOC_SHIPTO.ADDRESS1 SHIP_CUST_ADDRESS1,
		LOC_SHIPTO.ADDRESS2 SHIP_CUST_ADDRESS2,
		LOC_SHIPTO.ADDRESS3 SHIP_CUST_ADDRESS3,
		LOC_SHIPTO.ADDRESS4 SHIP_CUST_ADDRESS4,
		LOC_SHIPTO.CITY SHIP_CITY,
		LOC_SHIPTO.STATE SHIP_STATE,
		LOC_SHIPTO.COUNTY SHIP_COUNTY,
		LOC_SHIPTO.POSTAL_CODE SHIP_POSTAL,
		RCT.COMMENTS HDR_NOTE,
		JRS.NAME SALES_BRANCH
		--,NVL( jrre.attribute1,DECODE (rct.org_id, 456, 'D2', 457, 'CH', 'NA')) sales_office_code
		,
		JRRE.ATTRIBUTE1 SALES_OFFICE_CODE,
		(
			SELECT
					FFVC1.DESCRIPTION
				FROM
					FND_FLEX_VALUES_VL FFVC,
					FND_FLEX_VALUES_VL FFVC1,
					FND_FLEX_VALUES_VL FFVC2,
					FND_FLEX_VALUE_NORM_HIERARCHY FFVCP1,
					FND_FLEX_VALUE_NORM_HIERARCHY FFVCP2
				WHERE
					GCC.SEGMENT2 = FFVC.FLEX_VALUE
					AND FFVC.FLEX_VALUE_SET_ID = 1014929
					AND FFVC.ENABLED_FLAG = 'Y'
					AND FFVC.FLEX_VALUE BETWEEN FFVCP1.CHILD_FLEX_VALUE_LOW AND FFVCP1.CHILD_FLEX_VALUE_HIGH
					AND FFVCP1.PARENT_FLEX_VALUE LIKE 'P%'
					--AND ffvcp1.RANGE_ATTRIBUTE ='C'
					AND FFVCP1.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND SYSDATE BETWEEN NVL(FFVCP1.START_DATE_ACTIVE, SYSDATE) AND NVL(FFVCP1.END_DATE_ACTIVE, SYSDATE)
					AND FFVCP2.PARENT_FLEX_VALUE LIKE 'P%'
					--AND ffvcp2.RANGE_ATTRIBUTE ='C'
					AND SYSDATE BETWEEN NVL(FFVCP2.START_DATE_ACTIVE, SYSDATE) AND NVL(FFVCP2.END_DATE_ACTIVE, SYSDATE)
					AND FFVCP2.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND FFVCP1.PARENT_FLEX_VALUE BETWEEN FFVCP2.CHILD_FLEX_VALUE_LOW AND FFVCP2.CHILD_FLEX_VALUE_HIGH
					AND FFVC1.ENABLED_FLAG = 'Y'
					AND FFVC2.ENABLED_FLAG = 'Y'
					AND FFVC1.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND FFVC2.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND FFVC1.FLEX_VALUE = FFVCP1.PARENT_FLEX_VALUE
					AND FFVC2.FLEX_VALUE = FFVCP2.PARENT_FLEX_VALUE
					AND ROWNUM = 1
		) SALES_DISTRICT,
		(
			SELECT
					FFVC3.DESCRIPTION
				FROM
					FND_FLEX_VALUES_VL FFVC,
					FND_FLEX_VALUES_VL FFVC1,
					FND_FLEX_VALUES_VL FFVC2,
					FND_FLEX_VALUES_VL FFVC3,
					FND_FLEX_VALUE_NORM_HIERARCHY FFVCP1,
					FND_FLEX_VALUE_NORM_HIERARCHY FFVCP2,
					FND_FLEX_VALUE_NORM_HIERARCHY FFVCP3
				WHERE
					GCC.SEGMENT2 = FFVC.FLEX_VALUE
					AND FFVC.FLEX_VALUE_SET_ID = 1014929
					AND FFVC.ENABLED_FLAG = 'Y'
					AND FFVC.FLEX_VALUE BETWEEN FFVCP1.CHILD_FLEX_VALUE_LOW AND FFVCP1.CHILD_FLEX_VALUE_HIGH
					AND FFVCP1.PARENT_FLEX_VALUE LIKE 'P%'
					--AND ffvcp1.RANGE_ATTRIBUTE ='C'
					AND FFVCP1.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND SYSDATE BETWEEN NVL(FFVCP1.START_DATE_ACTIVE, SYSDATE) AND NVL(FFVCP1.END_DATE_ACTIVE, SYSDATE)
					AND FFVCP2.PARENT_FLEX_VALUE LIKE 'P%'
					--AND ffvcp2.RANGE_ATTRIBUTE ='C'
					AND SYSDATE BETWEEN NVL(FFVCP2.START_DATE_ACTIVE, SYSDATE) AND NVL(FFVCP2.END_DATE_ACTIVE, SYSDATE)
					AND FFVCP2.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND FFVCP1.PARENT_FLEX_VALUE BETWEEN FFVCP2.CHILD_FLEX_VALUE_LOW AND FFVCP2.CHILD_FLEX_VALUE_HIGH
					AND FFVCP3.PARENT_FLEX_VALUE LIKE 'P%'
					--AND ffvcp2.RANGE_ATTRIBUTE ='C'
					AND SYSDATE BETWEEN NVL(FFVCP3.START_DATE_ACTIVE, SYSDATE) AND NVL(FFVCP3.END_DATE_ACTIVE, SYSDATE)
					AND FFVCP3.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND FFVCP2.PARENT_FLEX_VALUE BETWEEN FFVCP3.CHILD_FLEX_VALUE_LOW AND FFVCP3.CHILD_FLEX_VALUE_HIGH
					AND FFVC1.ENABLED_FLAG = 'Y'
					AND FFVC2.ENABLED_FLAG = 'Y'
					AND FFVC3.ENABLED_FLAG = 'Y'
					AND FFVC1.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND FFVC2.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND FFVC3.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND FFVC1.FLEX_VALUE = FFVCP1.PARENT_FLEX_VALUE
					AND FFVC2.FLEX_VALUE = FFVCP2.PARENT_FLEX_VALUE
					AND FFVC3.FLEX_VALUE = FFVCP3.PARENT_FLEX_VALUE
					AND ROWNUM = 1
		) TERRITORY,
		(
			SELECT
					FLL.DESCRIPTION
				FROM
					FND_FLEX_VALUES_VL FLL
				WHERE
					FLL.FLEX_VALUE_SET_ID = 1014929 -- location
					AND FLL.FLEX_VALUE = GCC.SEGMENT2
		) LOCATION_DESC,
		GCC.SEGMENT1 REC_GL_ACCT_ENTITY,
		GCC.SEGMENT2 REC_GL_ACCT_LOCATION,
		GCC.SEGMENT3 REC_GL_ACCT_COST_CENTER,
		GCC.SEGMENT4 REC_GL_ACCT_ACCOUNT,
		GCC.SEGMENT5 REC_GL_ACCT_PRODUCT,
		GCC.SEGMENT6 REC_GL_ACCT_INTERCOMPANY,
		GCC.SEGMENT7 REC_GL_ACCT_FUTURE1,
		GCC.SEGMENT8 REC_GL_ACCT_FUTURE2,
		RBS.NAME BATCH_SOURCE,
		DECODE(RBS.NAME, 'P21', RCT.INTERFACE_HEADER_ATTRIBUTE10, RCT.INTERFACE_HEADER_ATTRIBUTE2) BILLING_TYPE,
		HOU.NAME OU_NAME,
		RCT.ATTRIBUTE5 "RELATED TRX NUMBER",
		RCT.EXCHANGE_RATE,
		GJH.NAME JOURNAL_NAME,
		NULL JOURNAL_ID,
		GJB.NAME GL_BATCH_NAME,
		GJB.POSTED_DATE,
		DECODE(RBS.NAME, 'P21', DECODE(RCT.INTERFACE_HEADER_ATTRIBUTE10, 'SER', RCT.PURCHASE_ORDER, NULL), NULL) TRNBI_SRV_CALL_ID
	FROM
		RA_CUSTOMER_TRX_ALL RCT 
		left outer join AR_PAYMENT_SCHEDULES_ALL APS on APS.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
		inner join RA_CUSTOMER_TRX_LINES_ALL RCTL on RCTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
		inner join RA_BATCH_SOURCES_ALL RBS on RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID and RBS.ORG_ID = RCT.ORG_ID
		left outer join JTF_RS_SALESREPS JRS on JRS.SALESREP_ID = RCT.PRIMARY_SALESREP_ID AND JRS.ORG_ID = RCT.ORG_ID
		left outer join JTF_RS_RESOURCE_EXTNS JRRE on JRS.RESOURCE_ID = JRRE.RESOURCE_ID
		inner join HZ_CUST_ACCOUNTS HCA_BILLTO on RCT.BILL_TO_CUSTOMER_ID = HCA_BILLTO.CUST_ACCOUNT_ID
		inner join HZ_PARTIES HP_BILLTO on HCA_BILLTO.PARTY_ID = HP_BILLTO.PARTY_ID
		inner join HZ_CUST_SITE_USES_ALL HCSU_BILLTO on RCT.BILL_TO_SITE_USE_ID = HCSU_BILLTO.SITE_USE_ID
		inner join HZ_CUST_ACCT_SITES_ALL HCAS_BILLTO on HCSU_BILLTO.CUST_ACCT_SITE_ID = HCAS_BILLTO.CUST_ACCT_SITE_ID 
		inner join HZ_PARTY_SITES HPS_BILLTO on HPS_BILLTO.PARTY_SITE_ID = HCAS_BILLTO.PARTY_SITE_ID
		inner join HZ_LOCATIONS LOC_BILLTO on LOC_BILLTO.LOCATION_ID = HPS_BILLTO.LOCATION_ID
		inner join HZ_CUST_ACCOUNTS HCA_SHIPTO on NVL(RCT.SHIP_TO_CUSTOMER_ID, RCT.BILL_TO_CUSTOMER_ID) = HCA_SHIPTO.CUST_ACCOUNT_ID
		inner join HZ_PARTIES HP_SHIPTO on HCA_SHIPTO.PARTY_ID = HP_SHIPTO.PARTY_ID
		inner join HZ_CUST_SITE_USES_ALL HCSU_SHIPTO on NVL(RCT.SHIP_TO_SITE_USE_ID, RCT.BILL_TO_SITE_USE_ID) = HCSU_SHIPTO.SITE_USE_ID
		inner join HZ_CUST_ACCT_SITES_ALL HCAS_SHIPTO on HCSU_SHIPTO.CUST_ACCT_SITE_ID = HCAS_SHIPTO.CUST_ACCT_SITE_ID
		inner join HZ_PARTY_SITES HPS_SHIPTO on HPS_SHIPTO.PARTY_SITE_ID = HCAS_SHIPTO.PARTY_SITE_ID
		inner join HZ_LOCATIONS LOC_SHIPTO on LOC_SHIPTO.LOCATION_ID = HPS_SHIPTO.LOCATION_ID
		inner join RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD on RCTGD.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
		inner join HR_OPERATING_UNITS HOU on HOU.ORGANIZATION_ID = RCT.ORG_ID
		inner join XLA_DISTRIBUTION_LINKS XDL on RCTGD.CUST_TRX_LINE_GL_DIST_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1 AND RCTGD.EVENT_ID = XDL.EVENT_ID
		inner join XLA_AE_HEADERS AEH on XDL.AE_HEADER_ID = AEH.AE_HEADER_ID
		inner join XLA_AE_LINES AEL on XDL.AE_HEADER_ID = AEL.AE_HEADER_ID AND XDL.AE_LINE_NUM = AEL.AE_LINE_NUM
		inner join GL_CODE_COMBINATIONS_KFV GCC on AEL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
		left outer join GL_IMPORT_REFERENCES GIR on GIR.GL_SL_LINK_TABLE = AEL.GL_SL_LINK_TABLE AND GIR.GL_SL_LINK_ID = AEL.GL_SL_LINK_ID
		left outer join GL_JE_LINES GJL on GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
		inner join GL_JE_HEADERS GJH on GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
		inner join GL_JE_BATCHES GJB on GJB.JE_BATCH_ID = GJH.JE_BATCH_ID
		left outer join MTL_SYSTEM_ITEMS MSI on MSI.INVENTORY_ITEM_ID = RCTL.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID = NVL(RCTL.WAREHOUSE_ID, 99)
	WHERE 0=0
		AND RBS.NAME IN('P21', 'ORDER ENTRY', 'TCS MANUAL') -- batch source P21 and Order Entry only
		AND RCTL.LINE_TYPE = 'LINE'
		AND RCTL.LINE_NUMBER = 1
		AND RCT.ORG_ID IN(456, 457) -- US TCS and CA TCS  Only
		AND RCT.COMPLETE_FLAG = 'Y'
		AND NVL(RCTGD.LATEST_REC_FLAG, 'Y') = 'Y'
		AND RCTGD.ACCOUNT_CLASS = 'REC'
		AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL'
		AND XDL.APPLICATION_ID = 222
AND GJH.JE_SOURCE = 'Receivables'
;