-- Billing Accounting Report Query
SELECT --NULL zero_or_non_zero
		NVL(RCTGD.AMOUNT, 0) LINE_GL_AMT,
		NVL(RCTGD.ACCTD_AMOUNT, 0) LINE_GL_FUN_AMT,
		NULL BUSINESS_UNIT_GL,
		RBS.NAME BILL_SOURCE_ID,
		RCTGD.GL_DATE GL_DATE,
		RCT.TRX_NUMBER TRAN_NBR
		--,rctl.line_number LINE_SEQ_NUM
		,
		NULL LINE_SEQ_NUM,
		RCTT.TYPE TRX_CLASS,
		RCTT.NAME TRX_TYPE,
		HCA_BILLTO.ACCOUNT_NUMBER BILL_CUST_ACCT,
		HCA_BILLTO.ACCOUNT_NAME BILL_CUST_NAME
		-- ,rct.attribute5 linked_inv_nbr
		,
		RCT.ATTRIBUTE8 CRD_JOB_NBR,
		DECODE(RBS.NAME, 'P21', RCT.INTERFACE_HEADER_ATTRIBUTE2, NVL(RCTL.SALES_ORDER, RCTL.INTERFACE_LINE_ATTRIBUTE1)) SALES_ORD_NBR
		--,(SELECT NAME  FROM hr_organization_units_v houv  WHERE houv.organization_id = rctl.warehouse_id and rownum=1) business_unit
		,
		NULL BUSINESS_UNIT
		--        ,Decode(rbs.NAME ,'P21' ,
		--           ( select resource_name from jtf_rs_resource_extns_tl jrt where jrt.resource_id = jrre.resource_id and rownum =1)
		--           ,(SELECT NAME  FROM hr_organization_units_v houv  WHERE houv.organization_id = rctl.warehouse_id and rownum=1)) plant_loc
		,
		NULL PLANT_LOC,
		NULL PLANNED_SHIPMENT,
		(
			SELECT
					FFVC1.DESCRIPTION
				FROM
					FND_FLEX_VALUES_VL FFVC,
					FND_FLEX_VALUES_VL FFVC1,
					FND_FLEX_VALUES_VL FFVC2,
					FND_FLEX_VALUE_NORM_HIERARCHY FFVCP1,
					FND_FLEX_VALUE_NORM_HIERARCHY FFVCP2
				WHERE
					GCC_REC.SEGMENT2 = FFVC.FLEX_VALUE
					AND FFVC.FLEX_VALUE_SET_ID = 1014929
					AND FFVC.ENABLED_FLAG = 'Y'
					AND FFVC.FLEX_VALUE BETWEEN FFVCP1.CHILD_FLEX_VALUE_LOW AND FFVCP1.CHILD_FLEX_VALUE_HIGH
					AND FFVCP1.PARENT_FLEX_VALUE LIKE 'P%'
					--AND ffvcp1.RANGE_ATTRIBUTE ='C'
					AND FFVCP1.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND SYSDATE BETWEEN NVL(FFVCP1.START_DATE_ACTIVE, SYSDATE) AND NVL(FFVCP1.END_DATE_ACTIVE, SYSDATE)
					AND FFVCP2.PARENT_FLEX_VALUE LIKE 'P%'
					--AND ffvcp2.RANGE_ATTRIBUTE ='C'
					AND SYSDATE BETWEEN NVL(FFVCP2.START_DATE_ACTIVE, SYSDATE) AND NVL(FFVCP2.END_DATE_ACTIVE, SYSDATE)
					AND FFVCP2.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND FFVCP1.PARENT_FLEX_VALUE BETWEEN FFVCP2.CHILD_FLEX_VALUE_LOW AND FFVCP2.CHILD_FLEX_VALUE_HIGH
					AND FFVC1.ENABLED_FLAG = 'Y'
					AND FFVC2.ENABLED_FLAG = 'Y'
					AND FFVC1.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND FFVC2.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND FFVC1.FLEX_VALUE = FFVCP1.PARENT_FLEX_VALUE
					AND FFVC2.FLEX_VALUE = FFVCP2.PARENT_FLEX_VALUE
					AND ROWNUM = 1
		)
		SALES_DISTRICT,
		(
			SELECT
					FFVC3.DESCRIPTION
				FROM
					FND_FLEX_VALUES_VL FFVC,
					FND_FLEX_VALUES_VL FFVC1,
					FND_FLEX_VALUES_VL FFVC2,
					FND_FLEX_VALUES_VL FFVC3,
					FND_FLEX_VALUE_NORM_HIERARCHY FFVCP1,
					FND_FLEX_VALUE_NORM_HIERARCHY FFVCP2,
					FND_FLEX_VALUE_NORM_HIERARCHY FFVCP3
				WHERE
					GCC_REC.SEGMENT2 = FFVC.FLEX_VALUE
					AND FFVC.FLEX_VALUE_SET_ID = 1014929
					AND FFVC.ENABLED_FLAG = 'Y'
					AND FFVC.FLEX_VALUE BETWEEN FFVCP1.CHILD_FLEX_VALUE_LOW AND FFVCP1.CHILD_FLEX_VALUE_HIGH
					AND FFVCP1.PARENT_FLEX_VALUE LIKE 'P%'
					--AND ffvcp1.RANGE_ATTRIBUTE ='C'
					AND FFVCP1.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND SYSDATE BETWEEN NVL(FFVCP1.START_DATE_ACTIVE, SYSDATE) AND NVL(FFVCP1.END_DATE_ACTIVE, SYSDATE)
					AND FFVCP2.PARENT_FLEX_VALUE LIKE 'P%'
					--AND ffvcp2.RANGE_ATTRIBUTE ='C'
					AND SYSDATE BETWEEN NVL(FFVCP2.START_DATE_ACTIVE, SYSDATE) AND NVL(FFVCP2.END_DATE_ACTIVE, SYSDATE)
					AND FFVCP2.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND FFVCP1.PARENT_FLEX_VALUE BETWEEN FFVCP2.CHILD_FLEX_VALUE_LOW AND FFVCP2.CHILD_FLEX_VALUE_HIGH
					AND FFVCP3.PARENT_FLEX_VALUE LIKE 'P%'
					--AND ffvcp2.RANGE_ATTRIBUTE ='C'
					AND SYSDATE BETWEEN NVL(FFVCP3.START_DATE_ACTIVE, SYSDATE) AND NVL(FFVCP3.END_DATE_ACTIVE, SYSDATE)
					AND FFVCP3.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND FFVCP2.PARENT_FLEX_VALUE BETWEEN FFVCP3.CHILD_FLEX_VALUE_LOW AND FFVCP3.CHILD_FLEX_VALUE_HIGH
					AND FFVC1.ENABLED_FLAG = 'Y'
					AND FFVC2.ENABLED_FLAG = 'Y'
					AND FFVC3.ENABLED_FLAG = 'Y'
					AND FFVC1.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND FFVC2.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND FFVC3.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
					AND FFVC1.FLEX_VALUE = FFVCP1.PARENT_FLEX_VALUE
					AND FFVC2.FLEX_VALUE = FFVCP2.PARENT_FLEX_VALUE
					AND FFVC3.FLEX_VALUE = FFVCP3.PARENT_FLEX_VALUE
					AND ROWNUM = 1
		)
		TERRITORY,
		RCT.INVOICE_CURRENCY_CODE TRX_CURRENCY_CD,
		RCT.ATTRIBUTE9 PROJECT_TYPE,
		RCT.REASON_CODE CLAIM_TYPE,
		RCT.PURCHASE_ORDER PO_REF
		-- ,rct.attribute1 BILL_TYPE_ID
		--,rct.PRIMARY_SALESREP_ID Sales_Branch
		--,NVL( jrre.attribute1,DECODE (rct.org_id, 456, 'D2', 457, 'CH', 'NA')) sales_office_code
		,
		JRRE.ATTRIBUTE1 SALES_OFFICE_CODE,
		JRS.NAME SALES_BRANCH_NAME,
		(
			SELECT
					FLL.DESCRIPTION
				FROM
					FND_FLEX_VALUES_VL FLL
				WHERE
					FLL.FLEX_VALUE_SET_ID = 1014929 -- location
					AND FLL.FLEX_VALUE = GCC_REC.SEGMENT2
		)
		LOCATION_DESC,
		GCC_REC.SEGMENT1 REC_GL_ACCT_ENTITY,
		GCC_REC.SEGMENT2 REC_GL_ACCT_LOCATION,
		GCC_REC.SEGMENT3 REC_GL_ACCT_COST_CENTER,
		GCC_REC.SEGMENT4 REC_GL_ACCT_ACCOUNT,
		GCC_REC.SEGMENT5 REC_GL_ACCT_PRODUCT,
		GCC_REC.SEGMENT6 REC_GL_ACCT_INTERCOMPANY,
		GCC_REC.SEGMENT7 REC_GL_ACCT_FUTURE1,
		GCC_REC.SEGMENT8 REC_GL_ACCT_FUTURE2,
		GCC.SEGMENT1 REV_GL_ACCT_ENTITY,
		GCC.SEGMENT2 REV_GL_ACCT_LOCATION,
		GCC.SEGMENT3 REV_GL_ACCT_COST_CENTER,
		GCC.SEGMENT4 REV_GL_ACCT_ACCOUNT,
		GCC.SEGMENT5 REV_GL_ACCT_PRODUCT,
		GCC.SEGMENT6 REV_GL_ACCT_INTERCOMPANY,
		GCC.SEGMENT7 REV_GL_ACCT_FUTURE1,
		GCC.SEGMENT8 REV_GL_ACCT_FUTURE2,
		RCTGD.COMMENTS REG_GL_TYPE,
		RCTGD.ACCOUNT_CLASS ACCOUNT_CLASS,
		DECODE(RBS.NAME, 'P21', SUBSTR(RCTL.DESCRIPTION, 1, INSTR(RCTL.DESCRIPTION, '~', 1, 1) - 1), MSI.SEGMENT1) ITEM_NUMBER,
		DECODE(RBS.NAME, 'P21', SUBSTR(RCTL.DESCRIPTION, INSTR(RCTL.DESCRIPTION, '~', 1, 1) + 1), NVL(RCTL.TRANSLATED_DESCRIPTION, RCTL.DESCRIPTION)) ITEM_DESC,
		HOU.NAME OU_NAME,
		RCT.EXCHANGE_RATE,
		GJH.NAME JOURNAL_NAME,
		NULL JOURNAL_ID,
		GJB.NAME GL_BATCH_NAME,
		GJB.POSTED_DATE,
		(
			SELECT
					MIC.SEGMENT1||'.'|| MIC.SEGMENT2 ||'.'|| MIC.SEGMENT3 ||'.'|| MIC.SEGMENT4 ||'.'|| MIC.SEGMENT5 ||'.'|| MIC.SEGMENT6
				FROM
					MTL_ITEM_CATEGORIES_V MIC,
					MTL_SYSTEM_ITEMS MSI1
				WHERE
					MIC.INVENTORY_ITEM_ID = MSI1.INVENTORY_ITEM_ID
					AND MSI1.SEGMENT1 = DECODE(RBS.NAME, 'P21', SUBSTR(RCTL.DESCRIPTION, 1, INSTR(RCTL.DESCRIPTION, '~', 1, 1) - 1), MSI.SEGMENT1)
					AND MIC.CATEGORY_SET_NAME = 'IRPLN SIOP CATEGORY'
					AND MIC.ORGANIZATION_ID = MSI1.ORGANIZATION_ID
					AND MSI1.ORGANIZATION_ID = NVL(RCTL.WAREHOUSE_ID, 99)
					AND ROWNUM = 1
		)
		SIOP_NUMBER
	FROM
		RA_CUSTOMER_TRX_ALL RCT
	INNER JOIN RA_CUSTOMER_TRX_LINES_ALL RCTL         ON RCTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
	INNER JOIN RA_BATCH_SOURCES_ALL RBS               ON RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID AND RBS.ORG_ID = RCT.ORG_ID
	INNER JOIN RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD     ON RCTGD.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
	INNER JOIN RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD_REC ON RCTGD_REC.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID AND NVL(RCTGD.CUSTOMER_TRX_LINE_ID, RCTL.CUSTOMER_TRX_LINE_ID) = RCTL.CUSTOMER_TRX_LINE_ID
	INNER JOIN HZ_CUST_ACCOUNTS HCA_BILLTO            ON RCT.BILL_TO_CUSTOMER_ID = HCA_BILLTO.CUST_ACCOUNT_ID
	INNER JOIN RA_CUST_TRX_TYPES_ALL RCTT             ON RCT.CUST_TRX_TYPE_ID = RCTT.CUST_TRX_TYPE_ID AND RCTT.ORG_ID = RCT.ORG_ID
	INNER JOIN HZ_PARTIES HP_BILLTO                   ON HCA_BILLTO.PARTY_ID = HP_BILLTO.PARTY_ID
	LEFT OUTER JOIN JTF_RS_SALESREPS JRS              ON JRS.SALESREP_ID = RCT.PRIMARY_SALESREP_ID AND JRS.ORG_ID = RCT.ORG_ID
	LEFT OUTER JOIN JTF_RS_RESOURCE_EXTNS JRRE        ON JRS.RESOURCE_ID = JRRE.RESOURCE_ID
	INNER JOIN XLA_DISTRIBUTION_LINKS XDL             ON RCTGD.CUST_TRX_LINE_GL_DIST_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1 AND RCTGD.EVENT_ID = XDL.EVENT_ID
	INNER JOIN XLA_AE_LINES AEL                       ON XDL.AE_HEADER_ID = AEL.AE_HEADER_ID AND XDL.AE_LINE_NUM = AEL.AE_LINE_NUM
	INNER JOIN GL_CODE_COMBINATIONS_KFV GCC           ON AEL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
	INNER JOIN HR_OPERATING_UNITS HOU                 ON HOU.ORGANIZATION_ID = RCT.ORG_ID
	INNER JOIN XLA_DISTRIBUTION_LINKS XDL_REC         ON RCTGD_REC.CUST_TRX_LINE_GL_DIST_ID = XDL_REC.SOURCE_DISTRIBUTION_ID_NUM_1
	INNER JOIN XLA_AE_HEADERS AEH                     ON XDL.AE_HEADER_ID = AEH.AE_HEADER_ID AND RCTGD.EVENT_ID = XDL_REC.EVENT_ID
	INNER JOIN XLA_AE_LINES AEL_REC                   ON XDL_REC.AE_HEADER_ID = AEL_REC.AE_HEADER_ID AND XDL_REC.AE_LINE_NUM = AEL_REC.AE_LINE_NUM
	INNER JOIN GL_CODE_COMBINATIONS_KFV GCC_REC       ON AEL_REC.CODE_COMBINATION_ID = GCC_REC.CODE_COMBINATION_ID
	INNER JOIN XLA_AE_HEADERS AEH_REC                 ON XDL_REC.AE_HEADER_ID = AEH_REC.AE_HEADER_ID
	LEFT OUTER JOIN MTL_SYSTEM_ITEMS MSI              ON MSI.INVENTORY_ITEM_ID = RCTL.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID = NVL(RCTL.WAREHOUSE_ID, 99)
	LEFT OUTER JOIN GL_IMPORT_REFERENCES GIR          ON GIR.GL_SL_LINK_TABLE = AEL.GL_SL_LINK_TABLE AND GIR.GL_SL_LINK_ID = AEL.GL_SL_LINK_ID
	LEFT OUTER JOIN GL_JE_LINES GJL                   ON GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
	INNER JOIN GL_JE_HEADERS GJH                      ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
	INNER JOIN GL_JE_BATCHES GJB                      ON GJB.JE_BATCH_ID = GJH.JE_BATCH_ID
	WHERE
		0 = 0
		AND RCT.COMPLETE_FLAG = 'Y'
		AND RCT.ORG_ID IN(456, 457)                         -- US TCS and CA TCS  Only
		AND RBS.NAME IN('P21', 'ORDER ENTRY', 'TCS MANUAL') -- batch source P21 and Order Entry only
		AND RCTGD.ACCOUNT_CLASS <> 'REC'
		AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL'
		AND XDL.APPLICATION_ID = 222
		AND RCTGD_REC.ACCOUNT_CLASS = 'REC'
		AND NVL(RCTGD_REC.LATEST_REC_FLAG, 'Y') = 'Y'
		AND XDL_REC.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL'
		AND XDL_REC.APPLICATION_ID = 222
		AND GJH.JE_SOURCE = 'Receivables' ;