-- describe DM_030_CALC_SUM_PIVOT;
alter table DM_030_CALC_SUM_PIVOT add R12_GL_ACCOUNT VARCHAR2(10);

update DM_030_CALC_SUM_PIVOT CFP set
R12_GL_ACCOUNT=(select R12_ACCOUNT from R12_TRANE_ACCOUNTS_PS PSA where PSA.PS_ACCOUNT = CFP.GL_ACCOUNT)
where exists (select R12_ACCOUNT from R12_TRANE_ACCOUNTS_PS PSA where PSA.PS_ACCOUNT = CFP.GL_ACCOUNT);

alter table DM_030_CALC_SUM_PIVOT add PS_GL_ACCOUNT VARCHAR2(20);
update DM_030_CALC_SUM_PIVOT set PS_GL_ACCOUNT = GL_ACCOUNT;
update DM_030_CALC_SUM_PIVOT set GL_ACCOUNT = R12_GL_ACCOUNT;
alter table DM_030_CALC_SUM_PIVOT drop column R12_GL_ACCOUNT;

-- select * from DM_030_CALC_SUM_PIVOT;
commit;

alter table DM_030_CALC_SUM_PIVOT add R12_GL_ACCOUNT_DESCR varchar2(128);

update DM_030_CALC_SUM_PIVOT CFP
set R12_GL_ACCOUNT_DESCR = (select DESCR from R12_ACCOUNT_FILTER_UPD AFU where AFU.R12_ACCOUNT = CFP.GL_ACCOUNT)
where exists (select DESCR from R12_ACCOUNT_FILTER_UPD AFU where AFU.R12_ACCOUNT = CFP.GL_ACCOUNT);

alter table DM_030_CALC_SUM_PIVOT add PS_GL_ACCOUNT_DESCR varchar2(30);
update DM_030_CALC_SUM_PIVOT set PS_GL_ACCOUNT_DESCR = GL_ACCOUNT_DESCR;
-- NOTE: GL_ACCOUNT_DESCRIPTION isn't big enough for R12 descriptions
alter table DM_030_CALC_SUM_PIVOT modify GL_ACCOUNT_DESCR varchar2(128);
update DM_030_CALC_SUM_PIVOT set GL_ACCOUNT_DESCR =  R12_GL_ACCOUNT_DESCR;
alter table DM_030_CALC_SUM_PIVOT drop column R12_GL_ACCOUNT_DESCR;

commit;

