alter table DM_030_COST_FLOW_PIVOT add R12_GL_ACCOUNT VARCHAR2(10);

update DM_030_COST_FLOW_PIVOT CFP set
R12_GL_ACCOUNT=(select R12_ACCOUNT from R12_TRANE_ACCOUNTS_PS PSA where PSA.PS_ACCOUNT = CFP.GL_ACCOUNT)
where exists (select R12_ACCOUNT from R12_TRANE_ACCOUNTS_PS PSA where PSA.PS_ACCOUNT = CFP.GL_ACCOUNT);

alter table DM_030_COST_FLOW_PIVOT add PS_GL_ACCOUNT VARCHAR2(10);
update DM_030_COST_FLOW_PIVOT set PS_GL_ACCOUNT = GL_ACCOUNT;
update DM_030_COST_FLOW_PIVOT set GL_ACCOUNT = R12_GL_ACCOUNT;
alter table DM_030_COST_FLOW_PIVOT drop column R12_GL_ACCOUNT;

commit;

alter table DM_030_COST_FLOW_PIVOT add R12_GL_ACCOUNT_DESCR varchar2(128);

update DM_030_COST_FLOW_PIVOT CFP
set R12_GL_ACCOUNT_DESCR = (select DESCR from R12_ACCOUNT_FILTER_UPD AFU where AFU.R12_ACCOUNT = CFP.GL_ACCOUNT)
where exists (select DESCR from R12_ACCOUNT_FILTER_UPD AFU where AFU.R12_ACCOUNT = CFP.GL_ACCOUNT);

alter table DM_030_COST_FLOW_PIVOT add PS_GL_ACCOUNT_DESCR varchar(30);
update DM_030_COST_FLOW_PIVOT set PS_GL_ACCOUNT_DESCR = GL_ACCOUNT_DESCRIPTION;
-- NOTE: GL_ACCOUNT_DESCRIPTION isn't big enough
alter table DM_030_COST_FLOW_PIVOT modify GL_ACCOUNT_DESCRIPTION varchar2(128);
update DM_030_COST_FLOW_PIVOT set GL_ACCOUNT_DESCRIPTION = R12_GL_ACCOUNT_DESCR;
alter table DM_030_COST_FLOW_PIVOT drop column R12_GL_ACCOUNT_DESCR;

commit;

