SELECT 'GL_CODE_COMBINATIONS_KFV', COUNT( *) FROM GL_CODE_COMBINATIONS_KFV UNION ALL
SELECT 'GL_JE_HEADERS', COUNT( *) FROM GL_JE_HEADERS UNION ALL
-- select 'RA_BATCH_SOURCE_ALL', count(*) from RA_BATCH_SOURCE_ALL UNION ALL
SELECT 'RA_CUST_TRX_LINE_GL_DIST_ALL', COUNT( *) FROM 		RA_CUST_TRX_LINE_GL_DIST_ALL UNION ALL
SELECT 'RA_CUSTOMER_TRX_ALL', COUNT( *) FROM RA_CUSTOMER_TRX_ALL UNION ALL
SELECT 'RA_CUSTOMER_TRX_LINES_ALL', COUNT( *) FROM RA_CUSTOMER_TRX_LINES_ALL ORDER BY 1;