SELECT
					/*+ FIRST_ROWS */
					TO_CHAR(A.JOURNAL_DATE, 'YYYYMM') AS JRNL_YEAR_MONTH,
					A.R12_ACCOUNT
					-- -SS- ACCOUNT
					AS GL_ACCOUNT,
					CASE
						WHEN A.R12_ENTITY IN('5773', '5588') THEN 'CAD'
						WHEN A.R12_ENTITY IN('5575', '5612', '5743', '9256', '9258', '9298', '9299', '9984') THEN 'USD'
						ELSE '???'
						END
					-- -SS- ASX.NATION_CURR
					AS COUNTRY_INDICATOR,
					TRUNC(A.JOURNAL_DATE, 'MM') AS JOURNAL_DATE,
					SUM(A.MONETARY_AMOUNT * - 1) AS REVENUE_AMOUNT,
					AFU.LIKE_52_53_54_NOT_5268,
					count(*) as count
				FROM
					R12_BI_ACCT_ENTRY_STG A
					-- -SS- OTR
				INNER JOIN R12_TRNBI_BI_HDR_STG B -- -SS- OTR
					ON /* A.BUSINESS_UNIT = B.BUSINESS_UNIT AND */ A.INVOICE = B.INVOICE AND A.CUSTOMER_TRX_ID = B.CUSTOMER_TRX_ID
				INNER JOIN R12_BI_HDR_STG C -- -SS- OTR
					ON /* B.BUSINESS_UNIT = C.PS_BUSINESS_UNIT AND */ B.INVOICE = C.INVOICE AND B.CUSTOMER_TRX_ID = C.CUSTOMER_TRX_ID /* AND C.ENTRY_TYPE = 'IN' */
					-- -SS- NEW
				left outer JOIN R12_ACCOUNT_FILTER_UPD AFU ON AFU.R12_ACCOUNT = A.R12_ACCOUNT
					-- -SS- /NEW
				/* -SS- issue 88
				INNER JOIN R12_TRANE_ACCOUNTS_PS PSA
					-- -SS- OTR
				ON A.R12_ACCOUNT = PSA.R12_ACCOUNT -- -SS- R12_2_R12
				*/
					/* -SS- ,
					DBO.ACTUATE_SEC_XREF ASX */
				WHERE
					A.JOURNAL_DATE BETWEEN TO_DATE('01/01/2003', 'MM/DD/YYYY') AND LAST_DAY(ADD_MONTHS(SYSDATE, - 1))
					-- -SS- issue 88: AND PSA.TRANE_ACCOUNT_IND = 'X'
					-- AND A.R12_ENTITY IN('5773', '5588', '5575', '5612', '5743', '9256', '9258', '9298', '9299', '9984') -- -SS- CAN, USA
					-- -SS- AND A.BUSINESS_UNIT_GL IN ('CAN', 'CSD')
					-- -SS- AND A.BUSINESS_UNIT_GL = ASX.PSGL(+)
					-- -SS- AND A.ACCOUNT = PSA.ACCOUNT (+)
					-- -SS- AND A.BUSINESS_UNIT = B.BUSINESS_UNIT
					-- -SS- AND A.INVOICE = B.INVOICE
					-- -SS- AND B.BUSINESS_UNIT = C.BUSINESS_UNIT
					-- -SS- AND B.INVOICE = C.INVOICE
					-- -SS- AND C.ENTRY_TYPE = 'IN'
					-- -SS- NEW
					-- AND AFU.LIKE_52_53_54_NOT_5268 = 'Y'
					-- -SS- /NEW
					-- -SS- AND(A.ACCOUNT LIKE '52%' OR A.ACCOUNT LIKE '53%' OR A.ACCOUNT LIKE '54%')
					-- -SS- AND A.ACCOUNT NOT LIKE '5268%'
					and a.r12_account like '282%'
				GROUP BY
					TO_CHAR(A.JOURNAL_DATE, 'YYYYMM'),
					A.R12_ACCOUNT,
					CASE
						WHEN A.R12_ENTITY IN('5773', '5588') THEN 'CAD'
						WHEN A.R12_ENTITY IN('5575', '5612', '5743', '9256', '9258', '9298', '9299', '9984') THEN 'USD'
						ELSE '???'
						END,
					-- -SS- ASX.NATION_CURR
					TRUNC(A.JOURNAL_DATE, 'MM'),
					AFU.LIKE_52_53_54_NOT_5268
					;
select * from R12_BI_ACCT_ENTRY_STG;
select * from R12_TRNBI_BI_HDR_STG;
select *
				FROM
					R12_BI_ACCT_ENTRY_STG A
					-- -SS- OTR
				INNER JOIN R12_TRNBI_BI_HDR_STG B -- -SS- OTR
					ON /* A.BUSINESS_UNIT = B.BUSINESS_UNIT AND */ A.INVOICE = B.INVOICE AND A.CUSTOMER_TRX_ID = B.CUSTOMER_TRX_ID
				INNER JOIN R12_BI_HDR_STG C -- -SS- OTR
					ON /* B.BUSINESS_UNIT = C.PS_BUSINESS_UNIT AND */ B.INVOICE = C.INVOICE AND B.CUSTOMER_TRX_ID = C.CUSTOMER_TRX_ID
;
select distinct ENTRY_TYPE from R12_BI_HDR_STG;

			SELECT
					/*+ FIRST_ROWS */
					TO_CHAR(A.JOURNAL_DATE, 'YYYYMM') AS JRNL_YEAR_MONTH,
					A.R12_ACCOUNT
					/* ACCOUNT */
					AS GL_ACCOUNT,
					CASE
						WHEN A.R12_ENTITY IN('5773', '5588') THEN 'CAD'
						WHEN A.R12_ENTITY IN('5575', '5612', '5743', '9256', '9258', '9298', '9299', '9984') THEN 'USD'
						ELSE '???'
						END
					/* ASX.NATION_CURR */
					AS COUNTRY_INDICATOR,
					TRUNC(A.JOURNAL_DATE, 'MM') AS JOURNAL_DATE,
					SUM(A.MONETARY_AMOUNT * - 1) AS REVENUE_AMOUNT
				FROM
					R12_BI_ACCT_ENTRY_STG A -- -SS- OTR
				INNER JOIN R12_TRNBI_BI_HDR_STG B -- -SS- OTR
					ON /* A.BUSINESS_UNIT = B.BUSINESS_UNIT AND */ A.INVOICE = B.INVOICE AND A.CUSTOMER_TRX_ID = B.CUSTOMER_TRX_ID
				INNER JOIN R12_BI_HDR_STG C -- -SS- OTR
					ON /* B.BUSINESS_UNIT = C.PS_BUSINESS_UNIT AND */ B.INVOICE = C.INVOICE AND B.CUSTOMER_TRX_ID = C.CUSTOMER_TRX_ID /* AND C.ENTRY_TYPE = 'IN' */
					-- -SS- NEW
				INNER JOIN R12_ACCOUNT_FILTER_UPD AFU ON AFU.R12_ACCOUNT = A.R12_ACCOUNT
					-- -SS- /NEW
				/* -SS- issue 88:
				INNER JOIN R12_TRANE_ACCOUNTS_PS PSA -- -SS- OTR
				ON A.R12_ACCOUNT = PSA.R12_ACCOUNT -- -SS- R12_2_R12
				*/
					/* -SS- ,
					DBO.ACTUATE_SEC_XREF ASX */
				WHERE
					A.JOURNAL_DATE BETWEEN TO_DATE('01/01/2004', 'MM/DD/YYYY') AND LAST_DAY(ADD_MONTHS(SYSDATE, - 1))
					-- -SS- issue 88: AND PSA.TRANE_ACCOUNT_IND = 'X'
					-- -SS- separate conditions for PS and R12
					AND A.R12_ENTITY IN('5773', '5588', '5575', '5612', '5743', '9256', '9258', '9298', '9299', '9984') -- -SS- CAN, USA
					-- -SS- AND A.BUSINESS_UNIT_GL IN('CAN', 'CSD')
					-- -SS- AND A.BUSINESS_UNIT_GL = ASX.PSGL(+)
					-- -SS- AND A.ACCOUNT = PSA.ACCOUNT (+)
					-- -SS- AND A.BUSINESS_UNIT = B.BUSINESS_UNIT
					-- -SS- AND A.INVOICE = B.INVOICE
					-- -SS- AND B.BUSINESS_UNIT = C.BUSINESS_UNIT
					-- -SS- AND B.INVOICE = C.INVOICE
					-- -SS- AND C.ENTRY_TYPE = 'IN'
					-- -SS- NEW
					AND AFU.LIKE_5268 = 'Y'
					-- -SS- /NEW
					-- -SS- AND(A.ACCOUNT LIKE '5268%')
				GROUP BY
					TO_CHAR(A.JOURNAL_DATE, 'YYYYMM'),
					A.R12_ACCOUNT,
					CASE
						WHEN A.R12_ENTITY IN('5773', '5588') THEN 'CAD'
						WHEN A.R12_ENTITY IN('5575', '5612', '5743', '9256', '9258', '9298', '9299', '9984') THEN 'USD'
						ELSE '???'
						END,
					-- -SS- ASX.NATION_CURR
					TRUNC(A.JOURNAL_DATE, 'MM');

select count(*)
				FROM
					R12_BI_ACCT_ENTRY_STG A -- -SS- OTR
				INNER JOIN R12_TRNBI_BI_HDR_STG B -- -SS- OTR
					ON /* A.BUSINESS_UNIT = B.BUSINESS_UNIT AND */ A.INVOICE = B.INVOICE AND A.CUSTOMER_TRX_ID = B.CUSTOMER_TRX_ID
				INNER JOIN R12_BI_HDR_STG C -- -SS- OTR
					ON /* B.BUSINESS_UNIT = C.PS_BUSINESS_UNIT AND */ B.INVOICE = C.INVOICE AND B.CUSTOMER_TRX_ID = C.CUSTOMER_TRX_ID /* AND C.ENTRY_TYPE = 'IN' */
					-- -SS- NEW
				left outer JOIN R12_ACCOUNT_FILTER_UPD AFU ON AFU.R12_ACCOUNT = A.R12_ACCOUNT
				where afu.r12_account is null;

describe r12_bi_hdr_stg
describe R12_TRNBI_BI_HDR_STG;

select distinct R12_ACCOUNT from R12_ACCOUNT_FILTER_UPD where LIKE_5268 = 'Y';
select distinct R12_ACCOUNT from R12_ACCOUNT_FILTER_UPD where LIKE_52_53_54_NOT_5268 = 'Y';

