SELECT
		/*+ NO_CPU_COSTING */
		'P21' AS QUERY_SOURCE,
		BUSINESS_UNIT AS BU,
		SUM(P7_TOTAL) AS REVENUE_AMOUNT,
		SUM(100 *(P7_TOTAL - TRUNC(P7_TOTAL))) AS REVENUE_AMOUNT_DEC,
		GL_ACCOUNT AS GL_ACCOUNT,
		DEPTID AS DEPT_ID,
		DEPT_DESCR AS DEPT_DESCR,
		PRODCODE AS MANF_PROD_ID,
		PROD_DESCR AS MANF_PROD_DESCR
		/* CHANGING 5/18/2007 MSUN*/
		,
		GL_PRODCODE AS DIST_GL_PRODUCT,
		NVL(RESERVE_GROUP, 'LARGE') AS RESERVE_GROUP,
		JRNL_DATE AS JRNL_DATE,
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'YYYY')) AS JRNL_YEAR,
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'MM')) AS JRNL_MONTH,
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'YYYY')) * 100 + TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'MM')) AS JRNL_YEAR_MONTH,
		JRNL_ID AS JRNL_ID,
		CURRENCY AS CURRENCY,
		NATION_CURR AS COUNTRY_INDICATOR
	FROM
		(
			SELECT
					/*+ NO_CPU_COSTING */
					D.R12_ENTITY AS BUSINESS_UNIT, 
					D.INVOICE AS INVOICE,
					D.LINE_SEQ_NUM AS SEQ_NUM,
					D.ACCT_ENTRY_TYPE AS ENTRY_TYPE,
					D.JOURNAL_ID AS JRNL_ID,
					D.JOURNAL_DATE AS JRNL_DATE,
					D.R12_ACCOUNT AS GL_ACCOUNT,
					D.MONETARY_AMOUNT AS P7_TOTAL,
					D.R12_LOCATION AS DEPTID,
					DP.DESCR AS DEPT_DESCR,
					PR.DESCR AS PROD_DESCR,
					X.PRODUCT_CATEGORY AS RESERVE_GROUP,
					A.MANF_PROD_ID AS PRODCODE, 
					CASE WHEN D.R12_PRODUCT IN('41204', '41198')
						THEN '41204'
						ELSE D.R12_PRODUCT
					END AS GL_PRODCODE,
					D.CURRENCY_CD AS CURRENCY,
					CASE WHEN D.R12_ENTITY IN('5773', '5588')
						THEN 'CAD'
						ELSE 'USD'
					END AS NATION_CURR
				FROM
					R12_BI_LINE_STG A                                                   
				INNER JOIN R12_BI_ACCT_ENTRY_STG D ON D.LINE_SEQ_NUM = A.LINE_SEQ_NUM AND D.INVOICE = A.INVOICE AND D.CUSTOMER_TRX_ID = A.CUSTOMER_TRX_ID
				INNER JOIN R12_BI_HDR_STG B ON D.INVOICE = B.INVOICE AND D.CUSTOMER_TRX_ID = B.CUSTOMER_TRX_ID
				INNER JOIN R12_TRNBI_BI_HDR_STG C ON D.INVOICE = C.INVOICE AND D.CUSTOMER_TRX_ID = C.CUSTOMER_TRX_ID
				INNER JOIN R12_ACCOUNT_FILTER_UPD AFU ON AFU.R12_ACCOUNT = D.R12_ACCOUNT
				INNER JOIN OTR_PROD_CODE_XREF_RCPO X ON A.MANF_PROD_ID = X.MANF_PROD_CODE
				LEFT OUTER JOIN R12_TRANE_PRODUCTS_PS PR        ON D.R12_PRODUCT = PR.R12_PRODUCT 
				LEFT OUTER JOIN R12_TRANE_LOCATIONS DP ON DP.R12_LOCATION = D.R12_LOCATION 
				WHERE
					D.JOURNAL_DATE BETWEEN '01-oct-16' AND '31-oct-16'
					AND B.BILL_SOURCE_ID = 'P21'
					AND C.TRNBI_PROJECT_TYPE = '7'
					AND D.LEDGER = 'ACTUALS'
					AND X.TWO_FIVE = 'Y'
					AND X.GL_LEDGER = 'CSD'
					AND AFU.EQUAL_700000 = 'Y'
					AND D.R12_PRODUCT <> '41208' 
					AND D.R12_PRODUCT <> '41399'
					AND D.R12_PRODUCT <> '41132' 
					AND D.R12_PRODUCT <> '41499' 
					AND D.R12_PRODUCT <> '41205' 
		)
	GROUP BY
		BUSINESS_UNIT,
		GL_ACCOUNT,
		DEPTID,
		DEPT_DESCR,
		PROD_DESCR,
		PRODCODE, --ADD BY ALEX
		GL_PRODCODE, --ADD BY ALEX
		NVL(RESERVE_GROUP, 'LARGE'),
		JRNL_DATE,
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'YYYY')),
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'MM')),
		TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'YYYY')) * 100 + TO_NUMBER(TO_CHAR(TO_DATE(JRNL_DATE), 'MM')),
		JRNL_ID,
		CURRENCY,
		NATION_CURR