SELECT -- COUNT(*) cnt, count(distinct RCT.TRX_NUMBER) numTransactions
		RCT.TRX_NUMBER AS INVOICE,
		RCTL.LINE_NUMBER AS LINE_SEQ_NUM,
		RCT.REASON_CODE AS ACCT_ENTRY_TYPE,
		RCTGD.AMOUNT AS MONETARY_AMOUNT,
		GJH.NAME AS JOURNAL_ID,
		RCTGD.GL_DATE AS JOURNAL_DATE,
		RCT.INVOICE_CURRENCY_CODE AS CURRENCY_CD,
		GCC.SEGMENT4 AS R12_ACCOUNT,
		GCC.SEGMENT5 AS R12_PRODUCT,
		GCC.SEGMENT1 AS R12_ENTITY,
		GCC.SEGMENT2 AS R12_LOCATION,
		RCT.CUSTOMER_TRX_ID AS CUSTOMER_TRX_ID
	FROM
		RA_CUSTOMER_TRX_ALL RCT
	INNER JOIN RA_CUSTOMER_TRX_LINES_ALL RCTL     ON RCTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
	INNER JOIN RA_BATCH_SOURCES_ALL RBS           ON RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID AND RBS.ORG_ID = RCT.ORG_ID
	INNER JOIN RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD ON RCTGD.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID -- and rctgd.CUSTOMER_TRX_LINE_ID = rctl.CUSTOMER_TRX_LINE_ID
	INNER JOIN XLA_DISTRIBUTION_LINKS XDL         ON RCTGD.CUST_TRX_LINE_GL_DIST_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1 AND RCTGD.EVENT_ID = XDL.EVENT_ID
-- base trans and lines
	INNER JOIN XLA_AE_LINES AEL                   ON XDL.AE_HEADER_ID = AEL.AE_HEADER_ID AND XDL.AE_LINE_NUM = AEL.AE_LINE_NUM
	LEFT OUTER JOIN GL_IMPORT_REFERENCES GIR      ON GIR.GL_SL_LINK_TABLE = AEL.GL_SL_LINK_TABLE AND GIR.GL_SL_LINK_ID = AEL.GL_SL_LINK_ID
	LEFT OUTER JOIN GL_JE_LINES GJL               ON GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
	LEFT JOIN GL_JE_HEADERS GJH                  ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
	LEFT JOIN GL_CODE_COMBINATIONS_KFV GCC       ON AEL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
	WHERE
		0 = 0
		AND RCT.ATTRIBUTE9 = '7'
		AND RBS.BATCH_SOURCE_ID IN('90003', '90006', '87004', '87003', '90005')
		AND RCT.ORG_ID IN(456, 457) -- US TCS and CA TCS  Only
--		AND RCT.TRX_NUMBER IN('1521904', '1519059')
and rct.trx_number = '50026153'
		AND RCTL.LINE_TYPE = 'LINE'  -- eliminates Tax
		AND RCTGD.GL_DATE > '01-OCT-16' 
		-- AND RCTL.LINE_NUMBER = 1
		AND RCT.COMPLETE_FLAG = 'Y'  -- no change
		AND NVL(RCTGD.LATEST_REC_FLAG, 'Y') = 'Y'
		AND RCTGD.ACCOUNT_CLASS = 'REV'
		AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL'
		AND XDL.APPLICATION_ID = 222
		AND GJH.JE_SOURCE = 'Receivables'
		;

-- does every occurrance of 100% apply to only one line?
SELECT
		RCT.TRX_NUMBER AS INVOICE,
		RCT.CUSTOMER_TRX_ID AS CUSTOMER_TRX_ID,
		RCTL.LINE_NUMBER AS LINE_SEQ_NUM,
count(distinct RCTL.revenue_amount)
	FROM
		RA_CUSTOMER_TRX_ALL RCT
	INNER JOIN RA_BATCH_SOURCES_ALL RBS           ON RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID AND RBS.ORG_ID = RCT.ORG_ID
	INNER JOIN RA_CUSTOMER_TRX_LINES_ALL RCTL ON RCTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
	INNER JOIN RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD ON RCTGD.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID and rctgd.CUSTOMER_TRX_LINE_ID = rctl.CUSTOMER_TRX_LINE_ID
	INNER JOIN XLA_DISTRIBUTION_LINKS XDL
		ON RCTGD.CUST_TRX_LINE_GL_DIST_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
		AND RCTGD.EVENT_ID = XDL.EVENT_ID
WHERE 0=0 -- ROWNUM < 10
		AND RCT.ATTRIBUTE9 = '7'
		AND RBS.BATCH_SOURCE_ID IN('90003', '90006', '87004', '87003', '90005')
		AND RCT.ORG_ID IN(456, 457) -- US TCS and CA TCS  Only
		AND RCTL.LINE_TYPE = 'LINE'  -- eliminates Tax
		AND RCTGD.GL_DATE > '01-OCT-16' 
		AND RCT.COMPLETE_FLAG = 'Y'  -- no change
		AND NVL(RCTGD.LATEST_REC_FLAG, 'Y') = 'Y'
		AND RCTGD.ACCOUNT_CLASS = 'REV'
		AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL'
		AND XDL.APPLICATION_ID = 222
and rctgd.percent >= 99.9999 and rctgd.percent <= 100.0001
group by
		RCT.TRX_NUMBER,
		RCT.CUSTOMER_TRX_ID,
		RCTL.LINE_NUMBER
-- order by rctgd.customer_trx_line_id
order by 4 desc
;

-- does every unique line have at least 1 100% ?
SELECT
		RCT.TRX_NUMBER AS INVOICE,
		RCT.CUSTOMER_TRX_ID AS CUSTOMER_TRX_ID,
		RCTL.LINE_NUMBER AS LINE_SEQ_NUM,
max(case when rctgd.percent >= 99.9999 and rctgd.percent <= 100.0001 then 1 else 0 end) as has_100_percent
	FROM
		RA_CUSTOMER_TRX_ALL RCT
	INNER JOIN RA_BATCH_SOURCES_ALL RBS           ON RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID AND RBS.ORG_ID = RCT.ORG_ID
	INNER JOIN RA_CUSTOMER_TRX_LINES_ALL RCTL ON RCTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
	INNER JOIN RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD ON RCTGD.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID and rctgd.CUSTOMER_TRX_LINE_ID = rctl.CUSTOMER_TRX_LINE_ID
	INNER JOIN XLA_DISTRIBUTION_LINKS XDL
		ON RCTGD.CUST_TRX_LINE_GL_DIST_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
		AND RCTGD.EVENT_ID = XDL.EVENT_ID
WHERE 0=0 -- ROWNUM < 10
		AND RCT.ATTRIBUTE9 = '7'
		AND RBS.BATCH_SOURCE_ID IN('90003', '90006', '87004', '87003', '90005')
		AND RCT.ORG_ID IN(456, 457) -- US TCS and CA TCS  Only
		AND RCTL.LINE_TYPE = 'LINE'  -- eliminates Tax
		AND RCTGD.GL_DATE > '01-OCT-16' 
		AND RCT.COMPLETE_FLAG = 'Y'  -- no change
		AND NVL(RCTGD.LATEST_REC_FLAG, 'Y') = 'Y'
		AND RCTGD.ACCOUNT_CLASS = 'REV'
		AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL'
		AND XDL.APPLICATION_ID = 222
		-- AND GJH.JE_SOURCE = 'Receivables'
group by
	RCT.TRX_NUMBER,
	RCT.CUSTOMER_TRX_ID,
	RCTL.LINE_NUMBER
 order by 4 asc
		;
		
-- where GL_ACCOUNT_TYPE = 'R', do we have any redundancy? NO
SELECT
		RCT.TRX_NUMBER AS INVOICE,
		RCT.CUSTOMER_TRX_ID AS CUSTOMER_TRX_ID,
		RCTL.LINE_NUMBER AS LINE_SEQ_NUM,
		COUNT(DISTINCT RCTL.REVENUE_AMOUNT)
	FROM
		RA_CUSTOMER_TRX_ALL RCT
	INNER JOIN RA_BATCH_SOURCES_ALL RBS           ON RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID AND RBS.ORG_ID = RCT.ORG_ID
	INNER JOIN RA_CUSTOMER_TRX_LINES_ALL RCTL ON RCTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
	INNER JOIN RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD ON RCTGD.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID and rctgd.CUSTOMER_TRX_LINE_ID = rctl.CUSTOMER_TRX_LINE_ID
	INNER JOIN XLA_DISTRIBUTION_LINKS XDL
		ON RCTGD.CUST_TRX_LINE_GL_DIST_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
		AND RCTGD.EVENT_ID = XDL.EVENT_ID
	INNER JOIN XLA_AE_LINES AEL                   ON XDL.AE_HEADER_ID = AEL.AE_HEADER_ID AND XDL.AE_LINE_NUM = AEL.AE_LINE_NUM
	LEFT OUTER JOIN GL_IMPORT_REFERENCES GIR      ON GIR.GL_SL_LINK_TABLE = AEL.GL_SL_LINK_TABLE AND GIR.GL_SL_LINK_ID = AEL.GL_SL_LINK_ID
	LEFT OUTER JOIN GL_JE_LINES GJL               ON GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
	LEFT JOIN GL_JE_HEADERS GJH                   ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
	LEFT JOIN GL_CODE_COMBINATIONS_KFV GCC        ON AEL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
WHERE 0=0 -- ROWNUM < 10
		AND RCT.ATTRIBUTE9 = '7'
		AND RBS.BATCH_SOURCE_ID IN('90003', '90006', '87004', '87003', '90005')
		AND RCT.ORG_ID IN(456, 457) -- US TCS and CA TCS  Only
		AND RCTL.LINE_TYPE = 'LINE'  -- eliminates Tax
		--AND RCTL.LINE_NUMBER = 1 (do not use drops multi-line item data)
		AND RCTGD.GL_DATE > '01-OCT-16' 
		AND RCT.COMPLETE_FLAG = 'Y'  -- no change
		AND NVL(RCTGD.LATEST_REC_FLAG, 'Y') = 'Y'
		AND RCTGD.ACCOUNT_CLASS = 'REV'
		-- AND RCTGD.percent = 100
		AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL'
		AND XDL.APPLICATION_ID = 222
		AND GJH.JE_SOURCE = 'Receivables'
AND GCC.GL_ACCOUNT_TYPE = 'R'
GROUP BY
	RCT.TRX_NUMBER,
	RCT.CUSTOMER_TRX_ID,
	RCTL.LINE_NUMBER
order by 4 desc;

-- does any unique invoice/line NOT have GL_ACCOUNT_TYPE = 'R'? YES
SELECT
		RCT.TRX_NUMBER AS INVOICE,
		RCT.CUSTOMER_TRX_ID AS CUSTOMER_TRX_ID,
		RCTL.LINE_NUMBER AS LINE_SEQ_NUM,
		max(case when GCC.GL_ACCOUNT_TYPE = 'R' then 1 else 0 end) as HAS_R
	FROM
		RA_CUSTOMER_TRX_ALL RCT
	INNER JOIN RA_BATCH_SOURCES_ALL RBS           ON RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID AND RBS.ORG_ID = RCT.ORG_ID
	INNER JOIN RA_CUSTOMER_TRX_LINES_ALL RCTL ON RCTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
	INNER JOIN RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD ON RCTGD.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID and rctgd.CUSTOMER_TRX_LINE_ID = rctl.CUSTOMER_TRX_LINE_ID
	INNER JOIN XLA_DISTRIBUTION_LINKS XDL
		ON RCTGD.CUST_TRX_LINE_GL_DIST_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
		AND RCTGD.EVENT_ID = XDL.EVENT_ID
	INNER JOIN XLA_AE_LINES AEL                   ON XDL.AE_HEADER_ID = AEL.AE_HEADER_ID AND XDL.AE_LINE_NUM = AEL.AE_LINE_NUM
	LEFT OUTER JOIN GL_IMPORT_REFERENCES GIR      ON GIR.GL_SL_LINK_TABLE = AEL.GL_SL_LINK_TABLE AND GIR.GL_SL_LINK_ID = AEL.GL_SL_LINK_ID
	LEFT OUTER JOIN GL_JE_LINES GJL               ON GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
	LEFT JOIN GL_JE_HEADERS GJH                   ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
	LEFT JOIN GL_CODE_COMBINATIONS_KFV GCC        ON AEL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
WHERE 0=0 -- ROWNUM < 10
		AND RCT.ATTRIBUTE9 = '7'
		AND RBS.BATCH_SOURCE_ID IN('90003', '90006', '87004', '87003', '90005')
		AND RCT.ORG_ID IN(456, 457) -- US TCS and CA TCS  Only
		AND RCTL.LINE_TYPE = 'LINE'  -- eliminates Tax
		--AND RCTL.LINE_NUMBER = 1 (do not use drops multi-line item data)
		AND RCTGD.GL_DATE > '01-OCT-16' 
		AND RCT.COMPLETE_FLAG = 'Y'  -- no change
		AND NVL(RCTGD.LATEST_REC_FLAG, 'Y') = 'Y'
		AND RCTGD.ACCOUNT_CLASS = 'REV'
		-- AND RCTGD.percent = 100
		AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL'
		AND XDL.APPLICATION_ID = 222
		AND GJH.JE_SOURCE = 'Receivables'
GROUP BY
	RCT.TRX_NUMBER,
	RCT.CUSTOMER_TRX_ID,
	RCTL.LINE_NUMBER
order by 4 ASC;

-- does every occurrance of 100% apply to only one line where GL_ACCOUNT_TYPE = 'R'? YES
SELECT
		RCT.TRX_NUMBER AS INVOICE,
		RCT.CUSTOMER_TRX_ID AS CUSTOMER_TRX_ID,
		RCTL.LINE_NUMBER AS LINE_SEQ_NUM,
count(distinct RCTL.revenue_amount)
	FROM
		RA_CUSTOMER_TRX_ALL RCT
	INNER JOIN RA_BATCH_SOURCES_ALL RBS           ON RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID AND RBS.ORG_ID = RCT.ORG_ID
	INNER JOIN RA_CUSTOMER_TRX_LINES_ALL RCTL ON RCTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
	INNER JOIN RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD ON RCTGD.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID and rctgd.CUSTOMER_TRX_LINE_ID = rctl.CUSTOMER_TRX_LINE_ID
	INNER JOIN XLA_DISTRIBUTION_LINKS XDL
		ON RCTGD.CUST_TRX_LINE_GL_DIST_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
		AND RCTGD.EVENT_ID = XDL.EVENT_ID
	INNER JOIN XLA_AE_LINES AEL                   ON XDL.AE_HEADER_ID = AEL.AE_HEADER_ID AND XDL.AE_LINE_NUM = AEL.AE_LINE_NUM
	LEFT OUTER JOIN GL_IMPORT_REFERENCES GIR      ON GIR.GL_SL_LINK_TABLE = AEL.GL_SL_LINK_TABLE AND GIR.GL_SL_LINK_ID = AEL.GL_SL_LINK_ID
	LEFT OUTER JOIN GL_JE_LINES GJL               ON GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
	LEFT JOIN GL_JE_HEADERS GJH                   ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
	LEFT JOIN GL_CODE_COMBINATIONS_KFV GCC        ON AEL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
WHERE 0=0 -- ROWNUM < 10
		AND RCT.ATTRIBUTE9 = '7'
		AND RBS.BATCH_SOURCE_ID IN('90003', '90006', '87004', '87003', '90005')
		AND RCT.ORG_ID IN(456, 457) -- US TCS and CA TCS  Only
		AND RCTL.LINE_TYPE = 'LINE'  -- eliminates Tax
		AND RCTGD.GL_DATE > '01-OCT-16' 
		AND RCT.COMPLETE_FLAG = 'Y'  -- no change
		AND NVL(RCTGD.LATEST_REC_FLAG, 'Y') = 'Y'
		AND RCTGD.ACCOUNT_CLASS = 'REV'
		AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL'
		AND XDL.APPLICATION_ID = 222
and rctgd.percent >= 99.9999 and rctgd.percent <= 100.0001
and GCC.GL_ACCOUNT_TYPE = 'R'
group by
		RCT.TRX_NUMBER,
		RCT.CUSTOMER_TRX_ID,
		RCTL.LINE_NUMBER
-- order by rctgd.customer_trx_line_id
order by 4 desc;


-- where GL_ACCOUNT_TYPE = 'R' are there PERCENT != 100?
SELECT
		RCT.TRX_NUMBER AS INVOICE,
		RCT.CUSTOMER_TRX_ID AS CUSTOMER_TRX_ID,
		RCTL.LINE_NUMBER AS LINE_SEQ_NUM,
		rctgd.percent
	FROM
		RA_CUSTOMER_TRX_ALL RCT
	INNER JOIN RA_BATCH_SOURCES_ALL RBS           ON RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID AND RBS.ORG_ID = RCT.ORG_ID
	INNER JOIN RA_CUSTOMER_TRX_LINES_ALL RCTL ON RCTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
	INNER JOIN RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD ON RCTGD.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID and rctgd.CUSTOMER_TRX_LINE_ID = rctl.CUSTOMER_TRX_LINE_ID
	INNER JOIN XLA_DISTRIBUTION_LINKS XDL
		ON RCTGD.CUST_TRX_LINE_GL_DIST_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
		AND RCTGD.EVENT_ID = XDL.EVENT_ID
	INNER JOIN XLA_AE_LINES AEL                   ON XDL.AE_HEADER_ID = AEL.AE_HEADER_ID AND XDL.AE_LINE_NUM = AEL.AE_LINE_NUM
	LEFT OUTER JOIN GL_IMPORT_REFERENCES GIR      ON GIR.GL_SL_LINK_TABLE = AEL.GL_SL_LINK_TABLE AND GIR.GL_SL_LINK_ID = AEL.GL_SL_LINK_ID
	LEFT OUTER JOIN GL_JE_LINES GJL               ON GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
	LEFT JOIN GL_JE_HEADERS GJH                   ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
	LEFT JOIN GL_CODE_COMBINATIONS_KFV GCC        ON AEL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
WHERE 0=0 -- ROWNUM < 10
		AND RCT.ATTRIBUTE9 = '7'
		AND RBS.BATCH_SOURCE_ID IN('90003', '90006', '87004', '87003', '90005')
		AND RCT.ORG_ID IN(456, 457) -- US TCS and CA TCS  Only
		AND RCTL.LINE_TYPE = 'LINE'  -- eliminates Tax
		AND RCTGD.GL_DATE > '01-OCT-16' 
		AND RCT.COMPLETE_FLAG = 'Y'  -- no change
		AND NVL(RCTGD.LATEST_REC_FLAG, 'Y') = 'Y'
		AND RCTGD.ACCOUNT_CLASS = 'REV'
		AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL'
		AND XDL.APPLICATION_ID = 222
and (rctgd.percent < 99.9999 or rctgd.percent > 100.0001)
and GCC.GL_ACCOUNT_TYPE = 'R'
;

		select rctgd.account_class, rctgd.comments, count(*)
		from RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD
		group by rctgd.account_class, rctgd.comments;

select distinct comments from RA_CUST_TRX_LINE_GL_DIST_ALL where percent = 100;

SELECT
		RCT.TRX_NUMBER AS INVOICE,
		RCT.CUSTOMER_TRX_ID AS CUSTOMER_TRX_ID,
		RCTL.LINE_NUMBER AS LINE_SEQ_NUM,
		ael.ae_line_num,
		gir.reference_8,
		GCC.GL_ACCOUNT_TYPE, -- R
		GCC.SEGMENT4 AS GL_ACCOUNT, -- 411101
		rctgd.percent,
		GJH.NAME AS JOURNAL_ID,
--		RCTL.LINE_TYPE,
		rctl.revenue_amount,
		rctgd.cust_trx_line_gl_dist_id,
		rctgd.event_id,
		GCC.*
/*	
		RCT.COMPLETE_FLAG,
		RCT.REASON_CODE AS ACCT_ENTRY_TYPE,
		RCT.INVOICE_CURRENCY_CODE AS CURRENCY_CD,
		RCTGD.LATEST_REC_FLAG,
		RCTGD.ACCOUNT_CLASS,
		RCTGD.AMOUNT AS MONETARY_AMOUNT,
		RCTGD.GL_DATE AS JOURNAL_DATE
*/		
	FROM
		RA_CUSTOMER_TRX_ALL RCT
	INNER JOIN RA_BATCH_SOURCES_ALL RBS           ON RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID AND RBS.ORG_ID = RCT.ORG_ID
	INNER JOIN RA_CUSTOMER_TRX_LINES_ALL RCTL ON RCTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
	INNER JOIN RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD ON RCTGD.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID and rctgd.CUSTOMER_TRX_LINE_ID = rctl.CUSTOMER_TRX_LINE_ID
	INNER JOIN XLA_DISTRIBUTION_LINKS XDL
		ON RCTGD.CUST_TRX_LINE_GL_DIST_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1
		AND RCTGD.EVENT_ID = XDL.EVENT_ID
	INNER JOIN XLA_AE_LINES AEL                   ON XDL.AE_HEADER_ID = AEL.AE_HEADER_ID AND XDL.AE_LINE_NUM = AEL.AE_LINE_NUM
	LEFT OUTER JOIN GL_IMPORT_REFERENCES GIR      ON GIR.GL_SL_LINK_TABLE = AEL.GL_SL_LINK_TABLE AND GIR.GL_SL_LINK_ID = AEL.GL_SL_LINK_ID
	LEFT OUTER JOIN GL_JE_LINES GJL               ON GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
	LEFT JOIN GL_JE_HEADERS GJH                   ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
	LEFT JOIN GL_CODE_COMBINATIONS_KFV GCC        ON AEL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
WHERE 0=0 -- ROWNUM < 10
	AND RCT.ATTRIBUTE9 = '7'
	AND RBS.BATCH_SOURCE_ID IN('90003', '90006', '87004', '87003', '90005')
	AND RCT.ORG_ID IN(456, 457) -- US TCS and CA TCS  Only
	AND RCTL.LINE_TYPE = 'LINE'  -- eliminates Tax
	--AND RCTL.LINE_NUMBER = 1 (do not use drops multi-line item data)
	AND RCTGD.GL_DATE > '01-OCT-16' 
	AND RCT.COMPLETE_FLAG = 'Y'  -- no change
	AND NVL(RCTGD.LATEST_REC_FLAG, 'Y') = 'Y'
	AND RCTGD.ACCOUNT_CLASS = 'REV'
	-- AND RCTGD.percent = 100
	AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL'
	AND XDL.APPLICATION_ID = 222
	AND GJH.JE_SOURCE = 'Receivables'
--		AND RCT.TRX_NUMBER IN('1521904', '1519059')
AND RCT.TRX_NUMBER = '50011837'
order by 1, 3, 4;

SELECT COUNT(*) cnt, count(distinct RCT.TRX_NUMBER) numTransactions
	FROM
		RA_CUSTOMER_TRX_ALL RCT
	INNER JOIN RA_CUSTOMER_TRX_LINES_ALL RCTL     ON RCTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
	INNER JOIN RA_BATCH_SOURCES_ALL RBS           ON RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID AND RBS.ORG_ID = RCT.ORG_ID
	INNER JOIN RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD ON RCTGD.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID -- and rctgd.CUSTOMER_TRX_LINE_ID = rctl.CUSTOMER_TRX_LINE_ID
	INNER JOIN XLA_DISTRIBUTION_LINKS XDL         ON RCTGD.CUST_TRX_LINE_GL_DIST_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1 AND RCTGD.EVENT_ID = XDL.EVENT_ID
-- base trans and lines
	INNER JOIN XLA_AE_LINES AEL                   ON XDL.AE_HEADER_ID = AEL.AE_HEADER_ID AND XDL.AE_LINE_NUM = AEL.AE_LINE_NUM
	LEFT OUTER JOIN GL_IMPORT_REFERENCES GIR      ON GIR.GL_SL_LINK_TABLE = AEL.GL_SL_LINK_TABLE AND GIR.GL_SL_LINK_ID = AEL.GL_SL_LINK_ID
	LEFT OUTER JOIN GL_JE_LINES GJL               ON GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
	LEFT JOIN GL_JE_HEADERS GJH                   ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
	LEFT JOIN GL_CODE_COMBINATIONS_KFV GCC        ON AEL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
	WHERE
		0 = 0
		AND RCT.ATTRIBUTE9 = '7'
		AND RBS.BATCH_SOURCE_ID IN('90003', '90006', '87004', '87003', '90005')
		AND RCT.ORG_ID IN(456, 457) -- US TCS and CA TCS  Only
		AND RCTL.LINE_TYPE = 'LINE'  -- eliminates Tax
		-- AND RCTGD.GL_DATE > '01-OCT-16' 
		-- AND RCTL.LINE_NUMBER = 1
		AND RCT.COMPLETE_FLAG = 'Y'  -- no change
		AND NVL(RCTGD.LATEST_REC_FLAG, 'Y') = 'Y'
		AND RCTGD.ACCOUNT_CLASS = 'REV'
		AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL'
		AND XDL.APPLICATION_ID = 222
		AND GJH.JE_SOURCE = 'Receivables'
and gcc.segment4 = '411101' and (rctgd.percent >= 99.9999 and rctgd.percent <= 100.0001)
and RCTGD.GL_DATE between to_date('01-OCT-16') and to_date('31-OCT-16');
-- 3146936	136208

SELECT 
		RCT.TRX_NUMBER,
		RCT.CUSTOMER_TRX_ID,
		RCTL.LINE_NUMBER,
count(distinct RCTL.revenue_amount)
	FROM
		RA_CUSTOMER_TRX_ALL RCT
	INNER JOIN RA_CUSTOMER_TRX_LINES_ALL RCTL     ON RCTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
	INNER JOIN RA_BATCH_SOURCES_ALL RBS           ON RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID AND RBS.ORG_ID = RCT.ORG_ID
	INNER JOIN RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD ON RCTGD.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID -- and rctgd.CUSTOMER_TRX_LINE_ID = rctl.CUSTOMER_TRX_LINE_ID
	INNER JOIN XLA_DISTRIBUTION_LINKS XDL         ON RCTGD.CUST_TRX_LINE_GL_DIST_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1 AND RCTGD.EVENT_ID = XDL.EVENT_ID
-- base trans and lines
	INNER JOIN XLA_AE_LINES AEL                   ON XDL.AE_HEADER_ID = AEL.AE_HEADER_ID AND XDL.AE_LINE_NUM = AEL.AE_LINE_NUM
	LEFT OUTER JOIN GL_IMPORT_REFERENCES GIR      ON GIR.GL_SL_LINK_TABLE = AEL.GL_SL_LINK_TABLE AND GIR.GL_SL_LINK_ID = AEL.GL_SL_LINK_ID
	LEFT OUTER JOIN GL_JE_LINES GJL               ON GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
	LEFT JOIN GL_JE_HEADERS GJH                   ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
	LEFT JOIN GL_CODE_COMBINATIONS_KFV GCC        ON AEL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
	WHERE
		0 = 0
		AND RCT.ATTRIBUTE9 = '7'
		AND RBS.BATCH_SOURCE_ID IN('90003', '90006', '87004', '87003', '90005')
		AND RCT.ORG_ID IN(456, 457) -- US TCS and CA TCS  Only
		AND RCTL.LINE_TYPE = 'LINE'  -- eliminates Tax
		-- AND RCTGD.GL_DATE > '01-OCT-16' 
		-- AND RCTL.LINE_NUMBER = 1
		AND RCT.COMPLETE_FLAG = 'Y'  -- no change
		AND NVL(RCTGD.LATEST_REC_FLAG, 'Y') = 'Y'
		AND RCTGD.ACCOUNT_CLASS = 'REV'
		AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL'
		AND XDL.APPLICATION_ID = 222
		AND GJH.JE_SOURCE = 'Receivables'
and gcc.segment4 = '411101' and (rctgd.percent >= 99.9999 and rctgd.percent <= 100.0001)
and RCTGD.GL_DATE between to_date('01-OCT-16') and to_date('31-OCT-16')
group by
		RCT.TRX_NUMBER,
		RCT.CUSTOMER_TRX_ID,
		RCTL.LINE_NUMBER
order by 4 desc
;

SELECT 
		RCT.TRX_NUMBER,
		RCT.CUSTOMER_TRX_ID,
max(RCTL.LINE_NUMBER) as max_line
	FROM
		RA_CUSTOMER_TRX_ALL RCT
	INNER JOIN RA_CUSTOMER_TRX_LINES_ALL RCTL     ON RCTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
	INNER JOIN RA_BATCH_SOURCES_ALL RBS           ON RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID AND RBS.ORG_ID = RCT.ORG_ID
	INNER JOIN RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD ON RCTGD.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID -- and rctgd.CUSTOMER_TRX_LINE_ID = rctl.CUSTOMER_TRX_LINE_ID
	INNER JOIN XLA_DISTRIBUTION_LINKS XDL         ON RCTGD.CUST_TRX_LINE_GL_DIST_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1 AND RCTGD.EVENT_ID = XDL.EVENT_ID
-- base trans and lines
	INNER JOIN XLA_AE_LINES AEL                   ON XDL.AE_HEADER_ID = AEL.AE_HEADER_ID AND XDL.AE_LINE_NUM = AEL.AE_LINE_NUM
	LEFT OUTER JOIN GL_IMPORT_REFERENCES GIR      ON GIR.GL_SL_LINK_TABLE = AEL.GL_SL_LINK_TABLE AND GIR.GL_SL_LINK_ID = AEL.GL_SL_LINK_ID
	LEFT OUTER JOIN GL_JE_LINES GJL               ON GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
	LEFT JOIN GL_JE_HEADERS GJH                   ON GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
	LEFT JOIN GL_CODE_COMBINATIONS_KFV GCC        ON AEL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
	WHERE
		0 = 0
		AND RCT.ATTRIBUTE9 = '7'
		AND RBS.BATCH_SOURCE_ID IN('90003', '90006', '87004', '87003', '90005')
		AND RCT.ORG_ID IN(456, 457) -- US TCS and CA TCS  Only
		AND RCTL.LINE_TYPE = 'LINE'  -- eliminates Tax
		-- AND RCTGD.GL_DATE > '01-OCT-16' 
		-- AND RCTL.LINE_NUMBER = 1
		AND RCT.COMPLETE_FLAG = 'Y'  -- no change
		AND NVL(RCTGD.LATEST_REC_FLAG, 'Y') = 'Y'
		AND RCTGD.ACCOUNT_CLASS = 'REV'
		AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL'
		AND XDL.APPLICATION_ID = 222
		AND GJH.JE_SOURCE = 'Receivables'
and gcc.segment4 = '411101' and (rctgd.percent >= 99.9999 and rctgd.percent <= 100.0001)
and RCTGD.GL_DATE between to_date('01-OCT-16') and to_date('31-OCT-16')
group by
		RCT.TRX_NUMBER,
		RCT.CUSTOMER_TRX_ID,
		RCTL.LINE_NUMBER
order by 3 desc
;

