select
'unknown' as BILL_SOURCE_ID,
RCT.REASON_CODE as ENTRY_TYPE,
RCT.TRX_NUMBER as INVOICE,
RCT.CUSTOMER_TRX_ID,
null as PS_BUSINESS_UNIT
from
RA_CUSTOMER_TRX_ALL RCT
where RCT.REASON_CODE = 'P21';
