SELECT
		RBS.NAME AS BILL_SOURCE_ID,
		RCT.REASON_CODE AS ENTRY_TYPE,
		RCT.TRX_NUMBER AS INVOICE,
		RCT.CUSTOMER_TRX_ID,
		'NA' AS PS_BUSINESS_UNIT
	FROM
		RA_CUSTOMER_TRX_ALL RCT
	INNER JOIN RA_BATCH_SOURCES_ALL RBS ON RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID AND RBS.ORG_ID = RCT.ORG_ID
	WHERE
		0 = 0
		AND RCT.ATTRIBUTE9 = '7'
		AND RBS.BATCH_SOURCE_ID IN('90003', '90006', '87004', '87003', '90005')
		AND RCT.ORG_ID IN(456, 457) ;