select
'NA' as BUSINESS_UNIT,
RCT.TRX_NUMBER as INVOICE,
RCTL.LINE_NUMBER LINE_SEQ_NUM,
GCC.SEGMENT5 as R12_PRODUCT,
'' as SRC_ED_CREATE_DATE,
'' as SRC_ED_CREATE_ID,
'' as ED_CREATE_DATE,
'' as ED_CREATE_ID,
RCT.CUSTOMER_TRX_ID as CUSTOMER_TRX_ID,
(
	SELECT
			/* MIC.SEGMENT1||'.'|| MIC.SEGMENT2 ||'.'|| MIC.SEGMENT3 ||'.'|| MIC.SEGMENT4 ||'.'|| MIC.SEGMENT5 ||'.'|| */ MIC.SEGMENT6
		FROM
			MTL_ITEM_CATEGORIES_V MIC,
			MTL_SYSTEM_ITEMS MSI1
		WHERE
			MIC.INVENTORY_ITEM_ID = MSI1.INVENTORY_ITEM_ID
			AND MSI1.SEGMENT1 = DECODE(RBS.NAME, 'P21', SUBSTR(RCTL.DESCRIPTION, 1, INSTR(RCTL.DESCRIPTION, '~', 1, 1) - 1), MSI.SEGMENT1)
			AND MIC.CATEGORY_SET_NAME = 'IRPLN SIOP CATEGORY'
			AND MIC.ORGANIZATION_ID = MSI1.ORGANIZATION_ID
			AND MSI1.ORGANIZATION_ID = NVL(RCTL.WAREHOUSE_ID, 99)
			AND ROWNUM = 1
)
as MANF_PROD_CODE
from
RA_CUSTOMER_TRX_ALL RCT
inner join RA_CUSTOMER_TRX_LINES_ALL RCTL on RCTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
inner join RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD on RCTGD.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID AND NVL(RCTGD.CUSTOMER_TRX_LINE_ID, RCTL.CUSTOMER_TRX_LINE_ID) = RCTL.CUSTOMER_TRX_LINE_ID
inner join XLA_DISTRIBUTION_LINKS XDL on RCTGD.CUST_TRX_LINE_GL_DIST_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1 AND RCTGD.EVENT_ID = XDL.EVENT_ID
inner join XLA_AE_LINES AEL on XDL.AE_HEADER_ID = AEL.AE_HEADER_ID AND XDL.AE_LINE_NUM = AEL.AE_LINE_NUM
inner join GL_CODE_COMBINATIONS_KFV GCC on AEL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
inner join RA_BATCH_SOURCES_ALL RBS on RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID AND RBS.ORG_ID = RCT.ORG_ID
left outer join MTL_SYSTEM_ITEMS MSI on MSI.INVENTORY_ITEM_ID = RCTL.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID = NVL(RCTL.WAREHOUSE_ID, 99)
where 1=1
AND RCTGD.ACCOUNT_CLASS <> 'REC' -- ????
AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL' -- ????
AND XDL.APPLICATION_ID = 222 -- ????
;
