SELECT hdr.invoice, hdr.customer_trx_id, bae.line_seq_num, count(*)
	FROM
		R12_BI_HDR_STG HDR
	INNER JOIN R12_TRNBI_BI_HDR_STG TBH  ON HDR.INVOICE = TBH.INVOICE AND HDR.CUSTOMER_TRX_ID = TBH.CUSTOMER_TRX_ID
	INNER JOIN R12_BI_ACCT_ENTRY_STG BAE ON HDR.INVOICE = BAE.INVOICE AND HDR.CUSTOMER_TRX_ID = BAE.CUSTOMER_TRX_ID
--	INNER JOIN R12_BI_LINE_STG LIN       ON HDR.LINE_SEQ_NUM = LIN.LINE_SEQ_NUM AND HDR.INVOICE = LIN.INVOICE AND HDR.CUSTOMER_TRX_ID = LIN.CUSTOMER_TRX_ID
		--INNER JOIN R12_ACCOUNT_FILTER_UPD AFU    ON AFU.R12_ACCOUNT = D.R12_ACCOUNT
		--    INNER JOIN OTR_PROD_CODE_XREF_RCPO X     ON A.MANF_PROD_ID = X.MANF_PROD_CODE
		--    LEFT OUTER JOIN R12_TRANE_PRODUCTS_PS PR ON D.R12_PRODUCT = PR.R12_PRODUCT
		--    LEFT OUTER JOIN R12_TRANE_LOCATIONS DP   ON DP.R12_LOCATION = D.R12_LOCATION
	WHERE
		0 = 0
		and HDR.INVOICE in (1521904,1519059)	-- 
--		and HDR.CUSTOMER_TRX_ID in (50381339, 50381342)
--		AND D.JOURNAL_DATE BETWEEN '01-oct-16' AND '31-oct-16'
		--AND B.BILL_SOURCE_ID = 'P21'
		--AND B.BILL_SOURCE_ID = 'ORDER ENTRY'
		--AND B.BILL_SOURCE_ID = 'TCS MANUAL'
		--group by  A.MANF_PROD_ID
		--AND C.TRNBI_PROJECT_TYPE = '7'
		--AND D.LEDGER = 'ACTUALS'
		--AND X.TWO_FIVE = 'Y'
		/*
		AND X.GL_LEDGER = 'CSD'
		AND AFU.EQUAL_700000 = 'Y'
		AND D.R12_PRODUCT <> '41208'
		AND D.R12_PRODUCT <> '41399'
		AND D.R12_PRODUCT <> '41132'
		AND D.R12_PRODUCT <> '41499'
		AND D.R12_PRODUCT <> '41205'
		*/
		group by hdr.invoice, hdr.customer_trx_id, bae.line_seq_num
		order by 1, 2, 3, 4
	
		;
SELECT COUNT( *) FROM R12_BI_LINE_STG;  -- 973K
SELECT COUNT( *) FROM R12_BI_ACCT_ENTRY_STG; --37 Million
SELECT COUNT( *) FROM R12_BI_HDR_STG; -- 117774
SELECT COUNT( *) FROM R12_TRNBI_BI_HDR_STG; -- 117775

select ed_create_date, count(*) from R12_BI_HDR_STG group by ed_create_date;
select distinct * from r12_bi_line_stg where invoice = 1521904 and line_seq_num = 1;

select distinct ed_create_date, count(*) from r12_bi_line_stg group by ed_create_date;