-- R12_TRNBI_BI_HDR_PSB;
select
'NA' as BUSINESS_UNIT,
RCT.TRX_NUMBER as INVOICE,
RCT.ATTRIBUTE9 as TRNBI_PROJECT_TYPE,
'' as SRC_ED_CREATE_DATE,
'' as SRC_ED_CREATE_ID,
'' as ED_CREATE_DATE,
'' as ED_CREATE_ID,
RCT.CUSTOMER_TRX_ID as CUSTOMER_TRX_ID
from
RA_CUSTOMER_TRX_ALL RCT;
