SELECT
		FFVC3.DESCRIPTION
	FROM
		FND_FLEX_VALUES_VL FFVC
		INNER JOIN FND_FLEX_VALUES_VL FFVC1 on FFVC1.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
		INNER JOIN FND_FLEX_VALUES_VL FFVC2 on FFVC2.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
		INNER JOIN FND_FLEX_VALUES_VL FFVC3 on FFVC3.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
		INNER JOIN FND_FLEX_VALUE_NORM_HIERARCHY FFVCP1 on FFVC1.FLEX_VALUE = FFVCP1.PARENT_FLEX_VALUE AND FFVCP1.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
		INNER JOIN FND_FLEX_VALUE_NORM_HIERARCHY FFVCP2 on FFVC2.FLEX_VALUE = FFVCP2.PARENT_FLEX_VALUE AND FFVCP2.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
  INNER JOIN FND_FLEX_VALUE_NORM_HIERARCHY FFVCP3 on FFVC3.FLEX_VALUE = FFVCP3.PARENT_FLEX_VALUE AND FFVCP3.FLEX_VALUE_SET_ID = FFVC.FLEX_VALUE_SET_ID
	WHERE 0=0
		AND FFVC.FLEX_VALUE_SET_ID = 1014929
		AND FFVC.ENABLED_FLAG = 'Y'
		AND FFVC.FLEX_VALUE BETWEEN FFVCP1.CHILD_FLEX_VALUE_LOW AND FFVCP1.CHILD_FLEX_VALUE_HIGH
		AND FFVCP1.PARENT_FLEX_VALUE LIKE 'P%'
		--AND ffvcp1.RANGE_ATTRIBUTE ='C'
		AND SYSDATE BETWEEN NVL(FFVCP1.START_DATE_ACTIVE, SYSDATE) AND NVL(FFVCP1.END_DATE_ACTIVE, SYSDATE)
		AND FFVCP2.PARENT_FLEX_VALUE LIKE 'P%'
		--AND ffvcp2.RANGE_ATTRIBUTE ='C'
		AND SYSDATE BETWEEN NVL(FFVCP2.START_DATE_ACTIVE, SYSDATE) AND NVL(FFVCP2.END_DATE_ACTIVE, SYSDATE)
		AND FFVCP1.PARENT_FLEX_VALUE BETWEEN FFVCP2.CHILD_FLEX_VALUE_LOW AND FFVCP2.CHILD_FLEX_VALUE_HIGH
		AND FFVCP3.PARENT_FLEX_VALUE LIKE 'P%'
		--AND ffvcp2.RANGE_ATTRIBUTE ='C'
		AND SYSDATE BETWEEN NVL(FFVCP3.START_DATE_ACTIVE, SYSDATE) AND NVL(FFVCP3.END_DATE_ACTIVE, SYSDATE)
		AND FFVCP2.PARENT_FLEX_VALUE BETWEEN FFVCP3.CHILD_FLEX_VALUE_LOW AND FFVCP3.CHILD_FLEX_VALUE_HIGH
		AND FFVC1.ENABLED_FLAG = 'Y'
		AND FFVC2.ENABLED_FLAG = 'Y'
		AND FFVC3.ENABLED_FLAG = 'Y'
		AND ROWNUM = 1;