SELECT DISTINCT
		CLAIM.CLAIM_NUMBER,
		CLAIM.TYPE,
		COMMERCIAL_POLICY,
		CLAIMED_ITEM.ITEM_REF_INV_ITEM,
		CLAIM.FAILURE_DATE,
		INVENTORY_ITEM.SHIPMENT_DATE,
		INVENTORY_ITEM.DELIVERY_DATE AS START_DATE,
		SALES_ORDER.SALES_ORDER_NUMBER,
		SALES_ORDER.MFG,
		SERIAL_NUMBER,
		SALES_ORDER.ORIGINAL_SOURCE_ID,
		SIOP_SEGMENT1,
		SIOP_SEGMENT2,
		SIOP_SEGMENT3,
		SIOP_SEGMENT4,
		SIOP_SEGMENT5,
		SIOP_SEGMENT6,
		POLICY_DEFINITION.CODE,
		POLICY_DEFINITION.DESCRIPTION,
		POLICY_DEFINITION.PRIORITY,
		--   policy.till_date, Policy till date is not showing correctly Mohit reviewed sql but needs to investigate further
		POLICY_DEFINITION.WARRANTY_TYPE,
		POLICY_DEFINITION.MONTHS_FRM_DELIVERY,
		POLICY_DEFINITION.MONTHS_FRM_SHIPMENT,
		TRUE_COVERAGE_MONTHS,
		LINE_ITEM_GROUP.NAME,
--		LINE_ITEM_GROUP.GL_AMT,
		GL_CODE_WNTY_EXPENSE_REV,
		Line_Item_Group.Accepted_Amt
	FROM
		CLAIM
	INNER JOIN CLAIMED_ITEM           ON CLAIM.ID = CLAIMED_ITEM.CLAIM
	INNER JOIN INVENTORY_ITEM         ON CLAIMED_ITEM.ITEM_REF_INV_ITEM = INVENTORY_ITEM.ID
	INNER JOIN ITEM                   ON ITEM.ID = INVENTORY_ITEM.OF_TYPE
	INNER JOIN SALES_ORDER            ON INVENTORY_ITEM.FOR_SALES_ORDER = SALES_ORDER.ID
	INNER JOIN WARRANTY               ON WARRANTY.FOR_ITEM = INVENTORY_ITEM.ID
	INNER JOIN PAYMENT                ON CLAIM.PAYMENT = PAYMENT.ID
	INNER JOIN LINE_ITEM_GROUPS       ON PAYMENT.ID = LINE_ITEM_GROUPS.FOR_PAYMENT
	INNER JOIN LINE_ITEM_GROUP        ON LINE_ITEM_GROUPS.LINE_ITEM_GROUPS = LINE_ITEM_GROUP.ID
	LEFT OUTER JOIN APPLICABLE_POLICY ON LINE_ITEM_GROUP.APPLICABLE_POLICY = APPLICABLE_POLICY.ID -- LINE_ITEM_GROUP.APPLICABLE_POLICY can be null
	LEFT OUTER JOIN POLICY            ON WARRANTY.ID = POLICY.WARRANTY
	LEFT OUTER JOIN POLICY_DEFINITION ON APPLICABLE_POLICY.POLICY_DEFINITION = POLICY_DEFINITION.ID
	WHERE
		0 = 0
		AND CLAIM.FILED_ON_DATE > '13-NOV-2016'
		AND claim.business_unit_info = 'HVAC TCP' --Jean Skemp recommends using original source id instead
		AND STATE = 'ACCEPTED_AND_CLOSED'
		AND ORIGINAL_SOURCE_ID IN('CS', 'GP')
		--AND CLAIM.CLAIM_NUMBER = 'C-10764041'
		--AND CLAIM.CLAIM_NUMBER = 'C-10764014'
		AND CLAIM.CLAIM_NUMBER = 'C-10764437' 
		--and inventory_item.serial_number like 'R14G59044'
		
		--and line_item_group.name = 'Others'
		and accepted_amt <> 0
		ORDER BY claim_number, serial_number
		;


select distinct name from LINE_ITEM_GROUP order by 1;

select distinct warranty_type,
commercial_policy,
CLAIM.TYPE
FROM
		CLAIM
	INNER JOIN CLAIMED_ITEM           ON CLAIM.ID = CLAIMED_ITEM.CLAIM
	INNER JOIN INVENTORY_ITEM         ON CLAIMED_ITEM.ITEM_REF_INV_ITEM = INVENTORY_ITEM.ID
	INNER JOIN ITEM                   ON ITEM.ID = INVENTORY_ITEM.OF_TYPE
	INNER JOIN SALES_ORDER            ON INVENTORY_ITEM.FOR_SALES_ORDER = SALES_ORDER.ID
	INNER JOIN WARRANTY               ON WARRANTY.FOR_ITEM = INVENTORY_ITEM.ID
	INNER JOIN PAYMENT                ON CLAIM.PAYMENT = PAYMENT.ID
	INNER JOIN LINE_ITEM_GROUPS       ON PAYMENT.ID = LINE_ITEM_GROUPS.FOR_PAYMENT
	INNER JOIN LINE_ITEM_GROUP        ON LINE_ITEM_GROUPS.LINE_ITEM_GROUPS = LINE_ITEM_GROUP.ID
	LEFT OUTER JOIN APPLICABLE_POLICY ON LINE_ITEM_GROUP.APPLICABLE_POLICY = APPLICABLE_POLICY.ID -- LINE_ITEM_GROUP.APPLICABLE_POLICY can be null
	LEFT OUTER JOIN POLICY            ON WARRANTY.ID = POLICY.WARRANTY
	LEFT OUTER JOIN POLICY_DEFINITION ON APPLICABLE_POLICY.POLICY_DEFINITION = POLICY_DEFINITION.ID
;