SELECT DISTINCT
		CLAIM.CLAIM_NUMBER,
		CLAIM.TYPE,
		CLAIM.COMMERCIAL_POLICY,
		CLAIMED_ITEM.ITEM_REF_INV_ITEM,
		CLAIM.FAILURE_DATE,
		INVENTORY_ITEM.SHIPMENT_DATE,
		INVENTORY_ITEM.DELIVERY_DATE AS START_DATE,
		SALES_ORDER.SALES_ORDER_NUMBER,
		SALES_ORDER.MFG,
		SERIAL_NUMBER,
		SALES_ORDER.ORIGINAL_SOURCE_ID,
		SIOP_SEGMENT1,
		SIOP_SEGMENT2,
		SIOP_SEGMENT3,
		SIOP_SEGMENT4,
		SIOP_SEGMENT5,
		SIOP_SEGMENT6,
		POLICY_DEFINITION.CODE,
		POLICY_DEFINITION.DESCRIPTION,
		POLICY_DEFINITION.PRIORITY,
		--   policy.till_date, Policy till date is not showing correctly Mohit reviewed sql but needs to investigate further
		POLICY_DEFINITION.WARRANTY_TYPE,
		POLICY_DEFINITION.MONTHS_FRM_DELIVERY,
		POLICY_DEFINITION.MONTHS_FRM_SHIPMENT,
		POLICY_DEFINITION.TRUE_COVERAGE_MONTHS,
		COMP_OWN.COMP_OWN
	FROM
		CLAIM
	INNER JOIN CLAIMED_ITEM      ON CLAIM.ID = CLAIMED_ITEM.CLAIM
	INNER JOIN INVENTORY_ITEM    ON CLAIMED_ITEM.ITEM_REF_INV_ITEM = INVENTORY_ITEM.ID
	INNER JOIN ITEM              ON ITEM.ID = INVENTORY_ITEM.OF_TYPE
	INNER JOIN SALES_ORDER       ON INVENTORY_ITEM.FOR_SALES_ORDER = SALES_ORDER.ID
	INNER JOIN WARRANTY          ON WARRANTY.FOR_ITEM = INVENTORY_ITEM.ID
	INNER JOIN PAYMENT           ON CLAIM.PAYMENT = PAYMENT.ID
	INNER JOIN LINE_ITEM_GROUPS  ON PAYMENT.ID = LINE_ITEM_GROUPS.FOR_PAYMENT
	INNER JOIN LINE_ITEM_GROUP   ON LINE_ITEM_GROUPS.LINE_ITEM_GROUPS = LINE_ITEM_GROUP.ID
	INNER JOIN APPLICABLE_POLICY ON LINE_ITEM_GROUP.APPLICABLE_POLICY = APPLICABLE_POLICY.ID -- LINE_ITEM_GROUP.APPLICABLE_POLICY can be null
	INNER JOIN POLICY            ON WARRANTY.ID = POLICY.WARRANTY
	INNER JOIN POLICY_DEFINITION ON APPLICABLE_POLICY.POLICY_DEFINITION = POLICY_DEFINITION.ID
	LEFT OUTER JOIN 
		(SELECT DISTINCT DECODE(INSTR(UPPER(DG.NAME), 'INDEPENDENT'), 0, 'YES', 'NO') COMP_OWN, C.CLAIM_NUMBER FROM CLAIM C
				INNER JOIN SERVICE_PROVIDER SP  ON C.FOR_DEALER = SP.ID
				INNER JOIN DEALERS_IN_GROUP DIG ON DIG.DEALER = SP.ID
				INNER JOIN DEALER_GROUP DG      ON DIG.DEALER_GROUP = DG.ID
		)
		COMP_OWN ON COMP_OWN.CLAIM_NUMBER = CLAIM.CLAIM_NUMBER
	WHERE
		0 = 0
		AND CLAIM.FILED_ON_DATE > '13-NOV-2016'
		--AND claim.business_unit_info = 'HVAC TCP' --Jean Skemp recommends using original source id insteal
		AND STATE = 'ACCEPTED_AND_CLOSED'
		AND ORIGINAL_SOURCE_ID IN('CS', 'GP')
		and claim.claim_number = 'C-10764292'
		--and inventory_item.serial_number like '11492KBA3R'
		--ORDER BY claim, serial_number, priority
	;