SELECT DISTINCT
		C.CLAIM_NUMBER,
		II.SERIAL_NUMBER,
		C.TYPE,
		C.COMMERCIAL_POLICY,
		PD.WARRANTY_TYPE,
		months_between(C.FAILURE_DATE, II.SHIPMENT_DATE) fail2ship,
		months_between(C.FAILURE_DATE, II.DELIVERY_DATE) fail2start,
		LIG.NAME,
		LIG.ACCEPTED_AMT,
		C.FAILURE_DATE,
		II.SHIPMENT_DATE,
		II.DELIVERY_DATE AS START_DATE,
		SO.SALES_ORDER_NUMBER,
		SO.MFG,
		SO.ORIGINAL_SOURCE_ID,
		SIOP_SEGMENT1,
		SIOP_SEGMENT2,
		SIOP_SEGMENT3,
		SIOP_SEGMENT4,
		SIOP_SEGMENT5,
		SIOP_SEGMENT6,
		PD.CODE,
		PD.DESCRIPTION,
		PD.PRIORITY,
		--   pol.till_date, Policy till date is not showing correctly Mohit reviewed sql but needs to investigate further
		PD.MONTHS_FRM_DELIVERY,
		PD.MONTHS_FRM_SHIPMENT,
		PD.TRUE_COVERAGE_MONTHS,
		DEALER_GRP.COMP_OWN,
		DEALER_GRP.INTERNAL,
		DEALER_GRP.DEALER_GROUP_NAME
	FROM
		CLAIM C
	INNER JOIN CLAIMED_ITEM CI     ON C.ID = CI.CLAIM
	INNER JOIN INVENTORY_ITEM II   ON CI.ITEM_REF_INV_ITEM = II.ID
	INNER JOIN ITEM    I          ON I.ID = II.OF_TYPE
	INNER JOIN SALES_ORDER SO       ON II.FOR_SALES_ORDER = SO.ID
	INNER JOIN WARRANTY W         ON W.FOR_ITEM = II.ID
	INNER JOIN PAYMENT P          ON C.PAYMENT = P.ID
	INNER JOIN LINE_ITEM_GROUPS LIGS  ON P.ID = LIGS.FOR_PAYMENT
	INNER JOIN LINE_ITEM_GROUP LIG  ON LIGS.LINE_ITEM_GROUPS = LIG.ID
	INNER JOIN APPLICABLE_POLICY AP ON LIG.APPLICABLE_POLICY = AP.ID -- LIG.APPLICABLE_POLICY can be null
	INNER JOIN POLICY POL            ON W.ID = POL.WARRANTY
	INNER JOIN POLICY_DEFINITION PD ON AP.POLICY_DEFINITION = PD.ID
		--INNER JOIN POLICY_DEFINITION ON POL.POLICY_DEFINITION = PD.ID
	LEFT OUTER JOIN
		(SELECT DISTINCT DECODE(INSTR(UPPER(DG.NAME), 'INDEPENDENT'), 0, 'YES', 'NO') COMP_OWN, 
			DECODE(UPPER(DG.NAME),
				'USA COMPANY OWNED PARTS', 'YES', 
				'USA COMPANY OWNED SERVICE', 'YES', 
				'CANADA COMPANY OWNED PARTS', 'YES', 
				'CANADA COMPANY OWNED SERVICE', 'YES', 
			'NO') as INTERNAL,
			dg.name dealer_group_name,
			C.CLAIM_NUMBER 
			FROM CLAIM C
			INNER JOIN SERVICE_PROVIDER SP  ON C.FOR_DEALER = SP.ID
			INNER JOIN DEALERS_IN_GROUP DIG ON DIG.DEALER = SP.ID
			INNER JOIN DEALER_GROUP DG      ON DIG.DEALER_GROUP = DG.ID
		)
		DEALER_GRP ON DEALER_GRP.CLAIM_NUMBER = C.CLAIM_NUMBER
	WHERE
		0 = 0
		AND C.FILED_ON_DATE > '13-NOV-2016'
		and LIG.ACCEPTED_AMT <> 0
		--AND c.business_unit_info = 'HVAC TCP' --Jean Skemp recommends using original source id insteal
		AND STATE = 'ACCEPTED_AND_CLOSED'
		AND ORIGINAL_SOURCE_ID IN('CS', 'GP')
		-- and c.claim_number = 'C-10764292'
		--and ii.serial_number like '11492KBA3R'
		ORDER BY claim_number, serial_number, priority
		;

