SELECT DISTINCT
CLAIM.ID AS CLAIM_ID,
SUM(SPLIT_AMOUNT_AMT) AS COMMISSION_AMT
FROM CLAIM

INNER JOIN
PAYMENT
ON 1=1
AND CLAIM.PAYMENT = PAYMENT.ID

LEFT OUTER JOIN
CREDIT_MEMO
ON 1=1
AND PAYMENT.ACTIVE_CREDIT_MEMO = CREDIT_MEMO.ID -- (+)

INNER JOIN
CLAIMED_ITEM
ON 1=1
AND CLAIM.ID = CLAIMED_ITEM.CLAIM

INNER JOIN
INVENTORY_ITEM
ON 1=1
AND CLAIMED_ITEM.ITEM_REF_INV_ITEM = INVENTORY_ITEM.ID

INNER JOIN
ITEM
ON 1=1
AND ITEM.ID = INVENTORY_ITEM.OF_TYPE

INNER JOIN
SALES_ORDER
ON 1=1
AND INVENTORY_ITEM.FOR_SALES_ORDER = SALES_ORDER.ID

INNER JOIN
SERVICE_INFORMATION SI
ON 1=1
AND CLAIM.SERVICE_INFORMATION = SI.ID

INNER JOIN
SERVICE S
ON 1=1
AND SI.SERVICE_DETAIL = S.ID

INNER JOIN
SERVICE_COMMISSION_DETAILS SCD
ON 1=1
AND S.ID = SCD.SERVICE

INNER JOIN
COMMISSION_DETAIL CD
ON 1=1
AND SCD.COMMISSION_DETAILS = CD.ID

INNER JOIN
COMMISSION_CODE CC
ON 1=1
AND CC.ID = CD.COMMISSION_CODE

