SELECT
EXTRACT_EXTENDED.CLAIM_NUMBER,
EXTRACT_EXTENDED.COST_CATEGORY AS STEP_NUMBER,
EXTRACT_EXTENDED.SEGMENT1 AS BUSINESS_UNIT,
PRODGRP.PRODUCT_CATEGORY AS RESERVE_GROUP,
EXTRACT_EXTENDED.COMMERCIAL_POLICY,
EXTRACT_EXTENDED.TAVANT_CLAIM_TYPE,
EXTRACT_EXTENDED.CLAIM_TYPE,
EXTRACT_EXTENDED.COST_CATEGORY,
EXTRACT_EXTENDED.GL_EXPENSE_AMT AS EXPENSE_AMOUNT,
100 * (EXTRACT_EXTENDED.GL_EXPENSE_AMT - TRUNC(EXTRACT_EXTENDED.GL_EXPENSE_AMT)) AS EXPENSE_AMOUNT_DEC,
EXTRACT_EXTENDED.MATERIAL_LABOR,
EXTRACT_EXTENDED.SEGMENT4 AS GL_ACCOUNT,
EXTRACT_EXTENDED.EXPENSE_TYPE_DESCR,
'unknown' AS OFFICE_NAME,
EXTRACT_EXTENDED.SEGMENT5 AS GL_PROD_CODE,
EXTRACT_EXTENDED.MANF_PROD_CODE,
'unknown' AS CUSTOMER_NUMBER,
'unknown' AS CUSTOMER_NAME,
'unknown' AS INTERNAL_EXTERNAL,
'unknown' AS TRX_DATE, -- WHAT IS TRX DATE?  Date Of Claim on UI
'unknown' AS TRX_YEAR,
'unknown' AS TRX_MONTH,
'unknown' AS INTMONTHS_TRX_TO_BASE, -- WHAT IS BASE DATE?
'unknown' AS INTMONTHS_SHIP_TO_BASE,
EXTRACT_EXTENDED.SHIP_DATE,
TO_NUMBER(TO_CHAR(TO_DATE(EXTRACT_EXTENDED.SHIP_DATE), 'YYYY')) * 100 + TO_NUMBER(TO_CHAR(TO_DATE(EXTRACT_EXTENDED.SHIP_DATE), 'MM')) AS SHIP_YEAR_MONTH,
'unknown' AS INTMONTHS_SHIP_TO_TRX,
EXTRACT_EXTENDED.START_DATE,
'unknown' AS INTMONTHS_START_TO_TRX,
EXTRACT_EXTENDED.FAILURE_DATE AS FAIL_DATE,
'unknown' AS INTMONTHS_FAIL_TO_TRX,
EXTRACT_EXTENDED.WARRANTY_TYPE,
EXTRACT_EXTENDED.WARRANTY_DURATION,
EXTRACT_EXTENDED.GL_EXPENSE_CURR AS CURRENCY,
CASE
	WHEN EXTRACT_EXTENDED.SEGMENT1 IN('5773', '5588') THEN 'CAD'
	WHEN EXTRACT_EXTENDED.SEGMENT1 IN('5575', '5612', '5743', '9256', '9258', '9298', '9299', '9984') THEN 'USD'
	ELSE '???'
	END AS COUNTRY_INDICATOR,
'unknown' AS RETROFIT_ID,
'NA' AS GL_DEPT,
'unknown' AS IN_RESERVE_PERCENT,
'unknown' AS IN_RESERVE_PERCENT_25,
'unknown' AS TRX_LAG,
'unknown' AS START_LAG_25,
'unknown' AS TRXYEARMONTH,
'unknown' AS EXPENSE_AMT_IN_RES,
'unknown' AS EXPENSE_AMT_NOT_IN_RES
FROM (

SELECT 
EXTRACT.*,
-- CLAIM_TYPE
CASE COMMERCIAL_POLICY
	WHEN 0 THEN CASE TAVANT_CLAIM_TYPE
		WHEN 'MACHINE' THEN CASE WARRANTY_TYPE
			WHEN 'EXTENDED' THEN 'NA'
			WHEN 'GOODWILL' THEN 'CONCESSION'
			WHEN 'STANDARD' THEN 'MATERIAL'
			ELSE 'UNKNOWN WARRANTY_TYPE'
			END
		WHEN 'CAMPAIGN' THEN CASE
			-- NOT SURE ABOUT THIS - LOCAL PURCHASE?
			WHEN (UPPER(COST_CATEGORY) IN ('LABOR') OR UPPER(COST_CATEGORY) LIKE 'TRAVEL%') THEN 'RETROFIT LABOR'
			ELSE 'RETROFIT MATERIAL'
			END
		ELSE 'UNKNOWN TAVANT_CLAIM_TYPE'
		END
	WHEN 1 THEN CASE TAVANT_CLAIM_TYPE
		WHEN 'MACHINE' THEN 'CONCESSION'
		WHEN 'CAMPAIGN' THEN 'NA'
		ELSE 'UNKNOWN TAVANT_CLAIM_TYPE'
		END
	ELSE 'UNKNOWN COMMERCIAL_POLICY'
	END AS CLAIM_TYPE,
CASE COST_CATEGORY
	WHEN 'Additional Travel Hours' THEN 'LABOR'
	WHEN 'Freight' THEN 'MATERIAL'
	WHEN 'Labor' THEN 'LABOR'
	WHEN 'Local Purchase' THEN 'MATERIAL'
	WHEN 'Non Oem Parts' THEN 'MATERIAL'
	WHEN 'Oem Parts' THEN 'MATERIAL'
	WHEN 'Others' THEN 'LABOR'
	WHEN 'Rebate' THEN 'MATERIAL'
	WHEN 'Travel by Hours' THEN 'LABOR'
	WHEN 'Travel by Perdiem' THEN 'LABOR'
	ELSE 'unknown'
	END AS MATERIAL_LABOR,
CASE COST_CATEGORY
	WHEN 'Additional Travel Hours' THEN 'LABOR'
	WHEN 'Freight' THEN 'FREIGHT'
	WHEN 'Item Freight And Duty' THEN 'FREIGHT'
	WHEN 'Labor' THEN 'LABOR'
	WHEN 'Local Purchase' THEN 'MATERIAL'
	WHEN 'Meals' THEN 'OTHER'
	WHEN 'Miscellaneous Parts' THEN 'OTHER'
	WHEN 'Non Oem Parts' THEN 'MATERIAL'
	WHEN 'Oem Parts' THEN 'MATERIAL'
	WHEN 'Other Freight And Duty' THEN 'OTHER'
	WHEN 'Others' THEN 'LABOR'
	WHEN 'Parking' THEN 'OTHER'
	WHEN 'Per Diem' THEN 'OTHER'
	WHEN 'Rebate' THEN 'REBATE'
	WHEN 'Rental Charges' THEN 'OTHER'
	WHEN 'Tolls' THEN 'OTHER'
	WHEN 'Travel By Distance' THEN 'OTHER'
	WHEN 'Travel By Trip' THEN 'OTHER'
	WHEN 'Travel by Hours' THEN 'LABOR'
	WHEN 'Travel by Perdiem' THEN 'LABOR'
	ELSE CASE
		WHEN REBATES_GL_AMT IS NOT NULL THEN 'REBATE'
		ELSE 'unknown'
		END
	END AS EXPENSE_TYPE_DESCR,
MONTHS_BETWEEN(FAILURE_DATE, SHIP_DATE) AS SHIP2FAIL,
MONTHS_BETWEEN(FAILURE_DATE, START_DATE) AS START2FAIL,
-- WARRANTY_DURATION
CASE WARRANTY_TYPE
	WHEN 'EXTENDED' THEN 'NA'
	WHEN 'GOODWILL' THEN CASE
		WHEN TRUNC(FAILURE_DATE) - TRUNC(SHIP_DATE) < 548 THEN '<548'
		ELSE '>=548'
		END
	ELSE CASE
		WHEN MONTHS_BETWEEN(FAILURE_DATE, SHIP_DATE) <= 18 OR MONTHS_BETWEEN(FAILURE_DATE, START_DATE) <= 12 THEN '1ST-YEAR'
		WHEN MONTHS_BETWEEN(FAILURE_DATE, SHIP_DATE) <= 66 OR MONTHS_BETWEEN(FAILURE_DATE, START_DATE) <= 60 THEN '2-5-YEAR'
		WHEN MONTHS_BETWEEN(FAILURE_DATE, SHIP_DATE) <= 66 AND MONTHS_BETWEEN(FAILURE_DATE, START_DATE) <= 60 THEN '>2-5-YEAR'
		ELSE '>5-YEAR'
		END
	END AS WARRANTY_DURATION
FROM (

-- Extract
SELECT
		PAYMENTS.CLAIM_NUMBER,
		PAYMENTS.TAVANT_CLAIM_TYPE,
		PAYMENTS.COMMERCIAL_POLICY,
		PAYMENTS.QUERY_SOURCE,
		PAYMENTS.WARRANTY_TYPE,
		PAYMENTS.PRIORITY,
		PAYMENTS.PART_NBR,
		PAYMENTS.COST_CATEGORY,
		PAYMENTS.GL_EXPENSE_STRING,
		PAYMENTS.SEGMENT1,
		PAYMENTS.SEGMENT2,
		PAYMENTS.SEGMENT3,
		PAYMENTS.SEGMENT4,
		PAYMENTS.SEGMENT5,
		PAYMENTS.SEGMENT6,
		PAYMENTS.SEGMENT7,
		PAYMENTS.SEGMENT8,
		PAYMENTS.GL_EXPENSE_AMT,
		PAYMENTS.GL_EXPENSE_CURR,
		PAYMENTS.REBATES_GL_NAME,
		PAYMENTS.REBATES_GL_CODE_WNTY_EXP_REV,
		PAYMENTS.REBATES_GL_AMT,
		PAYMENTS.REBATES_GL_CURR,
		PAYMENTS.FAILURE_DATE,
		PAYMENTS.FILED_ON_DATE,
		ITEMS.SHIP_DATE,
		ITEMS.START_DATE,
		ITEMS.MANF_PROD_CODE
	FROM
		TAV_PAYMENT_RAW PAYMENTS
	INNER JOIN (
		SELECT
		CLAIM_NUMBER,
		COUNT(DISTINCT CLAIMED_ITEM_ID) AS ITEM_COUNT,
		MIN(ITEM_REF_INV_ITEM) AS MIN_ITEM_REF_INV_ITEM,
		COUNT(DISTINCT ITEM_REF_INV_ITEM) AS COUNT_OF_ITEM_REF_INV_ITEM,
		MIN(SHIPMENT_DATE) AS SHIP_DATE,
		COUNT(DISTINCT SHIPMENT_DATE) AS COUNT_OF_SHIP_DATE,
		MIN(DELIVERY_DATE) AS START_DATE,
		COUNT(DISTINCT DELIVERY_DATE) AS COUNT_OF_START_DATE,
		MIN(SALES_ORDER_NUMBER) AS MIN_SALES_ORDER_NUMBER,
		COUNT(DISTINCT SALES_ORDER_NUMBER) AS COUNT_OF_SALES_ORDER_NUMBER,
		MIN(MFG) AS MIN_MFG,
		COUNT(DISTINCT MFG) AS COUNT_OF_MFG,
		MIN(ORIGINAL_SOURCE_ID) AS MIN_ORIGINAL_SOURCE_ID,
		COUNT(DISTINCT ORIGINAL_SOURCE_ID) AS COUNT_OF_ORIGINAL_SOURCE_ID,
		MIN(SIOP_SEGMENT6) AS MANF_PROD_CODE,
		COUNT(DISTINCT SIOP_SEGMENT6) AS COUNT_OF_MANF_PROD_CODE
		-- ,LISTAGG(PRODUCT_DEFINITION_CODE, ', ') WITHIN GROUP (ORDER BY PRODUCT_DEFINITION_CODE) AS PD_CODES
		FROM
			TAV_ITEM_RAW
		GROUP BY
			CLAIM_NUMBER
	) ITEMS
		ON ITEMS.CLAIM_NUMBER = PAYMENTS.CLAIM_NUMBER
	WHERE
		0 = 0
-- AND CLAIM.CLAIM_NUMBER = 'C-10764292'
-- order by 1, 2, 3, 4, 5

) EXTRACT
) EXTRACT_EXTENDED
 LEFT OUTER JOIN PROD_CODE_XREF_RCPO_DR PRODGRP
 	ON EXTRACT_EXTENDED.MANF_PROD_CODE = PRODGRP.MANF_PROD_CODE AND 'CSD' = PRODGRP.GL_LEDGER
-- INNER JOIN DM_WAR_CSN_RSV_PCT_REF RES_PCT
--	ON EXTRACT_EXTENDED.EXPENSE_TYPE_DESCR = RES_PCT.EXPENSE_TYPE_DESCR AND unknown.COMPANY_OWNED_IND = RES_PCT.COMPANY_OWNED_IND
 LEFT OUTER JOIN DM_WAR_CSN_RSV_PCT_REF RES_PCT1 ON EXTRACT_EXTENDED.CLAIM_TYPE = RES_PCT1.CLAIM_TYPE
WHERE 0=0;
-- AND GL_EXPENSE_AMT <> 0;

select * from tav_item_raw where claim_number = 'C-10764014';