--Expense Query  for Cost Categories labor, non oem parts, travel, etc, everything but OEM parts
SELECT DISTINCT
		C.CLAIM_NUMBER,
		LIG.NAME AS COST_CATEGORY, --formerly expense type
		LIG.GL_CODE_WNTY_EXPENSE_REV,
		LIG.GL_AMT,
		LIG.GL_CURR,
		'---',
		lig.*
	FROM
		CLAIM C
	INNER JOIN PAYMENT P             ON C.PAYMENT = P.ID
	INNER JOIN LINE_ITEM_GROUPS LIGS ON P.ID = LIGS.FOR_PAYMENT
	INNER JOIN LINE_ITEM_GROUP LIG   ON LIGS.LINE_ITEM_GROUPS = LIG.ID
	WHERE
		0 = 0
		AND LIG.NAME NOT IN('Oem Parts', 'Claim Amount')
		AND C.CLAIM_NUMBER = 'C-10764292' 
		AND GL_CODE_WNTY_EXPENSE_REV IS NOT NULL 
	;