--Expense Query For Parts:
--r12 GL String Parts: ENTITY.LOCATION.COSTCENTER.ACCOUNT.R12PRODUCTCODE.INTERCOMPANY
SELECT
		C.CLAIM_NUMBER,
		I.ITEM_NUMBER AS PART_NBR,
		LIG.NAME AS COST_CATEGORY, --formerly expense type
		PPI.GL_CODE_COGS_REVERSAL AS GL_COGS_REVERSAL_STRING,
		PPI.GL_CODE_REVENUE_REVERSAL AS GL_REV_REVERSAL_STRING,
		PPI.GL_CODE_WNTY_EXPENSE_REV AS GL_EXPENSE_STRING,
		-- GL_ACCOUNT is Segment4 of the GL_EXPENSE_STRING
		PPI.GL_COGS_AMT,
		PPI.GL_COGS_CURR AS GL_COGS_CURRENCY,
		PPI.GL_REVENUE_AMT,
		PPI.GL_REVENUE_CURR,
		PPI.GL_EXPENSE_AMT,
		PPI.GL_EXPENSE_CURR
	FROM
		CLAIM C
	INNER JOIN PAYMENT P             ON C.PAYMENT = P.ID
	INNER JOIN LINE_ITEM_GROUPS LIGS ON P.ID = LIGS.FOR_PAYMENT
	INNER JOIN LINE_ITEM_GROUP LIG   ON LIGS.LINE_ITEM_GROUPS = LIG.ID
	INNER JOIN CURRENT_PART_INFO CPI ON LIG.ID = CPI.LINE_ITEM_GROUP
	INNER JOIN PART_PAYMENT_INFO PPI ON CPI.CURRENT_PART_PAYMENT_INFO = PPI.ID --NOTE: If modifier is not picked, PART_PAYMENT_INFO_MODIFIER table will be empty.
	INNER JOIN ITEM I                ON I.ID = PPI.ITEM ;
-- do we need an outer join here?
-- AND c.claim_number = 'C-10765255'
--'C-10765552'
--     or c.claim_number = 'C-10764718'
--     or c.claim_number = 'C-10764743'
--   or c.claim_number = 'C-10764732')
