SELECT distinct
		Res_Pct.Reserve_Pct,
		A.TAVANT_CLAIM_TYPE,
		A.COMPANY_OWNED,
		A.CREDIT_TO_THIRD_PARTY,
		A.COMMERCIAL_POLICY,
		A.COST_CATEGORY
	FROM
		TAV_TEMP A
	LEFT OUTER JOIN TAV_RESERVE_PCT RES_PCT 
		ON UPPER(A.TAVANT_CLAIM_TYPE) = UPPER(RES_PCT.TAVANT_CLAIM_TYPE) 
		AND UPPER(A.COMPANY_OWNED) = UPPER(RES_PCT.COMPANY_OWNED_IND) 
		AND UPPER(A.CREDIT_TO_THIRD_PARTY) = UPPER(RES_PCT.CREDIT_TO_THIRD_PARTY)
		AND UPPER(A.COST_CATEGORY_sv) = UPPER(RES_PCT.COST_CATEGORY) 
		AND UPPER(A.COMMERCIAL_POLICY) = UPPER(RES_PCT.COMMERCIAL_POLICY)
	WHERE Res_Pct.Reserve_Pct is null
	order by 1,2,3;
	
	SELECT DISTINCT COST_CATEGORY, COST_CATEGORY_SV 
FROM TAV_TEMP;

select * from tav_temp 
where tavant_claim_type = 'CAMPAIGN'
AND COST_CATEGORY = 'Local Purchase'
;

select * from tav_stg
where 0=0
-- AND claim_type = 'CAMPAIGN'
AND COST_CATEGORY LIKE 'OUTSIDE%'
;