DROP TABLE TAV_CAMPAIGN_RAW;
CREATE TABLE TAV_CAMPAIGN_RAW (
		ID NUMBER(19) NOT NULL,
		CODE VARCHAR2(255 CHAR) NOT NULL,
		DESCRIPTION VARCHAR2(1000 CHAR),
		FROM_DATE DATE,
		TILL_DATE DATE,
		D_CREATED_ON DATE,
		D_UPDATED_ON DATE,
		D_ACTIVE NUMBER(1),
		STATUS VARCHAR2(32 CHAR),
		CAUSAL_PART NUMBER(19),
		FINANCIAL_BUDGET NUMBER(19,2),
		AMOUNT_UTILIZED NUMBER(19,2),
		FINANCIAL_CURRENCY VARCHAR2(10)
);
