DROP TABLE TAV_PAYMENT_RAW;
CREATE TABLE TAV_PAYMENT_RAW (
CLAIM_NUMBER VARCHAR2(255 CHAR) NOT NULL,
TAVANT_CLAIM_TYPE VARCHAR2(31 CHAR) NOT NULL,
COMMERCIAL_POLICY NUMBER(1),
QUERY_SOURCE VARCHAR2(8 CHAR),
WARRANTY_TYPE VARCHAR2(255 CHAR),
PRIORITY NUMBER(19),
PART_NBR VARCHAR2(255 CHAR),
COST_CATEGORY VARCHAR2(255 CHAR), 
GL_EXPENSE_STRING VARCHAR2(64 CHAR),
SEGMENT1 VARCHAR2(10 CHAR),
SEGMENT2 VARCHAR2(10 CHAR),
SEGMENT3 VARCHAR2(10 CHAR),
SEGMENT4 VARCHAR2(10 CHAR),
SEGMENT5 VARCHAR2(10 CHAR),
SEGMENT6 VARCHAR2(10 CHAR),
SEGMENT7 VARCHAR2(10 CHAR),
SEGMENT8 VARCHAR2(10 CHAR),
GL_EXPENSE_AMT NUMBER(19,2),
GL_EXPENSE_CURR VARCHAR2(10),
REBATES_GL_NAME VARCHAR2(255 CHAR),
REBATES_GL_CODE_WNTY_EXP_REV VARCHAR2(255 CHAR),
REBATES_GL_AMT NUMBER(19,2),
REBATES_GL_CURR VARCHAR2(10),
FAILURE_DATE DATE,
FILED_ON_DATE DATE
);
COMMIT;