SELECT
		COUNT( *),
		MIN(RES_PCT.RESERVE_PCT) - MAX(RES_PCT.RESERVE_PCT) DIFF,
		MIN(RES_PCT.RESERVE_PCT),
		MAX(RES_PCT.RESERVE_PCT),
		RES_PCT.TAVANT_CLAIM_TYPE,
		RES_PCT.COMMERCIAL_POLICY,
		RES_PCT.TAVANT_WARRANTY_TYPE,
		RES_PCT.COST_CATEGORY,
		RES_PCT.COMPANY_OWNED_IND,
		RES_PCT.CREDIT_TO_THIRD_PARTY
	FROM
		TAV_RESERVE_PCT RES_PCT
	GROUP BY
		RES_PCT.TAVANT_CLAIM_TYPE,
		RES_PCT.COMMERCIAL_POLICY,
		RES_PCT.TAVANT_WARRANTY_TYPE,
		RES_PCT.COST_CATEGORY,
		RES_PCT.COMPANY_OWNED_IND,
		RES_PCT.CREDIT_TO_THIRD_PARTY
	HAVING Count(*) > 1
	ORDER BY
		1 DESC ;