SELECT DISTINCT
		CLAIM.CLAIM_NUMBER,
		CLAIM.TYPE,
		COMMERCIAL_POLICY,
		COMP_OWN.COMP_OWN,
		CLAIMED_ITEM.ITEM_REF_INV_ITEM,
		CLAIM.FAILURE_DATE,
		INVENTORY_ITEM.SHIPMENT_DATE,
		INVENTORY_ITEM.DELIVERY_DATE AS START_DATE,
		SALES_ORDER.SALES_ORDER_NUMBER,
		SALES_ORDER.MFG,
		SERIAL_NUMBER,
		SALES_ORDER.ORIGINAL_SOURCE_ID,
		SIOP_SEGMENT1,
		SIOP_SEGMENT2,
		SIOP_SEGMENT3,
		SIOP_SEGMENT4,
		SIOP_SEGMENT5,
		SIOP_SEGMENT6,
		POLICY_DEFINITION.CODE,
		POLICY_DEFINITION.DESCRIPTION,
		POLICY_DEFINITION.PRIORITY,
		--   policy.till_date, Policy till date is not showing correctly Mohit reviewed sql but needs to investigate further
		POLICY_DEFINITION.WARRANTY_TYPE,
		POLICY_DEFINITION.MONTHS_FRM_DELIVERY,
		POLICY_DEFINITION.MONTHS_FRM_SHIPMENT,
		TRUE_COVERAGE_MONTHS,
		LINE_ITEM_GROUP.NAME,
		LINE_ITEM_GROUP.GL_AMT,
		GL_CODE_WNTY_EXPENSE_REV,
		LINE_ITEM_GROUP.ACCEPTED_AMT
	FROM
		CLAIM
	INNER JOIN CLAIMED_ITEM           ON CLAIM.ID = CLAIMED_ITEM.CLAIM
	INNER JOIN INVENTORY_ITEM         ON CLAIMED_ITEM.ITEM_REF_INV_ITEM = INVENTORY_ITEM.ID
	INNER JOIN ITEM                   ON ITEM.ID = INVENTORY_ITEM.OF_TYPE
	INNER JOIN SALES_ORDER            ON INVENTORY_ITEM.FOR_SALES_ORDER = SALES_ORDER.ID
	INNER JOIN WARRANTY               ON WARRANTY.FOR_ITEM = INVENTORY_ITEM.ID
	INNER JOIN PAYMENT                ON CLAIM.PAYMENT = PAYMENT.ID
	INNER JOIN LINE_ITEM_GROUPS       ON PAYMENT.ID = LINE_ITEM_GROUPS.FOR_PAYMENT
	INNER JOIN LINE_ITEM_GROUP        ON LINE_ITEM_GROUPS.LINE_ITEM_GROUPS = LINE_ITEM_GROUP.ID
	LEFT OUTER JOIN APPLICABLE_POLICY ON LINE_ITEM_GROUP.APPLICABLE_POLICY = APPLICABLE_POLICY.ID -- LINE_ITEM_GROUP.APPLICABLE_POLICY can be null
	LEFT OUTER JOIN POLICY            ON WARRANTY.ID = POLICY.WARRANTY
	LEFT OUTER JOIN POLICY_DEFINITION ON APPLICABLE_POLICY.POLICY_DEFINITION = POLICY_DEFINITION.ID
	LEFT OUTER JOIN
		(SELECT DISTINCT DECODE(INSTR(UPPER(DG.NAME), 'INDEPENDENT'), 0, 'Y', 'N') COMP_OWN, 
		-- need to add in another decode use following logic.
		-- dealer_group.name 
		/*
		'USA Company Owned Service' = internal
		'USA Company Owned Parts' = internal
		'Canada Company Owned Parts' = internal
		'Canada Company Owned Service' = internal
		else 
			external
		*/			
		C.CLAIM_NUMBER 
		
		FROM CLAIM C
				INNER JOIN SERVICE_PROVIDER SP  ON C.FOR_DEALER = SP.ID
				INNER JOIN DEALERS_IN_GROUP DIG ON DIG.DEALER = SP.ID
				INNER JOIN DEALER_GROUP DG      ON DIG.DEALER_GROUP = DG.ID
		)
		COMP_OWN ON COMP_OWN.CLAIM_NUMBER = Claim.CLAIM_NUMBER
	WHERE
		0 = 0
		AND CLAIM.FILED_ON_DATE > '13-NOV-2016'
		AND CLAIM.BUSINESS_UNIT_INFO = 'HVAC TCP' --Jean Skemp recommends using original source id instead
		AND STATE = 'ACCEPTED_AND_CLOSED'
		AND ORIGINAL_SOURCE_ID IN('CS', 'GP')
		AND CLAIM.CLAIM_NUMBER LIKE 'C%'
		AND SALES_ORDER.SALES_ORDER_NUMBER  = '78P116'
		--AND CLAIM.CLAIM_NUMBER = 'C-10764292'  -- rebate
		--AND CLAIM.CLAIM_NUMBER = 'C-10764041'
		--AND CLAIM.CLAIM_NUMBER = 'C-10764014'
		--AND CLAIM.CLAIM_NUBER = 'C-10764437'
		--and inventory_item.serial_number like 'R14G59044'
		--and line_item_group.name = 'Others'
		--and accepted_amt <> 0
		--and SIOP_SEGMENT4 = '685211'
		------ IMPORTANT GL_ACCOUNT <> '685211'
		------ USE ENTITY Exlusions
	ORDER BY
		CLAIM_NUMBER,
		SERIAL_NUMBER ;
SELECT DISTINCT NAME FROM LINE_ITEM_GROUP ORDER BY 1;
SELECT DISTINCT
		WARRANTY_TYPE,
		COMMERCIAL_POLICY,
		CLAIM.TYPE
	FROM
		CLAIM
	INNER JOIN CLAIMED_ITEM           ON CLAIM.ID = CLAIMED_ITEM.CLAIM
	INNER JOIN INVENTORY_ITEM         ON CLAIMED_ITEM.ITEM_REF_INV_ITEM = INVENTORY_ITEM.ID
	INNER JOIN ITEM                   ON ITEM.ID = INVENTORY_ITEM.OF_TYPE
	INNER JOIN SALES_ORDER            ON INVENTORY_ITEM.FOR_SALES_ORDER = SALES_ORDER.ID
	INNER JOIN WARRANTY               ON WARRANTY.FOR_ITEM = INVENTORY_ITEM.ID
	INNER JOIN PAYMENT                ON CLAIM.PAYMENT = PAYMENT.ID
	INNER JOIN LINE_ITEM_GROUPS       ON PAYMENT.ID = LINE_ITEM_GROUPS.FOR_PAYMENT
	INNER JOIN LINE_ITEM_GROUP        ON LINE_ITEM_GROUPS.LINE_ITEM_GROUPS = LINE_ITEM_GROUP.ID
	LEFT OUTER JOIN APPLICABLE_POLICY ON LINE_ITEM_GROUP.APPLICABLE_POLICY = APPLICABLE_POLICY.ID -- LINE_ITEM_GROUP.APPLICABLE_POLICY can be null
	LEFT OUTER JOIN POLICY            ON WARRANTY.ID = POLICY.WARRANTY
	LEFT OUTER JOIN POLICY_DEFINITION ON APPLICABLE_POLICY.POLICY_DEFINITION = POLICY_DEFINITION.ID
	WHERE
		0 = 0
		AND CLAIM.BUSINESS_UNIT_INFO = 'HVAC TCP' ;
		AND CLAIM.ORIGINAL_SOURCE_ID IN('CS', 'GP')
		select distinct name from dealer_group;

select 
	SALES_ORDER.SALES_ORDER_NUMBER

	FROM
		CLAIM
	INNER JOIN CLAIMED_ITEM           ON CLAIM.ID = CLAIMED_ITEM.CLAIM
	INNER JOIN INVENTORY_ITEM         ON CLAIMED_ITEM.ITEM_REF_INV_ITEM = INVENTORY_ITEM.ID
	INNER JOIN ITEM                   ON ITEM.ID = INVENTORY_ITEM.OF_TYPE
	INNER JOIN SALES_ORDER            ON INVENTORY_ITEM.FOR_SALES_ORDER = SALES_ORDER.ID
	WHERE 0=0
	AND CLAIM.FILED_ON_DATE > '13-NOV-2016'
		AND CLAIM.BUSINESS_UNIT_INFO = 'HVAC TCP' --Jean Skemp recommends using original source id instead
		AND STATE = 'ACCEPTED_AND_CLOSED'
		AND ORIGINAL_SOURCE_ID IN('CS', 'GP')
	group by  SALES_ORDER.SALES_ORDER_NUMBER
	having count(distinct CLAIM.CLAIM_NUMBER) > 1;
	
select distinct
	claim.*

	FROM
		CLAIM
	INNER JOIN CLAIMED_ITEM           ON CLAIM.ID = CLAIMED_ITEM.CLAIM
	INNER JOIN INVENTORY_ITEM         ON CLAIMED_ITEM.ITEM_REF_INV_ITEM = INVENTORY_ITEM.ID
	INNER JOIN ITEM                   ON ITEM.ID = INVENTORY_ITEM.OF_TYPE
	INNER JOIN SALES_ORDER            ON INVENTORY_ITEM.FOR_SALES_ORDER = SALES_ORDER.ID
	WHERE 0=0
	--and SALES_ORDER.SALES_ORDER_NUMBER in ('70C039','78P116','CSCA0120F1','E2Q252','L3Q838','LHA052','T1L619','W3B947','Y3B232')
	-- and SALES_ORDER.SALES_ORDER_NUMBER in ('78P116')  -- this is three lines with a clone
		and SALES_ORDER.SALES_ORDER_NUMBER in ('E2Q252')
	and claim.claim_number like 'C%'
	;
	
	select * from payment;
