SELECT
		RCT.INTERFACE_HEADER_ATTRIBUTE1 CLAIM_NUMBER,
		GCC_REC.SEGMENT1 ENTITY,
		GCC_REC.SEGMENT2 LOCATION,
		GCC_REC.SEGMENT3 COST_CENTER,
		GCC_REC.SEGMENT4 ACCOUNT,
		GCC_REC.SEGMENT5 PRODUCT_CODE,
		GCC_REC.SEGMENT6 ICP,
		GCC_REC.SEGMENT7 FUTURE1,
		GCC_REC.SEGMENT8 FUTURE2,
		(
			SELECT
					F.DESCRIPTION
				FROM
					FND_ID_FLEX_STRUCTURES B
					INNER JOIN FND_ID_FLEX_SEGMENTS C 0N 1=1 AND B.ID_FLEX_CODE = C.ID_FLEX_CODE AND B.ID_FLEX_NUM = C.ID_FLEX_NUM AND B.APPLICATION_ID = C.APPLICATION_ID
					INNER JOIN FND_FLEX_VALUE_SETS D 0N 1=1 AND C.FLEX_VALUE_SET_ID = D.FLEX_VALUE_SET_ID
					INNER JOIN FND_FLEX_VALUES E 0N 1=1 AND D.FLEX_VALUE_SET_ID = E.FLEX_VALUE_SET_ID
					INNER JOIN FND_FLEX_VALUES_TL F 0N 1=1 AND E.FLEX_VALUE_ID = F.FLEX_VALUE_ID
				WHERE
					B.APPLICATION_ID = '101'
					AND B.ID_FLEX_CODE = 'GL#'
					AND C.SEGMENT_NUM = 2
					AND F.LANGUAGE = 'US'
					AND E.FLEX_VALUE = GCC_REC.SEGMENT2
					AND B.ID_FLEX_NUM = GCC_REC.CHART_OF_ACCOUNTS_ID
		) LOCATION_NAME,
		GJH.NAME JOURNAL_NAME,
		RCT.TRX_NUMBER INV_NBR,
		RCT.TRX_DATE TRX_DATE,
		RCTL.LINE_NUMBER LINE_NBR,
		RCTL.DESCRIPTION LINE_DESCRIPTION,
		RCTL.EXTENDED_AMOUNT LINE_AMOUNT,
		RCT.INVOICE_CURRENCY_CODE INVOICE_CURRENCY_CODE
	FROM
		RA_CUSTOMER_TRX_ALL RCT
	INNER JOIN RA_CUSTOMER_TRX_LINES_ALL RCTL 0N RCTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
	INNER JOIN RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD_REC 0N RCTGD_REC.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
	INNER JOIN XLA_DISTRIBUTION_LINKS XDL_REC 0N RCTGD_REC.CUST_TRX_LINE_GL_DIST_ID = XDL_REC.SOURCE_DISTRIBUTION_ID_NUM_1 AND RCTGD_REC.EVENT_ID = XDL_REC.EVENT_ID
	INNER JOIN XLA_AE_HEADERS AEH_REC 0N XDL_REC.AE_HEADER_ID = AEH_REC.AE_HEADER_ID
	INNER JOIN XLA_AE_LINES AEL_REC 0N XDL_REC.AE_HEADER_ID = AEL_REC.AE_HEADER_ID AND XDL_REC.AE_LINE_NUM = AEL_REC.AE_LINE_NUM
	INNER JOIN GL_CODE_COMBINATIONS_KFV GCC_REC 0N AEL_REC.CODE_COMBINATION_ID = GCC_REC.CODE_COMBINATION_ID
	INNER JOIN GL_JE_HEADERS GJH 0N GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
	left outer JOIN GL_IMPORT_REFERENCES GIR 0N GIR.GL_SL_LINK_TABLE = AEL_REC.GL_SL_LINK_TABLE AND GIR.GL_SL_LINK_ID = AEL_REC.GL_SL_LINK_ID
	LEFT OUTER JOIN GL_JE_LINES GJL 0N GJL.JE_HEADER_ID = GIR.JE_HEADER_ID AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
	INNER JOIN GL_LEDGERS GLL 0N GJH.LEDGER_ID = GLL.LEDGER_ID
	WHERE
		0 = 0
		--AND rct.trx_number = '1566232'
		AND RCT.ORG_ID IN(456, 122, 89, 457, 458, 94)
		AND RCTGD_REC.ACCOUNT_CLASS = 'REC'
		AND NVL(RCTGD_REC.LATEST_REC_FLAG, 'Y') = 'Y'
		AND GCC_REC.SEGMENT4 = '123502'
		AND XDL_REC.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL'
		AND XDL_REC.APPLICATION_ID = 222
		AND GJH.JE_SOURCE = 'Receivables'
		AND GLL.LEDGER_CATEGORY_CODE = 'PRIMARY' ;