SELECT
		SESS.SID,
		SESS.SERIAL#,
		SESS.PROCESS,
		SESS.STATUS,
		SESS.USERNAME,
		SESS.SCHEMANAME,
--		sess.*,
		SQL.SQL_TEXT
	FROM
		V$SESSION SESS
	LEFT OUTER JOIN V$SQL SQL ON SQL.SQL_ID = SESS.SQL_ID
	WHERE
		SESS.TYPE = 'USER'
 		AND SESS.USERNAME IN('CCDCAS','CCDCAT', 'CCDCAU', 'ENT_RPT', 'ACTU_CACHE_ADMIN', 'DBO') ;
;
-- ALTER SYSTEM KILL SESSION 'SID , SERIAL#' IMMEDIATE;
-- ALTER SYSTEM DISCONNECT SESSION 'SID , SERIAL#'' IMMEDIATE;

ALTER SYSTEM KILL SESSION '100, 25578' IMMEDIATE;

ALTER SYSTEM DISCONNECT SESSION '276, 58041' IMMEDIATE;