grant SELECT on MAP_EXTWARRANTYCOMMNDATA_VW to "ENT_RPT";
grant SELECT on MAP_EXTWARRANTYSALESDATA1_VW to ENT_REPORTING;
grant SELECT on MAP_SALESDATA1_VW to ENT_REPORTING;
grant SELECT on MAP_SALESDATA68_VW to ENT_REPORTING;