SELECT
		REPORT_TYPE,
		RUN_PERIOD,
		SHIP_PERIOD,
		SUM(ROUND(DEFERRED_REVENUE, 2)),
		SUM(ROUND(FORECAST_REVENUE, 2)),
		SUM(ROUND(FORECAST_MNTHLY_TOTAL, 2)),
		SUM(ROUND(FORECAST_YR_TOTAL, 2)),
		SUM(ROUND(REC_REV_MNTHLY, 2))
	FROM
		DBO.DM_030_REV_RELEASE
		--from DBO.Dm_030_Rev_Release_bak
	GROUP BY
		REPORT_TYPE,
		RUN_PERIOD,
		SHIP_PERIOD
	ORDER BY
		1,
		2,
		3,
		4;
SELECT
		REPORT_TYPE,
		SUM(ROUND(DEFERRED_REVENUE, 2)),
		SUM(ROUND(FORECAST_REVENUE, 2)),
		SUM(ROUND(FORECAST_MNTHLY_TOTAL, 2)),
		SUM(ROUND(FORECAST_YR_TOTAL, 2)),
		SUM(ROUND(REC_REV_MNTHLY, 2))
	FROM
		DBO.DM_030_REV_RELEASE
	WHERE
		RUN_PERIOD = '01-DEC-16'
	GROUP BY
		REPORT_TYPE;
DESC DM_030_REV_RELEASE;
SELECT DISTINCT REPORT_TYPE, GL_ACCOUNT FROM DBO.DM_030_REV_RELEASE;
DESC DBO.R12_GL_ACCOUNT_SCD;
SELECT DISTINCT
		R12_ACCOUNT,
		PS_ACCOUNT
	FROM
		DBO.R12_GL_ACCOUNT_SCD
	WHERE(PS_ACCOUNT LIKE '52%'
		OR PS_ACCOUNT LIKE '53%'
		OR PS_ACCOUNT LIKE '54%')
		AND R12_ACCOUNT <> '9999'
	ORDER BY
		1;
DESC DBO.DM_030_REV_RELEASE;
SELECT DISTINCT GL_ACCOUNT FROM DBO.DM_030_REV_RELEASE WHERE REPORT_TYPE = '16-126' ORDER BY 1;
SELECT
		REPORT_TYPE,
		RUN_PERIOD,
		SHIP_PERIOD,
		SUM(ROUND(DEFERRED_REVENUE, 2))
		--from DBO.Dm_030_Rev_Release
	FROM
		DBO.DM_030_REV_RELEASE_BAK
	GROUP BY
		REPORT_TYPE,
		RUN_PERIOD,
		SHIP_PERIOD
	ORDER BY
		1,
		2,
		3,
		4;
DESC DM_030_REV_RELEASE;