--  R12_BI_HDR_STG.sql
SELECT
		RCT.TRX_NUMBER AS INVOICE,
		RBS.NAME AS BILL_SOURCE_ID,
		RCTT.TYPE AS ENTRY_TYPE,
		RCT.CUSTOMER_TRX_ID
	FROM
		RA_CUSTOMER_TRX_ALL RCT
	INNER JOIN RA_BATCH_SOURCES_ALL RBS ON RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID AND RBS.ORG_ID = RCT.ORG_ID
	INNER JOIN RA_CUST_TRX_TYPES_ALL RCTT ON RCT.CUST_TRX_TYPE_ID = RCTT.CUST_TRX_TYPE_ID
	WHERE
		0 = 0
		-- AND RCT.ATTRIBUTE9 = '7'
		AND RBS.BATCH_SOURCE_ID IN('90003', '90006', '87004', '87003', '90005')
		AND RCT.ORG_ID IN(456, 457)
;