-- R12_BI_LINE_STG
SELECT
		RCT.TRX_NUMBER AS INVOICE,
		RCTL.LINE_NUMBER LINE_SEQ_NUM,
		GCC.SEGMENT5 AS R12_PRODUCT,
		RCT.CUSTOMER_TRX_ID AS CUSTOMER_TRX_ID,
		(
			SELECT
					MIC.SEGMENT6
				FROM
					MTL_ITEM_CATEGORIES_V MIC,
					MTL_SYSTEM_ITEMS MSI1
				WHERE
					MIC.INVENTORY_ITEM_ID = MSI1.INVENTORY_ITEM_ID
					AND MSI1.SEGMENT1 = DECODE(RBS.NAME, 'P21', SUBSTR(RCTL.DESCRIPTION, 1, INSTR(RCTL.DESCRIPTION, '~', 1, 1) - 1), MSI.SEGMENT1)
					AND MIC.CATEGORY_SET_NAME = 'IRPLN SIOP CATEGORY'
					AND MIC.ORGANIZATION_ID = MSI1.ORGANIZATION_ID
					AND MSI1.ORGANIZATION_ID = NVL(RCTL.WAREHOUSE_ID, 99)
					AND ROWNUM = 1
		) AS MANF_PROD_ID
	FROM
		RA_CUSTOMER_TRX_ALL RCT
	INNER JOIN RA_BATCH_SOURCES_ALL RBS           ON RBS.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID AND RBS.ORG_ID = RCT.ORG_ID
	INNER JOIN RA_CUSTOMER_TRX_LINES_ALL RCTL     ON RCTL.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID
	INNER JOIN RA_CUST_TRX_LINE_GL_DIST_ALL RCTGD ON RCTGD.CUSTOMER_TRX_ID = RCT.CUSTOMER_TRX_ID AND NVL(RCTGD.CUSTOMER_TRX_LINE_ID, RCTL.CUSTOMER_TRX_LINE_ID) = RCTL.CUSTOMER_TRX_LINE_ID
	INNER JOIN XLA_DISTRIBUTION_LINKS XDL         ON RCTGD.CUST_TRX_LINE_GL_DIST_ID = XDL.SOURCE_DISTRIBUTION_ID_NUM_1 AND RCTGD.EVENT_ID = XDL.EVENT_ID
	INNER JOIN XLA_AE_LINES AEL                   ON XDL.AE_HEADER_ID = AEL.AE_HEADER_ID AND XDL.AE_LINE_NUM = AEL.AE_LINE_NUM
	INNER JOIN GL_CODE_COMBINATIONS_KFV GCC       ON AEL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
	LEFT OUTER JOIN MTL_SYSTEM_ITEMS MSI          ON MSI.INVENTORY_ITEM_ID = RCTL.INVENTORY_ITEM_ID AND MSI.ORGANIZATION_ID = NVL(RCTL.WAREHOUSE_ID, 99)
	WHERE
		0 = 0
		-- AND RCT.ATTRIBUTE9 = '7'
		AND RBS.BATCH_SOURCE_ID IN('90003', '90006', '87004', '87003', '90005')
		AND RCT.ORG_ID IN(456, 457)
		AND RCTL.LINE_TYPE = 'LINE'  -- eliminates Tax
		AND RCTGD.GL_DATE > '01-OCT-16' 
		AND RCT.COMPLETE_FLAG = 'Y'  
		AND NVL(RCTGD.LATEST_REC_FLAG, 'Y') = 'Y'
		AND RCTGD.ACCOUNT_CLASS = 'REC'
		AND XDL.SOURCE_DISTRIBUTION_TYPE = 'RA_CUST_TRX_LINE_GL_DIST_ALL'
		AND XDL.APPLICATION_ID = 222
;