/* Prepaid Comm claims detail Dollar AMT*/ 
SELECT /*+ NO_CPU_COSTING */
sum(A.MONETARY_AMOUNT),
A.ACCOUNT , 
PSA.DESCR AS ACCOUNT_DESC,
case when A.CURRENCY_CD = 'USD' then 'USA' when A.CURRENCY_CD = 'CAD' THEN 'CAN' END AS COUNTRY_INDICATOR
FROM  OTR_BI_ACCT_ENTRY_PSB A, OTR_TRNBI_BI_HDR_PSB B, OTR_BI_HDR_PSB C 
,OTR_TRANE_ACCOUNTS_PS PSA
  
WHERE   
A.JOURNAL_DATE >= TRUNC(TO_DATE(TO_DATE('1-'||:RunDate,'dd-mon-yy')),'YEAR') 
AND JOURNAL_DATE <= LAST_DAY(to_date('1-'||:RunDate,'dd-mon-yy'))
AND A.BUSINESS_UNIT IN ('BIUSA','BICAN','BIUSC') 
AND A.BUSINESS_UNIT_GL IN ('CSD','CAN')
AND A.ACCOUNT like '5%'
AND A.DEPTID = 'SL00'
and case when A.CURRENCY_CD = 'USD' then 'USA' when A.CURRENCY_CD = 'CAD' THEN 'CAN' END= UPPER(:COUNTRY)
AND A.BUSINESS_UNIT = B.BUSINESS_UNIT 
AND A.INVOICE = B.INVOICE 
AND B.BUSINESS_UNIT = C.BUSINESS_UNIT 
AND B.INVOICE = C.INVOICE 
AND A.ACCOUNT = PSA.ACCOUNT (+)
AND PSA.TRANE_ACCOUNT_IND='X'
--and c.BILL_SOURCE_ID = 'FAL'
AND C.ENTRY_TYPE  ='CR'
GROUP BY A.ACCOUNT,PSA.DESCR,case when A.CURRENCY_CD = 'USD' then 'USA' when A.CURRENCY_CD = 'CAD' THEN 'CAN' END
--ORDER BY A.ACCOUNT,case when A.CURRENCY_CD = 'USD' then 'USA' when A.CURRENCY_CD = 'CAD' THEN 'CAN' END


union
/* Qry to fetch accounts wich does not exist in OTR_BI_ACCT_ENTRY_PSB table */
SELECT  /*+ NO_CPU_COSTING */
0 as MONETARY_AMOUNT,
PSA.ACCOUNT , 
PSA.DESCR AS ACCOUNT_DESC,
'' AS COUNTRY_INDICATOR
 FROM dbo.otr_TRANE_ACCOUNTS_ps psa
WHERE  PSA.TRANE_ACCOUNT_IND='X'
AND PSA.ACCOUNT LIKE '5%' 
and not exists(select 'X'
FROM OTR_BI_ACCT_ENTRY_PSB dist,dbo.ACTUATE_SEC_XREF ASX,OTR_BI_HDR_PSB C 
WHERE  
  DIST.BUSINESS_UNIT_GL= ASX.PSGL   
and dist.JOURNAL_DATE >= TRUNC(TO_DATE(TO_DATE('1-'||:RunDate,'dd-mon-yy')),'YEAR') 
AND dist.JOURNAL_DATE< =LAST_DAY(to_date('1-'||:RunDate,'dd-mon-yy'))
AND DIST.ACCOUNT LIKE '5%'
and CASE WHEN ASX.NATION_CURR ='USD' THEN 'USA' ELSE 'CAN' END = UPPER(:COUNTRY)
AND dist.BUSINESS_UNIT = C.BUSINESS_UNIT 
AND dist.INVOICE = C.INVOICE 
AND dist.ACCOUNT = PSA.ACCOUNT  
aND PSA.TRANE_ACCOUNT_IND='X'
AND C.ENTRY_TYPE  ='CR')
ORDER BY  ACCOUNT