/* Comm detail Dollar Amt MTD3 */
SELECT
  /*+ NO_CPU_COSTING */
  TO_DATE('1-'||:RunDate, 'dd-mon-yy') AS GL_BEGINDATE,
  LAST_DAY(TO_DATE('1-'||:RunDate, 'dd-mon-yy')) GL_END_DATE,
  CASE
    WHEN A.COUNTRY_INDICATOR IS NULL THEN B.COUNTRY_INDICATOR
    ELSE A.COUNTRY_INDICATOR
    END AS COUNTRY_INDICATOR,
  CASE
    WHEN A.GL_ACCOUNT IS NULL THEN B.ACCOUNT
    ELSE A.GL_ACCOUNT
    END AS GL_ACCOUNT,
	NVL(A.DOLLAR_AMOUNT, 0) DOLLAR_AMOUNT,
  CASE
    WHEN B.GL_ACC_DESCR IS NULL THEN A.GL_ACC_DESCR
    ELSE B.GL_ACC_DESCR
    END AS GL_ACC_DESCR, NVL(B.AMORT_COMM_AND_PREPAID_COMM, 0) AS AMORT_COMM_AND_PREPAID_COMM,
  NVL(C.SHORT_TERM_COMM, 0) AS SHORT_TERM_COMM,
  NVL(C.LONG_TERM_COMM, 0) AS LONG_TERM_COMM

FROM (
  -- A
  SELECT
    /*+ NO_CPU_COSTING */
    TO_DATE('1-'||:RunDate, 'dd-mon-yy') AS GL_BEGINDATE,
    LAST_DAY(TO_DATE('1-'||:RunDate, 'dd-mon-yy')) AS GL_END_DATE,
    CASE
      WHEN DIST.R12_ENTITY IN('5773', '5588') THEN 'CAN'
      ELSE 'USA'
    END AS COUNTRY_INDICATOR,
    DIST.R12_ACCOUNT AS GL_ACCOUNT,
    SUM(CASE
      WHEN DIST.DEBIT_AMT = 0 OR DIST.DEBIT_AMT IS NULL OR DIST.CREDIT_AMOUNT <> ''
        THEN DIST.CREDIT_AMOUNT * - 1
      ELSE DIST.DEBIT_AMT
      END) AS DOLLAR_AMOUNT, 
    AFU.DESCR AS GL_ACC_DESCR,
    0 AS AMORT_COMM_AND_PREPAID_COMM,
    0 AS SHORT_TERM_COMM,
    0 AS LONG_TERM_COMM
    
  FROM dbo.R12_TRNCO_CM_DIST_PSB Dist
  INNER JOIN R12_ACCOUNT_FILTER_UPD AFU
    ON AFU.R12_ACCOUNT = DIST.R12_ACCOUNT

  WHERE
    DIST.JOURNAL_DATE
      BETWEEN TO_DATE('1-'||:RunDate, 'dd-mon-yy')
      AND LAST_DAY(to_date('1-'||:RunDate, 'dd-mon-yy'))
  AND AFU.LIKE_5 = 'Y'
  AND 'USA' = UPPER(:COUNTRY)
  AND DIST.R12_ENTITY IN('5575', '5612', '5743', '9256', '9258', '9298', '9299', '9984') -- USA
  AND((DIST.PS_DEPTID = 'NA'
  AND DIST.R12_LOCATION IN('113602', '115615' /* USA */))
  OR(DIST.PS_DEPTID <> 'NA'
  AND DIST.PS_DEPTID = 'SL00'))

  GROUP BY
    CASE
      WHEN DIST.R12_ENTITY IN('5773', '5588') THEN 'CAN'
      ELSE 'USA'
      END, 
    DIST.R12_ACCOUNT, 
    AFU.DESCR

  UNION ALL

  SELECT
    /*+ NO_CPU_COSTING */
    TO_DATE('1-'||:RunDate, 'dd-mon-yy') AS GL_BEGINDATE,
    LAST_DAY(TO_DATE('1-'||:RunDate, 'dd-mon-yy')) GL_END_DATE,
    CASE
      WHEN DIST.R12_ENTITY IN('5773', '5588') THEN 'CAN'
      ELSE 'USA'
      END AS COUNTRY_INDICATOR,
    DIST.R12_ACCOUNT AS GL_ACCOUNT,
    SUM(CASE
      WHEN DIST.DEBIT_AMT = 0 OR DIST.DEBIT_AMT IS NULL OR DIST.CREDIT_AMOUNT <> ''
        THEN DIST.CREDIT_AMOUNT * - 1
      ELSE DIST.DEBIT_AMT
      END) AS DOLLAR_AMOUNT, 
    AFU.DESCR AS GL_ACC_DESCR, 
    0 AS AMORT_COMM_AND_PREPAID_COMM,
    0 AS SHORT_TERM_COMM, 0 AS LONG_TERM_COMM
    
  FROM DBO.R12_TRNCO_CM_DIST_PSB DIST
  INNER JOIN R12_ACCOUNT_FILTER_UPD AFU
    ON AFU.R12_ACCOUNT = DIST.R12_ACCOUNT

  WHERE 1=1
  AND DIST.JOURNAL_DATE BETWEEN TO_DATE('1-'||:RunDate, 'dd-mon-yy')
  AND LAST_DAY(to_date('1-'||:RunDate, 'dd-mon-yy'))
  AND AFU.LIKE_5 = 'Y'
  AND 'CAN' = UPPER(:COUNTRY)
  AND DIST.R12_ENTITY IN('5773', '5588')
  AND((DIST.PS_DEPTID = 'NA'
  AND DIST.R12_LOCATION IN('129003'))
  OR(DIST.PS_DEPTID <> 'NA'
  AND DIST.PS_DEPTID = 'SL00'))

  GROUP BY
    CASE
      WHEN DIST.r12_entity IN('5773', '5588') THEN 'CAN'
      ELSE 'USA'
      END, 
    DIST.R12_ACCOUNT, 
    AFU.DESCR

) A,
(
  -- B
  SELECT
    /*+ NO_CPU_COSTING */
    TO_DATE('1-'||:RunDate, 'dd-mon-yy') AS GL_BEGINDATE, 
    LAST_DAY(TO_DATE('1-'||:RunDate, 'dd-mon-yy')) GL_END_DATE, 
    B.COUNTRY_INDICATOR, 
    B.GL_ACCOUNT AS ACCOUNT, 
    0 AS DOLLAR_AMOUNT, 
    B.GL_ACCOUNT_DESCR AS GL_ACC_DESCR, 
    SUM(B.AMORT_COMM_AND_PREPAID_COMM) AS AMORT_COMM_AND_PREPAID_COMM

  FROM (
    SELECT
      A.COUNTRY_INDICATOR,
      A.GL_ACCOUNT,
      A.GL_ACCOUNT_DESCR,
      TO_DATE('1-'||:RunDate, 'dd-mon-yy'),
      (MAX(A.COMM_AMORT_MNTHLY) + CASE
        WHEN A.FORECAST_PERIOD = TO_DATE('1-'||:RunDate, 'dd-mon-yy')
          THEN MAX(A.PREPAID_COMMISSION)
        ELSE 0
        END) AS AMORT_COMM_AND_PREPAID_COMM,
      A.FORECAST_PERIOD

    FROM DW_DM_030_COMM_AMORTIZATION A
    INNER JOIN R12_ACCOUNT_FILTER_UPD AFU
      ON AFU.R12_ACCOUNT = A.GL_ACCOUNT 

    WHERE 
      A.COUNTRY_INDICATOR = UPPER(:COUNTRY)
    AND A.RUN_PERIOD >= TO_DATE('1-'||UPPER(:RunDate), 'dd-mon-yy')
    AND a.RUN_PERIOD < LAST_DAY(TO_DATE('1-'||:RunDate, 'dd-mon-yy'))
    AND AFU.LIKE_5 = 'Y' 
    AND A.FORECAST_PERIOD >= TO_DATE('1-'||UPPER(:RunDate), 'dd-mon-yy')
    AND A.FORECAST_PERIOD < (LAST_DAY(to_date('1-'||:RunDate, 'dd-mon-yy')))

    GROUP BY
    A.COUNTRY_INDICATOR,
    A.GL_ACCOUNT,
    A.GL_ACCOUNT_DESCR,
    A.FORECAST_PERIOD

  ) B

  GROUP BY
  B.COUNTRY_INDICATOR,
  GL_ACCOUNT, B.GL_ACCOUNT_DESCR

) B,
(
  -- C
  SELECT
    /*+ NO_CPU_COSTING */
    TRUNC(TO_DATE(TO_DATE('1-'||:RunDate, 'dd-mon-yy')), 'YEAR') - 1 AS GL_BEGINDATE,
    LAST_DAY(TO_DATE('1-'||:RunDate, 'dd-mon-yy')) GL_END_DATE,
    B.COUNTRY_INDICATOR,
    B.GL_ACCOUNT AS ACCOUNT,
    0 AS DOLLAR_AMOUNT,
    B.GL_ACCOUNT_DESCR AS GL_ACC_DESCR,
    SUM(B.SHORT_TERM_COMM) AS SHORT_TERM_COMM,
    SUM(B.LONG_TERM_COMM) AS LONG_TERM_COMM

  FROM (
    -- B
    SELECT
    A.COUNTRY_INDICATOR,
    A.GL_ACCOUNT,
    A.GL_ACCOUNT_DESCR,
    TO_DATE('1-'||:RunDate, 'dd-mon-yy'),
    MAX(A.SHORT_TERM_PP_COMM) AS SHORT_TERM_COMM,
    MAX(A.LONG_TERM_PP_COMM) AS LONG_TERM_COMM,
    A.FORECAST_PERIOD

    FROM DW_DM_030_COMM_AMORTIZATION A
    INNER JOIN R12_ACCOUNT_FILTER_UPD AFU
      ON AFU.R12_ACCOUNT = A.GL_ACCOUNT 
 
    WHERE 
      A.COUNTRY_INDICATOR = UPPER(:COUNTRY)
    AND A.RUN_PERIOD >= TO_DATE('1-'||UPPER(:RunDate), 'dd-mon-yy')
    AND A.RUN_PERIOD < ADD_MONTHS(TO_DATE('1-'||:RunDate, 'dd-mon-yy'), 1)
    AND AFU.LIKE_5 = 'Y' 
    AND A.SHIP_PERIOD >= CASE
      WHEN TO_DATE('1-'||:RunDate, 'dd-mon-yy') = TRUNC(TO_DATE(TO_DATE('1-'||:RunDate, 'dd-mon-yy')), 'YEAR')
        THEN TRUNC(TRUNC(TO_DATE('1-'||:RunDate, 'dd-mon-yy'), 'YEAR') - 1) - 30
      ELSE TRUNC(TO_DATE(TO_DATE('1-'||:RunDate, 'dd-mon-yy')), 'YEAR')
      END
    AND A.SHIP_PERIOD <( TO_DATE('1-'||:RunDate, 'dd-mon-yy'))

    GROUP BY
    A.COUNTRY_INDICATOR,
    A.GL_ACCOUNT,
    A.GL_ACCOUNT_DESCR,
    A.FORECAST_PERIOD

  ) B

  GROUP BY
  B.COUNTRY_INDICATOR,
  GL_ACCOUNT,
  B.GL_ACCOUNT_DESCR

) C

WHERE A.GL_ACCOUNT (+) = B.ACCOUNT
AND A.COUNTRY_INDICATOR (+) = B.COUNTRY_INDICATOR
AND B.ACCOUNT = C.ACCOUNT (+)
AND B.COUNTRY_INDICATOR = C.COUNTRY_INDICATOR (+)

UNION

SELECT
  /*+ NO_CPU_COSTING */
  TO_DATE('1-'||:RunDate, 'dd-mon-yy') AS GL_BEGINDATE,
  LAST_DAY(TO_DATE('1-'||:RunDate, 'dd-mon-yy')) gl_End_Date,
  '' AS COUNTRY_INDICATOR,
  AFU.R12_ACCOUNT AS GL_ACCOUNT,
  0 AS DOLLAR_AMOUNT, 
  AFU.DESCR AS GL_ACC_DESCR, 
  0 AS AMORT_COMM_AND_PREPAID_COMM,
  0 AS SHORT_TERM_COMM,
  0 AS LONG_TERM_COMM
  
FROM
R12_ACCOUNT_FILTER_UPD AFU
  
WHERE 1=1
AND AFU.LIKE_5 = 'Y'
AND NOT EXISTS (
  SELECT 'X'
  FROM DBO.R12_TRNCO_CM_DIST_PSB DIST 
  WHERE 1=1
  AND DIST.R12_ACCOUNT = AFU.R12_ACCOUNT 
  AND DIST.JOURNAL_DATE BETWEEN TO_DATE('1-'||:RunDate, 'dd-mon-yy')
  AND LAST_DAY(TO_DATE('1-'||:RunDate, 'dd-mon-yy'))
  AND CASE
    WHEN DIST.R12_ENTITY IN('5773', '5588') THEN 'CAN'
    ELSE 'USA'
    END = UPPER(:COUNTRY)
  AND DIST.R12_ENTITY IN ('5773', '5588', '5575', '5612', '5743', '9256', '9258', '9298', '9299', '9984')
)
AND NOT EXISTS (
  SELECT 'X'
  FROM DW_DM_030_COMM_AMORTIZATION A
  WHERE A.RUN_PERIOD >= TO_DATE('1-'||:RunDate, 'dd-mon-yy')
  AND A.RUN_PERIOD < ADD_MONTHS(TO_DATE('1-'||:RunDate, 'dd-mon-yy'), 1)
  AND A.GL_ACCOUNT = AFU.R12_ACCOUNT 
  AND A.SHIP_PERIOD >= CASE
    WHEN TO_DATE('1-'||:RunDate, 'dd-mon-yy') = TRUNC(TO_DATE(TO_DATE('1-'||:RunDate, 'dd-mon-yy')), 'YEAR')
      THEN TRUNC(TRUNC(TO_DATE('1-'||:RunDate, 'dd-mon-yy'), 'YEAR') - 1) - 30
    ELSE TRUNC(TO_DATE(TO_DATE('1-'||:RunDate, 'dd-mon-yy')), 'YEAR')
    END
  AND A.SHIP_PERIOD < (TO_DATE('1-'||:RunDate, 'dd-mon-yy'))
  AND A.COUNTRY_INDICATOR = UPPER(:COUNTRY)
)