<?xml version="1.0" encoding="UTF-8"?>
<com.actuate.istudio.iod.model:IRelationalMap xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:com.actuate.istudio.iod.model="http:///com/actuate/istudio/iod/model.ecore" displayName="SYS.V_$INSTANCE" version="1.1" tableName=".SYS.V_$INSTANCE">
  <columns>
    <columns xsi:type="com.actuate.istudio.iod.model:IRelationalColumn" dataType="Double" container="/" name="INSTANCE_NUMBER" displayFormat="" columnType="Source" aggregate="None" analysisType="Measure" hasNull="true" categoryPath="/" sourceName="INSTANCE_NUMBER" sourceOptional="true" nativeDataType="NUMBER" nativeDataTypeCode="3"/>
    <columns xsi:type="com.actuate.istudio.iod.model:IRelationalColumn" dataType="Varchar" container="/" name="INSTANCE_NAME" displayLength="16" displayFormat="" columnType="Source" aggregate="None" hasNull="true" categoryPath="/" sourceName="INSTANCE_NAME" sourceOptional="true" nativeDataType="VARCHAR2" nativeDataTypeCode="12" nativeSize="16"/>
    <columns xsi:type="com.actuate.istudio.iod.model:IRelationalColumn" dataType="Varchar" container="/" name="HOST_NAME" displayLength="64" displayFormat="" columnType="Source" aggregate="None" hasNull="true" wrap="Word" categoryPath="/" sourceName="HOST_NAME" sourceOptional="true" nativeDataType="VARCHAR2" nativeDataTypeCode="12" nativeSize="64"/>
    <columns xsi:type="com.actuate.istudio.iod.model:IRelationalColumn" dataType="Varchar" container="/" name="VERSION" displayLength="17" displayFormat="" columnType="Source" aggregate="None" hasNull="true" categoryPath="/" sourceName="VERSION" sourceOptional="true" nativeDataType="VARCHAR2" nativeDataTypeCode="12" nativeSize="17"/>
    <columns xsi:type="com.actuate.istudio.iod.model:IRelationalColumn" dataType="Timestamp" container="/" name="STARTUP_TIME" displayLength="19" displayFormat="" columnType="Source" aggregate="None" hasNull="true" categoryPath="/" sourceName="STARTUP_TIME" sourceOptional="true" nativeDataType="DATE" nativeDataTypeCode="93" nativeSize="19"/>
    <columns xsi:type="com.actuate.istudio.iod.model:IRelationalColumn" dataType="Varchar" container="/" name="STATUS" displayLength="12" displayFormat="" columnType="Source" aggregate="None" hasNull="true" categoryPath="/" sourceName="STATUS" sourceOptional="true" nativeDataType="VARCHAR2" nativeDataTypeCode="12" nativeSize="12"/>
    <columns xsi:type="com.actuate.istudio.iod.model:IRelationalColumn" dataType="Varchar" container="/" name="PARALLEL" displayLength="6" displayFormat="" columnType="Source" aggregate="None" hasNull="true" categoryPath="/" sourceName="PARALLEL" sourceOptional="true" nativeDataType="VARCHAR2" nativeDataTypeCode="12" nativeSize="3"/>
    <columns xsi:type="com.actuate.istudio.iod.model:IRelationalColumn" dataType="Double" container="/" name="&quot;THREAD#&quot;" displayFormat="" columnType="Source" aggregate="None" analysisType="Measure" hasNull="true" categoryPath="/" sourceName="&quot;THREAD#&quot;" sourceOptional="true" nativeDataType="NUMBER" nativeDataTypeCode="3"/>
    <columns xsi:type="com.actuate.istudio.iod.model:IRelationalColumn" dataType="Varchar" container="/" name="ARCHIVER" displayLength="9" displayFormat="" columnType="Source" aggregate="None" hasNull="true" categoryPath="/" sourceName="ARCHIVER" sourceOptional="true" nativeDataType="VARCHAR2" nativeDataTypeCode="12" nativeSize="7"/>
    <columns xsi:type="com.actuate.istudio.iod.model:IRelationalColumn" dataType="Varchar" container="/" name="LOG_SWITCH_WAIT" displayLength="15" displayFormat="" columnType="Source" aggregate="None" hasNull="true" categoryPath="/" sourceName="LOG_SWITCH_WAIT" sourceOptional="true" nativeDataType="VARCHAR2" nativeDataTypeCode="12" nativeSize="15"/>
    <columns xsi:type="com.actuate.istudio.iod.model:IRelationalColumn" dataType="Varchar" container="/" name="LOGINS" displayLength="10" displayFormat="" columnType="Source" aggregate="None" hasNull="true" categoryPath="/" sourceName="LOGINS" sourceOptional="true" nativeDataType="VARCHAR2" nativeDataTypeCode="12" nativeSize="10"/>
    <columns xsi:type="com.actuate.istudio.iod.model:IRelationalColumn" dataType="Varchar" container="/" name="SHUTDOWN_PENDING" displayLength="6" displayFormat="" columnType="Source" aggregate="None" hasNull="true" categoryPath="/" sourceName="SHUTDOWN_PENDING" sourceOptional="true" nativeDataType="VARCHAR2" nativeDataTypeCode="12" nativeSize="3"/>
    <columns xsi:type="com.actuate.istudio.iod.model:IRelationalColumn" dataType="Varchar" container="/" name="DATABASE_STATUS" displayLength="17" displayFormat="" columnType="Source" aggregate="None" hasNull="true" categoryPath="/" sourceName="DATABASE_STATUS" sourceOptional="true" nativeDataType="VARCHAR2" nativeDataTypeCode="12" nativeSize="17"/>
    <columns xsi:type="com.actuate.istudio.iod.model:IRelationalColumn" dataType="Varchar" container="/" name="INSTANCE_ROLE" displayLength="18" displayFormat="" columnType="Source" aggregate="None" hasNull="true" categoryPath="/" sourceName="INSTANCE_ROLE" sourceOptional="true" nativeDataType="VARCHAR2" nativeDataTypeCode="12" nativeSize="18"/>
    <columns xsi:type="com.actuate.istudio.iod.model:IRelationalColumn" dataType="Varchar" container="/" name="ACTIVE_STATE" displayLength="10" displayFormat="" columnType="Source" aggregate="None" hasNull="true" categoryPath="/" sourceName="ACTIVE_STATE" sourceOptional="true" nativeDataType="VARCHAR2" nativeDataTypeCode="12" nativeSize="9"/>
    <columns xsi:type="com.actuate.istudio.iod.model:IRelationalColumn" dataType="Varchar" container="/" name="BLOCKED" displayLength="6" displayFormat="" columnType="Source" aggregate="None" hasNull="true" categoryPath="/" sourceName="BLOCKED" sourceOptional="true" nativeDataType="VARCHAR2" nativeDataTypeCode="12" nativeSize="3"/>
  </columns>
  <parameters/>
  <properties key="dbtype" value="Oracle_10g"/>
  <connection href="_DRTRNP.dcd#/"/>
</com.actuate.istudio.iod.model:IRelationalMap>
