SELECT
		CASE WHEN DIST.R12_ENTITY IN('5773', '5588')
			THEN 'CDN'
			ELSE 'USD'
		END AS COUNTRY_INDICATOR, --  /* ASX.NATION_CURR */
		TO_CHAR(DIST.JOURNAL_DATE, 'YYYYMM') AS JRNL_YEAR_MONTH,
		DIST.R12_ENTITY AS BU,          --  /* -SS- BUSINESS_UNIT_GL */
		DIST.R12_ACCOUNT AS GL_ACCOUNT, -- /* -SS- ACCOUNT */
		DIST.R12_LOCATION AS GL_DEP_ID, -- /* -SS- deptid */
		'P/S LEDGER' AS QUERY_SOURCE,
		DIST.R12_PRODUCT AS GL_PRODUCT_ID, -- /* -SS- product */
		DIST.JOURNAL_DATE AS JOURNAL_DATE,
		DIST.JOURNAL_ID AS JOURNAL_ID,
		CASE WHEN DIST.DEBIT_AMT = 0 OR DIST.DEBIT_AMT IS NULL OR DIST.CREDIT_AMOUNT <> ''
			THEN DIST.CREDIT_AMOUNT * - 1
			ELSE DIST.DEBIT_AMT
		END AS DOLLAR_AMOUNT,
		(100 *(DIST.DEBIT_AMT - TRUNC(DIST.DEBIT_AMT))) AS DOLLAR_AMOUNT_DEC
	FROM
		DBO.R12_TRNCO_CM_DIST_PSB DIST                                            -- /* -SS- OTR */
	INNER JOIN R12_TRANE_ACCOUNTS_PS PSA ON DIST.R12_ACCOUNT = PSA.R12_ACCOUNT -- /* -SS- OTR */  --  /* -SS- ACCOUNT */  /* -SS- ACCOUNT */
		/* -SS- /* -SS- ,DBO.ACTUATE_SEC_XREF ASX */
	WHERE
		1 = 2
		AND PSA.TRANE_ACCOUNT_IND = 'X'
		/* -SS- AND DIST.BUSINESS_UNIT_GL = ASX.PSGL */
		AND DIST.JOURNAL_DATE BETWEEN TO_DATE('11/01/2004', 'MM/DD/YYYY') AND TO_DATE('12/31/2009', 'MM/DD/YYYY')
		AND DIST.R12_ACCOUNT
		/* -SS- ACCOUNT */
		LIKE '52%'
		/* -SS- ???? */
		AND DIST.R12_ENTITY NOT IN('5773', '5588') -- /* -SS- ASX.NATION_CURR = 'USD' */
		AND(DIST.R12_LOCATION
		/* -SS- deptid */
		IS NULL
		OR(DIST.R12_LOCATION
		/* -SS- deptid */
		= 'SL00'
		/* -SS- ???? */
		))
UNION ALL
SELECT
		CASE WHEN DIST.R12_ENTITY IN('5773', '5588')
			THEN 'CDN'
			ELSE 'USD'
		END
		/* ASX.NATION_CURR */
		AS COUNTRY_INDICATOR,
		TO_CHAR(DIST.JOURNAL_DATE, 'YYYYMM') AS JRNL_YEAR_MONTH,
		DIST.R12_ENTITY
		/* -SS- BUSINESS_UNIT_GL */
		AS BU,
		DIST.R12_ACCOUNT
		/* -SS- ACCOUNT */
		AS GL_ACCOUNT,
		DIST.R12_LOCATION
		/* -SS- deptid */
		AS GL_DEP_ID,
		'P/S LEDGER' AS QUERY_SOURCE,
		DIST.R12_PRODUCT
		/* -SS- product */
		AS GL_PRODUCT_ID,
		DIST.JOURNAL_DATE AS JOURNAL_DATE,
		DIST.JOURNAL_ID AS JOURNAL_ID,
		CASE WHEN DIST.DEBIT_AMT = 0 OR DIST.DEBIT_AMT IS NULL OR DIST.CREDIT_AMOUNT <> ''
			THEN DIST.CREDIT_AMOUNT * - 1
			ELSE DIST.DEBIT_AMT
		END AS DOLLAR_AMOUNT,
		(100 *(DIST.DEBIT_AMT - TRUNC(DIST.DEBIT_AMT))) AS DOLLAR_AMOUNT_DEC
	FROM
		DBO.R12_TRNCO_CM_DIST_PSB
		/* -SS- OTR */
		DIST,
		R12_TRANE_ACCOUNTS_PS
		/* -SS- OTR */
		PSA
		/* -SS- ,DBO.ACTUATE_SEC_XREF ASX  */
	WHERE
		1 = 2
		AND DIST.R12_ACCOUNT
		/* -SS- ACCOUNT */
		= PSA.R12_ACCOUNT
		/* -SS- ACCOUNT */
		AND PSA.TRANE_ACCOUNT_IND = 'X'
		/* -SS- AND DIST.BUSINESS_UNIT_GL = ASX.PSGL */
		AND DIST.JOURNAL_DATE BETWEEN TO_DATE('11/01/2004', 'MM/DD/YYYY') AND TO_DATE('12/31/2009', 'MM/DD/YYYY')
		AND DIST.R12_ACCOUNT
		/* -SS- ACCOUNT */
		LIKE '53%'
		/* -SS- ???? */
		AND DIST.R12_ENTITY NOT IN('5773', '5588')
		/* -SS- ASX.NATION_CURR = 'USD' */
		AND(DIST.R12_LOCATION
		/* -SS- deptid */
		IS NULL
		OR(DIST.R12_LOCATION
		/* -SS- deptid */
		= 'SL00'
		/* -SS- ???? */
		))
UNION ALL
SELECT
		CASE WHEN DIST.R12_ENTITY IN('5773', '5588')
			THEN 'CDN'
			ELSE 'USD'
		END
		/* ASX.NATION_CURR */
		AS COUNTRY_INDICATOR,
		TO_CHAR(DIST.JOURNAL_DATE, 'YYYYMM') AS JRNL_YEAR_MONTH,
		DIST.R12_ENTITY
		/* -SS- BUSINESS_UNIT_GL */
		AS BU,
		DIST.R12_ACCOUNT
		/* -SS- ACCOUNT */
		AS GL_ACCOUNT,
		DIST.R12_LOCATION
		/* -SS- DEPTID */
		AS GL_DEP_ID,
		'P/S LEDGER' AS QUERY_SOURCE,
		DIST.R12_PRODUCT
		/* -SS- PRODUCT */
		AS GL_PRODUCT_ID,
		DIST.JOURNAL_DATE AS JOURNAL_DATE,
		DIST.JOURNAL_ID AS JOURNAL_ID,
		CASE WHEN DIST.DEBIT_AMT = 0 OR DIST.DEBIT_AMT IS NULL OR DIST.CREDIT_AMOUNT <> ''
			THEN DIST.CREDIT_AMOUNT * - 1
			ELSE DIST.DEBIT_AMT
		END AS DOLLAR_AMOUNT,
		(100 *(DIST.DEBIT_AMT - TRUNC(DIST.DEBIT_AMT))) AS DOLLAR_AMOUNT_DEC
	FROM
		DBO.R12_TRNCO_CM_DIST_PSB DIST                                            -- /* -SS- OTR */
	INNER JOIN R12_TRANE_ACCOUNTS_PS PSA ON DIST.R12_ACCOUNT = PSA.R12_ACCOUNT -- /* -SS- ACCOUNT */ /* -SS- ACCOUNT */ -- /* -SS- OTR */
		/* -SS- ,DBO.ACTUATE_SEC_XREF ASX */
	WHERE
		1 = 2
		AND PSA.TRANE_ACCOUNT_IND = 'X'
		/* -SS- AND DIST.BUSINESS_UNIT_GL = ASX.PSGL */
		AND DIST.JOURNAL_DATE BETWEEN TO_DATE('11/01/2004', 'MM/DD/YYYY') AND TO_DATE('12/31/2009', 'MM/DD/YYYY')
		AND DIST.R12_ACCOUNT
		/* -SS- ACCOUNT */
		LIKE '54%'
		/* -SS- ???? */
		AND DIST.R12_ENTITY NOT IN('5773', '5588')
		/* -SS- ASX.NATION_CURR = 'USD' */
		AND(DIST.R12_LOCATION
		/* -SS- DEPTID */
		IS NULL
		OR(DIST.R12_LOCATION
		/* -SS- DEPTID */
		= 'SL00'
		/* -SS- ???? */
		))
UNION ALL
SELECT
		CASE WHEN DIST.R12_ENTITY IN('5773', '5588')
			THEN 'CDN'
			ELSE 'USD'
		END
		/* ASX.NATION_CURR */
		AS COUNTRY_INDICATOR,
		TO_CHAR(DIST.JOURNAL_DATE, 'YYYYMM') AS JRNL_YEAR_MONTH,
		DIST.R12_ENTITY
		/* -SS- BUSINESS_UNIT_GL */
		AS BU,
		DIST.R12_ACCOUNT
		/* -SS- ACCOUNT */
		AS GL_ACCOUNT,
		DIST.R12_LOCATION
		/* -SS- DEPTID */
		AS GL_DEP_ID,
		'P/S LEDGER' AS QUERY_SOURCE,
		DIST.R12_PRODUCT
		/* -SS- PRODUCT */
		AS GL_PRODUCT_ID,
		DIST.JOURNAL_DATE AS JOURNAL_DATE,
		DIST.JOURNAL_ID AS JOURNAL_ID,
		CASE WHEN DIST.DEBIT_AMT = 0 OR DIST.DEBIT_AMT IS NULL OR DIST.CREDIT_AMOUNT <> ''
			THEN DIST.CREDIT_AMOUNT * - 1
			ELSE DIST.DEBIT_AMT
		END AS DOLLAR_AMOUNT,
		(100 *(DIST.DEBIT_AMT - TRUNC(DIST.DEBIT_AMT))) AS DOLLAR_AMOUNT_DEC
	FROM
		DBO.R12_TRNCO_CM_DIST_PSB DIST                                            -- /* -SS- OTR */
	INNER JOIN R12_TRANE_ACCOUNTS_PS PSA ON DIST.R12_ACCOUNT = PSA.R12_ACCOUNT -- /* -SS- ACCOUNT */ /* -SS- ACCOUNT */ -- /* -SS- OTR */
		/* -SS- ,DBO.ACTUATE_SEC_XREF ASX */
	WHERE
		1 = 2
		AND PSA.TRANE_ACCOUNT_IND = 'X'
		/* -SS- AND DIST.BUSINESS_UNIT_GL = ASX.PSGL */
		AND DIST.JOURNAL_DATE BETWEEN TO_DATE('11/01/2004', 'MM/DD/YYYY') AND TO_DATE('12/31/2009', 'MM/DD/YYYY')
		AND DIST.R12_ACCOUNT
		/* -SS- ACCOUNT */
		LIKE '52%'
		/* -SS- ???? */
		AND DIST.R12_ENTITY IN('5773', '5588')
		/* -SS- ASX.NATION_CURR = 'CAD' */
		AND(DIST.R12_LOCATION
		/* -SS- DEPTID */
		IS NULL
		OR(DIST.R12_LOCATION
		/* -SS- DEPTID */
		= 'TCA0'
		/* -SS- ???? */
		)
		OR(DIST.R12_LOCATION
		/* -SS- DEPTID */
		= 'SL00'
		/* -SS- ???? */
		))
UNION ALL
SELECT
		CASE WHEN DIST.R12_ENTITY IN('5773', '5588')
			THEN 'CDN'
			ELSE 'USD'
		END
		/* ASX.NATION_CURR */
		AS COUNTRY_INDICATOR,
		TO_CHAR(DIST.JOURNAL_DATE, 'YYYYMM') AS JRNL_YEAR_MONTH,
		DIST.R12_ENTITY
		/* -SS- BUSINESS_UNIT_GL */
		AS BU,
		DIST.R12_ACCOUNT
		/* -SS- ACCOUNT */
		AS GL_ACCOUNT,
		DIST.R12_LOCATION
		/* -SS- DEPTID */
		AS GL_DEP_ID,
		'P/S LEDGER' AS QUERY_SOURCE,
		DIST.R12_PRODUCT
		/* -SS- PRODUCT */
		AS GL_PRODUCT_ID,
		DIST.JOURNAL_DATE AS JOURNAL_DATE,
		DIST.JOURNAL_ID AS JOURNAL_ID,
		CASE WHEN DIST.DEBIT_AMT = 0 OR DIST.DEBIT_AMT IS NULL OR DIST.CREDIT_AMOUNT <> ''
			THEN DIST.CREDIT_AMOUNT * - 1
			ELSE DIST.DEBIT_AMT
		END AS DOLLAR_AMOUNT,
		(100 *(DIST.DEBIT_AMT - TRUNC(DIST.DEBIT_AMT))) AS DOLLAR_AMOUNT_DEC
	FROM
		DBO.R12_TRNCO_CM_DIST_PSB DIST                                            -- /* -SS- OTR */
	INNER JOIN R12_TRANE_ACCOUNTS_PS PSA ON DIST.R12_ACCOUNT = PSA.R12_ACCOUNT -- /* -SS- ACCOUNT */ /* -SS- ACCOUNT */ -- /* -SS- OTR */
		/* -SS- ,DBO.ACTUATE_SEC_XREF ASX */
	WHERE
		1 = 2
		AND PSA.TRANE_ACCOUNT_IND = 'X'
		/* -SS- AND DIST.BUSINESS_UNIT_GL = ASX.PSGL */
		AND DIST.JOURNAL_DATE BETWEEN TO_DATE('11/01/2004', 'MM/DD/YYYY') AND TO_DATE('12/31/2009', 'MM/DD/YYYY')
		AND DIST.R12_ACCOUNT
		/* -SS- ACCOUNT */
		LIKE '53%'
		/* -SS- ???? */
		AND DIST.R12_ENTITY IN('5773', '5588')
		/* -SS- ASX.NATION_CURR = 'CAD' */
		AND(DIST.R12_LOCATION
		/* -SS- DEPTID */
		IS NULL
		OR(DIST.R12_LOCATION
		/* -SS- DEPTID */
		= 'TCA0'
		/* -SS- ???? */
		)
		OR(DIST.R12_LOCATION
		/* -SS- DEPTID */
		= 'SL00'
		/* -SS- ???? */
		))
UNION ALL
SELECT
		CASE WHEN DIST.R12_ENTITY IN('5773', '5588')
			THEN 'CDN'
			ELSE 'USD'
		END
		/* ASX.NATION_CURR */
		AS COUNTRY_INDICATOR,
		TO_CHAR(DIST.JOURNAL_DATE, 'YYYYMM') AS JRNL_YEAR_MONTH,
		DIST.R12_ENTITY
		/* -SS- BUSINESS_UNIT_GL */
		AS BU,
		DIST.R12_ACCOUNT
		/* -SS- ACCOUNT */
		AS GL_ACCOUNT,
		DIST.R12_LOCATION
		/* -SS- DEPTID */
		AS GL_DEP_ID,
		'P/S LEDGER' AS QUERY_SOURCE,
		DIST.R12_PRODUCT
		/* -SS- PRODUCT */
		AS GL_PRODUCT_ID,
		DIST.JOURNAL_DATE AS JOURNAL_DATE,
		DIST.JOURNAL_ID AS JOURNAL_ID,
		CASE WHEN DIST.DEBIT_AMT = 0 OR DIST.DEBIT_AMT IS NULL OR DIST.CREDIT_AMOUNT <> ''
			THEN DIST.CREDIT_AMOUNT * - 1
			ELSE DIST.DEBIT_AMT
		END AS DOLLAR_AMOUNT,
		(100 *(DIST.DEBIT_AMT - TRUNC(DIST.DEBIT_AMT))) AS DOLLAR_AMOUNT_DEC
	FROM
		DBO.R12_TRNCO_CM_DIST_PSB DIST                                            -- /* -SS- OTR */
	INNER JOIN R12_TRANE_ACCOUNTS_PS PSA ON DIST.R12_ACCOUNT = PSA.R12_ACCOUNT -- /* -SS- ACCOUNT */ /* -SS- ACCOUNT */ -- /* -SS- OTR */
		/* -SS- ,DBO.ACTUATE_SEC_XREF ASX */
	WHERE
		1 = 2
		AND PSA.TRANE_ACCOUNT_IND = 'X'
		/* -SS- AND DIST.BUSINESS_UNIT_GL = ASX.PSGL */
		AND DIST.JOURNAL_DATE BETWEEN TO_DATE('11/01/2004', 'MM/DD/YYYY') AND TO_DATE('12/31/2009', 'MM/DD/YYYY')
		AND DIST.R12_ACCOUNT
		/* -SS- ACCOUNT */
		LIKE '54%'
		/* -SS- ???? */
		AND DIST.R12_ENTITY IN('5773', '5588')
		/* -SS- ASX.NATION_CURR = 'CAD' */
		AND(DIST.R12_LOCATION
		/* -SS- DEPTID */
		IS NULL
		OR(DIST.R12_LOCATION
		/* -SS- DEPTID */
		= 'TCA0'
		/* -SS- ???? */
		)
		OR(DIST.R12_LOCATION
		/* -SS- DEPTID */
		= 'SL00'
		/* -SS- ???? */
		))
UNION ALL
SELECT
		CASE WHEN GL_CODE.R12_ENTITY IN('5773', '5588')
			THEN 'CDN'
			ELSE 'USD'
		END
		/* ASX.NATION_CURR */
		AS COUNTRY_INDICATOR,
		/* -SS- ASX.NATION_CURR AS COUNTRY_INDICATOR, */
		TO_CHAR(COMM.GL_POSTED_DATE, 'YYYYMM') AS JRNL_YEAR_MONTH,
		GL_CODE.R12_ENTITY
		/* -SS- SEGMENT1 */
		AS BU,
		GL_CODE.R12_ACCOUNT
		/* -SS- SEGMENT2 */
		AS GL_ACCOUNT,
		GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		AS GL_DEP_ID,
		'P/S LEDGER' AS QUERY_SOURCE,
		GL_CODE.R12_PRODUCT
		/* -SS- SEGMENT4 */
		AS GL_PRODUCT_ID,
		COMM.GL_POSTED_DATE AS JOURNAL_DATE,
		CAST(COMM.CMS_POSTING_ID AS VARCHAR2(10 BYTE)) AS JOURNAL_ID,
		CASE WHEN COMM.DEBIT_AMOUNT = 0 OR COMM.DEBIT_AMOUNT IS NULL OR COMM.CREDIT_AMOUNT <> ''
			THEN COMM.CREDIT_AMOUNT * - 1
			ELSE COMM.DEBIT_AMOUNT
		END AS DOLLAR_AMOUNT,
		(100 *(COMM.DEBIT_AMOUNT - TRUNC(COMM.DEBIT_AMOUNT))) AS REVENUE_AMOUNT_DEC
	FROM
		BH.CMS_COMMISSION_DISTRIBUTIONS COMM
	INNER JOIN R12_GL_CODE_COMBINATIONS GL_CODE ON COMM.CODE_COMBINATION_ID = GL_CODE.CODE_COMBINATION_ID --/* -SS- */
	LEFT OUTER JOIN R12_TRANE_ACCOUNTS_PS PSA   ON GL_CODE.R12_ACCOUNT = PSA.R12_ACCOUNT                  -- /* -SS- ACCOUNT */ /* -SS- SEGMENT2 */ (+) --/* -SS- OTR */
		/* -SS- ,ACTUATE_SEC_XREF ASX */
	WHERE
		1 = 2
		AND PSA.TRANE_ACCOUNT_IND = 'X'
		/* -SS- AND GL_CODE.SEGMENT1 = ASX.PSGL(+) */
		AND COMM.GL_POSTED_DATE BETWEEN TO_DATE('1/01/2000', 'MM/DD/YYYY') AND TO_DATE('10/31/2004', 'MM/DD/YYYY')
		AND GL_CODE.R12_ACCOUNT
		/* -SS- SEGMENT2 */
		LIKE '52%'
		/* -SS- ???? */
		AND GL_CODE.R12_ENTITY NOT IN('5773', '5588')
		/* -SS- AND ASX.NATION_CURR = 'USD' */
		AND(GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		IS NULL
		OR(GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		= 'SL00'
		/* -SS- ???? */
		))
UNION ALL
SELECT
		CASE WHEN GL_CODE.R12_ENTITY IN('5773', '5588')
			THEN 'CDN'
			ELSE 'USD'
		END
		/* ASX.NATION_CURR */
		AS COUNTRY_INDICATOR,
		/* -SS- ASX.NATION_CURR AS COUNTRY_INDICATOR, */
		TO_CHAR(COMM.GL_POSTED_DATE, 'YYYYMM') AS JRNL_YEAR_MONTH,
		GL_CODE.R12_ENTITY
		/* -SS- SEGMENT1 */
		AS BU,
		GL_CODE.R12_ACCOUNT
		/* -SS- SEGMENT2 */
		AS GL_ACCOUNT,
		GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		AS GL_DEP_ID,
		'P/S LEDGER' AS QUERY_SOURCE,
		GL_CODE.R12_PRODUCT
		/* -SS- SEGMENT4 */
		AS GL_PRODUCT_ID,
		COMM.GL_POSTED_DATE AS JOURNAL_DATE,
		CAST(COMM.CMS_POSTING_ID AS VARCHAR2(10 BYTE)) AS JOURNAL_ID,
		CASE WHEN COMM.DEBIT_AMOUNT = 0 OR COMM.DEBIT_AMOUNT IS NULL OR COMM.CREDIT_AMOUNT <> ''
			THEN COMM.CREDIT_AMOUNT * - 1
			ELSE COMM.DEBIT_AMOUNT
		END AS DOLLAR_AMOUNT,
		(100 *(COMM.DEBIT_AMOUNT - TRUNC(COMM.DEBIT_AMOUNT))) AS REVENUE_AMOUNT_DEC
	FROM
		BH.CMS_COMMISSION_DISTRIBUTIONS COMM
	INNER JOIN R12_GL_CODE_COMBINATIONS GL_CODE ON COMM.CODE_COMBINATION_ID = GL_CODE.CODE_COMBINATION_ID --/* -SS- */
	LEFT OUTER JOIN R12_TRANE_ACCOUNTS_PS PSA   ON GL_CODE.R12_ACCOUNT = PSA.R12_ACCOUNT                  -- /* -SS- ACCOUNT */ /* -SS- SEGMENT2 */ (+) --/* -SS- OTR */
		/* -SS- ,ACTUATE_SEC_XREF ASX */
	WHERE
		1 = 2
		AND PSA.TRANE_ACCOUNT_IND = 'X'
		/* -SS- AND GL_CODE.SEGMENT1 = ASX.PSGL(+) */
		AND COMM.GL_POSTED_DATE BETWEEN TO_DATE('1/01/2000', 'MM/DD/YYYY') AND TO_DATE('10/31/2004', 'MM/DD/YYYY')
		AND GL_CODE.R12_ACCOUNT
		/* -SS- SEGMENT2 */
		LIKE '53%'
		/* -SS- ???? */
		AND GL_CODE.R12_ENTITY NOT IN('5773', '5588')
		/* -SS- AND ASX.NATION_CURR = 'USD' */
		AND(GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		IS NULL
		OR(GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		= 'SL00'
		/* -SS- ???? */
		))
UNION ALL
SELECT
		CASE WHEN GL_CODE.R12_ENTITY IN('5773', '5588')
			THEN 'CDN'
			ELSE 'USD'
		END
		/* ASX.NATION_CURR */
		AS COUNTRY_INDICATOR,
		/* -SS- ASX.NATION_CURR AS COUNTRY_INDICATOR, */
		TO_CHAR(COMM.GL_POSTED_DATE, 'YYYYMM') AS JRNL_YEAR_MONTH,
		GL_CODE.R12_ENTITY
		/* -SS- SEGMENT1 */
		AS BU,
		GL_CODE.R12_ACCOUNT
		/* -SS- SEGMENT2 */
		AS GL_ACCOUNT,
		GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		AS GL_DEP_ID,
		'P/S LEDGER' AS QUERY_SOURCE,
		GL_CODE.R12_PRODUCT
		/* -SS- SEGMENT4 */
		AS GL_PRODUCT_ID,
		COMM.GL_POSTED_DATE AS JOURNAL_DATE,
		CAST(COMM.CMS_POSTING_ID AS VARCHAR2(10 BYTE)) AS JOURNAL_ID,
		CASE WHEN COMM.DEBIT_AMOUNT = 0 OR COMM.DEBIT_AMOUNT IS NULL OR COMM.CREDIT_AMOUNT <> ''
			THEN COMM.CREDIT_AMOUNT * - 1
			ELSE COMM.DEBIT_AMOUNT
		END AS DOLLAR_AMOUNT,
		(100 *(COMM.DEBIT_AMOUNT - TRUNC(COMM.DEBIT_AMOUNT))) AS REVENUE_AMOUNT_DEC
	FROM
		BH.CMS_COMMISSION_DISTRIBUTIONS COMM
	INNER JOIN R12_GL_CODE_COMBINATIONS GL_CODE ON COMM.CODE_COMBINATION_ID = GL_CODE.CODE_COMBINATION_ID --/* -SS- */
	LEFT OUTER JOIN R12_TRANE_ACCOUNTS_PS PSA   ON GL_CODE.R12_ACCOUNT = PSA.R12_ACCOUNT                  -- /* -SS- ACCOUNT */ /* -SS- SEGMENT2 */ (+) --/* -SS- OTR */
		/* -SS- ,ACTUATE_SEC_XREF ASX */
	WHERE
		1 = 2
		AND PSA.TRANE_ACCOUNT_IND = 'X'
		/* -SS- AND GL_CODE.SEGMENT1 = ASX.PSGL(+) */
		AND COMM.GL_POSTED_DATE BETWEEN TO_DATE('1/01/2000', 'MM/DD/YYYY') AND TO_DATE('10/31/2004', 'MM/DD/YYYY')
		AND GL_CODE.R12_ACCOUNT
		/* -SS- SEGMENT2 */
		LIKE '54%' -- /* -SS- ???? */
		AND GL_CODE.R12_ENTITY NOT IN('5773', '5588') -- /* -SS- AND ASX.NATION_CURR = 'USD' */
		AND(GL_CODE.R12_LOCATION -- /* -SS- SEGMENT3 */
		IS NULL
		OR(GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		= 'SL00'
		/* -SS- ???? */
		))
UNION ALL
SELECT
		CASE WHEN GL_CODE.R12_ENTITY IN('5773', '5588')
			THEN 'CDN'
			ELSE 'USD'
		END
		/* ASX.NATION_CURR */
		AS COUNTRY_INDICATOR,
		/* -SS- ASX.NATION_CURR AS COUNTRY_INDICATOR, */
		TO_CHAR(COMM.GL_POSTED_DATE, 'YYYYMM') AS JRNL_YEAR_MONTH,
		GL_CODE.R12_ENTITY
		/* -SS- SEGMENT1 */
		AS BU,
		GL_CODE.R12_ACCOUNT
		/* -SS- SEGMENT2 */
		AS GL_ACCOUNT,
		GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		AS GL_DEP_ID,
		'P/S LEDGER' AS QUERY_SOURCE,
		GL_CODE.R12_PRODUCT
		/* -SS- SEGMENT4 */
		AS GL_PRODUCT_ID,
		COMM.GL_POSTED_DATE AS JOURNAL_DATE,
		CAST(COMM.CMS_POSTING_ID AS VARCHAR2(10 BYTE)) AS JOURNAL_ID,
		CASE WHEN COMM.DEBIT_AMOUNT = 0 OR COMM.DEBIT_AMOUNT IS NULL OR COMM.CREDIT_AMOUNT <> ''
			THEN COMM.CREDIT_AMOUNT * - 1
			ELSE COMM.DEBIT_AMOUNT
		END AS DOLLAR_AMOUNT,
		(100 *(COMM.DEBIT_AMOUNT - TRUNC(COMM.DEBIT_AMOUNT))) AS REVENUE_AMOUNT_DEC
	FROM
		BH.CMS_COMMISSION_DISTRIBUTIONS COMM
	INNER JOIN R12_GL_CODE_COMBINATIONS GL_CODE ON COMM.CODE_COMBINATION_ID = GL_CODE.CODE_COMBINATION_ID -- /* -SS- */
	LEFT OUTER JOIN R12_TRANE_ACCOUNTS_PS PSA   ON GL_CODE.R12_ACCOUNT = PSA.R12_ACCOUNT                  -- /* -SS- SEGMENT2 */ /* -SS- ACCOUNT */ (+)-- /* -SS- OTR */
		/* -SS- ,ACTUATE_SEC_XREF ASX */
	WHERE
		1 = 2
		AND PSA.TRANE_ACCOUNT_IND = 'X'
		/* -SS- AND GL_CODE.SEGMENT1 = ASX.PSGL(+) */
		AND COMM.GL_POSTED_DATE BETWEEN TO_DATE('1/01/2000', 'MM/DD/YYYY') AND TO_DATE('10/31/2004', 'MM/DD/YYYY')
		AND GL_CODE.R12_ACCOUNT
		/* -SS- SEGMENT2 */
		LIKE '52%'
		/* -SS- ???? */
		AND GL_CODE.R12_ENTITY IN('5773', '5588')
		/* -SS- AND ASX.NATION_CURR = 'CAD' */
		AND(GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		IS NULL
		OR(GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		= 'TCA0'
		/* -SS- ???? */
		)
		OR(GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		= 'SL00'
		/* -SS- ???? */
		))
UNION ALL
SELECT
		CASE WHEN GL_CODE.R12_ENTITY IN('5773', '5588')
			THEN 'CDN'
			ELSE 'USD'
		END
		/* ASX.NATION_CURR */
		AS COUNTRY_INDICATOR,
		/* -SS- ASX.NATION_CURR AS COUNTRY_INDICATOR, */
		TO_CHAR(COMM.GL_POSTED_DATE, 'YYYYMM') AS JRNL_YEAR_MONTH,
		GL_CODE.R12_ENTITY
		/* -SS- SEGMENT1 */
		AS BU,
		GL_CODE.R12_ACCOUNT
		/* -SS- SEGMENT2 */
		AS GL_ACCOUNT,
		GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		AS GL_DEP_ID,
		'P/S LEDGER' AS QUERY_SOURCE,
		GL_CODE.R12_PRODUCT
		/* -SS- SEGMENT4 */
		AS GL_PRODUCT_ID,
		COMM.GL_POSTED_DATE AS JOURNAL_DATE,
		CAST(COMM.CMS_POSTING_ID AS VARCHAR2(10 BYTE)) AS JOURNAL_ID,
		CASE WHEN COMM.DEBIT_AMOUNT = 0 OR COMM.DEBIT_AMOUNT IS NULL OR COMM.CREDIT_AMOUNT <> ''
			THEN COMM.CREDIT_AMOUNT * - 1
			ELSE COMM.DEBIT_AMOUNT
		END AS DOLLAR_AMOUNT,
		(100 *(COMM.DEBIT_AMOUNT - TRUNC(COMM.DEBIT_AMOUNT))) AS REVENUE_AMOUNT_DEC
	FROM
		BH.CMS_COMMISSION_DISTRIBUTIONS COMM
	INNER JOIN R12_GL_CODE_COMBINATIONS GL_CODE ON COMM.CODE_COMBINATION_ID = GL_CODE.CODE_COMBINATION_ID --  /* -SS- */
	LEFT OUTER JOIN R12_TRANE_ACCOUNTS_PS PSA   ON GL_CODE.R12_ACCOUNT = PSA.R12_ACCOUNT                  -- /* -SS- SEGMENT2 */   /* -SS- ACCOUNT */ (+) -- /* -SS- OTR */
		/* -SS- ,ACTUATE_SEC_XREF ASX */
	WHERE
		1 = 2
		AND PSA.TRANE_ACCOUNT_IND = 'X'
		/* -SS- AND GL_CODE.SEGMENT1 = ASX.PSGL(+) */
		AND COMM.GL_POSTED_DATE BETWEEN TO_DATE('1/01/2000', 'MM/DD/YYYY') AND TO_DATE('10/31/2004', 'MM/DD/YYYY')
		AND GL_CODE.R12_ACCOUNT
		/* -SS- SEGMENT2 */
		LIKE '53%'
		/* -SS- ???? */
		AND GL_CODE.R12_ENTITY IN('5773', '5588')
		/* -SS- AND ASX.NATION_CURR = 'CAD' */
		AND(GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		IS NULL
		OR(GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		= 'TCA0'
		/* -SS- ???? */
		)
		OR(GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		= 'SL00'
		/* -SS- ???? */
		))
UNION ALL
SELECT
		CASE WHEN GL_CODE.R12_ENTITY IN('5773', '5588')
			THEN 'CDN'
			ELSE 'USD'
		END
		/* ASX.NATION_CURR */
		AS COUNTRY_INDICATOR,
		/* -SS- ASX.NATION_CURR AS COUNTRY_INDICATOR, */
		TO_CHAR(COMM.GL_POSTED_DATE, 'YYYYMM') AS JRNL_YEAR_MONTH,
		GL_CODE.R12_ENTITY
		/* -SS- SEGMENT1 */
		AS BU,
		GL_CODE.R12_ACCOUNT
		/* -SS- SEGMENT2 */
		AS GL_ACCOUNT,
		GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		AS GL_DEP_ID,
		'P/S LEDGER' AS QUERY_SOURCE,
		GL_CODE.R12_PRODUCT
		/* -SS- SEGMENT4 */
		AS GL_PRODUCT_ID,
		COMM.GL_POSTED_DATE AS JOURNAL_DATE,
		CAST(COMM.CMS_POSTING_ID AS VARCHAR2(10 BYTE)) AS JOURNAL_ID,
		CASE WHEN COMM.DEBIT_AMOUNT = 0 OR COMM.DEBIT_AMOUNT IS NULL OR COMM.CREDIT_AMOUNT <> ''
			THEN COMM.CREDIT_AMOUNT * - 1
			ELSE COMM.DEBIT_AMOUNT
		END AS DOLLAR_AMOUNT,
		(100 *(COMM.DEBIT_AMOUNT - TRUNC(COMM.DEBIT_AMOUNT))) AS REVENUE_AMOUNT_DEC
	FROM
		BH.CMS_COMMISSION_DISTRIBUTIONS COMM
	INNER JOIN R12_GL_CODE_COMBINATIONS GL_CODE ON COMM.CODE_COMBINATION_ID = GL_CODE.CODE_COMBINATION_ID-- /* -SS- */
	LEFT OUTER JOIN R12_TRANE_ACCOUNTS_PS PSA   ON GL_CODE.R12_ACCOUNT = PSA.R12_ACCOUNT                 -- /* -SS- SEGMENT2 */  /* -SS- ACCOUNT */ (+) --  /* -SS- OTR */
		/* -SS- ,ACTUATE_SEC_XREF ASX */
	WHERE
		1 = 2
		AND PSA.TRANE_ACCOUNT_IND = 'X'
		/* -SS- AND GL_CODE.SEGMENT1 = ASX.PSGL(+) */
		AND COMM.GL_POSTED_DATE BETWEEN TO_DATE('1/01/2000', 'MM/DD/YYYY') AND TO_DATE('10/31/2004', 'MM/DD/YYYY')
		AND GL_CODE.R12_ACCOUNT
		/* -SS- SEGMENT2 */
		LIKE '54%'
		/* -SS- ???? */
		AND GL_CODE.R12_ENTITY IN('5773', '5588')
		/* -SS- AND ASX.NATION_CURR = 'CAD' */
		AND(GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		IS NULL
		OR(GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		= 'TCA0'
		/* -SS- ???? */
		)
		OR(GL_CODE.R12_LOCATION
		/* -SS- SEGMENT3 */
		= 'SL00'
		/* -SS- ???? */
		))
UNION ALL

/* COMMISSION DATA BACK FROM 1998 TO 1999*/
SELECT
		CASE WHEN UPD.COUNTRY_INDICATOR = 'CAN'
			THEN 'CAD'
			ELSE 'USD'
		END AS COUNTRY_INDICATOR,
		TO_CHAR(UPD.JRNL_DATE, 'YYYYMM') AS JRNL_YEAR_MONTH,
		'' AS BU,
		UPD.GL_ACCOUNT AS GL_ACCOUNT,
		'' AS GL_DEP_ID,
		'COMM 1998' AS QUERY_SOURCE,
		'' AS GL_PRODUCT_ID,
		UPD.JRNL_DATE AS JOURNAL_DATE,
		''AS JOURNAL_ID,
		UPD.REVENUE_AMOUNT AS REVENUE_AMOUNT,
		(100 *(UPD.REVENUE_AMOUNT - TRUNC(UPD.REVENUE_AMOUNT))) AS REVENUE_AMOUNT_DEC
	FROM
		MD_030_COMMISSION_DTL_UPD UPD
	LEFT OUTER JOIN R12_TRANE_ACCOUNTS_PS PSA ON UPD.GL_ACCOUNT = PSA.R12_ACCOUNT -- /* -SS- OTR */  -- /* -SS- ACCOUNT */ (+)
	WHERE
		1 = 2
		AND PSA.TRANE_ACCOUNT_IND = 'X'
		AND UPD.JRNL_DATE BETWEEN TO_DATE('01/01/1998', 'MM/DD/YYYY') AND TO_DATE('12/31/1999', 'MM/DD/YYYY')
