/* SR: NOT USED ANY PLACE
Query is probably not corrected as LAG table does is not bound to other queries.
In addition LAG query is DWT, but OTR_TRANE_ACCOUNTS_PS is in DRT
*/
SELECT DISTINCT
		GLA.R12_ACCOUNT
		/* -SS- ACCOUNT */
		,
		(
		CASE WHEN GLA.R12_ENTITY NOT IN('5773', '5588')
				/* -SS- ASX.NATION_CURR='USD' */
			THEN 'USA'
			ELSE 'CAN'
				/* -SS-
				WHEN ASX.NATION_CURR='CAD' THEN 'CAN'
				ELSE 'CURRENCY: ' || ASX.NATION_CURR
				*/
		END) AS COUNTRY_INDICATOR,
		-- -SS- issue 88: PSA.DESCR AS DESCRIPTION,
		AFU.DESCR AS DESCRIPITON,
		LAG.REPORT_TYPE,
		CAST(LAG.TRX_LAG AS INTEGER) AS TRX_LAG,
		LAG.FACTOR
	FROM
		R12_GL_ACCOUNT_SCD GLA -- -SS-
		-- -SS- NEW
	INNER JOIN R12_ACCOUNT_FILTER_UPD AFU ON AFU.R12_ACCOUNT = GLA.R12_ACCOUNT
		-- -SS- /NEW
	INNER JOIN SY_EXT_LAG_RULES_UPD LAG ON LAG.REPORT_TYPE = '2-16'
	-- -SS- issue 88: INNER JOIN R12_TRANE_ACCOUNTS_PS PSA ON GLA.R12_ACCOUNT = PSA.R12_ACCOUNT -- R12_2_R12 -- -SS- OTR
	
		-- -SS- ,ACTUATE_SEC_XREF ASX
	WHERE 1=1
		-- -SS- GLA.ACCOUNT = PSA.ACCOUNT (+)
		-- -SS- AND GLA.COMPANY=(CASE WHEN ASX.PSGL IS NULL  THEN GLA.COMPANY ELSE ASX.PSGL END )
		-- -SS- issue 88: PSA.TRANE_ACCOUNT_IND = 'X' 
		-- -SS- NEW
		AND AFU.EW_ACTIVITY = 'Y'
		-- -SS- /NEW
		-- -SS- OLD: AND GLA.ACCOUNT IN ('523500', '526892', '526893', '528100', '528200', '528300', '532100')
		-- -SS- and lag.report_type ='2-16'
		--AND CASE WHEN ASX.NATION_CURR='USD' THEN 'USA'WHEN ASX.NATION_CURR='CAD' THEN 'CAN' ELSE 'CURRENCY: ' ||ASX.NATION_CURR END ='CAN'
		--select report_type, cast(trx_lag as number(12)) trx_lag, factor,
		--case when REPORT_TYPE ='1-15' then '523500'  end as account,
		--case when REPORT_TYPE ='1-15' then 'USA'  end AS  COUNTRY_INDICATOR,
		--case when REPORT_TYPE ='1-15' THEN '1st Year Labor Warr' END  DESCRIPTION
		-- from sy_ext_lag_rules_upd
		;